### ISSUE TITLE
Core contribution platform revamp

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/participation-org#100]
### Goal:

Solidify our core contribution platform mozillians.org with fixes, new functionality and visual revamp.

**Planning document is here:**
https://docs.google.com/document/d/1ZM0v8l6h0r5uMGdXAIXUozgXvS4btLmh6v0a1GiR1tg/edit?usp=sharing

**Reference:**
https://partinfra.etherpad.mozilla.org/2015Q3

**Objective:** Create a solid platform for contributors, community managers and other services to rely on.

**Key result 1:** Deliver functionality as outlined on the planning pad. (reference)
### Success:

1) Restructure group functionality and amend it for NDA group
2) Finalize migration to API v2
3) Complete all maintenance work
4) Restructure profile view and edit
5) Restructure search to expose all fields
6) Migrate away from Persona
### Roles:

Owner: @ppapadeas
Responsible: @akatsoulas , @comzeradd, @johngian  
Involved: @geroter 
### Required:
- [ ] NDA Mozillians group functionality
- [x] Migrate all v1 API users to v2 API
- [x] Upgrade to django 1.8
- [ ] Upgrade celery to version 3+
- [ ] Implement Multiple curators per group
- [x] Restructure profile view and edit
- [ ] Enhance search experience
- [ ] Migrate to FirefoxAccounts authentication

**Comment by CaptainCalliope** [comment]
This is exciting to see! Especially the FirefoxAccounts authentication!

I'm interested in finding out more about the NDA group functionality. What work is being planned here? 

I created a bug last year (that may or may not be relevant here) that highlights how the way in which the NDA group is currently administered acts as a barrier to participation: https://bugzilla.mozilla.org/show_bug.cgi?id=1065570

**Comment by LucyeoH** [comment]
@ppapadeas can you please add dates and owners to your sub-issues? Makes it WAY easier to see whose accountable and if things are on track.

**Comment by LucyeoH-zz** [comment]
@ppapadeas status update. Can you indicate in the comments here: 
- What the blockers were: 
- What you would change in your approach moving forwards
- What you're moving to the next HB

**Comment by LucyeoH-zz** [comment]
NDA functionality - move to next heartbeat, didn't have capacity for this. 
Upgrade celery 3+ - dependent on IT capacity (blocked by IT - need to update django first will happen Monday)
Implement multiple curators per group - needs to be moved, didn't have capacity for this (was always intended for next heartbeat) 
Enhance search - prioritized for next heartbeat  
Migrate to FirefoxAccounts authentication - prioritized for next heartbeat (project evolved - see notes below) (Needs to be broken into sub-goals - add links for bugzilla)

**Comment by comzeradd** [comment]
Bugs that track the work around tasks of this heartbeat:
- [Restructure profile view and edit](https://bugzilla.mozilla.org/show_bug.cgi?id=1129848)
- [Use allauth library to adopt more auth methods](https://bugzilla.mozilla.org/show_bug.cgi?id=1191246) (eg. Fx Accounts, Github, etc)
