### ISSUE TITLE
Volunteer Task - Curriculum

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#102]
# Curriculum Contribution

Volunteer subtask of #81 
- Helping craft learning objectives/outcomes and curriculum  for 'Foundations of Mozilla' curriculum, based on research #101.
- Help design a standard for community curriculum, that allows others to 'plug-in' their education & training to the Community Education Platform.
## Prerequisite

Volunteers for this role, must have some experience in instructional design and have personal/professional goals in education/open education. 
## Participation Steps
1. [Read this document](https://docs.google.com/document/d/1fZyp6q3RHAYFI-OKxue5Gtmg3JaDCb4jEvq_OFiFBEQ/edit) to gain a better understanding of what our goals for this curriculum.
2. Visit the education portal, to see how we are currently structuring [learning & participation](http://education.mozilla-community.org/modules/marketpulse/participation_ladder/).  The portal pulls markdown files from our [community_curriculum](https://github.com/emmairwin/community_curriculum).  
3. Once you've done this background reading, please add your name in the comments below and I'll reach out to you :)  

Please use comments to ask questions if you / I'm sure you'll have a few questions!

**Comment by SOFTowaha** [comment]
+1 ;
Count me in :)

**Comment by Nidhiya** [comment]
Me too :smile:

**Comment by emmairwin** [comment]
Hey @SOFTowaha , @Nidhiya thanks for your interest!    If you can please send me a short email at eirwin at mozilla.com with your background  & goals in education . As mentioned in the pre-requisties, I need contributors with education background, as I won't have time to mentor.

I won't be getting to this until next week, but here are a couple of ways to gain greater knowledge in the meantime:

1) Familiarize yourself with [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) .  [All curriculum is in markdown](https://github.com/emmairwin/community_curriculum/blob/master/participation/design_thinking_for_participation/en/design_thinking_collaborative.md), and if you are familiar then you will be in a better place to help :)
2)  Consider sending a [pull request to this file](https://github.com/emmairwin/community_curriculum/blob/master/technical_training/github/participation_stories.md) with your name and a link to any profile of yours on the web.  If you haven't used Github before, [Open Hatch curriculum can help you setup locally](https://openhatch.org/wiki/Open_Source_Comes_to_Campus/Curriculum/Laptop_setup/OSX_git), and an [activity that will teach you how to add your name to the page I linked](https://openhatch.org/wiki/Open_Source_Comes_to_Campus/Curriculum/Directory).  The Open Hatch community is also available on Freenode #openhatch to help you get unstuck.
3) If this sound like too much, I still need help for the research task: https://github.com/mozilla/participation-org/issues

Feel free to use this space for questions, and you can follow the main issue #81 for status.  Hope this helps!

**Comment by AkshayTiwari** [comment]
I'm in.

**Comment by emmairwin** [comment]
Closing this for now, next heartbeat I will create an u pdated version.  Thanks everyone!
