### ISSUE TITLE
Volunteer Task - Test fork of teach.mozilla.org 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#104]
See comment below for tasks (this has been updated from jekyll work to testing a fork of teach.mozilla.org

**Comment by emmairwin** [comment]
If we go with a fork of the teach.mozilla.org fork , as I believe we will there are a couple of things we need to know better.   If someone has time to pick up a bit of research from me it would help this go faster.  

**What we need to know**
- [ ] How to pull in an entire markdown file from a remote address, and display as content in teach.mozilla.org
- [ ] If there will be styling challenges we need to accommodate (meaning when we pull in markdown how to images display etc)
- [ ] Why the html code (converted from markdown) is displaying literally:
  ![2015-08-15_1718](https://cloud.githubusercontent.com/assets/60618/9291395/bd972e90-4371-11e5-8a8c-f816b5cc7c7c.png)

**What we already know**
We can use a node package with react to process markdown, and it's works.

### Testing
- Follow the instructions here: https://github.com/mozilla/teach.webmaker.org/blob/develop/README.md to get your localhost up and running, EXCEPT don't fork their copy, [fork my develop branch](https://github.com/emmairwin/teach.webmaker.org/tree/develop) .
- Once you have it up and running it should look like this (if the side menu is different you might have the wrong copy)
  ![full screen](https://cloud.githubusercontent.com/assets/60618/9291425/693cd85c-4373-11e5-9dea-c89e834e2b77.png)
- Understand the basic file structure:  pages are the 'pages' folder 'components' (like header, footer, side menu) are in the components folder.  You only need look in the page folder for moz-participation.jsx 
- You'll see a line:   var html = marked('I am using **markdown**.');   which is a the hard-coded markdown text displayed when you click on the Participation menu item.  THIS is where we need to test pulling in external markdown.
- This is the documentation for the [marked node module](https://github.com/emmairwin/marked/blob/master/README.md) to better understand how we can leverage it .
- Figure out how to pull the markdown [in this external document to that page](https://github.com/emmairwin/community_curriculum/blob/master/participation/design_thinking_for_participation/en/design_thinking_group.md).

Leave comments here as to how that goes.  Thinking  @SOFTowaha might be interested in giving this a go.

**Comment by SOFTowaha** [comment]
Thank you Emma! I'm super interested to work with this :)

**Comment by emmairwin** [comment]
Even though @SOFTowaha is working on this, will close and create a new one for the next heartbeat (will create on Monday) .

Next Steps

1) Continue with testing as described above.
