### ISSUE TITLE
Issue Planning Template 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#110]
*\* Hit edit and then copy and paste the formatting to create new issues! **
## Goal:

[One line goal description] 
## Success:

  [What would success look like] 
## Related Issues & Links:

[Reference meta issues and past issues] #
## Roles:

Owner: 
Involved: 
## Required:
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: Aug 7th)

**Comment by ioana-chiorean** [comment]
@LucyeoH  - Non-team persons and non -collaborator won't be  able to hit Edit to see the markdown behind. 
See example from webmaker: https://github.com/mozilla/webmaker-core/issues/401

**Comment by MajkenC** [comment]
Yes, just followed the link Nuke gave me to here, and I can't hit edit to copy the markup.
