### ISSUE TITLE
Incorporate feedback, launch and close selection process for global gatherings

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#112]
## Goal:

Launch and completion of the selection process for Developing Participation Leaders through 3 global gatherings (MozFest, Leadership Summit and Orlando workweek), with strong communication throughout to all relevant stakeholders.
## Success:
1. Concepts for gatherings and selection process are refined using the feedback received. How this feedback was used is made clear on Discourse.
2. Strong MozFest space plan is in place, sessions identified and Mozilla leaders contacted. All of this is done with strong coordination with the MozFest team in a way that is coherent with the existing session application process and other spaces.
3. Application process (and gatherings) is opened on Aug 28 and closed on Sept 11 with great communication across Discourse, mailing lists, social media, blogs, etc.
## Related:

[Planning document is here:](https://docs.google.com/document/d/1D6GaVk64BqgR7sR_rg_HOelD9iY9hyjGqMNL01ebiVk/edit)

[Concept document:](https://docs.google.com/presentation/d/1twJ0oZPbKs7aRzGb-5gpbNZPBg0c49F2m-FKQlyv2fg/edit#slide=id.p)

[Feedback on Discourse:](https://discourse.mozilla-community.org/t/draft-for-feedback-developing-participation-leaders-mozfest-leadership-summit-work-week-2015/3390)

Last Heartbeat: Issue #80 
## Roles:

Owner: @geroter
Involved: @nukeador @couci @francjp @emmairwin 
Consulted: Sarah + Michelle - MozFest @rosanardila @emmairwin
## Required:
- [x] Get feedback from Council and other key volunteer stakeholders (@nukeador, medium, Due: Aug 26) 
- [x] Incorporate feedback, finalize concepts and selection process (@geroter, consult with @rosanardila and @emmairwin , medium, Due: Aug 27) 
- [x] Finalize location for Leadership Summit (@couci, small, Due: Aug 27)
- [x] Build application and do QA (@geroter, medium, Due: Aug 27)
- [x] Finalize MozFest Space and Track framing and communicate with stakeholders (@emmairwin, medium, Due: Aug 25)
- [x] Launch application communication on multiple channels (@geroter with support from @emmairwin @LucyeoH @nukeador @couci , medium, Due: Aug 28)
- [x] Develop and communicate application coaching process, including making sure staff are available ( @nukeador , medium, Due: Aug 31)
- [x] Review MozFest sessions and build rough space plan/schedule (@geroter, large, Due: Sept 4)
- [x] Setup for logistics for all of the gatherings -- organize visa and travel processes so they are ready to go ( @francjp , large, Due: Sept 9)
- [x] Run staff process on Orlando Work Week nominations, including incorporating applications (@geroter, medium, Due: Sept 9)
- [ ] Create and organize selection committee to begin reviewing applications on Sept 14th (@geroter, medium, Due: Sept 10)
- [ ] Have communication templates built for both acceptance and regrets ( @nukeador  , small, Due: Aug 27)

**Comment by couci** [comment]
e-mailed the venue for availability, waiting for a response

**Comment by geroter** [comment]
A couple of days late, but the final initiative plan and the application are live.

Plan:
https://docs.google.com/presentation/d/1Jaf44pt8G_D5QdZzk2vbFDOqE-hatayIkWwF77Myyxg/edit#slide=id.p

Wiki:
https://wiki.mozilla.org/Participation/Globalgatherings2015

**Comment by geroter** [comment]
Draft outline of Participation Space at MozFest, including participant profiles and pathways:
https://docs.google.com/document/d/15Gbi8wv6NFqGb-8H1b42uEENtk8D4YSMYpFq8FiBAPE/edit#heading=h.mgdha5wttmr1

**Comment by geroter** [comment]
Selection committee will be setup today (Fri Sept 11) -- initial conversations to set this up have been had.

Logistics + communication templates will carry forward to the next Heartbeat.

**Comment by francjp** [comment]
draft of the logistics plan: https://docs.google.com/a/mozilla.com/spreadsheets/d/1zsjwk_EqxBT6NcevNg7YxZtUnOI1fkGEbIJTR_xW5Yw/edit?usp=sharing
