### ISSUE TITLE
Connect Market & User Insight Team with Relevant Research Opportunities 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#117]
## Goal:

Connect the market and user insight team with relevant opportunities. 
## Success:

People with an interest in market and user insight are connected to projects that could benefit from their contribution. 
## Related Issues & Links:
#84
## Roles:

Owner: @emmairwin 
Involved: @williamq @rosanardila 
## Required:
- [ ] 1) Rosana and William provide the details for contribution as per comments in #84 . (owner, [small, medium, large], Due: Aug 7th) 
- [ ] 2) @emmairwin  connect with our Marketpulse mentors and leaders to discuss these new opportunities (owner, [small, medium, large], Due: Aug 7th) 
- [ ] 3) Update the User Insight group from Whistler , with an outline of the above points with perhaps, what we expect to come next for contribution in this area.  (owner, [small, medium, large], Due: Aug 7th) 
- [ ] Check with @geroter might also have important insights into how this should be wrapped. (owner, [small, medium, large], Due: Aug 7th)

**Comment by LucyeoH-zz** [comment]
@emmairwin recommendation: Push this to next heartbeat where we'll have more clarity.

**Comment by emmairwin** [comment]
@LucyeoH we will have to, I think timewise.   I wonder though if we should at least pen an email that explains where we are.

**Comment by LucyeoH-zz** [comment]
Agreed -> Moved to next heartbeat
