### ISSUE TITLE
Provide Support and Create Volunteer Integration Strategy for Heartbeat Process

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#118]
## Goal:

Increase the efficacy of the heartbeat process.
## Success:

At the end of this heartbeat more than 50% of issues are completed (have all of their sub-issues checked off) and we have a strategy for volunteer integration into the heartbeat process
## Related Issues & Links:
#86
## Roles:

Owner: @lucyeoh
Involved: @thomasfarrow
## Required:
- [x] Meet with all project owners (who aren't on pto) to make sure issues are properly planned  (@lucyeoh [small], Due: Aug 25th) 
- [x] Review @thomasfarrow volunteer integration document and provide feedback (@lucyeoh, [small], Due: Aug 28th) 
- [x] Meet with all project owners who were on pto to make sure issues are properly planned given limited time  (@lucyeoh [small], Due: Sept 2nd) 
- [x] Reach out to each issue owner at half-way point for updates and to tweak issues (@lucyeoh, [small], Due: Sept 2nd) 
- [x] Share volunteer integration document with team for feedback (@lucyeoh, [small], Due: Sept 4th) 
- [x] Send "last week" reminder to all team (@lucyeoh, [small], Due: Sept 7nd)

**Comment by LucyeoH-zz** [comment]
Hey @thomasfarrow I left some comments on your [background doc](https://docs.google.com/document/d/1CN7c8J7p3cZTcBKO1Z9g1eaMPq-8uOCF23S9PctVkk8/edit#) ! Awesome work!!

**Comment by brianking** [comment]
I'm not sure the context of this background doc, but it looks something like categorizing volunteers. Here are some definitions that were defined last year:
https://wiki.mozilla.org/Community#Who_Is_In_The_Mozilla_Community.3F

**Comment by emmairwin** [comment]
Also on background doc - would be helpful to consider how volunteer roles plug into the proposed framework:  http://tiptoes.ca/participation-leadership-framework-01/  
AND I think this work can be strongly influenced by Participation Personas I worked on earlier this year (which is the result of community consultation)  :  http://education.mozilla-community.org/modules/about/personas/

**Comment by LucyeoH-zz** [comment]
Discourse Topic for Discussion [here](https://discourse.mozilla-community.org/t/volunteer-integration-with-participation-team/3980/1)
