### ISSUE TITLE
Support new NDA process 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#122]
## Goal:

To improve communication between Mozilla and volunteers by supporting the new NDA process to make sure it is community friendly and oriented. 
## Success:

New NDA process is accessible and community friendly.   
## Related Issues & Links:
#119
## Roles:

Owner: @lucyeoh
Involved:  Legal Team @ppapadeas 
## Required:
- [x] Create draft emails for the all auto responses for the new NDA process and send to Urmika (@lucyeoh, [medium], Due: Aug 28th)
  
  Next Heartbeat:
- Co-present with legal team at the steering committee meeting  (@lucyeoh [small] Due: Sept 15)

**Comment by ppapadeas** [comment]
related to #136 (technical implementation)

**Comment by LucyeoH-zz** [comment]
Next Heatbeat - Co-present with legal team at the steering committee meeting (@lucyeoh [small] Due: Sept 15)
