### ISSUE TITLE
Athens Training Days logistics

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#124]
## Goal:

To have all the logistics planned and in place for a successful team work week
## Success:

All logistics in place before the work week (2nd-6th of October)
## Roles:

Owner: @couci
Involved: @LucyeoH 
## Required
- [x] Book accommodation place for work week (@couci, [small], Due: Aug 27th) 
- [x] Co-ordinating team's flight schedules and transportation from/to the airport , (@couci, [medium], Due: Sept 9th) 
- [x] Co-ordinating team's transportation from/to the airport (@couci, [small], Due: Sept 9th) 
- [x] Define lunches and dinners for the team (@couci, [small], Due: Sept 9th)

**Comment by couci** [comment]
Started research for place near Athens, right now we have 2 options

**Comment by LucyeoH-zz** [comment]
@couci should we add transportation to and from the airport into the coordination? I know it's kind of part of flight schedules but wonder if it'd be better to be explicit.

**Comment by couci** [comment]
totally, added it on the tasks

**Comment by LucyeoH-zz** [comment]
![racoon gif](http://i.giphy.com/vzkSu4oe620Tu.gif)

**Comment by couci** [comment]
e-mail to the team sent for booking flights, still on research for accommodation

**Comment by couci** [comment]
accommodation has been fixed, sent request for booking

**Comment by couci** [comment]
all participants have booked their flights

**Comment by LucyeoH-zz** [comment]
Woo-hooo!!!!

**Comment by LucyeoH-zz** [comment]
- [x] Share email with Team updating them on travel plans and food plans @geroter
