### ISSUE TITLE
Create the first iteration of  the community Dashboard

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#125]
## Goal:

Start gathering the information for the dashboard and identifying the different data sources and possible roadblocks, while delivering a version 0.1 of the data for the 10 focus communities 
## Success:
1. We know where to get the data for all categories for the dashboard 
2. Collect 100% of the data for which we don’t need external help for the 10 focus communities
3. Make a plan for the rest of the data
4. We have a first iteration of the Dashboard design (on google docs)
## Roles:
- Owner: @rosanardila
- Involved: @nukeador @couci @deimidis
- Consulted: @akatsoulas @johngian  Reps Council
## Required:
- [x] First pass at all categories making sure they are defined and we know where the data can come from by August 28th @rosanardila @nukeador @deimidis [medium]
- [x] Short meeting to decide how to move forward with data and design survey, by August 28th @rosanardila @nukeador @deimidis @couci [small]
- [x] Finalize survey and send out @rosanardila, by August 31st [medium]
- [x] Meeting to check in and iterate with dashboard design, Sept 4th @rosanardila @nukeador @deimidis @couci [small]
- [x] First iteration of the Dashboard ready by Sept 9th @rosanardila @nukeador @deimidis @couci [large]

**Comment by rosanardila** [comment]
Survey out, here's the link: http://bit.ly/1L0hQat

**Comment by nukeador** [comment]
During our 1:1s we are gathering some channels where we can get the information. Also #133 is going to support this goal.

**Comment by nukeador** [comment]
We are on track, now integrating the first data into the dashboard draft.

**Comment by couci** [comment]
first version has been drafted, we are now importing data

**Comment by rosanardila** [comment]
This is a first version of the dashboard with real data from India. Please note that we don't have sufficient data and that we will need to send the survey again in order to have representative data, but this gives an idea of how the dashboard will look like for the different countries: 

https://docs.google.com/spreadsheets/d/1E3y0eoNDxQ-dFu5E5B6qHbbOItKAQRzAwIwPzLVWUvM/edit?usp=sharing

There is a main dashboard with all the data and that provides this template so that we can generate the country specific dashboards.

**Comment by rosanardila** [comment]
Next steps for next heartbeat: get a bigger sample for the data and create a report with the analysis of this data and the data gathered through the 1:1s for the focus communities
