### ISSUE TITLE
Deliver first iteration of Mid-term plan for 3 communities

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#126]
## Goal:

The goal of this heartbeat is to get a first working version of the planning framework ready and in the hands of communities to test. At the same time we want to start the process of planning, getting communities to buy in and to commit to testing this framework with the participation team. 

The 3 communities we would like to test this with are:
- Germany (we're still considering if this would be the best one in Europe, so this could change)
- Indonesia
- Mexico
## Success:
1. Getting a v 0.1 of the planning framework for the communities to work on
2. Get the buy-in from the communities for a 6 month plan
3. Kick off planning process, get a draft plan with at least what is already in the pipeline
## Roles:
- Owner: @rosanardila
- Involved: @rosanardila @nukeador @deimidis
- Consulted: @williamq @brianking 
## Required:
- [x] Finish the version  0.1 of the planning framework @rosanardila by August 28th [medium]
- [x] Start getting buy-in from focus communities 
  - [x] Indonesia @rosanardila
  - [x] Mexico @deimidis
  - [x] Germany @nukeador, by Sept 1st [medium]
- [ ] Meetings with communities are done and the draft for the plan is created together @rosanardila, @deimidis, @nukeador by Sept 9th [medium]

**Comment by rosanardila** [comment]
https://docs.google.com/document/d/1LRS4mKCumoVKHD6nQYN4i8HUCUlASZgvY3ktY1PO_hk/edit#heading=h.30j0zll

**Comment by nukeador** [comment]
I'm talking with some German contributors this week and I expect to have positive reactions around the plan.

Scheduling a day/time with all the community is turning more complicated as I expected but still working on figuring out something before the deadline date.

**Comment by nukeador** [comment]
I'll be meeting German community next Monday 7th.

**Comment by rosanardila** [comment]
I had a conversation with a big group from the Indonesian community and 1:1s with some Reps. The community was already thinking about long term planning and we'll collaborate in the next heartbeat on the plan.

**Comment by deimidis** [comment]
I had a conversation with 5 community leaders yesterday and we agree to begin this plan next week. First steps involve:
- [ ] Each of them will think in their views for the next 6 months
- [ ] Think how we will engage the community in this plan

**Comment by rosanardila** [comment]
We missed delivering the first draft, t took us longer to schedule the 1:1s and the team was involved in the coaching for global gatherings. 
There is buy-in in the communities, so we're targeting to get a v1.0. of the plan.

**Comment by brianking** [comment]
Mostly on track. Longer than expected to schedule 1:1s. Overlap with global gatherings meetings.

v1 of plan at end of next heartbeat.
