### ISSUE TITLE
Testing coaching and documenting learnings

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#127]
## Goal:

The goal of this heartbeat is to test a more scalable coaching for volunteers by having conversations with at least 40 volunteers and documenting the learnings into a framework.
## Success
1. Talk to 40 volunteers and ensure that the conversations are valuable for volunteers 
2. Document learnings and create a v.01 of a coaching framework
## Roles:
- Owner: @rosanardila
- Involved: @rosanardila @nukeador @deimidis @couci
- Consulted: @eirwin @williamq @brianking @geroter 
## Required:
- [x] Define a guide for 1:1 sessions and iterate based on experiences @nukeador   by August 27th [medium]
- [x] Get input from Partnerships team to understand how the coaching can support their efforts @rosanardila by Sept 2nd [small]
- [x] Meeting to track progress and iterate Sept 4th @deimidis @nukeador [small]
- [x] Talk to 40 volunteers by Sept 11th @rosanardila @nukeador @deimidis [large]
- [ ] Get a v 0.1 of the framework by Sept 9th @rosanardila @nukeador @deimidis @couci [medium]

**Comment by nukeador** [comment]
During this week we are having most of the 1:1s and we are constantly evolving based on the experience from previous ones. There are a lot of places where coaching will help individuals in their local communities.

**Comment by brianking** [comment]
Run a lot of 1:1 coaching sessions. Documenting everything.
Writing down findings as base of framework.
Mostly clear on what needs to be done next - on track for end of quarter.

Just ran out of time working on other stuff.

Moving remaining task to new heartbeat.
