### ISSUE TITLE
Planning is fully underway for 6 events and presentations in Germany in the 2nd half of September

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#128]
## Goal:

The "Mozilla and Firefox brand building efforts in Germany  boosted by larger and stronger community" objective is fully on-track, with people in place, detailed event plans and specific roles and actions.
## Success:
1. We found a person/contractor who can help drive this work
2. Detailed planning is underway for 6 events and presentations in the 2nd half of September
3. Alignment with functional/product teams on detailed leadership role descriptions and actions
## Related Issues & Links:
- Meta: #105 
- [Initiative plan](https://docs.google.com/document/d/1-ka6nj50x5ywinIPdUZQj-qqL6cEKOZTkDx-p-BW4Jg/edit#)
## Roles:

Owner: @brianking 
Involved: @geroter
## Required:
- [x] Finalize concept and get feedback from stakeholders ( @geroter and @brianking , medium , Due Aug 28)
- [ ] Finalize plan for team involvement, including getting feedback on leader roles ( @brianking , medium , Due: Aug 28) 
- [x] Get added contractor resource ( @geroter with @brianking support , medium , Due: Aug 31) 
- [x] Support existing German community in building out action plans ( @brianking and Michael Kohler, medium , Due: Sept 8) 
- [x] Coordinate with events team at Web Tech Fest events ( @geroter , medium , Aug 31)
- [x] Detailed plan is developed with contractor ( @brianking , medium, Due: Sept 10)
- [ ] All leader roles are written and actions articulated ( @brianking with @geroter , large, Sept 9)

**Comment by geroter** [comment]
Working document to summarize the concept is here:
https://docs.google.com/document/d/1057N3xIgVsgDw-H02y9oK8BaqdFqj1dMLJUnL4v2i3k/edit

**Comment by brianking** [comment]
Presence at http://rejectjs.org/ on Sep 24th is recommended by anyone I have talked to. The moving out to the next week of the Firefox OS Meeting, means @autonome and @mikehenrty are interested in going.

@geroter where can we followup about tickets and sponsorship?

**Comment by geroter** [comment]
Great! Once we have a contractor confirmed, we can follow-up about sponsorship/tickets because that person can coordinate our presence.

**Comment by brianking** [comment]
The main missing piece for me on this one is getting more teams on board as partners and building out leadership roles around them. Only Community Marketing and Policy have role descriptions currently.

So some work to be carried over to the next heartbeat.

**Comment by brianking** [comment]
Reopening because there were some issues not completed. See previous comment.
