### ISSUE TITLE
India Firefox for Android Coding Team

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#129]
## Goal:

The coding team in India starts working in an organized fashion on Firefox for Android bugs. 
## Success:

A skeleton structure is put in place for the program, team members are in place, leaders identified to run the program, and coding has begun.
## Related Issues & Links:
#98
## Roles:

Owner: @brianking
Involved: @debloper
## Required:
- [x] Screen applicants to the team (@debloper, [medium], Due: Sep 3rd) 
- [x] Assign leadership roles (@debloper @brianking, [small], Due: Sep 4th)
- [x] Bug triage and prioritization (@debloper @brianking, [medium], Due: Sep 7th)
- [ ] Document what the program will look like, get feedback and iterate, and socialise among the team (@brianking, [medium], Due: Sep 10th)
- [ ] Schedule first hack event (@debloper @brianking, [small], Due: Sep 11th)

**Comment by ioana-chiorean** [comment]
Guys, ping me to get the bugs fixed in verification state. ( both official side of me and community qa one)

**Comment by brianking** [comment]
We got some of the way there, in terms of building out the team, assigning leaders, and talking to the engineering team about priorities and how we can get mentorship.

TODO: Document the program, outreach and motivation to the team, and getting started hacking!

**Comment by brianking** [comment]
Reopening because there were some issues not completed. See previous comment.
