### ISSUE TITLE
Start Building Out Basics Of Firefox OS Participation Program

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#130]
## Goal:

With the participation plan now in place (pending approval), we should move forward and lay the groundwork for a successful program.
## Success:

At the end of this heartbeat, we would have contributor roles defined (and role of Firefox OS community manager), a prototype of a participation hub, and have researched the basics of a first class open source project to determine gaps to be filled.
## Related Issues & Links:

Meta: #88 
Past: #96 #95 #94 #93 #92
## Roles:

Owner: @williamq 
Involved: @brianking
## Required:
- [ ] List technical contribution opportunities for b2gDroid and Ports - project specific (@brianking @autonome, [medium], Due: Sep 1st) 
- [ ] List basics of top level open source project, analyze what Firefox OS needs (@brianking @autonome, [medium], Due: Sep 3rd) 
- [x] Build out Firefox OS technical contributor role descriptions / personas (@brianking, [medium], Due: Sep 4th) 
- [ ] Base Firefox OS Participation Wiki Page built (@williamq , [medium], Due: Sep 4th) 
- [x] Identify/create all relevant communication channels for Fx OS Participation (@brianking, [medium], Due: Sep 7th)
- [ ] Scope out role of Firefox OS Community Manager (@brianking @mhoye, [medium], Due: Sep 11th)

**Comment by brianking** [comment]
From recent meeting notes...

Build out contributor role descriptions
- @autonome - started some dev contributor notes: https://wiki.mozilla.org/FirefoxOS/Participation#Notes
- QA in the past has worked on contributor role descriptions - will look for the link [marcia]

**Comment by brianking** [comment]
Removed participation hub task from this issue, it is being covered in issue #135

**Comment by brianking** [comment]
Updates:

Contributor personas:
https://docs.google.com/document/d/19E_6EvjFLTVLrLtTCHmuZFBC1DvYaSl5BXF55uYJSwA/edit?usp=sharing

Communication channels proposal: https://docs.google.com/a/mozilla.com/document/d/1jhSMt85xTwA4xRFytMxxZSmdAHL57KMtBWS2HqDSf_o/edit?usp=sharing

Both WIP.

**Comment by brianking** [comment]
Meeting again with @mhoye tomorrow to scope out more the community manager role.

**Comment by brianking** [comment]
Most of these are at various levels of complete, and will have to be carried over to the next heartbeat.

**Comment by brianking** [comment]
Reopening because there were some issues not completed. As noted most are moving, but we underestimated time and still had  to have a lot of stakeholder discussions.

**Comment by williamq** [comment]
Carrying this over to next heartbeat.
