### ISSUE TITLE
Gather data from mozillians.org

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#133]
In order to fill the country profiles and community dashboard in #125 we need to gather some data from mozillians that would avoid having to manually check for them.

mozillians.org has an API documented here:

http://mozillians.readthedocs.org/en/latest/api/apiv2/

And the data we need to gather per country is (just for vouched mozillians):
- Number of mozillians
- How old on average contributors are (date_mozillian)
- Top skill sets.

The countries to focus right now are:
- India
- Indonesia
- Bangladesh
- Philippines
- Germany
- France
- UK
- USA
- Mexico
- Brazil

[Discussion here](https://discourse.mozilla-community.org/t/gathering-country-data-from-mozillians-org-needs-help/3716/1).

**Comment by nukeador** [comment]
A MVP with a static report for these countries would be enough.

In the future having a way to get this report in real time would be awesome :D

**Comment by MichaelKohler** [comment]
I have to say, I feel tempted. Is there any deadline?

**Comment by nukeador** [comment]
September 11th is the deadline. It should be too complicated ;)

**Comment by MichaelKohler** [comment]
consider it done by then ;)

**Comment by SOFTowaha** [comment]
cool; count me in ;)

**Comment by nukeador** [comment]
Yes please, feel free to team up for this and iterate :)

**Comment by MichaelKohler** [comment]
Towaha, where's your area of expertise? API, Frontend, ..?

**Comment by nukeador** [comment]
Feel free to move the discussion here:

https://discourse.mozilla-community.org/t/gathering-country-data-from-mozillians-org-needs-help/3716/1

So we can keep comments here just about the code iterations ;)

**Comment by MichaelKohler** [comment]
https://github.com/MichaelKohler/community_dashboard_participation

**Comment by SOFTowaha** [comment]
I'd like to play with frontend. But I'd love it if I work with the APIs :) 

Let's discuss rest of the conversation of discourse /Telegram :)

**Comment by johngian** [comment]
Hey all !
Let me know if you need any help regarding Mozillians.org API.

**Comment by SOFTowaha** [comment]
Sure JohnGian :) Thanks in advance.

**Comment by safwanrahman** [comment]
@johngian I need to discuss something with you. When you will be available in IRC?

**Comment by safwanrahman** [comment]
So far, I have made a Django app which will make the work done. here is the repo link
https://github.com/safwanrahman/community
**So now waiting for the Elevated Keys.**

**Comment by safwanrahman** [comment]
By using the Public API Key, and using the Django app, I have got the following data:
![firefox_screenshot_2015-09-04t23-14-04 609z](https://cloud.githubusercontent.com/assets/7114151/9696137/f9b1912e-538c-11e5-8806-d496f7d805bc.png)

So just after getting the Elevated Keys, its possible to get the full actual data.

**Comment by m4hi2** [comment]
@safwanrahman I think, instead of creating rows for Skill-1 or 2, it's wise to create rows with the skill name. Like, Python, JS and what not! 
BTW, I'm forking the repo and let's see what can be done. I'll reach you through IRC after 10PM(BDT)

**Comment by brianking** [comment]
Blockers:
- getting API key, needs to talk with Pierros. Will download code and check. Currently manual checks.

3 active volunteer contributors.

Use template please for future issues.

**Comment by nukeador** [comment]
The app was successfully used to gather data:

https://docs.google.com/spreadsheets/d/1ko53E1qW_S0PY1Bza1Dr-j1H6UMLMgVj1McBR8SAJ_g/edit#gid=0

Thanks everyone!
