### ISSUE TITLE
Co-create first draft of plan for Phase 2 of Foxfooding program (devices) 

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#134]
## Goal:

Create first draft of plan with Jean Gong (Senior PM for Fx OS) for the second phase of the foxfooding program (devices) which aims tol ensure that core volunteers committed to participating in the foxfooding program are properly vetted and receive a Sony Xperia Z3C device. 
## Success:

 We have a solid first draft by September 11th that is ready to be circulated to stakeholders for buy-in and in time for Q4 rollout. 
## Roles:

Owner: @williamq
Involved: @brianking 
## Required:
- [x] meet with Jean Gong in SF and brainstorm/draft plan (@williamq, [large], Due: Sep 11th) 
- [x] meet with Doug Sherk for foxfooding dashboard design (@williamq, [medium], Due: Sep 8th) 
- [x] meet with Legal team (@williamq, [medium], Due: Sep 9th) 
- [x] meet with Irina Sandu for foxfooding insights and tracking (@williamq, [medium], Due: Sep 10th)
- [x] meet with WPR for foxfooding logistics for volunteers (@williamq, [medium], Due: Sep 10th)
- [x] meet with Marcia Knous for Flame strategy (@williamq, [medium], Due: Sep 8th)

**Comment by MichaelKohler** [comment]
What's the easiest way to keep being informed here? :)

**Comment by ioana-chiorean** [comment]
I guess commenting here? ( I am interested too :) )

**Comment by SunboX** [comment]
:+1: (just commenting :smirk:)

**Comment by birajkarmakar** [comment]
I am interested also.

**Comment by brianking** [comment]
Blockers:
None
- Met with Asa who is working with Marcia on updated Flames strategy.
- will add comments about meetings.
