### ISSUE TITLE
Foxfooding platform Phase 1

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/participation-org#135]
## Goal:

Create a foxfooding platform tech demo for phase 1 as outlined in the planning document: https://docs.google.com/document/d/18hLL0Pe-fvEnMcTjIuZiESTu6GoAD0sAxEjTKf7x7og/edit#
## Success:

Have a tech demo and UI up and running by the end of this heartbeat.
## Roles:

Owner: @ppapadeas
Involved: @williamq  
## Required:
- [x] Meeting with existing dashboard stakeholders
- [x] UI mockup by @comzeradd 
- [ ] Tech setup by @johngian & @akatsoulas 
- [ ]  Deployment by @johngian

**Comment by brianking** [comment]
I think a better name is Firefox OS Participation Hub.

**Comment by ppapadeas** [comment]
The requirements as defined are pointing to foxfooding specific participation. Not broader fxos participation. Did you have another take?

**Comment by brianking** [comment]
That is the way we have been "pitching" it recently, though without necessarily spec'ing it out more. But some of the current user stories, especially related to 'As a code contributor' already refer to activities outside of foxfooding.

Here is an initial mockup by @yopdesign ... ignore content, just an idea for layout.

![img_2015-09-02 15 05 37](https://cloud.githubusercontent.com/assets/114116/9632173/e04ebc60-5185-11e5-9dee-30b066cac769.jpg)

**Comment by LucyeoH-zz** [comment]
Review Buddy notes: 
- Lookings like you're missing the ["related issues & links"](https://github.com/mozilla/participation-org/issues/110)  sections can you add this and drop in any relevant links and issues. 
- Can you add due dates, and approximate size of task [small, medium, large] here
- Do you need anything to come out of the dashboard meeting or is having the meeting enough? 
- I think these goals look clear and very realistic!

**Comment by williamq** [comment]
A quick comment on Brian's earlier comment: the "long term" vision for the hub is indeed a place where you can find information on everything related to Firefox OS participation. In the short term though, the focus is exclusively on foxfooding.

**Comment by ppapadeas** [comment]
Coding the front-end
![foxie](https://cloud.githubusercontent.com/assets/498592/9815825/560a8910-5899-11e5-99ae-63f832198eb0.jpg)

**Comment by LucyeoH-zz** [comment]
Blockers: 
- Lots of discussions and back and forth
- Changed approaches part way through 
- Production EST End of September
- Move over to next heartbeat
