### ISSUE TITLE
New NDA functionality in mozillians.org

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/participation-org#136]
## Goal:

Make it easier to sign and manage signed NDA through mozillians.org. Details document: https://docs.google.com/document/d/1zATe7bpgsachaBGAycMJ3QSz1o5U2WKWY-QVmTuZYPk/edit
## Success:

Implement new NDA process through mozillians.org
## Roles:

Owner: @ppapadeas
Involved: @LucyeoH   
## Required:
- [x] Meeting with existing NDA stakeholders
- [x] Finalize product requirements
- [x] UI mockup by @comzeradd 
- [ ] Frontend coding by @comzeradd 
- [ ] Backend code and review by @johngian & @akatsoulas 
- [ ] Push to production

**Comment by MichaelKohler** [comment]
This sounds very interesting, any reason why the Google Doc is not open to view for everybody?

**Comment by LucyeoH-zz** [comment]
Review Buddy notes: 
- Lookings like you're missing the ["related issues & links"](https://github.com/mozilla/participation-org/issues/110)  sections can you add this and drop in a link to #122 
- Can you add due dates, and approximate size of task [small, medium, large] here
- This seems like it would make a really great demo, maybe sharing success with the team could be a final goal for this hb?

**Comment by MichaelKohler** [comment]
Is there any update regarding if the linked document could make public?

**Comment by geroter** [comment]
We actually don't own the document (someone from legal does) ... they have labelled it Confidential and Internal. Looking at the content, I'm not sure why.

@ppapadeas @LucyeoH any insight why that can't be a public document?

**Comment by flaki** [comment]
This really does look an interesting (and much welcome) change, looking forward to how this unfolds.
