### ISSUE TITLE
Participation Leadership Framework - Curriculum Development & Testing

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#140]
## Goal:

Development & Event Testing for 5 or 6 modules. 
Priority Order
- Personal Leadership
- Essential Mozilla
- Building for Action and Impact
- Working Open
- Developing Specialization
- Empowering Teams & People
## Success:

In this heartbeat we develop 4 quality modules and 2 module drafts for future testing.
In this heartbeat we fully test 4 modules.
In this heartbeat we run two in-person workshops
In this heartbeat we run 2 online workshops.
In this heartbeat all tested curriculum is posted on the Education Platform.
## Related Issues & Links:
#81 #120
- http://tiptoes.ca/participation-leadership-framework-01/
  ![2015-08-28_1244](https://cloud.githubusercontent.com/assets/60618/9857474/9a0eed08-5acf-11e5-9256-7836ef674b26.png)
## Roles:

Owner: @emmairwin
Involved: @geroter 
## Required:
- [x] Kick off Call @geroter @emmairwin  (@emmairwin @geroter , small, Due: Sept 16th) 
- [x] Identify top 4 learning outcomes we need by designing for teams at Mozilla already working with existing and community leaders (Tech speakers, FSA, Open Science, Privacy Task Force, Reps) .  (@emmairwin @geroter , small, Due: Sept 16th) .
- [x] Develop first 4 modules  (@emmairwin ,large , Due: Sept 18th) 
- [x] Test one or more modules at Open Science Leadership Summit  (@emmairwin , medium , Due: Sept 23rd) 
- [ ] Test one or more modules in Vancouver via collaboration with education community there. (@emmairwin , large , Due: Sept 30th)   **NOTE: Still researching if this will be possible with community there.**
- [x] Check in and Feedback Meeting -  (@emmairwin @geroter , small, Due: Sept 25th) 
- [x] Run first online workshop with one or more modules.  (@emmairwin ,large , Due: Sept 27th) 
- [x] Run second online workshop with one or more modules  (@emmairwin ,large , Due: Sept 27th) 
-  **Nice to Have** Run third online workshop  with one or more modules  (@emmairwin , small , Due: Sept 27th) 
- [ ] Based on feedback improve the first four modules, and post to Education Portal  (@emmairwin , small , Due: Sept 30th) 
- [x] Wrap Up Call
- [ ] Write Summary Blog Post   (@emmairwin , small , Sept: Aug 30th) 
# Volunteer Opportunities
#145 - Workshop Co-pilot
#144 - Curriculum QA

This heartbeat task is all about developing, testing and improving curriculum developed for the Participation Leadership Framework. Here are supporting volunteer tasks:

**Comment by ioana-chiorean** [comment]
@emmairwin the description is ending with " Here are supporting volunteer tasks: " and blank..
There are none or not yet?

**Comment by emmairwin** [comment]
Hi @ioana-chiorean - sorry definitely a placeholder just wrapping up the last ones, and will have created these by end of day.

**Comment by emmairwin** [comment]
5 Themes (and current workshop titles to support them)
- **Community Building/Participation Design** Workshop Name: "Supercharging your Community (Building and Activating), based on Open Science Leadership".
-  **Building a reputation, understanding where you fit, and can go**. Workshop name: A Bold Leap - Building your Mozilla Community Credentials""  ( Empowering Teams & People), based on Tech Speakers leadership needs.
-  **Six Degrees of Mozilla** - Understanding our Networks of Action
- **Finding your talent, and specializing for impact**  Workshop name:  "Find your Mozilla Superpower (essential Mozilla, self leadership), based on FSA leadership"
-  **Working Open**  Workshop name: "Open is an Attitude" (working open)

3 More Pending, though won't make it this heartbeat.

Breaking and Building Barriers - Proposing Particiaption
Building Bridges - Based on Makerfaire Education & Hive collaboration in Vancouver
Something for tech women

**Comment by emmairwin** [comment]
Location of curriculum development:  https://github.com/emmairwin/community_curriculum/tree/master/leadership

**Comment by emmairwin** [comment]
Not going to blog about the results at this point, draft versions of workshops are in the repo above, I know I need to make these clearer for editors and will be thinking about that.   Will present outcome in the Demo in Athens
