### ISSUE TITLE
Contribute Page is Set-Up To Run Experiments in Q4 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#141]
## Goal:

By the end of the heartbeat we are confident that the contribute page will be able to be forked in the next heartbeat. 
## Success:
- We have all the elements in place to fork the page by the start of the next hearbeat. 
- We have identified the infrastructure required to run and maintain experiments on the contribute page. 
- We have worked it out with mozilla.org team so that they are happy and comfortable with the new set up. 
## Related Issues & Links:
#113
## Roles:

Owner: @lucyeoh
Involved: @ppapadeas 
Informed: @geroter 
## Required:
- [x] Update proposal for page ownership (@Lucyeoh [medium]Due: Sept 15) 
- [x] Create strategy for email management (@lucyeoh [medium]Due: Sept 17) 
- [x] Run email management proposal by Jess and decide whether it would make sense to got to San Fran (@lucyeoh [medium] Due: Sept 17) 
- [x] Figure out technical requirements for page ownership (@ppadeas [medium]Due: Sept 18th)
- [x] Set meeting with Holly and Jenn to propose new structure (@lucyeoh, [medium], Due: Sept 18th ) 
- [ ] Meet with George to discuss technical requirements for team (@ppadeas @geroter [Small] Due: Sept 30)

**Comment by ioana-chiorean** [comment]
Hey Lucy - let me know when you have anything to test here, will be my pleasure to check the page from a QA perspective!

**Comment by LucyeoH-zz** [comment]
Hey @ioana-chiorean much appreciated! Right now we're just working on how we'll structure ownership but as we get into testing that would be great!

**Comment by LucyeoH-zz** [comment]
Need to decide if this becomes an OKR for Q4.
