### ISSUE TITLE
Community Communications

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#142]
## Goal:

To improve and unify strategies for communicating between Mozilla, core contributors, and volunteer Mozillians. 
## Success:
- An actionable plan for the November Moment in Time Campaign that is in line with internal and external comms
- Support and communicate information about the new NDA process
- Community Feedback Group has a plan for it's fall growth campaign 
## Related Issues & Links:
#119
## Roles:

Owner: @lucyeoh
Involved: 
## Required:
- [x] Update November Moment in Time Plan (@lucyeoh [medium], Due: Sept 22nd) 
- [x] Assign projects for the moment in time plan (@lucyeoh [medium], Due: Sept 22nd) 
- [x] Identify temporary measure for sharing out #moco password and share on Reps-Geeral (@lucyeoh [small] Due: Sept 20) 
- Create a draft of the Core Contributor Trust Agreement (@lucyeoh [medium] Due: Sept 25th) 
- Share draft with Mitchell (@lucyoeh [medium] Due: Sept 28th) 
- Finish strategy for community feedback team (@lucyeoh, [medium], Due: Sept 29)

**Comment by ioana-chiorean** [comment]
Good. I am gonna track this.

**Comment by MichaelKohler** [comment]
Same here. Lucy, could you please share the current time plan for the Moment in Time with me? Quite sure I could help here since I'm also involved with the Campaign (and part of the Wednesday Moments in Time Cross-functional meetings).

**Comment by LucyeoH-zz** [comment]
@ioana-chiorean @MichaelKohler just shared my slides with you for the Nov moment in time campaign. I'd love your feedback but also to see how we can incorporate more contributors into this project.

**Comment by LucyeoH-zz** [comment]
Core contributor trust agreement moved to next Quarter.
