### ISSUE TITLE
Outward Communication

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#143]
## Goal:

Implement outward communication plan, in order to give people a better understanding of who we are as a team prior to Orlando. 
## Success:

We have communicated who we are and our mission to core stakeholders. 
## Related Issues & Links:
#115

[Participation Team Story](https://docs.google.com/presentation/d/1JpA-s3rBVJyAS-lVpILUj-ViY4kXI8_PVP0Enf2wES0/edit#slide=id.g6403de511_0_41)
[Participation Manifesto](https://docs.google.com/document/d/1aVZonT7P1uyvn_bwGYx06piRyOjLF8Wzt737MehERDU/edit#)
[Implementation Strategy](https://docs.google.com/document/d/1b3-QTtRXpdTIyLe6Dq-ud1QVbN1tS-waDh4ZxmGjlAs/edit#heading=h.a597g9xbg6j6)
## Roles:

Owner: @lucyeoh
Involved: @nukeador @deimidis 
## Required:
- [x] Clearly identify our stakeholders (@lucyeoh @deimidis , [medium], Due: Sept 17) 
- [x] Finalize implementation strategy (@lucyeoh @deimidis , [medium], Due: Sept 17) 
- [x] Review current implementation plan with @geroter and get sign off (@lucyeoh [small], Due: Sept 18) 
- [x] Create super short survey to get baseline of current knowledge and understanding from teams (TBD, [small], Due: Sept 18th) 
- [x] Updating the wiki page (@deimidis Due: Sept 18) 
- [x] Draft emails to Participation Leaders (@lucyeoh Due: Sept 23rd) 
- [x] Emails to Reps first pass (@deimidis Due: Sept 30th)
- [x] Review and clean-up  (@lucyeoh Due: Sept 30th)
- [ ] Email to functional team contacts first pass (@deimidis Due: Sept 30th)
- [ ] Review and clean up functional team contacts (@lucyeoh Due: Sept 30th)
- [ ] Talk to stakeholders and measure knowledge/response (@lucyeoh @nukeador @deimidis [medium], Due: Oct 2nd)

**Comment by guillermo** [comment]
I think you reference the wrong @guillermo :-)

**Comment by LucyeoH-zz** [comment]
Sorry @guillermo!

**Comment by LucyeoH-zz** [comment]
Pushing functional team contacts to Q4 (if this gets picked up again).

**Comment by asdofindia** [comment]
@LucyeoH, the "participation team story" doc requires permission. Is this intended?
