### ISSUE TITLE
Workshop Co-Facilitator

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#145]
Volunteer subtask of #140 
## Description

As part of the primary task, we have goals for running 2 in person workshops and 2 online.   I am looking for a co-pilot to run the two online versions **with me**, and THEN in October take what you've learned, and contributed-to and run the workshops in your local area as further tests.
- Please be sure you can commit to attending one preparation session with me  (1-2 hours)
- Please be sure you can co-pilot minimum of one workshop (time TBA but expect 1-2 hours)
- Run the same workshop with a small group in  your local Mozilla community and report back (in October)
## Prerequisite
- [Read this blog post](http://tiptoes.ca/participation-leadership-framework-01/) .
- [Understand the direction we're taking for Leadership during our Global Gatherings](https://wiki.mozilla.org/Participation/Globalgatherings2015)
- Have some experience teaching or facilitating groups (on or offline)
- Be interested in learning how to become a better facilitator and teacher 'by doing'
- Be interested in teaching others how to become better facilitators and teachers ' by doing'
## Participation Steps
1. Confirm you have prerequisites
2. Subscribe yourself to this issue.
3. Leave a comment here and I will reach out to you, please be sure you have the time commitment and local Mozilla community.
## Value to contributor

I hope that you will see this as a great mentoring opportunity, from you to me, and me to you.  A chance to help shape the early stages of community leadership workshops at Mozilla. You will have real input into the process and outcomes.  **This is a great opportunity for people interested in becoming better facilitators**.

**Comment by birajkarmakar** [comment]
@emmairwin I am interested here. Please let me know.

**Comment by ioana-chiorean** [comment]
Hey Emma - I am interested in this also. Let me know of the selection process and next steps.

**Comment by Amena-Islam** [comment]
Hi @emmairwin , I am from Bangladesh. I am very much interested and would love to know further updates regarding this from you. Hope to hear from you soon

**Comment by emmairwin** [comment]
Hey @birajkarmakar @ioana-chiorean  and @Amena-Islam   Thanks so much for your interest!
I am designing two workshops to deliver next week Monday and Tuesday , times to be confirmed but looking to be 9 and 10 AM PDT respectively.   We'll be delivering one to the Tech Speakers, and the other to FSA Student leaders.   

If you think you will be available at these times, and you have personal goals in the community for teaching and facilitating then please reach out to me at eirwin at mozilla.com .  The goals part is important because I want to include this person in more deeply in workshop facilitation in future, so if that sounds like where you want to invest primarily at Mozilla please reach out.

Thanks!

**Comment by emmairwin** [comment]
Thanks everyone, @Amena-Islam (https://mozillians.org/en-US/u/amena-islam/) responded in email, so with time and given her personal goals align with the outcome of teaching & facilitating, am going to include her in the next two workshops.  There will be more opportunities like this though, so stay tuned and thanks again!

**Comment by imromec** [comment]
Hi Emma, I am also interested.

**Comment by ashickurnoor** [comment]
Hello @emmairwin , I am interested to participate and run Workshop Co-Pilot .  I hope I am not too late :) .

**Comment by emmairwin** [comment]
Thanks everyone ! Will ping you in the next heartbeat issues with more opportunity :) this ks amena for attending sessions this week! Hopefully we can figure out better ways to work over low bandwidth

**Comment by Amena-Islam** [comment]
Thanks Emma for the appreciation. Extremely sorry, I couldn't able to keep
my commitment. My bad luck.
I will love to work with you in near future as well.

Thank you.

Amena

**Comment by ioana-chiorean** [comment]
@emmairwin  were the hangouts cancelled? :s

**Comment by Amena-Islam** [comment]
Hi there,

You’ve been invited by Synthiya to join the Dropbox Campus Cup! Campus Cup lets you team up with your classmates to earn up to 25 GB of free Dropbox space for two years!

To earn space, just invite friends and use Dropbox to share, collaborate, and get work done.

Join Campus Cup![2]

Note that you must be a student currently enrolled at a higher education institution in order to participate. Learn more about Campus Cup.[3]

Happy Dropboxing!


 
 Work together, win together. 

____________________________________________________
If you prefer not to receive invites from Dropbox, please go here[4].
Dropbox, Inc., PO Box 77767, San Francisco, CA 94107

[1]: https://www.dropbox.com/l/zJsX1XcVA8MYMx7Jy6QmvB/campuscup?text=1
[2]: https://www.dropbox.com/l/r2F8OtPRxaOc742niTNiIt/campuscup?text=1
[3]: https://www.dropbox.com/l/3cJzmT1rtEnrrAW02GLeVl/help/9131?text=1
[4]: https://www.dropbox.com/l/foxtxTZSytzKs1d5PjSqiJ?text=1

**Comment by MichaelKohler** [comment]
Above comment definitely looks like spam, is there an admin that can delete it?

**Comment by emmairwin** [comment]
Hangouts were not cancelled, just changed to use unhangout - part of the testing & learning for this one was that bit of clunkyness !
