### ISSUE TITLE
Marathi Campaign Leadership and Investment

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#146]
## Goal:

At the end of this heartbeat, we aim to have clear volunteer leadership and investment in this project, ready to work towards goals and using tactics that they helped co-create.
## Success:

The [marketing brief](https://docs.google.com/document/d/1SdBrG4rxVJcpKcYqyoqdIirQecx1QwjMWZjWYReYtMA/edit?usp=sharing) is fully filled out and a tentative date is set to launch the campaign.
## Related Issues & Links:
- Meta: #106 
- Previous: #123 
- [Marketing brief](https://docs.google.com/document/d/1SdBrG4rxVJcpKcYqyoqdIirQecx1QwjMWZjWYReYtMA/edit?usp=sharing)
- [India BCG group](https://discourse.mozilla-community.org/t/bcg-business-colloboration-group/3975/2)
- [Grow Firefox download campaign for Indian Languages Planning Doc](http://bit.ly/1KISsvF)
## Roles:

Owner: @brianking
Involved: @chelseanovak, @djaniketster, @chandrakantd
## Required:
- [ ] Consult with Divyk about the Business Collaboration Group to explore working opportunities (@brianking, [small], Due: 16 Sep)
- [x] Consult with Umesh about the Grow Firefox download campaign for Indian Languages to determine overlap (@brianking, [small], Due: 16 Sep)
- [x] Revised Team members list (@brianking, [small], Due: 23 Sep)
- [x] 2-4 campaign tactics/channels are finalised by the community (@brianking, [medium], Due: 24 Sep)
- [x] Initial set of metrics (@chelseanovak, [medium], Due: 25 Sep)
- [ ] Investigate feasibility of putting APK on SD cards (@brianking, [medium], Due: 2 Oct)

**Comment by brianking** [comment]
Update: nearly all of the tasks are in-progress.

We have @umeshagarwal on board and are merging this with a Hindi promotional campaign. More details soon ... we'll be documenting here on the wiki:
https://wiki.mozilla.org/Participation/India/Android_Marketing

**Comment by brianking** [comment]
The project scope has expanded to also include Hindi. 

Wiki page:
https://wiki.mozilla.org/Participation/India/Marathi_Hindi_Campaign_2015

**Comment by iamVP7** [comment]
@brianking  have a small doubt, how can other languages can participate. Say Tamil is one of the oldest language and other than India many places it is used. How can l10n:ta team can participate in this campaign.

**Comment by chelseanovak** [comment]
Hey there @viswaprasath

This is campaign is a test. We are trying it out in these two languages to
see if this kind of campaign works. If it does, then we will expand it to
include many more locales. If it doesn't, then we will adjust our plans and
try again. The campaign is just running for a month, so we should be able
to report back later in November and then work on a plan for other
languages in 2016.

Thanks!
Chelsea

**Comment by birajkarmakar** [comment]
Hi @chelseanovak 

Sounds good. I am also interested  for bengali language in next cycle.

**Comment by iamVP7** [comment]
Hi @chelseanovak

Cool. Thank you. Will be happy to contribute for spreading awareness about availability in Tamil.

Adding @jskcse4 who is long time L10N contributor for Tamil.

**Comment by brianking** [comment]
This will likely not be carried over to the next Participation team heartbeat as we have achieved our goal of launching a campaign. This will now be led by Community Marketing but we will monitor and assist where needed.

Thanks everyone!
