### ISSUE TITLE
New Logo for Participation

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/participation-org#149]
In February @brianking asked me to create a "quick logo for a small project" while I was in Berlin. As of now, the Participation Team is not anymore a small project, so after having a short chat with Lucy, I went on to refresh it up a bit. Attached is the proposal, together with a preview of how the sticker might look like

Changes made:
- Removed the "Team"
- Went with a less bolder font variant
- Added stroke to the logo, to make it easy to implement in monochrome or color backgrounds

This has been received well by Brian and Lucy but wanted to confirm it officially also here :)

![draft-01](https://cloud.githubusercontent.com/assets/5436686/9871016/fdeeda24-5b90-11e5-967b-f3ec29d5f300.jpg)
![2](https://cloud.githubusercontent.com/assets/5436686/9871017/02932846-5b91-11e5-93d7-b94150db202c.jpg)

**Comment by elioqoshi** [comment]
@geroter would love to get your thoughts

**Comment by brianking** [comment]
This looks great Elio, thanks for making the improvements.

**Comment by comzeradd** [comment]
I'd love to have that sticker to my laptop ;)

**Comment by emmairwin** [comment]
Looks great @elioqoshi  Can you explain the logo though, I've never been sure what it represented (shapes/colors)

**Comment by elioqoshi** [comment]
Thanks Emma! I had the thought of centralized decentralization in mind. A little bit of messy, yet working in unity and still diverse. It's a bit philosophical, not literal :)

**Comment by johngian** [comment]
@elioqoshi awesome work :rocket: 
By the way, are these files somewhere publicly accessible?

**Comment by geroter** [comment]
1) I think the quality of the work is great, and I do love the metaphorical qualities of the logo.

2) I still want to open -- not now but at some point in the future -- the much bigger conversation about the proliferation of logos/images used within and for audiences outside of Mozilla :)

**Comment by elioqoshi** [comment]
Thanks for the feedback!

@geroter , I agree and I do not think that Participation is going to be a brand which is recognized outside Mozilla, as it should be all Mozilla, so I do not see a huge problem here.

I however think that local communities should have their own mozilla brand reflecting their culture and values, as diversity is what brings us together at the end.

**Comment by elioqoshi** [comment]
@johngian they will be if we all are going ahead with this :)

**Comment by LucyeoH-zz** [comment]
@elioqoshi we're going ahead with this! Thanks for all your work with this!!

**Comment by elioqoshi** [comment]
@brianking here is the logo in PNG also

Small
![mozilla participation small](https://cloud.githubusercontent.com/assets/5436686/11299948/5ff25632-8f8b-11e5-8d53-0fdd86519978.png)

Big
![mozilla participation](https://cloud.githubusercontent.com/assets/5436686/11299952/63500158-8f8b-11e5-84b2-94df5cfaff6d.png)

**Comment by comzeradd** [comment]
Do you also have this in vector/svg?

**Comment by elioqoshi** [comment]
@comzeradd here we go: https://dl.dropboxusercontent.com/u/62482708/Mozilla%20Participation.svg
