### ISSUE TITLE
Deliver the community dashboard and report for 10 focus communities

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#150]
## Goal:

Deliver the community dashboards and reports for the 10 focus communities
## Success:
1. A general dashboard with aggregated information is delivered
2. The 10 dashboards for the focus communities are delivered 
3. A report is done for all the 10 focus communities analyzing the dashboard data and the information we collected through our 1:1s
## Related Issues & Links:
#89 #125
## Roles:

Owner: @rosanardila
Involved: @nukeador, @couci @deimidis @francjp 
Consulted: @williamq @brianking 
## Required:
- [x] reach out to communities to get more respondents and allow the interested communities to translate the survey (@rosanardila @deimidis , [small], Due: Sept 15th) 
- [x] Document missing data and make a plan for it (@couci, [small], Due: Sept 18th) 
- [x] Analysis of event data ( @francjp , [medium], Due: Sept 23rd) 
- [x] Close survey and get the data for the analysis (@couci, [medium], Due:Set 23rd) 
- [x] First pass at analyzed data for the focus countries done, raw draft of a report (@rosanardila @deimidis @nukeador , [medium], Due: Sept 25th) 
- [x] Review and finalize reports and dashboards with buddies (@rosanardila @deimidis @nukeador, @couci , @francjp, [large], Due: Sept 29th)

**Comment by couci** [comment]
e-mail about missing data sent to the team, the dashboard will be updated accordingly

**Comment by brianking** [comment]
Review buddy notes / questions:

These might be outside the scope of this heartbeat, but....
- Any update on getting this localised?
- How / where will the data be presented?
- Is there a public sharing plan?

**Comment by couci** [comment]
- @deimidis has already done the localised work with the Brazilian community
- the data will be presented same as the last heartbeat (#125) https://docs.google.com/spreadsheets/d/1E3y0eoNDxQ-dFu5E5B6qHbbOItKAQRzAwIwPzLVWUvM/edit#gid=0 
- all the dashboards (for now we are building the 10 focused countries) will be public

**Comment by deimidis** [comment]
Just to clarify, I trasnlated community survey. I didn't think we are planning to localize dashbord yet. I think will be difficult meanwhile is a spreadsheet (but I don't know too much about Google spreadsheets)

**Comment by francjp** [comment]
Events data analysis presented here: https://docs.google.com/a/mozilla.com/presentation/d/1TwEuVL_KQZ7Mdl5vNuVjWbFsoaay4Hsn4jrga4AVYwU/edit?usp=sharing

Working on present more numbers and analysis soon.

**Comment by LucyeoH-zz** [comment]
6/6 complete! Closing!

**Comment by rosanardila** [comment]
all dashboards done and in this folder: https://drive.google.com/drive/u/0/folders/0B3CuegKgwkKkS2pQalF1STRCaTA
