### ISSUE TITLE
Deliver the mid-term plan for 3 communities

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#151]
## Goal:

Deliver the mid-term plan for Indonesia, Mexico and Germany
## Success:
1. Have a mid-term plan drafted
2. Have the majority of the community aligned around the plan
3. Document the learnings
## Related Issues & Links:
#90  #126
## Roles:

Owner: @rosanardila
Involved: @deimidis @nukeador 
Consulted: @couci @francjp  @MichaelKohler
## Required:
- [x] get the draft of the plan circulating with the larger community (@rosanardila @deimidis @nukeador , [small], Due: Sept 22nd)
- [x] get feedback from the community and adjust plan accordingly and with the community's support (@rosanardila @deimidis @nukeador, [medium], Due: Sept 25th)
- [ ] have a plan for the next 6 months that the majority of the community is aligned with  (@rosanardila @deimidis @nukeador, [medium], Due: Sept 29th)

**Comment by brianking** [comment]
Review buddy review / Questions:
- By _draft_, do you mean template? Do all communities have to use this or will there be room for a more customised plan?

**Comment by rosanardila** [comment]
Here are the presentation and the planning document that we're using to help the communities in this process: 
- [Presentation](https://docs.google.com/presentation/d/1U2yRp3Uomlyx9h-B59_wpH3EKOciULvFSZXzcvM9U9o/edit#slide=id.gc95ef35e2_0_10)
- [Planning document](https://docs.google.com/document/d/1LRS4mKCumoVKHD6nQYN4i8HUCUlASZgvY3ktY1PO_hk/edit)

**Comment by birajkarmakar** [comment]
Hi @brianking , @rosanardila and all
This is great initiative. Though I am not from above country but I have some plans to make healthy regional community. 

Actually I drafted a regional community structure, I would like to share with you all, if you give me to chance to say here. That will help mostly to increase more participation in regional communities.

**Comment by nukeador** [comment]
We had meetings with Mexico, Indonesia and Germany communities to start the mid-term plan, so we are on track but we'll need more time to come up with the final version of them (communities will probably need at least a month to do the full process).

This is something we should carry over next HB for sure.

**Comment by rosanardila** [comment]
All communities planning, we have feedback on the planning process. We learned that planning takes much longer, so we'll continue the process in Q4.
