### ISSUE TITLE
Deliver a framework for coaching and supporting focus communities in Q4

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#152]
## Goal:

Deliver a framework for coaching and supporting focus communities in Q4
## Success:
1. Document all the learnings from Q3
2. Create a framework for coaching volunteers
3. Design a system for provided ongoing support to focus communities through coaching and high touch interaction
## Related Issues & Links:
#91 #127
## Roles:

Owner: @rosanardila
Involved: @deimidis @nukeador @couci @francjp 
Consulted: @geroter 
## Required:
- [x] Distill the learnings from the 1:1s (@nukeador, @deimidis, @rosanardila, [medium], Due: Sept 22nd)
- [x] Have 1:1s with 40 volunteers (@nukeador, @deimidis, @rosanardila, @couci, @francjp  [large], Due: Sept 28th)
- [x] Deliver a system to provided ongoing support to focus communities through coaching and high touch interaction (@nukeador, @deimidis, @rosanardila, [medium], Due: Sept 30th)

**Comment by brianking** [comment]
Review buddy review / questions:
- Are there links to any docs or other resources related to this? If so, please edit and add to the description.

**Comment by rosanardila** [comment]
We weren't able to complete the 40 1:1s due to lack of time and because it proved difficult to schedule them with volunteers.

**Comment by nukeador** [comment]
But we completed the 40 1:1s if we consider the coaching sessions we did for the global gathering events too.

**Comment by rosanardila** [comment]
Framework and plan for Q4 here: https://docs.google.com/document/d/1UL5I0XJ_tbznn5z32a4YPqm4Ut_jhjJTse-FOgDjLRs/edit
