### ISSUE TITLE
Design and run Fx OS Participation Q4 planning meetup

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#153]
## Goal:

Host a meetup with all Fx OS Participation stakeholders that aims to get everyone aligned and produces a Q4 action plan for participation. 
## Success:
1. Q4 participation plan for Firefox OS is drafted
2. 100% alignment from all key stakeholders around Q4 plan
3. Document and socialise plan with leadership
## Related Issues & Links:
#131  #134
## Roles:

Owner: @williamq
Involved: @bking
Consulted: @geroter 
## Required:
- [ ] send email to team detailing objectives and outcomes of meeting
- [ ] decouple schedule from agenda
- [ ] update sessions
- [ ] harmonize expectations during Fx OS Participation weekly call 
- [ ] negotiate with people beforehand (what are the conflicts)
- [ ] talk to each participant and figure out what they want
- what do you think the group as a whole should accomplish?
- what do you want to accomplish yourself?
- what topics should we talk about?
- what do you think we might disagree on?

**Comment by LucyeoH-zz** [comment]
29th and 30th of September
