### ISSUE TITLE
Lock-down plan for Phase 2 of Foxfooding program

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#154]
## Goal:

Finalize plan of Phase 2 of Foxfooding program and get buy in from all stakeholders
## Success:
1. Plan is finalised and ready for implementation in Q4
2. 100% alignment from all key stakeholders 
3. Document and socialise plan with leadership
## Related Issues & Links:
#134
## Roles:

Owner: @williamq
Involved: Jean Gong, Dominik Strohmeier, Peter Dolanjski
Consulted: @geroter 
## Required:
- [ ] Draft summary document of Foxfooding planning week in SF (see #134)
- [ ] Define and agree on clear KPIs with Dominik
- [ ] Work with Asa and Lissy to get FxOS installer xpi finalised
- [ ] Define vetting process for volunteer foxfooders
- [ ] Draft logistic plan with WPR
- [ ] Create marketing/comms plan with Marvin 
- [ ] Test first beta of Participation Hub with Pierros

**Comment by LucyeoH-zz** [comment]
Review Buddy Notes: 
- Add dates, owners, and project sizes. i.e. "(owner [medium], Due: Sept 22nd) "
- Add to "Final Q3 Heartbeat" Milestone and Assign yourself.
