### ISSUE TITLE
Integrate with CommunityOps community

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/participation-org#155]
## Goal:

Integrate infrastructure deployment operations with CommunityOps team.
## Success:
1. Core CommunityOps team members have access on our AWS instance and deployed a test
2. Documentation is in place for practices, policies and inner workings
## Roles:

Owner: @ppapadeas
Involved: @johngian , @comzeradd , @akatsoulas 
Consulted: @geroter 
## Required:
- [x] Pierros ensures NDA and legal items
- [ ] IAM tokens and roles generated
- [ ] Successful and verified access on AWS PartInfra account
- [ ] Documentation is complete on process and policy
- [ ] A test is deployed by CommunityOps team

**Comment by LucyeoH-zz** [comment]
Flags: 
- Need to add estimated dates

**Comment by asdofindia** [comment]
Has this idea been dropped?

**Comment by buluma** [comment]
ongoing
