### ISSUE TITLE
Athens training days logistics part 2

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#156]
## Goal:

Co-ordinate the logistics for a nice stay in Athens
## Success:
1. All supplies bought
2. Every team member has the needed information for a pleasant stay in Athens
## Related Issues & Links:
#124
## Roles:

Owner: @couci
Involved: @LucyeoH 
## Required:
- [x] E-mail the owner and ask for the villas' facilities (@couci [small], Due: Sept 18th)
- [x] Remind the team about their room mates (@couci [small], Due: Sept 18th)
- [x] Co-ordinate last minute changes with cars (@couci [medium], Due: Sept 18th) 
- [x] Inform the team on weather and location of the villa (@couci [small], Due: Sept 28th)
- [x] Share contact info with the team and remind of the car pool schedule (@couci [small], Due: Sept 29th)
- [x] Buy all the work and food supplies needed (@couci,@LucyeoH [medium], Due: Oct 2nd)

**Comment by rosanardila** [comment]
Kudos Konstantina and Lucy for an amazing job on this one!!!
