### ISSUE TITLE
Financial Role in the community

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#157]
## Goal:

Create a financial plan for our 10 communities
## Success:
1. Define the role of the financial specialist
2. Draft a reusable template for the communities
## Related Issues & Links:
#151 #152
## Roles:

Owner: @couci
Involved: the Indonesian community
Consulted: @francjp
## Required:
- [x] E-mail Andi to brainstorm about his idea on the financial role (@couci [small], Due: Sept 18th)
- [ ] Draft a role definition (@couci [medium], Due: Sept 23rd)
- [x] Define the person inside the community (@couci [medium], Due: Sept 26th)
- [ ] Create a template for the financial plan (@couci,@francjp (for feedback), Due: Sept 30th)

**Comment by andi-belutz** [comment]
Meeting notes
https://etherpad.mozilla.org/Community-Finance

**Comment by couci** [comment]
@andi-belutz and Dian Ina are the two people responsible right now in the Indonesian community

**Comment by alamanda** [comment]
made some comments to the etherpad;)

**Comment by couci** [comment]
Need to transform the meeting notes into a defined role. Based on that we will create the template
