### ISSUE TITLE
Select, invite and coordinate visas and flights for global gatherings/participation leaders

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#159]
## Goal:

Finalize the selection of applicants, and invite those selected to all global gatherings. Have all flights booked and/or visas initiated for MozFest and the All Hands, have logistics steps fleshed out and communicated for the Leadership Summit.
## Success:
1. Selection process identifies applicants who reach a “bar” on leadership qualities, and balances diversity (gender, background, geographic), functional team/Mozilla needs, and budget. These considerations are clearly communicated to selection committee, functional teams and applicants/other stakeholders.
2. Invitations are sent for all global gatherings, with personal language and clear next steps for logistics and interactions (including setting up for a 1:1 conversation with each participant in advance of each gathering).
3. Flights are booked for MozFest. Visas are initiated for MozFest and the All Hands.
4. A tracking process is in place (including a dashboard with regular updates) for each step of the logistics process (communication, flight booking, visa, accommodation, etc.).
5. A coaching process is initiated for feedback to unsuccessful and successful applicants.
## Related Issues & Links:
#112
## Roles:

Owner: @geroter
Involved: @francjp
Consulted: All Participation Team + community managers + Directors
## Required:
- [x] Initial evaluation of applications and short-listing for each gathering (@geroter, [large], Due: Sept 18) 
- [x] Highly detailed logistics plan and resources (including invitation letter templates, visa letter templates, communication/email templates, etc) and tracking dashboard finalized and ready to put into action (@francjp, large, Due: Sept 21)
- [x] Final selection, with functional team input, completed (@geroter, large, Due: Sept 22) 
- [x] Invitation letters sent, setting up for flights and visas for MozFest/Orlando (@francjp, medium, Due: Sept 23)
- [x] Communication sent – to applicants and others – explaining selections and setting up coaching process (@geroter, small, Due: Sept 23) 
- [x] Flights/accomodations are booked for MozFest. Visas are initiated for MozFest and the All Hands. (@francjp, large, Due: Sept 30)

**Comment by francjp** [comment]
Logistics Plan: https://docs.google.com/a/mozilla.com/spreadsheets/d/1CYfE3HOaOTZ_vj6U9wBUnIQ3YbmFjayXUMEhz5QhAdY/edit?usp=sharing

**Comment by geroter** [comment]
All DONE!! Phew.
