### ISSUE TITLE
H2: Finish implementation of Global Communications volunteer group

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#16]
<h1>Project Description</h1>

Implementing a volunteer led Global Communications Group that distributes and collects feedback from major Firefox OS announcements. 

<h1>Why</h1>
- Provide Mozillians with reliable, locally relevant, and organized sources of information
- Make major communications a point of value and connection for community 
- Create a community-driven system for collecting community feedback/reactions after announcement 
- Make it easier to direct and localize communication
- Minimizes leaks by growing and strengthening the invested community and increasing control over communication

<h1>Primary Goals & Objectives</h1>
-  Establish a network of representatives from each major communication community who can help craft communications before they go out and collect feedback and sentiments from their communities after announcements are distributed.  
-  Provide basic training for representatives and host introductory meeting. 

<h1>Secondary Goals & Objectives</h1>
-  Set-up a web platform for distributing <strong>public/Mozillians only </strong>announcements that can be updated regularly
-  Set-up a web platform for <strong>closed/NDA</strong> announcements that can be updated regularly 

<h1>Team</h1>
- Owner @lucyeoh
- Members: @francjp @deimidis @bacharakis @flore-mozfr 
- Informed: @rosanardila 

<h1>Milestones (complete before dates)</h1>
- [x] Identify the largest communication communities (due May 15)
- [x] Identify one or two representatives for each of those communities: 
  - [x] Mozilla Francophone (@flore-mozfr due May 20)
  - [x] Mozilla Hispano (@bacharakis due May 20)
  - [x] Mozilla Balkans (@bacharakis due May 20)
  - [x] Arab Community (@bacharakis due May 20)
  - [x] Mozilla India (@bacharakis due May 20)
  - [x] Mozilla Brasil (@bacharakis due May 20)
  - [x] Mozilla Africa (@lucyeoh due May 20)
  - [x] Reps (@bacharakis due May 20)
  - [x] FSA (@Lucyeoh due May 20)
  - [x] L10N (@Lucyeoh due May 20)
  - [x] SUMO (@bacharakis due May 20)
- [x] Organize training for communication representatives with Communications Team
  - [ ] Talk to Mary about PR training (@Lucyeoh due May 21st)
  - [x] Talk to Laura Napoli (@lnapoli) about her work with PR training + Reps (@lucyeoh due May 21st)
- [x] Invite all representatives to a meeting 
- [ ] Create web platform for Mozillians where we can put up announcements (Owner: @bacharakis)
   -[ ] Create implementation strategy/assess feasibility @ppapadeas @bacharakis ( due ?) 
   -[ ] Timeline for creation @ppapadeas @bacharakis ( date TBD)

**Comment by LucyeoH-zz** [comment]
@deimidis you can see an updated list of what we're working on this week in our Milestones. This week we're focusing on identifying and contacting someone from each of the groups highlighted in yellow on this document http://ow.ly/MhfkU. Feel free to jump in if there is anyone from these groups you'd like to contact. We're aiming to share the responses we've received at our next meeting May 22nd (invitation sent).

**Comment by LucyeoH-zz** [comment]
Also let's not forget to give feedback on this doc for Rosana: https://docs.google.com/document/d/11kUuBcqWYjEDXKuh-AeI7RXAdbHd3nVIzng-eqmSasI/edit @francjp @deimidis @flore-mozfr @bacharakis by next Wednesday May 20th.

**Comment by LucyeoH-zz** [comment]
@flore-mozfr @bacharakis  Here's the copy I've been using for my emails if you want to use it to align our communications or adapt it for the people you're contacting! https://docs.google.com/document/d/1a-A3JDITG8nH2McB9LodAtmj08Ycy0CZuilFgl6g_q4/edit?usp=sharing

**Comment by goofy-bz** [comment]
nit-picking as usual
*Notez qu'en français le deux-points doit être précédé d'un espace (insécable)

**Comment by LucyeoH-zz** [comment]
Took a first stab at putting together a really basic page for us on the wiki. Please feel free to edit/beautify etc. https://wiki.mozilla.org/Participation/GlobalComms

**Comment by LucyeoH-zz** [comment]
- What was supposed to happen?
  Gather and plan training for representatives
- What did happen?
  We gathered representatives and planned training
- What are some improvements we should make?
- What should we keep the same in this process?
- What does the next Heartbeat for this project look like?
