### ISSUE TITLE
Start building out basis of Firefox OS participation program

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#160]
## Goal:

With the participation plan now in place (pending approval), we should move forward and lay the groundwork for a successful program.
## Success:

At the end of this heartbeat, we would have contributor roles defined (and role of Firefox OS community manager), a prototype of a participation hub, and have researched the basics of a first class open source project to determine gaps to be filled.
## Related Issues & Links:

Meta: #88 
Past: #96 #95 #94 #93 #92
## Roles:

Owner: @williamq 
Involved: @brianking
## Required:
- [ ] List technical contribution opportunities for b2gDroid and Ports - project specific (@brianking @autonome, [medium], Due: Sep 1st) 
- [ ] List basics of top level open source project, analyze what Firefox OS needs (@brianking @autonome, [medium], Due: Sep 3rd) 
- [x] Build out Firefox OS technical contributor role descriptions / personas (@brianking, [medium], Due: Sep 4th) 
- [ ] Base Firefox OS Participation Wiki Page built (@williamq , [medium], Due: Sep 4th) 
- [x] Identify/create all relevant communication channels for Fx OS Participation (@brianking, [medium], Due: Sep 7th)
- [ ] Scope out role of Firefox OS Community Manager (@brianking @mhoye, [medium], Due: Sep 11th)

**Comment by williamq** [comment]
This is a heartbeat carried over from #130

**Comment by 1Jamie** [comment]
If any help is needed for the site i am happy to help.
