### ISSUE TITLE
Firefox OS Participation Logo

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/participation-org#163]
Here is the Firefox OS logo with the Participation subtitle (requested by @brianking and @williamq )
https://dl.dropboxusercontent.com/u/62482708/Firefox%20OS%20Participation.zip

**Comment by elioqoshi** [comment]
![horizontal small](https://cloud.githubusercontent.com/assets/5436686/10513888/dc3cb28a-734a-11e5-853a-0f3d58927846.png)

![vertical small](https://cloud.githubusercontent.com/assets/5436686/10513887/dc37ccf2-734a-11e5-8392-942fe1d8e05b.png)

**Comment by geroter** [comment]
I love that Firefox logo with the added wordmark :)

On Thu, Oct 15, 2015 at 8:41 AM, Elio Qoshi notifications@github.com
wrote:

> [image: horizontal small]
> https://cloud.githubusercontent.com/assets/5436686/10513888/dc3cb28a-734a-11e5-853a-0f3d58927846.png
> [image: vertical small]
> https://cloud.githubusercontent.com/assets/5436686/10513887/dc37ccf2-734a-11e5-8392-942fe1d8e05b.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/participation-org/issues/163#issuecomment-148373652
> .

## 

George Roter
Head of Core Contributors, Participation

irc: geroter  |  skype: geroter
Cell - Canada: 416.670.2401
Cell - USA: 650.485.0079
<650%20308%208443>

**Comment by elioqoshi** [comment]
@geroter I thought that! Was afraid you'd kill me if I invented the wheel :P

**Comment by brianking** [comment]
Thanks @elioqoshi these look great.

**Comment by LucyeoH-zz** [comment]
Awesome work @elioqoshi !!!
