### ISSUE TITLE
[Global Gatherings] Logistics for Leadership Summit in January

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#164]
## Goal:

Confirm and finalize logistics for Leadership Summit in Singapore
## Success:

Define venue and hotel, with all the logistics involved to have a great event.
## Related Issues & Links:

https://github.com/mozilla/participation-org/issues/159 and https://docs.google.com/a/mozilla.com/spreadsheets/d/1CYfE3HOaOTZ_vj6U9wBUnIQ3YbmFjayXUMEhz5QhAdY/edit?usp=sharing#
## Roles:

Owner: @francjp, @geroter 
Involved: @emmairwin 
## Required:
- [x] Review the logistics plan for Leadership Summit (@francjp, [small], Due: Oct 20th) 
- [x] Define budget for the event (@geroter, [medium], Due: Oct 22nd) 
- [x] Create and open the registration form (@francjp, [medium], Due: Oct 24th)
- [x] Create an FAQ for volunteers and publish on Discourse (@francjp, [medium], Due: Oct 24th)
- [x] Confirm venue and hotel (@francjp, @geroter , [large], Due: Oct 30th) 
- [ ] Confirm vendor and other logistics issues (@francjp, @geroter , [large], Due: Nov 6th) 
- [ ] Review and book dinners (@francjp, [medium], Due: Nov 6th)

**Comment by LucyeoH-zz** [comment]
Move to the next heartbeat?

**Comment by francjp** [comment]
Hi @LucyeoH yes, please... forgot to update this anyway

**Comment by francjp** [comment]
Updating goals achieved... this is moving to the next heartbeat
