### ISSUE TITLE
H2: Track/support Participation Lab experiments

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#17]
<h1>Project Description</h1>

Goal 1: We will track and support both focused and distributed Participation Lab experiments. 
Goal 2: To create a registry of ongoing participation activities where somebody is trying that is a new way to do participation that has not been done before

<h1>Why</h1>
- To bring more teams and experiments into the Participation Lab
- To have a central way of tracking and supporting ongoing experiments
- To identify trends and track results of various experiments in a central place
- To see the participatory activities that are going on in the organization so we can see holes and patterns

<h1>Primary Goals & Objectives</h1>
-  Continue tracking
-  Make sure the learning goals are solid for each experiment currently being tracked and that we're set up for lessons 
-  Create a registry of the participatory actions that are going on in the organization

<h1>Secondary Goals & Objectives </h1>
-  Implement system to share the progress of ongoing experiments & lessons each heart beat 

<h1>Team</h1>
- Owner @lucyeoh
- Members: @emmairwin @geroter 
- Informed: 

<h1>Milestones (complete before dates)</h1>
- [x] Follow-up with outstanding people from H1 (@emmairwin @lucyeoh due by May 19th)
- [x] Make sure the learning goals are really solid for each experiment
- [x] Create a registry of the participatory stuff going on in the organization
  - [x] Create a spreadsheet to collect registry information
  - [x] Book 10 mins to get initial info from William, Brain, Emma
- [ ] Condense and create report about experiments before demo call (due by June 2nd)

**Comment by emmairwin** [comment]
Demo Report
- What was supposed to happen?
  
  Create a registry
  
  Create a share-out for all experiments
  
  Shore-up learning goals
- What did happen?
  
  Created a registry
  
  Decided to wait until we have concrete learnings to share then will create a report
  
  Started identifying learning milestones vs. project milestones 
- What are some improvements we should make?
  
  Stay the course
  
  Crowd source for registry experiments
- What should we keep the same in this process?
  
  Regular meetings and updates
- What does the next Heartbeat for this project look like?
  
  Review current listings and flag ones we need to push for learning results now

**Comment by LucyeoH-zz** [comment]
Enlisted experiments - https://docs.google.com/spreadsheets/d/1CIuBlRt6dmBD_JbDpjqDhun9JVGYYf-ehLIasOKltLk/edit
