### ISSUE TITLE
Finish mid-term plan for 3 focus communities

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#175]
## Goal:

Finish mid-term document and get general agreement within in Mexico, Germany and Indonesia communities
## Success:
- Final draft for the plan is delivered (vision, goals and objectives) by communities and there is a general support.
## Related Issues & Links:

Meta issue #171 
## Roles:

Owner: @nukeador
Involved: @rosanardila @deimidis 
## Required:
- [x] Check Mexico mid-term status (@deimidis [small], Due: Oct 23th) 
- [x] Check Indonesia mid-term status (@rosanardila [small], Due: Oct 23th) 
- [x] Check Germany mid-term status (@nukeador [small], Due: Oct 23th) 
- [ ] Help finishing the draft (Due: Oct 30th)
- [ ] Deliver mid-term plans (Due: Nov 3rd)
- [ ] Get community general support  (Due: Nov: 6th)

**Comment by nukeador** [comment]
Mid-term plan for Germany is still work in progress, there are already some discussions open.

**Comment by deimidis** [comment]
We had another meeting to define next steps. All communication is being made on Discourse

**Comment by gaby2300** [comment]
Awesome! I'll be available to help all I can with my 2 flame devices!!

Many thanks!
Best regards,
Gabriela
QA Mozilla Hispano Team Responsible

http://www.mozilla-hispano.org
http://twitter.com/mozilla_hispano
http://facebook.com/mozillahispano

**Comment by nukeador** [comment]
Currently conversations in the German community are moving and we are around 70% to get a final doc with goals. For sure this will have to be carried to next heartbeat.

**Comment by LucyeoH-zz** [comment]
Thanks for the comment!
