### ISSUE TITLE
Reps integration with November Firefox OS efforts

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#176]
Part of Objective 1 #189 
## Goal:

Work with partnership team on defining a strategy where Reps can chime in the November Firefox OS efforts, specially in all the activities around the hub.
## Success:

20% of Rep activity aimed at supporting Firefox OS
## Related Issues & Links:

Meta #172
Depends on #183 
## Roles:

Owner: @nukeador
Involved: @rosanardila
Informed: @brianking @williamq 
## Required:
- [x] Check-in meeting with partnership team (@nukeador [small], Due: Oct 23th)
- [ ] Action plan for Reps delivered (@nukeador [large], Due: Nov 5rd)

**Comment by nukeador** [comment]
We are drafting some comms for this week and early next week about this. I'm waiting to have the final dates and content to adapt the message.

**Comment by nukeador** [comment]
Action plan will be aligned with mozillians plan. Working with Brian and William on it.

**Comment by rosanardila** [comment]
is there anything planned for MozFest?

**Comment by nukeador** [comment]
Depends on when the Hub is going live. If we get it in time for the weekend we should ask people to sign-in for the foxfooding program.

**Comment by brianking** [comment]
We sent a call to action to all sponsored attendees to sign up for dogfooding.

Here are other Firefox OS activities happening there:
https://docs.google.com/spreadsheets/d/1-yPgPOZfsnvAmpyplsVNb0ppDpM88oznkIxsPnN67Fw/edit?usp=sharing
