### ISSUE TITLE
[Deleted] Identify Each Community Communication Channel and Create Draft Strategy Plan 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#178]
## Goal:

Each community communication channel is listed and a coordinated strategy plan is established that encompasses all of them. 
## Related Issues & Links:
#122
## Roles:

Owner: @lucyeoh
Involved: @deimidis 
## Required:
- [ ] Identify major methods that Mozilla uses to communicate with the community (@lucyeoh, [medium], Due: Oct 27th) 
- [ ] Identify the audience, and where we want to move them via collective communication  (@lucyeoh, [medium], Due: Oct 27th) 
- [ ] Formalize strategy for consolidating communication with each group  (@lucyeoh, [medium], Due: Nov 6th)

**Comment by ioana-chiorean** [comment]
@LucyeoH was this for the spreadsheet containing all communication channels for all communities?

**Comment by LucyeoH-zz** [comment]
Hey Ioana, yah I have a bunch of those spreadsheets. I'm pushing this for now as we're building out infrastructure for the NDA process that I think will facilitate this kind of communication in the future.
