### ISSUE TITLE
Implement coaching system

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#180]
## Goal:

Implement first iteration of plan developed in last Heartbeat
## Success:

Reach 30 core contributors, 90 active members and 45 emerging members and established a relationship with them. 
## Related Issues & Links:

Meta issue #171
## Roles:

Owner: @deimidis
Involved: @rosanaardila, @nukeador, @emmairwin, @geroter
## Required:
- [x] Define our involvement at MozFest coaching process (@deimidis, @rosanardila, @nukeador [small], Due: Oct 21st)
- [x] Create list of Core contributors that will be coach/mentored (@deimidis [small], Due: Oct 21st)
- [x] Create list of Core contributors that will be coach/mentored (@rosanardila [small], Due: Oct 21st)
- [x] Create list of Core contributors that will be coach/mentored (@nukeador [small], Due: Oct 21st)
- [x] Set meetings with active members and emerging volunteers (@deimidis [medium], Due: Oct 28)
- [x] Set meetings with active members and emerging volunteers (@nukeador [medium], Due: Oct 28)
- [ ] Set meetings with active members and emerging volunteers (@rosanardila [medium], Due: Oct 28)
- [x] Agree on guide to coach/mentoring session pre MozFest (@deimidis, @rosanardila, @nukeador, @emmairwin, @geroter)

**Comment by brianking** [comment]
@deimidis Don't forget to add Labels, Milestone, and Assignee.

**Comment by LucyeoH-zz** [comment]
How did this go?

**Comment by nukeador** [comment]
We did the coaching sessions with @emmairwin help
