### ISSUE TITLE
Foxfooding - Road To Public Launch

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#183]
## Goal:

Start Phase 2 of the Foxfooding Program
## Success:

The Firefox OS Participation Hub goes live and Mozillians have started to apply for the program
## Related Issues & Links:

Meta: #182
## Roles:

Owner: @williamq
Involved: @brianking, Firefox OS Participation Team
## Required:
- [ ] Metrics: Deliver full list of quests to Dominik (@williamq, [medium], Due: Oct 30th)
- [ ] Legal: Draft public wiki page detailing data that Mozilla will be collected through the Foxfooding program (@williamq, [medium], Due: Oct 30th)
- [ ] Legal: Draft rules and guidelines for Mika Challenge (@williamq, [medium], Due: Oct 30th)
- [x] Legal: Draft consent document detailing to device recipient that device is the property of Mozilla and can be reclaimed at any moment (@williamq, [medium], Due: Oct 30th)
- [x] Hub: Create copy for Hub (@brianking @williamq, [medium], Due: Oct 30th)
- [ ] QA: Update triaging process (Marcia Asa @williamq, [medium], Due: Oct 30th)
- [ ] Devices: Finalise device storage and shipment process (@williamq Jean, [medium], Due: Oct 30th)
- [x] Devices: Document vetting process that will help us identify committed and passionate foxfooders (@brianking @william, [medium], Due: Oct 30th)
- [x] Communications: Lay foundations for newsletter, news updates on hub, and Mika reports (@brianking Asa, [medium], Due: Oct 30th)
- [x] Community Engagement: Plan to engage Mozillians before and during launch of the Hub (@brianking @nukeador, [medium], Due: Oct 26th)

**Comment by LucyeoH-zz** [comment]
Seems like you might be able to consolidate into one issue to reflect the new KR "500 Foxfooding ADUs and 2,000 MAUs"?

**Comment by brianking** [comment]
@LucyeoH I'm confused. Isn't #182 a quarter-wide meta issue and this one is just for a single heartbeat. I'm not sure why they should be merged, unless you are referring to another issue.
