### ISSUE TITLE
[KR 4] 8 meetups/hack-a-thons/etc with 100 unique people in Berlin, with substantial contributions team priorities (FxOS, Marketing/Brand and Advocacy)

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#184]
Related to Objective 1 #189 
## Goal:

8 meetups/hack-a-thons/etc with 100 unique people in Berlin, with substantial contributions team priorities (FxOS, Marketing/Brand and Advocacy)
## Related Issues & Links:
#105
## Roles:

Owner: @brianking
Involved: @mariobehling, @geroter
## Key results:
- 10 Volunteer leaders onboarded to Mozilla and areas of contribution to drive
- 6 functional plans for 2016 to be integrated into a larger holistic plan for the German Community being driven by the Reps/Regional team
## Heartbeat Issues:

November 6 - #185
November 27 -
December 19 -

**Comment by MichaelKohler** [comment]
cc @fiji-flo
