### ISSUE TITLE
Create reports that reflect the current Participation structure

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#186]
## Goal:

Create sub budget reports for the sub-teams and a general budget report for the Participation team.
## Success:
- All reports are in by the end of the heartbeat.
## Related Issues & Links:

Meta #181 
## Roles:

Owner: @couci
Involved: 
Informed: @rosanardila @geroter 
## Required:
- [x] Reports based on the old structure for July (@couci [medium], Due: Oct 23th)
- [x] Rere report, including Reps and Regional (@couci [medium], Due: Oct 23th)
- [x] Participation partnership report and Swag report  (@couci [medium], Due: Oct 30th)
- [x] Infrastructure  report and leadership development  report  (@couci [medium], Due: Nov 2nd)
- [x] Team general costs report and Participation's team report (@couci [medium], Due: Nov 4th)

**Comment by couci** [comment]
All the July reports (that are based on the team's old structure) are in. Links can not be added here since they contain actual budget info that can not be public.

**Comment by couci** [comment]
the new reports will be based on this presentation https://docs.google.com/presentation/d/1qEEZys4_7ZSUGLK2ScUS6GqE9L-5dMeTRy5pA7M1dsE/edit#slide=id.gc6ad03242_1_5

**Comment by couci** [comment]
The following changes on the reports were made in order to reflect current team's structure:
- Reps Special and Regional were merged into Global - Local
- Reps Swag has been renamed to Participation Swag (in order to cover all team's requests)
- Community Ops has been changed to Infrastructure
- General Costs now include costs for Affiliated spaces that the Participation team is supporting
- New report for partnerships costs was created
- New report for leadership development costs was created

**Comment by couci** [comment]
Monthly template v.1 can be found [here](https://docs.google.com/spreadsheets/d/1TCnYG-u5pIf-5njZVjZEpvHlgLYyyyMDLjVv9A4eM5Q/edit#gid=1821395361)

**Comment by couci** [comment]
Monthly template v.2 can be found [here](https://docs.google.com/spreadsheets/d/1VEHSDNYGENlCGs45Nq73hVVIIunOAa8DlfDCS_vn40U/edit#gid=0)

**Comment by couci** [comment]
team's report has been updated in order to be able to adjust to team's new structure

**Comment by couci** [comment]
swag reports are also in

**Comment by couci** [comment]
all reports are in, will send them for final feedback to @rosanardila before they appear on the team's folder.

**Comment by LucyeoH-zz** [comment]
Yay closed!!
