### ISSUE TITLE
Definition of the financial role in the community

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#187]
## Goal:

Draft the definition of the role and meet again with the community on agreeing with the definition and the tracking tools.
## Success:
- Definition is in
- Community is agreeing and start implementing the role in the community
## Related Issues & Links:
#157

Meta #173 
## Roles:

Owner: @couci
Involved: @rosanardila @andi-belutz  @alamanda
Informed: @the Indonesian community
## Required:
- [x] Transform the meeting notes into a defined role and share for final feedback (@couci [medium], Due: Oct 30th)
- [ ] Meet with the community, make last changes and define tracking tools  (@couci @rosanardila [small], Due: Oct 31th)

**Comment by couci** [comment]
Here are the [meeting notes](https://docs.google.com/document/d/1gSMGeA1AZH1afjobVL97slHCqdzymAxaWcPvmApkFik/edit?usp=sharing) from the first meeting with @andi-belutz. I've added them here since we lost the etherpad

**Comment by couci** [comment]
Here is the first [draft](https://docs.google.com/document/d/1gSMGeA1AZH1afjobVL97slHCqdzymAxaWcPvmApkFik/edit) @andi-belutz @alamanda you both have edit rights so feel free to hack it :) The doc is also open for comments in case someone else would like to add feedback

**Comment by LucyeoH-zz** [comment]
Did this get finished?

**Comment by couci** [comment]
the definition is in, moving the meeting on the next heartbeat
