### ISSUE TITLE
Run Training at MozFest with Participation Leaders around Internalizing New Strategic Articulation 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#195]
## Goal:

Run a quick session with the 50+ core contributors attending MozFest about the updated Vision & Strategy for Mozilla. 
## Success:

Individuals who attend session are more aware of the new strategic articulation and can articulate it clearly to others. 
## Related Issues & Links:

[link](https://drive.google.com/a/mozilla.com/file/d/0B6wFp2KL3t9Vd05QX3RXYXcxRlU/view) #191
## Roles:

Owner: @lucyeoh
Involved: @emmairwin 
## Required:
- [x] Meet with Emma to discuss where/when this could happen (@lucyeoh, [small], Due: Oct 26th) 
- [x] Plan  (@lucyeoh, [small], Due: Oct 28th
- [x] Announce ( (@lucyeoh, [small], Due: Nov 2th
- [x] Run  (@lucyeoh, [small], Due: Nov 11th)

**Comment by ioana-chiorean** [comment]
:tada:
