### ISSUE TITLE
[KR 3] FirefoxOS Participation Hub v1

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/participation-org#197]
## Goal:

v1.0 of the Firefox OS Participation Hub is deployed
## Success:

by Nov 2nd with 80% of agreed scope and features (90% by Nov 15)
## Related Issues & Links:

[project brief](https://docs.google.com/document/d/1ODTmreY0vveBSN5y2AqF8t8QH_aM7BEd_XuqP8-5iX8/edit?ts=5617b5d2#)
## Roles:

Owner: @ppapadeas
Involved: @comzeradd , @akatsoulas , @johngian  
## Required:
- [x] UI Mockups are delivered
- [x] Project brief is approved
- [x] Deployment infrastructure is in place
- [x] Back-end development done
- [x] Deploy to productions

**Comment by ppapadeas** [comment]
UI mockups are delivered https://seacloud.cc/d/36c716313d/

**Comment by ppapadeas** [comment]
Project brief was approved and enhanced with [Foxfooding Hub metrics](https://docs.google.com/document/d/134XJ_WCPfUev1r8WEqHckfDq4ZjzEF-gtM2p2cmGWO8/edit#heading=h.4wo5vic4prss)

**Comment by ppapadeas** [comment]
Deployment infrastructure was delivered Monday 26th of Oct by @johngian 

Dev instance is running and updated on master merges here:
https://feedthefox-dev.paas.mozilla.community/

**Comment by johngian** [comment]
Yay!
 :rocket:
