### ISSUE TITLE
Leadership Planning for Mozfest

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#198]
## Goal:
- The first group of our Participation Leaders cohort, **arrives** at Mozfest with clearly articulated goals for developing and delivering programs that will build the skills of Mozillians in 2016.  They understand the opportunities  and experiences made possible by Mozfest to grow and develop their leadership skills while recognizing their own power to influence positive experiences and inspire others.
- The first group of our Participation Leaders cohort, **leaves** Mozfest feeling empowered and inspired to act on their goals for **building learning and leading opportunities for their communities in 2016**.  Fueled by new knowledge and skills these participation leaders will have further refined their goals and leave with a clear vision for next steps. 
- The leadership cohort starts to bond as ae leadership team, and can envision ways to influence the success of other emerging leaders as part of the next Global Event   - Mozlando.
## Related Issues & Links:
#195
## Roles:

Owner: @emmairwin
Involved: @geroter  
## Key results:
- [x] Complete coaching strategy, to include pre-work and coaching outcomes for all coaches.
- [x] Coach 15-20  cohort participants in their goals for Mozfest, based on their global gathering application.
- [x] Provide 1:1 for all facilitators running sessions in the Participation space (10 - 15), including additional coaching for facilitators also in our cohort.
- [x] Meet with FSA, Tech Speakers and others interested in collaborative sessions in our space.
- [x] Co-design or design a session for 'Mozilla Campus', 'Scaling the learning and leading program for Participation in 2016 .
- [x] Provide ways for Mozillians launching this first Global event to share their enthusiasm and goals through Discourse (Why Mozilla, Why Now, Why Me) and  'My Mozfest Experience'.
- [x] Prepare two experiences in the Participation Space : 'Participation Museum' and 'Participation Map'.
- [x] Complete, and share Participation Pathways  - blog and share widely.
- [x] Create Mozfest Participation space schedule.
- [x] Coordinate Mozfest planning with Participation Team & Cohort
## Open/Volunteer Tasks
- #199  Webify our schedule  (make it beautiful)

**Comment by LucyeoH-zz** [comment]
Woo-hoo! closed!
