### ISSUE TITLE
[Open Task]  Webify our Mozfest schedule  (make it beautiful)

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#199]
# Description

We have this spreadsheet schedule, which is good for planning, but entirely unattractive to view. It would also be nice to highlight the speakers and activities in our space.  And allow for update last-minute.

https://docs.google.com/spreadsheets/d/1Em8vJh1WFKhNUUbaRjTgAN3jYU7TwHyABmK5nab6mCY/edit#gid=1849284233

Open Science did a nice jojob: https://www.mozillascience.org/mozfest-2015
## Prerequisites
- Understanding of the schedule purpose (color legends etc)
## Participation Steps
1. Leave your thoughts here on how we can best achieve this without too much effort. My thought is to use Markdown and just pull it into the community Education site.  But maybe you have a better idea.
2.  Complete it by Tuesday of next week (Nov 3rd)

**Comment by deimidis** [comment]
1) Do we have descripton of the Pathways besides what you have in your blogpost?
2) Could we have Github pages in this repository?

**Comment by ioana-chiorean** [comment]
I can also help if we use markdown and if it will be in the Open Science form.

**Comment by comzeradd** [comment]
> Could we have Github pages in this repository?

Yes. We can create a `gh-pages` branch and this would be accessible through mozilla.github.io/participation-org.

**Comment by deimidis** [comment]
Thanks @comzeradd I think that could be a good idea to create something quick, and then export or link to it. I amde a first version of a table for Friday in Markdown. I have to research how to give css love to that besides the Markdown thing.

# Participation Mozfest Schedule

## Friday

| Time | Content | Who |
| --- | --- | --- |
| 10:00 - 12:00PM | Wrangler & community Summit prep | Just wranglers |
| 12:00 PM- 1:00 PM | Lunch with Community Leaders | Staff |
| 1:00  PM - 2:00 PM | Community Leadership Summit x 200 Participants | Everyone from Participation facilitating or not |
| 2:00 PM - 3:30 PM | Facilitator Skill-Building x 400 participants | Everyone from Participation facilitating or not |
| 3:30  PM - 4:00 PM | Break |  |
| 4:00  PM - 5:30 PM | Participation Leadership Orientation & Kickoff | Everyone |
| 5:30 PM onward | Space Setup & Sign Making! | Everyone not involved in science fair |
| 6:00:00 PM | Science Fair | Science Fair leads and participants |

We should define content and order (maybe copying Open Science one) and begin the document :)

**Comment by comzeradd** [comment]
Here is an example: http://mozilla.github.io/participation-org/

**Comment by deimidis** [comment]
Nice, where's is the document in the repo? To check out and continue from there

**Comment by comzeradd** [comment]
Just switch from `master` to `gh-pages`. https://github.com/mozilla/participation-org/tree/gh-pages

This is converted in markdown using github's generator. So, to avoid writing html tables I can re-generate this if I have the final schedule in Mardkdown, and then continue tweaking the UI.

**Comment by ioana-chiorean** [comment]
Some suggestions:
- [ ] Add MozFest logo too and some details about what MozFest is
- [ ] Discourse link should be for participation or for global Gathering -> Mozfest?
- [ ] Social Media stuff - twiiter, main wranglers ( Emma, George)
- [ ] Sat & Sun will have many facilitators - add a contact for them too ( I know is not up yet)
- [ ] Add a humanified picture ( team, Reps, previuos mozfest)
- [ ] Color the header and hours in the table 

I can continue after Guillermo ( my day time, his night time)

**Comment by emmairwin** [comment]
I am just catching up with this - thanks everyone!

@deimidis the pathway descriptions in my blog post are the only descriptions

@comzeradd @deimidis @ioana-chiorean what I propose is we create2 markdown files one for each of Saturday and Sunday(thur , friday are nice to have if we have time) and I will pull them into the edu portal which  uses markdown.
I'll build out the facilitator / session profiles if it makes sense to(maybe just names as Ioana suggests vrs session descriptions which will be in the mozfest schedule anyway).  Agree on link to discourse.  and previous humanified.
Also pathway colors are a nice to have.

I created this page.  if someone wants to create markdown files I can pull them in here no problem.

http://education.mozilla-community.org/modules/participation_mozfest/schedule/

**Comment by deimidis** [comment]
I didn't understand how to create the pages so @comzeradd could make the conversion. I change to the branch in my local copy, but didn't see where are the markdown files.

I will create the markdown files and upload it here

**Comment by comzeradd** [comment]
> I didn't understand how to create the pages so @comzeradd could make the conversion. I change to the branch in my local copy, but didn't see where are the markdown files.

I'm using the Github's generator through repo's settings.

I used the markdown files @deimidis sent and re-generated the page.

http://mozilla.github.io/participation-org/

**Comment by emmairwin** [comment]
This is amazing thank you!  I have to make some changes still, but so great !!!!

**Comment by emmairwin** [comment]
@comzeradd what's the best way to make edits to this? I made a couple directly but probably shoudl have checked first!

primarily
- block numbers are now 1-8   (1 being the first session Saturday, 8 being last session sunday)
- "Digging deep...a workshop on community research " has been added to location 2 on block 1
- Scaling Tech Speakers title has changed to: "Scaling by Doing:  Tech Speakers Starts With You"
- Hack on Firefox OS Smart TV  - is not in block 5 (first session sunday)  location 2

Should have little to know changes again, but I may  be forgetting one.

**Comment by comzeradd** [comment]
You have permissions to use the Markdown [generator for this repo](https://github.com/mozilla/participation-org/generated_pages/new). Just be careful to always have a backup of the markdown, because it doesn't provide preview and hitting back discards all changes.

Or you can also edit html directly as you did. Both are ok. If you use the markdown generator you can [remove](https://github.com/mozilla/participation-org/commit/061b94f0832e4ac0a8a72e10aaa919b3dcc90b4a) the header that Github always adds every time.

**Comment by comzeradd** [comment]
And this is now live here: http://participation.mozilla.community/

**Comment by ioana-chiorean** [comment]
:tada:

**Comment by emmairwin** [comment]
Thanks to all who helped with this!!!
