### ISSUE TITLE
Mozilla Give Thanks campaign 2015

### ISSUE THREAD

**Issue by MajkenC** [mozilla/participation-org#201]
From: https://discourse.mozilla-community.org/t/recognition-idea-mozilla-thanksgiving/5091

Let's encourage all Mozillians (but let's give an extra push to staff to get the ball rolling) to send out some messages of gratitude on Discourse and social media, the week starting November 23rd. Discourse, Facebook and Twitter all allow you to like other people's messages, too, so we can really show people their efforts are appreciated.

spin up a quick webpage that aggregates all of these thanks (with tags and such)
## Goal:

Make as many Mozillians as possible feel appreciated for their contributions, big or small.
## Success:

Hundreds (thousands?) of social media posts of thanks from all corners of Mozilla, to all corners of Mozilla. Contagious posts of thanks, lost of liking of posts of thanks.
## Related Issues & Links:

[Discourse discussion](https://discourse.mozilla-community.org/t/recognition-idea-mozilla-thanksgiving/5091/)
## Roles:

Owner: ?
Involved: @MajkenC @geroter ?
## Required:

Campaign branding
- [x] Name
- [ ] Logo
- [x] Hashtag

Messaging
- [ ]  Messaging to encourage participation ahead of time
- [ ]  Messaging to encourage people to join the campaign as it happens
- [ ]  Website to aggregate the thanks

Data/Metrics
- [ ]  How to measure impact?

**Comment by geroter** [comment]
Hey @MajkenC, can you build a quick project plan here with some dates/check-box style to do?

**Comment by nukeador** [comment]
@MajkenC here you have the template https://github.com/mozilla/participation-org/issues/110

**Comment by geroter** [comment]
New name to this "Mozilla Give Thanks campaign 2015"

We're building an MVP site right now, hopefully to demo at the end of MozFest:
https://docs.google.com/document/d/1px-BVFDnSo3cqN2cgnoxqkWEqtX2M6Dujaur2bMfIUM/edit#

**Comment by yofiesetiawan** [comment]
Oh here it is, the design that i'm proposing for this project...

![thanks mozilla community-03](https://cloud.githubusercontent.com/assets/2810823/11129787/e905787e-89b3-11e5-8116-0bad57aa28c0.jpg)

However i want to let developer team to improve it with their own perspective...

**Comment by comzeradd** [comment]
CC-ing @LeoMcA who started working on this during mozfest.

**Comment by emmairwin** [comment]
@yofiesetiawan that's beautiful!

**Comment by ioana-chiorean** [comment]
Is this up? Can we test is somewhere?

**Comment by MichaelKohler** [comment]
The current status currently lives at http://thanks.michaelkohler.info/ (Leo has access to the server as well)

**Comment by comzeradd** [comment]
And @LeoMcA's code repo: https://github.com/LeoMcA/thanks.mozilla.community

**Comment by ioana-chiorean** [comment]
> http://thanks.michaelkohler.info/

Good one! I will have a look in a bit.

**Comment by LeoMcA** [comment]
Sorry, I haven't been feeling particularly well health wise post-mozfest, and not had any energy to focus on this.

@yofiesetiawan love it! A few questions, though:
1. In the event of an avatar not being available what's it going to look like? I rather like the letter avatars [which Discourse uses](https://meta.discourse.org/t/change-letter-avatar-font-to-roboto/33918).
2. In the barely viable prototype we had a 'to' field for the person (or persons) the thanks is being sent to. Is there space for that in the card view?

**Comment by yofiesetiawan** [comment]
Hi @LeoMcA Avatar can just use letter avatars as you suggested
I attached the card design, when we have "TO"..

But let's talk about UX. I don't think including "TO" is a good idea. What if i want to thank to many different people? So i have my card everywhere like spamming the page? I prefer the message is general, people can type as many as they like without need to be specific for each message... I thought we are all only thank to "Mozilla" not "From & To"...

How do you think?

![thanks mozilla community-04](https://cloud.githubusercontent.com/assets/2810823/11256553/1add8dee-8e7f-11e5-9ac5-2cc2dd8d3039.jpg)

**Comment by comzeradd** [comment]
I think the point of this app is to thank Mozillians, not Mozilla. So if this is the UI of the main page, it would make more sense to have the Mozillian receiving the gratitude in the spotlight with the big avatar. The text should be the free text entered by the one who gives a "thank you". And just a small footnote inside that box indicating the name of the Mozillian who wrote it.

**Comment by yofiesetiawan** [comment]
hi @comzeradd i think that's still possibly create a spam look if one receive too many thank you message. And if the avatar is showing the person who receive the message, so how we get the image data of the avatar? Person who want to thank will upload the picture of the person s/he want to thank? Isn't that awkward? Uploading someone else picture?

**Comment by comzeradd** [comment]
I think the idea is to fetch these from mozillians.org API.

**Comment by yofiesetiawan** [comment]
@comzeradd so people who receive thank message must have mozillians.org profile, but that's still possibily create a spam look.. and i'm not sure how is the flow if we use mozillians.org API, do we need to input mozillians profile url when submitting message?

@geroter do you have any thoughts regarding this?

**Comment by MajkenC** [comment]
I agree, the spotlight is meant to be put on the people who are being appreciated. Nikos' feedback is spot on.

I also think that the "Give Thanks" should be featured more prominently than the logo.

The idea is also generate as many thanks as possible _not_ to try and restrict them, to try and group them together or to only thank people who "really" deserve it. The idea is to "spam" the community with thanks.

Does this site require you to give your thanks through it? Or can it pull the messages from watching Twitter and Facebook? Or do you sign into the site and then it shares your message on your social media account?

**Comment by MajkenC** [comment]
Also, is anyone working on the messaging? What will we say to encourage people to participate? When and how will we share it?

**Comment by emmairwin** [comment]
@MajkenC suggestion - maybe create some subtasks to help people recognize where they can help? Just an idea.

**Comment by emmairwin** [comment]
Also https://twitter.com/hashtag/LABHR?src=hash

consider plugging this into that initiative.

**Comment by MajkenC** [comment]
I started using the hashtag #mozthx2015 and made a wiki page here: https://wiki.mozilla.org/Give_Thanks_2015

Still time to get up a site though, but in the mean time we should start posting and get some momentum.

**Comment by ioana-chiorean** [comment]
Should we promote this then or still wait a bit?

**Comment by MajkenC** [comment]
I talked to @LeoMcA today. He hasn't had time to work on this. My feeling is we should just run with it. If he has time he is going to see about platforms that already exist to pull from the hashtag, but requires moderation. I'd be willing to do moderation if we can find a suitable tool in time.

**Comment by ioana-chiorean** [comment]
OK. Let's promote this then! :tada: :v:

**Comment by yofiesetiawan** [comment]
I'd say, with such brief for this campaign, especially because it use hashtag, it's far way better to just run it with social media... If we want to build a specific site, than it's just to short explain about the hashtag itself...

**Comment by yofiesetiawan** [comment]
BTW, talking about hashtag campaign, i think first design fits much better to this... Just sayin..
![thanks mozilla community-01](https://cloud.githubusercontent.com/assets/2810823/11386956/cf2b91dc-9358-11e5-88fa-fb6b0337c7f0.jpg)

**Comment by MajkenC** [comment]
Ooh! I like this!

**Comment by emmairwin** [comment]
Me too!

**Comment by LucyeoH-zz** [comment]
ACCOMPLISHED!! Can we get a report on how it went? @MajkenC

**Comment by ioana-chiorean** [comment]
Some data here: http://hashtagify.me/hashtag/mozthx2015 
https://twitter.com/search?q=mozthx2015&src=typd

**Comment by MajkenC** [comment]
Thanks Ioana, I wasn't sure how to get real data on the tags.

I would love to set a target to repeat this. I have some ideas on how we'd do better. 

a) Have a sign-up for people who like the idea in advance that reminds them when the campaign launches
b) we need to target, in a non-creepy way, people who are "first-followers." I don't think many people that I thanked turned around and thanked others. This is fine in general, but we also want to make sure the efforts reach people who will magnify it.
c) I only saw Emma mention the gratitude challenges. With more lead up and better promotion of the campaign home page, I'd be interested to see if they are helpful to more people.

**Comment by ioana-chiorean** [comment]
> c) I only saw Emma mention the gratitude challenges. With more lead up and better promotion of the campaign home page, I'd be interested to see if they are helpful to more people.

I did mentioned/promote  it on Telegram and Reps Call. ( not sure though if this is what u meant)
