### ISSUE TITLE
Create a repo for the Participation Leaders

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/participation-org#202]
We need to on-board the participation leaders onto Git. I think it  make sense to use a different repo rather than participation-org. My assumption is the issues in the repo will be "forumish" so we shouldn't clutter up the main repo.

**Comment by deimidis** [comment]
@emmairwin is using this one for education purpouses https://github.com/emmairwin/mozilla-community-edu

**Comment by jgmac1106** [comment]
Unless @emmairwin and @geroter want the participant leaders to have their own. Then I will re-open.

**Comment by jgmac1106** [comment]
@asdofindia  Let me know the repo posted by @deimidis is actually for a different portal. We should make a repo just for the participation leaders so we do not have to post to discourse, telegram, the yellow pages, and email.

**Comment by asdofindia** [comment]
There's also [participation leaders](https://discourse.mozilla-community.org/c/global-gatherings) category on discourse. It might be a better choice compared to a github repository with issues (considering the interface, discoverability and integration with all other conversations in discourse). 

But a github repository has this specific advantage that it is more action oriented with labels, assignee, etc.

**Comment by jgmac1106** [comment]
@asdofindia I agree. It can be hard, but if we are going to have one space to rule them all...we might as well hop on board, but I can head over to Discourse as well. Just trying to limit how many places I have to participate in order to contribute.

MLN is using both Git and Discourse currently and it can get annoying. Not everybody on Discourse is on Git and vice versa. So you have to repeat yourself. And say the same thing more than once.

**Comment by emmairwin** [comment]
Good Discussion.  @LucyeoH and I once talked about having a seperate repo for our 'open tasks', which might fit .  It would be good to think about how you want to use it, and how to avoid discussions becoming clutter.  If you think discussions should be part of a repo then tagging them appropriately will help people avoid that noise.  I wrote a post based on observations that some people do use Github for 'story telling'  http://tiptoes.ca/how-to-write-a-good-open-task/

I defer to Discourse for discussion to make them more findable.  Similar functionality (subscribe to discussion, email responses) but with the clear purpose of being for discussion.

**Comment by emmairwin** [comment]
@jgmac1106 would love to know more about those pain points for MLN GIt/Discourse use, so we can evaluate and avoid where possible!  Thanks so so much

**Comment by emmairwin** [comment]
Final comment, lets bring this to the Participation call next Thursday - we can populate a pad with questions and make a decision that day perhaps?  Thoughts?

**Comment by asdofindia** [comment]
We missed this in the Participation call, didn't we?

**Comment by debloper** [comment]
Having an org is rather better than having a repo only (I'll skip the 'why' 'til asked).

Like @mozilla-b2g, @mozilla-metrics, @mozilla-IT, @mozilla-l10n we've had one already created, called @mozilla-edu (can be renamed to fit our need - but that's how the effort was known initially, before the shaping up of participation team). IIRC, Emma & Ioana already have admin in that org as well.

Thoughts?

**Comment by asdofindia** [comment]
I'd written down some of the 'why's in [this thread](https://discourse.mozilla-community.org/t/create-a-github-organization-for-community-education/5109). Great to know we indeed have an organization.

**Comment by LucyeoH-zz** [comment]
@jgmac1106 @asdofindia looks like the Participation Leaders group is pretty active on [discourse](https://discourse.mozilla-community.org/c/participation-leaders). Please re-open if you think that a Participation Leaders GitHub would still be valuable.
