### ISSUE TITLE
Advancing mid-term planning with focus communities

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#205]
## Goal: Advancing Mid-term Planning with focus communities

Advance planning process with focus communities and start documenting the plans of the other 7 communities
## Success:
- Mid-term plans of Germany, Mexico and Indonesia are starting to take its individual shape
- We start documenting the activities and big events that the other 7 communities have planned
## Related Issues & Links:
#171 #200
## Roles:

Owner: @rosanardila
Involved: @nukeador @deimidis @couci
## Required:
- [x] Work with 3 communities to refine and finalize the planning (@rosanardila, @nukeador, @deimidis, [large], Due: Nov 19th)
- [x] Design a planning calendar to collect, display and share the planning from the other communities (@rosanardila, [medium], Due: Nov 18th)
- [x] Get 3 communities to put their current planning together online for the rest of the community to be able to chime in(@rosanardila, @nukeador, @deimidis, [small], Due: Nov 23rd)
- [x] Get the 7 communities to start populating the planning calendar (@rosanardila, @nukeador, @deimidis, [medium], Due: Nov 25th)

**Comment by nukeador** [comment]
Good news, the awesome German community already has a draft with their goals and plans that will share with the rest of the community for feedback and start implementing soon! Yay!

**Comment by rosanardila** [comment]
Indonesia's plan: https://docs.google.com/presentation/d/1X8xMplxiQ9livT6wqO3MKK-xNtA6KXeBe0K02RjHJyY/edit#slide=id.gc6f8954bc_0_164
Philippines progress: https://drive.google.com/file/d/0B84D7PhWR2flTFlJNXhLbHFkMmc/view?usp=sharing and blog http://www.mozillaphilippines.org/mozillaph-community-planning-oct-2015/
Italy progress: https://docs.google.com/presentation/d/1caRFpF0Ji1EPqwiYSU29IwhiOvu4mNWFvBelNTmm6hM/edit

**Comment by rosanardila** [comment]
The timeline is going out today, communities will have until the end of the year to populate the timeline.

The timeline is a super cool way for communities to just use a simple form to add events to a timeline and make them transparent and dicoverable and allow collaboration across the community.

Timeline example from Indonesia: http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1lvBCp0hdgAgegHaKsc-WdYxJscrx0Lql90U_uuzrD4w&font=Default&lang=en&initial_zoom=2&height=650

**Comment by rosanardila** [comment]
@nukeador and @deimidis will add info about Mexico and Germany, but this is closed.

**Comment by nukeador** [comment]
Mozilla.de plans https://discourse.mozilla-community.org/t/auswahl-der-ziele/5047/6

**Comment by deimidis** [comment]
Mozilla.mx discussions: https://discourse.mozilla-community.org/t/planificacion-2016-proyectos-para-la-comunidad/4919/4

Also we define 4 goals:
- Community organization
- Document Community organization and first steps for new volunteers
-  FSA and Firefox Clubs
- Firefox OS - Foxfooding
