### ISSUE TITLE
Finalize proposal for changes to the Reps program in 2015

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#206]
## Goal: Finalize proposal for changes to the Reps program in 2015

Synthesize all proposals for changes to the Reps program and lay out concrete options for change in 2015
## Success:
- A proposal on concrete changes to the Reps program based on all the discussion of this year
## Related Issues & Links:
#172
## Roles:

Owner: @rosanardila
Involved: @rosanardila @nukeador  @bacharakis @MichaelKohler Mozilla Reps Council and Peers
## Required:
- [x] synthesize all proposals (@rosanardila, @nukeador, @MichaelKohler, @bacharakis [ large], Due: Nov 17th)
- [x] Peers give feedback on it ( @ioana-chiorean, [large], Due: Nov 17th)
- [x] Council finalizes end of the year campaign and communicates with mentors (@rosanardila @nukeador, @bacharakis [large], Due: Nov 27th)
- [x] Council kicks off end of the year campaign (@rosanardila @nukeador, @bacharakis [medium], Due: Nov 30th)
- [x] Communications go out (@bacharakis @rosanardila, [medium,], Due: Dec 7th)

**Comment by ioana-chiorean** [comment]
- [x] Peers give feedback on it ( @ioana-chiorean, [large], Due: Nov 17th)

**Comment by rosanardila** [comment]
awesome Ioana, Thank you :)

**Comment by LucyeoH-zz** [comment]
Please keep @lucyeoh in the loop!

**Comment by nukeador** [comment]
End of the year activity campaing https://discourse.mozilla-community.org/t/end-of-year-activity-campaign/5671/

**Comment by rosanardila** [comment]
Proposal is ready, as well as comms. They will go out on Monday.
Closing this.
