### ISSUE TITLE
Mascot for Foxfooding

### ISSUE THREAD

**Issue by yofiesetiawan** [mozilla/participation-org#207]
# Create a Mascot for Foxfooding

Brief description of task.
- Create mascot that is cute and adorable
- Based on Red Panda
- For Foxfooding purpose

Project Owner : @williamq 
Involved : @yofiesetiawan & <a href="https://mozillians.org/en-US/u/poy/" target="_blank">Poy</a>
## Prerequisite

Volunteers for this role, must have advance in illustration design.
## Timeline
1. Sketch
2. Coloring
3. Final Art
## Deadline

15 November 2015

Please use comments to give feedbacks!

**Comment by yofiesetiawan** [comment]
This is a sketch artwork done by <a href="https://mozillians.org/en-US/u/poy/" target="_blank" >Poppy Betharia</a>.

![mika](https://cloud.githubusercontent.com/assets/2810823/11130236/86703192-89b6-11e5-8f51-60ab3881aedc.jpg)

**Comment by yofiesetiawan** [comment]
Mika in color..
![photo160510594824384947](https://cloud.githubusercontent.com/assets/2810823/11162972/1a01c5e0-8aef-11e5-9607-ace5a0339503.jpg)

**Comment by yofiesetiawan** [comment]
Mika in different color scheme..
![12235626_10205295762295959_1943280525_o](https://cloud.githubusercontent.com/assets/2810823/11163343/f79c9c5a-8afd-11e5-9a32-156edf9c4cbb.jpg)

**Comment by yofiesetiawan** [comment]
Another color scheme for Mika... (I like this one)
![12250317_10205295798536865_56375421_o](https://cloud.githubusercontent.com/assets/2810823/11163394/07dc54be-8b00-11e5-8f48-497b0e0f93d6.jpg)

**Comment by yofiesetiawan** [comment]
Hi, this is the source vector file in AI format...

https://dl.dropboxusercontent.com/u/4450713/mozilla/mika-foxfood-mascot.zip

**Comment by comzeradd** [comment]
Nice! Can you export this in svg? So it would be easier to be edited in open source vector editors ;)

**Comment by Jobava** [comment]
![mika-png](https://cloud.githubusercontent.com/assets/11072594/11474448/bfd599ae-9780-11e5-94f7-e33bbfb8d908.png)

This is my export of it, with a transparent background, suitable for printing on T-shirts, either as a whole or if you slice away the particular bits you like. If you want a bigger rendering, let me know!

By the way, .ai (Adobe Illustrator) is openable with InkScape: https://inkscape.org/en/

**Comment by comzeradd** [comment]
> By the way, .ai (Adobe Illustrator) is openable with InkScape

You are right :) I just tried it.

**Comment by yofiesetiawan** [comment]
Ah sorry, but i guess it's solved? Thanks @Jobava

**Comment by yofiesetiawan** [comment]
![mika-fxos-pose](https://cloud.githubusercontent.com/assets/2810823/12083607/fa2d9a7a-b2d8-11e5-8b19-c7c4bc33bb1f.jpg)
Our cute mascot, Mika, in Firefox OS Mascot poses..

**Comment by LucyeoH-zz** [comment]
Awesome work here! Looks like it's done. Closing!
