### ISSUE TITLE
Get More Non-Participation Team Involvement in EOQ Demos

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#209]
## Goal:

More unification across community facing teams. 
## Success:

At least 2 other teams share their work at demos. 
## Roles:

Owner: @lucyeoh
Involved: 
## Required:
- [x] Schedule EOQ Demos and set-up on AirMo (@lucyeoh, [small], Due: Nov 20th) 
- [x] Send invitations to FSA, L10N and SUMO to present (@lucyeoh, [small], Due: Nov 20th)

**Comment by ioana-chiorean** [comment]
Might be QA one of them?
