### ISSUE TITLE
Heartbeat 2: Experimental approach to community building in Africa to support Fx OS launch

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#21]
# Initiative description / framing

With Fx OS launching in 21 African countries in 2015 (of which 13 are with Orange), there is an opportunity to test a new approach to building new relationships and new communities of supporters/volunteers across the continent. 

We believe that by shifting our communication focus and value propositions onto the tangible benefits that Mozilla can provide for individuals and their communities (ie. new skills, work experiences, mentoring, tools, funding...)

Link to overall Q2 plan: https://docs.google.com/document/d/19Vd6qFByYVeMPFuOnUpkmh1kI-gNvT7K7bHXS5TQM6Q/edit 
# Deliverable

To verify this hypothesis, we will be driving four experiments with a strong focus on Fx OS targeting three different audiences over three months, that aim to empower individuals to "become an Internet leader and help shape their country's future”. These experiments will be rolled out in one P1 Orange launch country, Senegal, from May to July, 2015 (3 months).
# Primary Goals/Objectives for this Heartbeat

Design and roll-out 2 of the 4 experiments outlined in the overall plan: 
### 1) Fx OS SUMO internship

Tactic: Launch a 3 month internship that trains university students to become experts in Mozilla support and helps them provide high quality contributions directly supporting the Fx OS launch in Senegal (ie. SUMO). Local Reps will man a “recruitment booth” at various universities where students can apply for the internship. Local Reps will shortlist 5 applicants and onboard and train them for their internship.

Success metrics:
100 applicants for the internship
5 interns continue contributing to SUMO after internship
5 new contributors recruited within one month after internship
### 2) Adopt a Store

Tactic:  train Mozillians to become a Fx OS sales rep and "adopt" a store where Firefox OS products (ie. Klif) are sold (close to home, to the office…). Trained Mozillian commits to visiting the store on a regular basis (every week) to represent Mozilla and help store manager to promote Fx OS. Mozillian then gets commission on Klif sales. 

Success metrics:
30 stores  identified across Dakar
3 stores/volunteer
20% higher sales in "adopted" stores
# Secondary Goals/Objectives for this Heartbeat

Create draft agreement with Jokkolabs for train-the-trainer program run by staff and volunteers
# Milestones

May 19: kick-off meeting
May 21: meeting with Orange to finalize scope and timing of Adopt-a-store
May 22: final shortlist of SUMO interns (Senegal & Tunisia)
May 25: 1st SUMO training 
May 26: 2nd SUMO training
May 29: draft of "collaboration" agreement with Jokkolabs

RACI
Owner: William 
Project manager: William
Informed or Consulted: Brian, Ibrahima, Natalia, George, David Ascher, Ben Moskowitz, Cecile Pompei
### References

Overall Q2 Participation Plan for Africa: https://docs.google.com/document/d/19Vd6qFByYVeMPFuOnUpkmh1kI-gNvT7K7bHXS5TQM6Q/edit

Adopt-a-store program summary: https://docs.google.com/presentation/d/1ToWnaafcFuGboAqw_6hREVuDhQr6EWQhf5ytU2CfZo8/edit#slide=id.p12

Dakar planning etherpad: https://etherpad.mozilla.org/firefoxos-sn

**Comment by williamq** [comment]
# What was supposed to happen?

May 19: kick-off meeting
May 21: meeting with Orange to finalize scope and timing of Adopt-a-store
May 22: final shortlist of SUMO interns (Senegal & Tunisia)
May 25: 1st SUMO training
May 26: 2nd SUMO training
May 29: draft of "collaboration" agreement with Jokkolabs

# What did happen?
- We got more applicants than expected for the SUMO internship (140!) so it's taking a bit more time to sort. 
- SUMO team pushed back its schedule for training due to 1) Balkan meetup and 2) PTO for Michal and Madalian
- various challenges working with Ibrahima Sarr who is providing support in Senegal - he was stuck in Dakar after having lost his passport and had major issues with French embassy
- we postponed meetings with Orange twice due to avaibility conflicts
- discussion of potential partnership between Mozilla and Jokkolabs have begun but drafting of document delayed due to change of Karim Sy's travel plans to Paris. Carried over to next heartbeat.

# What are some improvements we should make?
- we need to anticipate better avaibility of various stakeholders (ie. SUMO/Orange)

# What should we keep the same in this process?
- short 15 min checking every 48 hours is really hepful and maintains momentum even if tasks postponed to later

# What does the next Heartbeat for this project look like?

Many of the tasks for this heartbeat were carried over so heartbeat will look pretty much the same. One big difference is that it will be expanded to now include Tunisia.

**Comment by brianking** [comment]
@williamq  Can this one be closed?

**Comment by williamq** [comment]
Yes, thanks Brian. 
- w
