### ISSUE TITLE
Lessons from Global Gatherings and FxOS are Shared and Surfaced 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#210]
## Goal:

Learnings from these 2 events are helping to create a model and framework for participation 
## Success:

3 blog posts 
## Related Issues & Links:
#166
## Roles:

Owner: @lucyeoh
Involved: @emmairwin 
## Required:
- [x] Interview William & Brian about lessons (@lucyeoh, [medium], Due: Nov 20th) 
- [x] Talk to Emma & George about putting together a learning-based blog post (@lucyeoh, [medium], Due: Nov 20th) 
- [x] Write FxOS blog post (@lucyeoh, @brianking  [medium], Due: Dec 4th)  
- [x] Write Global Gatherings Blog Post  (@lucyeoh, [medium], Due: Dec 4th) 
- [x] Write Participation Champions Blog Post (@lucyeoh, [medium], Due: Dec 4th) 
- [x] Write Leadership Summit retrospective blog (@emmairwin [medium], Due: Dec 21st) 
- [x] Write 2016 Strategic Planning Blog Post (@geroter  [medium], Due: Dec 21st) 
- [x] Write Reps retrospective blog (@rosanardila  [medium], Due: Dec 21st) 

Posted
- [x] Global Gatherings Blog Post  Posted (@emmairwin) https://blog.mozilla.org/community/2015/12/18/participation-leaders-summit/ 
- [x] Firefox OS blog post posted 
- [x] Participation Champions Blog Posted (@lucyeoh)
- [x] Leadership Summit retrospective blog Posted (@emmairwin )
- [x] 2016 Strategic Planning Blog Posted (@lucyeoh)  
- [x] Reps retrospective blog Posted (@rosanardila)

**Comment by brianking** [comment]
Where would the blog posts go?

**Comment by LucyeoH-zz** [comment]
Participation Blog -> Under Participation Lab Notes.

**Comment by LucyeoH-zz** [comment]
https://blog.mozilla.org/community/category/participation/

**Comment by LucyeoH-zz** [comment]
Will be done by EOY

**Comment by LucyeoH-zz** [comment]
@brianking do you think you'll be able to finish the FxOS post by EOY?
