### ISSUE TITLE
Mozlando Leadership Preparation

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#214]
## Goal:

10 regional communities, 200 participation leaders and our global-local organizing model are setup for impact in 2016
## Success:
- 90% of MozFest and Orlando All Hands volunteer Mozillians can identify at least 1 key take-away and have concrete action plans for building participation in 2016 - have incorporated this approach into a playbook
- All Orlando Participation Leaders coached for at least 30 min each with a focus on 2016 plans/contributions
- 75%  Functional Teams have prepped their volunteers 1:1 in how to incorporate their personal goals into the event
-  75% of teams have taken advantage of Participation 'Offerings' of support for Mozlando, including coaching, and leverage of existing opportunities to plug-in to activities, and discussions . (framework)
- All volunteers nominated for workweek by their functional area leads, will have been offered additional coaching for their participation goals (regional or functional)
- 
## Open Tasks (was 'volunteer task')

None at the moment
## Roles:

Owner: @emmairwin
Involved: @geroter @rosanardila @deimidis @nukeador  @francjp 

**Terminology**
Teams Communication = Functional Area Teams
Cohort Communication = Mozlando Participation Leaders
Participation Leaders = everyone in the cohort, not event-specific.
## Required:
- [x] Hold postmortem of coaching and Mozfest with key stakeholders (@emmairwin, [small], Due: November 17th) 
  - [ ] Sync with @lucyeoh about how this ties into team actives at Mozlando
- [x] Propose, templates and strategy for Orlando coaching to key stakeholders (@emmairwin, medium, Due: November 18th) 
- [x] Revise templates & strategy based on feedback. Launch coaching outreach (@emmairwin, @rosanardila @deimidis @nukeador , [large], Due: November 19th) 
- [x] Blog post
- [x]  Teams Communication - Initial Email for Orlando (setup for success) (@emmairwin, [small], Due: November 20th) 
- [x] Cohort Communication - Initial Email for Orlando (setup for success)   (@emmairwin, [small], Due: November 20th) 
- [x] Teams Communication - 2nd Email, will include templates and suggested timelines and techniques for coaching, open office hours for support, and method for plugging into existing participation leadership framework. (@emmairwin, [small], Due: November 27th) 
- [x] Cohort Communication - 2nd Email, follow up on coaching, suggested timelines for 'action items', and other team bonding activities.  (@emmairwin, [small], Due: November 27th) 
- [ ]  Teams Communication - 3rd Email, final follow-up outreach to support unmet coaching goals, including a schedule for coaching availability from the Participation team. Reminder of framework plugins.   (@emmairwin, [small], Due: December 4th) 
- [ ]  Cohort Communication - 3rd Email, final push for setting up for success.   (@emmairwin, [small], Due: December 4th) 
- [x]  All Participants have scheduled coaching  (@emmairwin, [small], Due: December 4th) 
- [x]  All Participants have completed coaching  (@emmairwin, [small], Due: December 4th) 
- [x]  75% of Participants have completed pre-event assignments  (@emmairwin, [small], Due: December 4th) 
- [x]  2 Hour Workshop for Mozlando is built, and QA'd.    (@geroter) , [small], Due: December 4th)

**Comment by LucyeoH** [comment]
Sync with @lucyeoh about how this ties into team activies at Mozlando!

**Comment by emmairwin** [comment]
pre-event intro on discourse was well attended, option to remix my mozlando story failed to have uptake (even though it had few words, and was well received as a fun activity) , although there were a couple of good ones.  for summit will have to think of what activities are lowest/most accessible for participation.
