### ISSUE TITLE
Coordinate with MLN Moving Forward

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#216]
## Goal:

Coordinated leadership effort for 2016, of which curriculum is one piece.
## Success:.

We have completed pre-work that prepares us for conversations in Orlando. Clear sense of prioritized conversations and understanding of touch points for collaboration into 2016
## Related Issues & Links:

Related to Chad's work here:  https://github.com/mozilla/learning-networks/issues/280
" begin scoping cross-over and collaborative opportunities to work on curriculum 'best' or common practices throughout Mozilla."
## Open Tasks

None for this one.
## Roles:

Owner: @emmairwin
Involved: @geroter 
## Required:
- [ ]  @geroter  will synchronize with @chrislarry33 and then provide feedback to the  team. ( by November 20)
- [ ] Attend MLN Curriculum Call  (November 23rd )
- [ ] Outline of people, conversations and outcomes for Mozlando (@emmairwin , by December 4th)

**Comment by emmairwin** [comment]
Related to Chad's work here:  https://github.com/mozilla/learning-networks/issues/280
" begin scoping cross-over and collaborative opportunities to work on curriculum 'best' or common practices throughout Mozilla."

**Comment by emmairwin** [comment]
A couple of things for those following along!  In response to questions also here #232 

1)   https://github.com/emmairwin/community_curriculum  is where curriculum has been built.
2)  The education Portal (linked above) is where I have posted curriculum that has been QA'd or otherwise feels OK to share as quality work.
3)   The most recent workshops are here:  https://github.com/emmairwin/community_curriculum/tree/master/leadership  but they are only in draft state, and it might look bad/poor if they were posted as content without that disclaimer or status IMHO.
4)  The education portal is a means to an end that I built instead of using a wiki which I really didn't want to use for curriculum, Akshay, Ioana and others have been amazing in helping improve and brainstorm solutions.  BUT in 2016  we will be moving to a new solution as determined through #216 .  
5) I purposely abstracted curriculum in it's own Repo so if we changed front-end, it wouldn't matter so long as we can render markdown.  
6)  We  (MLN, Open Science and other writing curriculum) had a kickoff call this week to talk about a single way to develop and share curriculum!  Here are some of the questions we covered - would love to know your thoughst as well, as anyone improving, writing, sharing or hoping to leverage curriculum in 2016:

If you want to answer these questions below would love your input:

Question: If we had a central repo/database/finder for curriculum for everyone at Mozilla writing curriculum.
- What  needs do you think we should consider for discover-ability, and searchablity?
- What should we build in 2016, what kind of vision, practices and templates ? 
- What have you seen elsewhere that does one of these really well?
-  How can we build contribution into that process? What does that look like? 
-  How (as we began to discuss in #230 , can we make contributing to curriculum a learning experience for learning Github?
  
  @verenanz1 you might have some thoughts on vision, practices, templates

**Comment by jgmac1106** [comment]
I have responded to the similar thread over in MLN and checked out the etherpad:

Here are a couple examples:
This is the d106 assignment bank. It is probably the best parallel as it is openly licensed and user generated: http://assignments.ds106.us/
The OER commons is also another amazing resource (and has plenty of curriculum we should be remixing): https://www.oercommons.org/
Teachers paying Teachers organizes over 1.7 million different lesson plans.

_The first level of contribution of curriculum has to be in the simplest form possible from as many channels possible._

I was thinking about this with the l10n work around the web literacy curriculum. Thinking I could ask different people in higher ed if they want to get their classes or grad students involved. 

But I can't we are conflating the goal of curriculum developemt with the goal of moving to Git.

If someone wants to translate curriculum or submit a new teaching kit we should be open to as many ways possible (email a document, a Thimble remix, Google Docs template a stripped down markdown to git-hub pages editor).

_I still say Thimble should be the major entry point that is pushed_

One of the original Participation Leader Goals was to unite people and product. Mozilla has invested millions in building the premier online editor. Leverage the tool.

It can do markdown files or html. If you are worried about the difficulty of mark up _keep the templates simple._ Let ease of use be the primary design consideration. I like pretty stuff but pretty stuff leads to user error.

Then contributors or participation leaders can curate the content from all the channels. It is at this point the Git repos get involved.

If there is someone submitting a lot of tier one curriculum they could then be trained in using Git. It will take 1:1 or small group synchronous support.

**Comment by asdofindia** [comment]
> What needs do you think we should consider for discover-ability, and searchablity?

For making things easy to discover, MDN is doing it correct with [Learning the Web](https://developer.mozilla.org/Learn). [Links are better than search](http://uxmyths.com/post/717755413/myth-search-will-solve-a-websites-navigation-problems)

Additionally, having suffered bandwidth limits, I prefer text-based resources to be given as much importance, if not more compared to videos.

And, teaching guides are becoming boring. Teaching guides are only useful if there's someone to teach. (I mean, not exactly. But they're designed for that). I am looking forward to seeing more of self-guided content. I don't think the actual school teachers in India will be taking up Web literacy as a part of their teaching lessons any time soon. And I can't rely on Mozilla volunteers to be everywhere. We're loosing a large number of learners by not creating content directed at them.

> What should we build in 2016, what kind of vision, practices, and templates?

Vision: Build something like a Wikipedia for Mozilla/Open-source/Advocacy/Open-Web.
Practices: Ease of contributing or at least transparency in how content is contributed. Ability to point out errors/missing resources. 

>  What have you seen elsewhere that does one of these really well?

Wikiversity? I don't know.

> How can we build contribution into that process? What does that look like?
> How can we make contributing to curriculum a learning experience for learning Github?

As @jgmac1106 pointed out, a tiered introduction for persistent contributors will probably work.

**Comment by jgmac1106** [comment]
Another example: The Smithsonian Institute just released the world's larget OER repository. https://learninglab.si.edu/

**Comment by asdofindia** [comment]
Aha, that Smithsonian Institute seems to have [done a lot of research](https://learninglab.si.edu/news/what-we-have-learned-so-far-the-digital-learning-resources-project) and come up with [some kind of a gallery for the content](http://scems.navnorth.com/) it has. This might be useful when thinking of a UI for our central database.

**Comment by emmairwin** [comment]
Thanks for feedback.  there will be a curriculum meeting in Orlando.
