### ISSUE TITLE
Launch "Save Mika!" (Foxfooding gamification)

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#219]
## Success:

50 participants by end of heartbeat
## Related Issues & Links:
- Meta: #182
- Mascot design: #207 
- Project Mika: https://docs.google.com/presentation/u/1/d/1MALfK-LKvESoEgKCwwW37epb9YLZNQiVV6w66en7SOg/edit#slide=id.ge7cfdd563_0_112
## Roles:

Owner: @wquiviger
Involved: @LucyeoH @brianking @dstrohmeier @ppapadeas 
## Required:
- [x] coordinate with Marcia and Domink for bug filing template foxfooders should use when filing bugs (@wquiviger, [medium], Due: Nov 18th)
- [x] finalize storyline and copy for quests based on product/engineering needs (@wquiviger @LucyeoH [medium], Due: Nov 18th)
- [x] get legal sign off from Elvin and Marshall (@wquiviger, [medium,], Due: Nov 18th)
- [x] get final design for Mika Mascot with @Yofie (@wquiviger, [medium,], Due: Nov 18th)
- [x] finalize scoring system + leaderboard display on hub (@wquiviger, [medium,], Due: Nov 18th)

**Comment by LucyeoH-zz** [comment]
#207 for Mika Mascot
