### ISSUE TITLE
Heartbeat 2: Support implementation of playbook for Webmaker App launch in Indonesia and Kenya

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#22]
# Initiative description / framing

Mozilla Foundation launching two new initiatives in 2015Q2:
- all-new Webmaker: a free, open source platform that is simple, fun and a key building block for understanding the Web. Emerging from beta in June. 
- Mozilla Clubs: an opportunity for makers, mentors and learners to meet regularly to learn the mechanics, culture and citizenship of the Web together. 

Together, these two initiatives aim to empower people everywhere to actively shape — not just passively use — the Web. To do this, we need your help. 

Link to overall Q2 plan: https://docs.google.com/presentation/d/1ALd2o6Lo47T_0PRfbewTWOrsqN9fj2qjuKJ7pbJJ_-M/edit#slide=id.g61dbf6ada_211
# Deliverable

The Participation team will work closely with communities on the ground in target markets (ie. Indonesia and Kenya) to get everyone familiar with and implement the Webmaker app playbook. 
# Primary Goals/Objectives for this Heartbeat

Create plan to rally local communities behing Webmaker app launch and implement playbook in Kenya and Indonesia
# Secondary Goals/Objectives for this Heartbeat

Start reaching out to Brazil and Bangladesh and prep them for next heartbeat
# Milestones
- May 19: kick-off meeting
- May 21: planning meeting with Kenya community
- May 22: planning meeting with Indonesia community
- May 26: share draft of plan to each community for feedback
- May 29: final draft of plan ready for implementation

RACI
Owner: William 
Project manager: William
Informed or Consulted: Brian, Bobby Richter, Paul Johnson
### References

Overall Q2 Webmaker playbook: https://docs.google.com/presentation/d/1ALd2o6Lo47T_0PRfbewTWOrsqN9fj2qjuKJ7pbJJ_-M/edit#slide=id.g61dbf6ada_211

**Comment by deimidis** [comment]
I'm working with Bobby and Paul in Brazil implementation of this plan, I would be ineterested on how we could share ideas and work

**Comment by williamq** [comment]
Yes, definitely. 

I had a chat with Bobby yesterday about this. I think the idea is for me to go to Jakarta and run a training workshop with the community there, first week of June. 

I have another meeting with Bobby and Paul next week so I’ll have more info on this. It would be good for you to join that meeting since we’ll be doing more or less the same thing I’m sure. 

I’ll let you know as soon as I know more about next week’s meeting. 
- w

**Comment by williamq** [comment]
## What was supposed to happen?

We were supposed to gather feedback from Kenya and Indonesia communty and work on final draft of plan. 

## What did happen?

We gathered feedback but did NOT come up with final plans. The latter was due to 2 things: 
1) playbook was not completely finished by the time Brian and I traveled to Kenya
2) trip to Jakarta was postponed 2 weeks so it will be drafted during the next heartbeat

## What are some improvements we should make?
- We were too optimistic about getting final playbook draft from Webmaker team in time so we should set more realistic deadlines
- we should coordinate with local community much more early in the process to coordinate travel better

## What should we keep the same in this process?
- we should continue liaising daily

## What does the next Heartbeat for this project look like?

The next heartbeat will focus on Indonesia (we'll move Kenya to next heartbeat) and William will be spending the weekend (June 13-15) with Indonesia community to come up with actionable plan to launch Webmaker in Indonesia mid-July.

**Comment by brianking** [comment]
@williamq  Can this one be closed?
