### ISSUE TITLE
Firefox OS Community Playbook v0.1

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#220]
## Goal:

Create first draft of Community Playbook for Firefox OS participation, modeled on the playbook used for the Webmaker launch. 
## Success:

Playbook 75% finalized
## Related Issues & Links:
- Meta: #182
- Webmaker playbook model: https://docs.google.com/presentation/d/1ALd2o6Lo47T_0PRfbewTWOrsqN9fj2qjuKJ7pbJJ_-M/edit#slide=id.g9cff24e8a_2_29
## Roles:

Owner: @wquiviger
Involved: @brianking @rosanardila @nukeador 
## Required:
- [ ] create outline of each section of playbook: Porting, Add-ons, Foxfooding, Smart TV, Gaia Development, Marketing, QA  (@wquiviger @brianking  [medium], Due: Nov 18th)
- [ ] work with Fx OS stakeholders leads to create content for each section based on outlines (@wquiviger, @brianking [medium], Due: Nov 20th)
- [ ] work with @rosanardila to establish regional roll-out sequence of playbook once it is finalized (@wquiviger, @rosanardila [medium], Due: Nov 23rd)

**Comment by ioana-chiorean** [comment]
@williamq - let me know if I can help you here :)

**Comment by LucyeoH-zz** [comment]
First draft completed still in feedback phase!
