### ISSUE TITLE
Advance Coaching framework to community members

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#222]
## Goal:

Learn from our previous quarter, add insights from others coaching frameworks and continue with our coaching sessions
## Success:

Reach 30 core contributors, 90 active members and 45 emerging members and established a relationship with them. 
## Related Issues & Links:
#171
## Roles:

Owner: @deimidis
Involved: @nukeador @rosanardila @emmairwin @geroter 
## Required:
- [x] Mozlando coaching guide (@emmairwin, [small], Due: Nov 19th) 
- [ ] Review of FACTS coaching model (@deimidis, [medium] Due: Nov 17th) 
- [x] Learnings at MozFest coaching (@deimidis, [small], Due: Nov 17th)
- [x] Second meeting with core contributors (@deimidis, @nukeador, @rosanardila , [big], Due: Dec 3rd)
- [x] Each Core contributor had a clear plan for their next 3 months (@deimidis, @nukeador, @rosanardila , [big], Due: Dec 3rd)
- [x] Contact 30 new contributors (@deimidis, @nukeador, @rosanardila , [big], Due: Dec 3rd)
- [x] Contact 10 new emergent leaders (@deimidis, @nukeador, @rosanardila , [big], Due: Dec 3rd)

**Comment by LucyeoH-zz** [comment]
Clarification: "new contributors" means people who haven't been met with in the past quarter.

**Comment by deimidis** [comment]
We decide to coach 45 volunteers invited to Orlando. 2 people couldn't attend Orlando meeting in the end, just 3 didn't answer emails or ask for a meeting with us.

Faye Tandog help us with coaching people in Asia.

**Comment by deimidis** [comment]
I still didn't finish review of the FACTS model.
