### ISSUE TITLE
Logistics for Singapore Leadership Summit

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#223]
## Goal:

Define and finalize the initial coordination for Leadership Summit
## Success:

Have the venue, hotel, catering, and A/V confirmed for the event, as well as the amount of rooms.
## Related Issues & Links:
#164
## Roles:

Owner: @francjp
Involved: @geroter 
Informed: @couci @emmairwin 
## Key results:
- [x] Get the agreement signed with the hotel and vendor (30/11)
- [x] Confirm catering (30/11)
- [x] Confirm A/V resources (30/11)
- [x] Confirm accommodation (3/12)

**Comment by LucyeoH-zz** [comment]
Add dates & turn bullets into checkboxes (so you can check them off as you go!)

**Comment by francjp** [comment]
All this has been slightly delayed since accounting hasn't give the final ok yet.
I'm waiting for Mitchell's approval.

This will continue in the next heartbeat.

**Comment by francjp** [comment]
Updated milestone and tags.
Came from previous heartbeats.

Need to update the budget to reflect the changes.

**Comment by LucyeoH-zz** [comment]
Woo! Completed!
