### ISSUE TITLE
Improve support documentation for Reps program

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#224]
## Goal:

Create a couple of documents to improve the resources that Reps has at this moments.
## Success:

Reps program using those templates as a base to
## Related Issues & Links:
#12
## Roles:

Owner: @francjp
Informed: @rosanardila @nukeador 
## Key results:
- Create a Planning pad template
- Create a plan for Budgeting training
- Review the events playbook
## Heartbeat Issues:

November 20 - Have at least 2 drafts
November 27 - Reviewed and with some feedback about Events playbook
December 4 - Finalize and publish the results.

**Comment by LucyeoH-zz** [comment]
Review event playbook to improve the quality of the document.

**Comment by LucyeoH-zz** [comment]
Notes: 
- Talk to Emma about budget training draft. 
- Add links so other ppl can help with the document review
- Sync with Konstantina and Nuke

**Comment by francjp** [comment]
Worked with Konstantina for Budget training proposals.
Haven't had enough time to move this forward... can I move it to the next heartbeat?

**Comment by francjp** [comment]
Updated milestone and tags.
This will be probably continued on the next hearbeat.
