### ISSUE TITLE
FOSDEM: Prepare selection of volunteers and talks

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#225]
## Goal:

Get the list of volunteers, and talks selected
## Success:

Have a final list of volunteers sponsored for attending FOSDEM, and select the talks for the devroom
## Related Issues & Links:

None
## Roles:

Owner: @francjp
Involved: Benoit, Ziggy
## Key results:
- [x] Publish the call for volunteers (13/11)
- [x] Select the amount of people (4/12)
- [x] Confirm budget
- [x] Select talks
- [x] Publish the CoC for the devroom (30/11)
## Heartbeat Issues:

November 20 - Have a pre-final list of volunteers sponsored
November 27 - Send reminder about C4P deadline
December 4 - Finalize volunteers and Talks selection

**Comment by brianking** [comment]
I'd like to help with talks selection.

**Comment by francjp** [comment]
Almost everything has been done.
Need to prepare the budget, and publish the volunteers selected. Talks will be published on December 18th in the FOSDEM site.

Code of conduct was created and finalized by Larissa, we are working in a way to publish at the devroom.

So this issue can be closed.

**Comment by francjp** [comment]
Reopening, since we need to publish the talks and confirm the volunteers... and the budget.

**Comment by ioana-chiorean** [comment]
Can the volunteer activities/tasks be open so those traveling on their own can help ?

**Comment by francjp** [comment]
We will open an etherpad to track who's going on their own. Need to confirm budget, but most probably we will have 8 volunteers (Reps, and non-Reps) sponsored by Participation team.

Volunteers and Talks will be announced this week (hopefully with the schedule, but not sure).

**Comment by francjp** [comment]
Update:
- Schedule confirmed and announced: https://fosdem.org/2016/schedule/track/mozilla/
- Volunteers selected and announced.
- Working on a CoC for the devroom (Ziggy and Larissa)
- Need to confirm shifts for our booth
- Need to confirm roles for volunteers
- [ ] Debrief Document (@francjp, [medium], Due: Feb 5th)
