### ISSUE TITLE
Firefox OS Marketing Plan for Developers

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#226]
## Goal:

Target developers with messaging and other programs to bring in new technincal contributions to Firefox OS
## Success:

Plan 75% finalized with 2 activities already started
## Related Issues & Links:
- Meta: #182
- Skeleton Plan: https://docs.google.com/document/d/19Vmbf_8BxsZ9dNtGEXuZaMKGC9M-sLLAk2F9W5ywZUg/edit?usp=sharing
## Roles:

Owner: @brianking
Involved: Marcia Zikan
## Required:
- [x] schedule kick-off meeting (@brianking  [small], Due: Nov 13th)
- [x] determine who needs to be pulled in to the team to work on this (@brianking Marcia  [medium], Due: Nov 16th)
- [ ] first draft of plan (@brianking Marcia  [large], Due: Nov 24th)
- [ ] send draft to Firefox OS Participation team and receive first round of feedback (@brianking Marcia  [large], Due: Dec 1st)
- [ ] kick-off two activities (@brianking Marcia  [medium], Due: Dec 3rd)

**Comment by brianking** [comment]
There are bits and pieces happening on this so far, but it has not picked up as much momentum as I would have liked. Will give full update at the end of the heartbeat.

**Comment by LucyeoH-zz** [comment]
Put off until post-Orlando!

**Comment by brianking** [comment]
No longer relevant.
