### ISSUE TITLE
Gather insights about the Reps Weekly Call 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/participation-org#227]
# Gather insight about reps engagement in the Weekly Reps Call

Volunteer subtask 

We would like to see the progress of the engagement of reps in the weekly call in the last 4 months 
- No of attendees in the call/pad
- No of watchers on airmo
- No of views of discourse topic
- No of views on links in discourse 
## Roles:
- Owner: @ioana-chiorean
- Involved: @couci
## Timeline
- [ ] Gather data from ethepads, wikis, discourse (@couci, @ioana-chiorean, [large], Due: 20th Nov)
  *\* Data will be recorded [here](https://docs.google.com/spreadsheets/d/1lR6XqEbjFRY7GP5Lt6EMtL60WvkzFd4iqC-mEslgqHo/edit?usp=sharing)
- [ ] Build up a nice display - charts, pies etc (@couci, @ioana-chiorean, [medium],  Due: 23rd Nov)
- [ ] Share the learnings in the council call( @couci, @ioana-chiorean, [small],  Due: 25th Nov)
- [ ] Share the learnings in the reps call (@couci, @ioana-chiorean, [small],  Due: 26th Nov)
- [ ] Open discourse/blog for feedback (@ioana-chiorean, [medium],  Due: 27th Nov)

**Comment by LucyeoH-zz** [comment]
Maybe loop Mardi into this! Trying to do a similar thing for internal call.

**Comment by ioana-chiorean** [comment]
We will sure do! Thanks for the tip!

**Comment by couci** [comment]
Didn't have time to work on this with @ioana-chiorean . Will transfer it to the next heartbeat and co-ordinate in Mozlando.

**Comment by ioana-chiorean** [comment]
Is this moved to the other milestone? I started a spreadsheet to gather data but it is a harder work than expected :))

**Comment by couci** [comment]
Yes, we are going to move on the next milestone @ioana-chiorean, please add the link of the spreadsheet here too and I'll move it on the next heartbeat.

**Comment by ioana-chiorean** [comment]
> Data will be recorded here

It is added in the first comment.

**Comment by LucyeoH-zz** [comment]
@ioana-chiorean hey! Is project still happening?

**Comment by ioana-chiorean** [comment]
Hey @LucyeoH - I am still working on this. 
I did parse several of them but needs more time. I have moved it to the next heartbeat. 

I did presented some of the insights gathers in a lightning talk at the Leadership Summit and i a 20min talk at FLOSCM (http://flosscommunitymetrics.org/)
