### ISSUE TITLE
Post-Launch Hub Momentum

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#228]
## Goal:

Determine fixes and new features roadmap for the Hub for the next month
## Success:

100% bugs triaged and prioritized, and feature roadmap written down
## Related Issues & Links:
- Meta: #182
- Hub: https://firefoxos.mozilla.community/
## Roles:

Owner: @brianking
Involved: @ppapadeas @comzeradd @akatsoulas @johngian @williamq 
## Required:
- [x] map out path to getting foxfooding OTA issue foxed (@brianking  [small], Due: Nov 13th)
- [x] schedule meeting on current status (@brianking  [small], Due: Nov 13th)
- [x] triage bugs (@brianking  [medium], Due: Nov 23rd)
- [ ] spec updated / new features (@brianking  [medium], Due: Nov 25th)
- [ ] Postmortem on participation hub process (@brianking @ppapadeas @williamq [medium], Due: Nov 27th)

**Comment by LucyeoH-zz** [comment]
[ ] Postmortem on participation hub process

**Comment by brianking** [comment]
About the OTA breakage and foxfooding bugs:
https://discourse.mozilla-community.org/t/i-think-ive-updated-to-a-broken-build-now-what/5384

**Comment by brianking** [comment]
https://github.com/mozilla/feedthefox/issues doesn't have a way to prioritize bugs yet, so I just left a comment in all open bugs.

**Comment by brianking** [comment]
OTA Update bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1224725

There are also discussions going on in email threads. The solution is not trivial. Every time we get close, a new issue comes up. The latest is that we wanted to target updates to users with a particular build id, but it now seems all (Mozfest, at least) foxfooders are not on the same build id.

**Comment by comzeradd** [comment]
> https://github.com/mozilla/feedthefox/issues doesn't have a way to prioritize bugs yet, so I just left a comment in all open bugs.

I added priority labels, so we can filter issues by priority.

**Comment by LucyeoH-zz** [comment]
Blocker: Infra Team time constraints.

**Comment by brianking** [comment]
Closing this. Has morphed into changing the Hub for CD. See #338.
