### ISSUE TITLE
Gathering Flickr Albums

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/participation-org#229]
Just an ongoing list of Flickr streams from #mozfest that have been shared across the Interwebz:
https://www.flickr.com/photos/phizkdayvil/albums/72157660402529978
https://www.flickr.com/photos/christosbacharakis/sets/72157661293035665

I will just edit this initial issue as people share. Please remember to check and respect the license assigned by the photographer.

**Comment by ioana-chiorean** [comment]
@yofiesetiawan shared his ones too: "My flickr album https://flickr.com/photos/30276804@N08/sets/72157658799225593 "

**Comment by Mte90** [comment]
https://www.flickr.com/photos/mozfest/albums/72157658567152683
https://www.flickr.com/photos/mozfest/albums/72157660181490099
https://www.flickr.com/photos/mozfest/albums/72157658649418943

Official photo from the official account of mozfest on flickr

**Comment by ioana-chiorean** [comment]
@brianking - My Mozfest 2015 pictures: https://flic.kr/s/aHskptpJau

**Comment by ioana-chiorean** [comment]
Tanha's: https://www.flickr.com/photos/phizkdayvil/sets/72157660402529978

**Comment by GDHFang** [comment]
https://www.flickr.com/photos/milkway_gdh/albums/72157661062416440/with/22604725374/ 

This is my Mozfest 2015 photos, all of them are released by CC-BY.

**Comment by shadowcrow** [comment]
https://www.flickr.com/photos/iampush/albums/72157660885043172 
My MozFest  photos continue update
released by CC-BY

**Comment by LucyeoH-zz** [comment]
@jgmac1106 looks like you got a bunch of great albums. Is this still something you're working on or can it close?

**Comment by ioana-chiorean** [comment]
Hey all - I've greated a group so we can add all albums in one place: https://www.flickr.com/groups/2900863@N24/ 
@jgmac1106 @shadowcrow @GDHFang @Mte90 @yofiesetiawan @brianking
