### ISSUE TITLE
Education for Firefox OS & Reps

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#232]
## Goal:

Stay connected with Reps  + FFOS Campaigns
## Success:
-  Clear understanding of emerging goals, and skills, knowledge, attitude required to help these initiatives reach success - early curriculum topics and workshop design goals have been identified for design in the next heartbeat.
## Related Issues & Links:
- https://github.com/mozilla/participation-org/issues/220
- https://github.com/mozilla/participation-org/issues/206
## Roles:

Owner: @emmairwin
Involved: @geroter  
## Required:
- [x] Reach out to @rosanardila  for update & schedule a second checkin on topic of Reps Education (@emmairwin, [small,] Due: Nov 27th) 
- [x] Reach out to @williamq  & schedule an update on Education related to Firefox OS(@emmairwin, [small],  Due: Nov 27th) 
- [x]Schedule a follow-up with @williamq on playbook and education support (@emmairwin, [small],  Due: Nov 27th) 
- [ ]  Schedule an update with @geroter [small] Due: Dec 27th) 
- [x] Summarize findings, with @verenanz1 and propose some first steps for curriculum design & workshops. Due: Dec 4th)

**Comment by emmairwin** [comment]
From discussion so far
- Waiting on playbook from @williamq which can help visualize educational support
- Waiting for decisions and confirmation on Reps Issue, in the meantime have done a high level and identified one action item
  
  update the github.com/emmairwin/community_curriculum to have an index of printable workshops.  
  Currently leadership workshops are not displayed on the Education Portal because they are not properly QA'd or tested more than once.  But having them in the repo makes it hard to 'discover' or understand.   Will create an index as a temporary measure - dependent on #216 for long-term soution for curriculum findablility, which ideally includes workshops in 'draft status'

**Comment by jgmac1106** [comment]
Where is the education portal?

**Comment by asdofindia** [comment]
@jgmac1106, It's at education.mozilla-community.org

(And it is true that a lot of people do not know where/what the education portal is.)

**Comment by ioana-chiorean** [comment]
cc me @emmairwin when u need some QAing over the page - i do no see this yet up.

**Comment by emmairwin** [comment]
To provide a bird's eye view of what we created for open science, tech women, FSA, tech speakers and other testing groups I put this together:  http://emmairwin.github.io/ 

This is a temporary way to see what workshops we’ve run, are testing or developing - for those planning 2016, to leverage and build on, vrs reinvent.

None of these are actually meant to be self-serve. A conversation needs to take place first. Emma can fill you in on the best formats, outcomes, and results to-date. What works better online, and offline.

**Comment by verenanz1** [comment]
Emma-

This really help me figure out what is going on.

I think we should talk about outcomes -what you mean by them...and I also think we should add in a connection to the Mozilla digital literacy competencies.

You have some great topics. I can go through each of them and now write up some notes, next steps.

When do you want me to get at least some of this done by?

Verena:)

**Comment by emmairwin** [comment]
@verenanz1 oh great, I was running so hard there for a while, it was hard to surface this overall.   This also reflects some of my thinking on how curriculum can be organized with attribute, workflow status.
Agree literacy should be part of that.

Although I put this together, I wouldn't say they are entirely self-serve at the moment, there might be some broken links, and explanation needed.  Quick thoughts

1)  I'll need some feedback as part of this issue (by end of this week) from @rosanardila and @williamq on what educational support they'll need in 2016. 
2)  If any of their edu priorities can be met with one of these existing workshops, then we would prioritize making those quality over the others.

And having your input would be amazing on those priorities.  Having said that if any one of these speaks to you to improve and re-work, definitely go for it - we still need them all!  no deadline at the moment!

Also I have to create a workshop for volunteers in Orlando, I'll ping you in email to get your thoughts there as well.  Thanks!  yay for amazing help!  so excited.

**Comment by verenanz1** [comment]
Ok - Sounds good. Ping me when you have some specific workshops that I can
work on.

Things are starting to make more sense Emma :)

On Tue, Dec 1, 2015 at 9:17 AM, Emma notifications@github.com wrote:

> @verenanz1 https://github.com/verenanz1 oh great, I was running so hard
> there for a while, it was hard to surface this overall. This also reflects
> some of my thinking on how curriculum can be organized with attribute,
> workflow status.
> Agree literacy should be part of that.
> 
> Although I put this together, I wouldn't say they are entirely self-serve
> at the moment, there might be some broken links, and explanation needed.
> Quick thoughts
> 
> 1) I'll need some feedback as part of this issue (by end of this week)
> from @rosanardila https://github.com/rosanardila and @williamq
> https://github.com/williamq on what educational support they'll need in
> 2016.
> 2) If any of these speak to those, then we would prioritize making those
> quality over the others.
> 
> And having your input would be amazing. So feel free to take a look at
> what's there, but I can better answer 'what' by the end of the week.
> Also I have to create a workshop for volunteers in Orlando, I'll ping you
> in email to get your thoughts there as well. Thanks! yay for amazing help!
> so excited.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/participation-org/issues/232#issuecomment-161018278
> .

## 

Verena Roberts BEd, MALT, MET

eLearning Consultant and Innovator

email: verenanz@gmail.com

twitter: @verenanz
skype: verenanz74

**Comment by jgmac1106** [comment]
@verenanz1 I can help as well if needed. I remember @emmairwin drafting these activities. They are good. 

One thing to note we may want to add the build the bridge activity from mozfest. That was a huge hit.

There was also a request for training on recruitment.

**Comment by verenanz1** [comment]
Greg - I would love to work with you on creating a set template, or at
least get us started ....

Emma suggested she needs some time before she wants me to jump in.

You tell me when...

V:)

On Tue, Dec 1, 2015 at 11:25 AM, Greg McVerry notifications@github.com
wrote:

> @verenanz1 https://github.com/verenanz1 I can help as well if needed. I
> remember @emmairwin https://github.com/emmairwin drafting these
> activities. They are good.
> 
> One thing to note we may want to add the build the bridge activity from
> mozfest. That was a huge hit.
> 
> There was also a request for training on recruitment.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/participation-org/issues/232#issuecomment-161054500
> .

## 

Verena Roberts BEd, MALT, MET

eLearning Consultant and Innovator

email: verenanz@gmail.com

twitter: @verenanz
skype: verenanz74

**Comment by jgmac1106** [comment]
I think its an after Orlando thing if I am synthesing issues and discourse
threads correctly.

There are many moving parts that may take direction and come into focus
(how many mixed metaphors can I fit?) after all hands.

We will rope in Helen as well.

**Comment by emmairwin** [comment]
What was the build the bridge activity?  Do you see a way we can connect
Orlando Cohort with Mozfest through a small activity.

Yes, after Orlando - we're very much in planning and discovery right now,
but we will hit the ground running soon.   Everything @jgmac1106 says including looping in helen. dream EDU contribution team forming.  <3

On Tue, Dec 1, 2015 at 10:24 AM, Greg McVerry notifications@github.com
wrote:

> @verenanz1 https://github.com/verenanz1 I can help as well if needed. I
> remember @emmairwin https://github.com/emmairwin drafting these
> activities. They are good.
> 
> One thing to note we may want to add the build the bridge activity from
> mozfest. That was a huge hit.
> 
> There was also a request for training on recruitment.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/participation-org/issues/232#issuecomment-161054500
> .

## 

Emma Irwin
@sunnydeveloper
Mozilla Reps Mentor

**Comment by emmairwin** [comment]
In addition to the index (which is a quick way to look up content)

We now have a [spreadsheet to track content ](https://docs.google.com/spreadsheets/d/1lopnYAW6FjZgdUW93djqHJ5dZu3iviDt4-N9l0d_9TI/edit#gid=0&vpid=A1)
- we know we have
- has been proposed so far.

I will be updating the proposals during Orlando, also feel free to add your own based on participation goals for 2016.  Thanks
