### ISSUE TITLE
Community Design Group Has Had First Meeting 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#233]
## Goal:

Have the first meeting of the Community Design Group with design staff and design contributors in January. 
## Success:

 We have a number of people (staff and contributors) who have accepted invitations to a meeting in January, and leaving feeling more connected and with clear next steps for working together successfully in 2016.
## Roles:

Owner: (staff piece) @lucyeoh (contributor piece) @elioqoshi
## Required:
- [x] Invites sent to all staff (@lucyeoh, [small], Due: Dec 24th) 
- [x] Invites sent to all contributors (@elio, [small], Due: Dec 24th) 
- [x] Create and share agenda for first meeting (@lucyeoh + @elioqoshi Due: Jan 7th)
## Want to get involved?

Staff - Please reach out to Lucy 
Contributors - Please fill out this [form](https://docs.google.com/forms/d/1Tw3Mw_CMiqcIQrJF7TB1yIETGYec__NiVhaSz0CAaE8/viewform)  here!

**Comment by Mte90** [comment]
That meeting will be online? 
In case if I want participate to search an help for the Italian community and discuss about my WordPress theme with Mozilla style:
- https://github.com/Mte90/WP-Mozilla
- https://github.com/Mte90/WP-Makerstrap 

Is possible?
I am a developer and not a good designer.

**Comment by ioana-chiorean** [comment]
Nice! Glad to see this rolling!

**Comment by Jobava** [comment]
Hey, can I be part of this?

**Comment by elioqoshi** [comment]
@Mte90 It will yes! Yeah, that could be a good thing to work on!
@ioana-chiorean thanks!

@Jobava Sure! I will reach out to you with the form :)

**Comment by comzeradd** [comment]
Count me in too ;)

**Comment by elioqoshi** [comment]
Awesome @comzeradd !

**Comment by ioana-chiorean** [comment]
Me too !

**Comment by elioqoshi** [comment]
Hey guys, make sure you fill out this form :)
https://docs.google.com/forms/d/1Tw3Mw_CMiqcIQrJF7TB1yIETGYec__NiVhaSz0CAaE8/viewform

**Comment by LucyeoH-zz** [comment]
@elioqoshi any ideas about times and dates you think we should aim to schedule the first meeting?

**Comment by elioqoshi** [comment]
@LucyeoH I was thinking of Thursday 17:00 UTC (Reps Call is always 16:00 UTC)
It should suit most people. (we can always refine again later)

**Comment by ioana-chiorean** [comment]
@elioqoshi  - might be very late for @yofiesetiawan - but we can start maybe 1h earlier than Reps?

**Comment by yofiesetiawan** [comment]
I like 15:00 UTC.. Can we set our meeting to that time?

**Comment by elioqoshi** [comment]
15:00 UTC is impossible for most staff in the US. @LucyeoH what would you think?
Also, the call would be 1x a month for now so we might be able to make an exception maybe

**Comment by elioqoshi** [comment]
Also, we already send the invite so we should stick with it (I told Yofie before organizing the meeting)
@yofiesetiawan are you able to do an exception for this time?

**Comment by yofiesetiawan** [comment]
@elioqoshi ups, sorry, i rarely check on mails in this holiday season, i wish we can rearrange after new year 2016? i'm cool to do it anytime after new year..

**Comment by anistuhin** [comment]
Would love to contribute in the developer issues as a developer, if any  :)

**Comment by elioqoshi** [comment]
@anistuhin thanks! Feel free to join the call and check the issues, there are some!

**Comment by LucyeoH-zz** [comment]
Our first meeting was a huge success and had over 27 people in attendance. 

Watch the recording of the meeting [here](https://air.mozilla.org/community-design-meeting/)
View the meeting slides [here](https://docs.google.com/presentation/d/1_Ctyz5sduYC7bi6j5MlvuCRlA60ho1YdNtmmDOU6H10/edit#slide=id.p)
Add questions/comments/discussion to the discourse topic [here](https://discourse.mozilla-community.org/c/community-design)
Check out the Repo [here](https://github.com/mozilla/Community-Design)
