### ISSUE TITLE
Integrate Reps Call Into Town Hall for Mozlando 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#234]
cc. @ioana-chiorean

**Comment by nukeador** [comment]
Airmo team is not going to available for streaming during mozlando.

**Comment by ioana-chiorean** [comment]
Shortest lifetime for an issue awards goes to... #234
Thanks everyone for chiming in and help getting to a resolution.

**Comment by geroter** [comment]
hey @nukeador is there a work-around for AirMo streaming? Especially considering our desire to have a town hall with lots of viewers ... Hangouts on Air?

**Comment by nukeador** [comment]
@geroter Uhmm, yes, for the Town Hall we can try that via youtube streaming. I guess that would be a separate issue from this one right¿
