### ISSUE TITLE
[Open Task] Curate Recommended Reading List

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/participation-org#235]
Going to start a thread over on Participation seeking recommended reads across different teams.

See the outcome as a categorized list of books and blog posts leaders can use in developing training across their field.

Would want the recommended reading list to cut across different disciplines/teams (i.e. design, learning, leading, management, coding, advocacy etc).

Goal is to to have published list by March. I will probably start it in Thimble and move it to gitpages once finalized.

**Comment by Mte90** [comment]
I've bought that https://www.packtpub.com/business/workshop-box-communication-skills-it-professionals for a developer like me is perfect :-)

**Comment by emmairwin** [comment]
great initiative.  question, how do you see this working (finding things, categorizing), what would contribution workflow look like. I"m sure this is all in your brain already - just peeking in !

**Comment by jgmac1106** [comment]
No idea on workflow. I will probably just start with a gSheet and make it
editable. Thenuse one tab for each category.

Once the list is stable I will create a Thimble project.

Could also go totally third party and make a subreddit so folks can up and
down vote....

But I like in house productions.

**Comment by jgmac1106** [comment]
Made some progress on this last week. Thinking a Discourse thread with a link to a gSheet will be the best approach.

**Comment by LucyeoH-zz** [comment]
Hey @jgmac1106 what's the status of this? If you have a discourse link ready I think this can be taken off the participation project list and we can direct people there. Or if this is an ongoign project, what do you anticipate the close date will be?

**Comment by jgmac1106** [comment]
I will push over to Discourse and reopen or start new issue if it goes anywhere. Right now its just ne, a few others, and a spreadsheet.
