### ISSUE TITLE
Preliminary Strategic Narrative Shared with 500 People

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#236]
From Mozlando a group of Participation Leaders and I came together to brainstorm ways to share the strategic narrative with 2,000 more Mozillians. 

Based on personas we came up with a 3-pronged approach. 

<h3>Blog Post</h3>

KPI - 500 views

Turn strategic narrative into a blog post, very values focused, verbose, and accurate
- [x] Create draft
- [x] Copy signed-off (waiting on George)
- [x] Get it translated - dev-l10n@lists.mozilla.org (Francesco Lodolo [@flodolo]) 
  - [x] Hindi  http://blog.mozillaindia.org/ (appears to be in english) (ankit) 
  - [x] French https://www.mozfr.org (flore) 
  - [x] German http://www.mozilla.de/ (michael kholer)
  - [x] Spanish https://www.mozilla-hispano.org/ (Guillermo) 
  - Portugese http://mozilla.pt/ (not active?) 
  - [x] Italian http://www.mozillaitalia.org (Flod) 
- [x] Share on regional blogs

Due Date: Jan 18th
Accountable: @lucyeoh

**Comment by rara79** [comment]
My GitHub name: @rara79 ;)

**Comment by Jobava** [comment]
I was there too! @Jobava

**Comment by elioqoshi** [comment]
+1 @elioqoshi

**Comment by flodolo** [comment]
I'm not completely sure why my name is in here ;-)

If it's about asking localizers to translate a blog post, the request doesn't need to come from me, it's actually a lot better if it comes from who manages the initiative:
- I would suggest [dev-l10n-web](https://groups.google.com/forum/#!forum/mozilla.dev.l10n.web) more than dev-l10n, given the argument.
- How do you plan to let localizers translate this blog post? I mean, where the translations are going to be stored, how they access them, etc.
- Make your story compelling: why should they localize these projects? Resources are limited, most teams need to pick what to work on.

**Comment by LucyeoH-zz** [comment]
Update: 
- [ ] Working to find a pathway to create an interactive graphic

**Comment by LucyeoH-zz** [comment]
This issue is continued here #297
