### ISSUE TITLE
Leverage our network to recruit for volunteer opportunities from across Mozilla

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#237]
We asked for teams from across Mozilla to pitch great volunteer opportunities they have available right now. **They need help recruiting for these!**

Please forward this along to people you know who would be great for these roles, and get in touch directly with the staff member who is offering the role (or reply to this issue).

**Comment by geroter** [comment]
## ROLE TITLE: Web Security Bug Verification

### Team: Enterprise Information Security

### Skills required:

Web App Security, common vulns like XSS, CSRF, SQLi. how to use a browser proxy.

### Time required:

Up to you

### Job description:

Get in touch!

### Contact:

Adam Muntner  
amuntner@mozilla.com

**Comment by geroter** [comment]
## ROLE TITLE: Open Researcher

### Team: Mofo research team

### Skills required:

Some useful skills are: critical thinking, observation, analytical mind. But the only ones that really matter are curiosity and an open mind.

### Time required:

This is for a year long experimental research project in Kenya, with Gates Foundation. We will study the impact of digital skills trainings and conduct research to understand how people learn best.### Job description:
https://docs.google.com/presentation/d/1TnJk4bBLetG1KQvVoTb17wvQdt5o_JveLUOvVIIAhOQ/edit?usp=sharing

### Contact:

Laura de Reynal
flower@mozillafoundation.org

**Comment by geroter** [comment]
## ROLE TITLE: Web Compatibility Issue Triager

### Team: Web Compat

### Skills required:

Debugging, Knowledge of standards, Ability to read code

### Time required:

1 to 2 hours, UNTIL THE END OF TIME (or like, however long fits into your schedule)

### Job description:

Get in touch!

### Contact:

Mike Taylor 
miket@mozilla.com

**Comment by geroter** [comment]
## ROLE TITLE: Web Compatibility Web Opener

### Team: Web Compat

### Skills required:

Ability to find find contacts for websites and frameworks and help with outreach (asking sites to update code, or fix problems that affect Firefox browser users).

### Time required:

1 to 5 per week (depending on availability), no limit on timeframe.

### Job description:

Get in touch!

### Contact:

Mike Taylor 
miket@mozilla.com

**Comment by geroter** [comment]
## ROLE TITLE: webcompat.com Design + UX contributor

### Team: Web Compat

### Skills required:

Design, UX, Mockups, providing feedback, working with GitHub issues, coding skills not required but could be an opportunity to learn or exercise existing skills.

### Time required:

2 to 5, for as long as someone has time to contribute. Ongoing.

### Job description:

None. But the contributor would be helping to improve http://webcompat.com/.

### Contact:

Mike Taylor 
miket@mozilla.com

**Comment by geroter** [comment]
## ROLE TITLE: Social Community Manager

### Team: Social Team

### Skills required:

Knowledge of and passion for social media Great communication skills Desire to help users get the most out of their browser Languages: local language + English (we are in special need of English, Spanish and Portuguese speakers!) 

### Time required:

2-3 hrs./wk

### Job description:

https://docs.google.com/a/mozilla.com/document/d/1fGvlwNVcjUZZatW0caopJhLvt1RoHN29oO6z1kr8tS4/edit?usp=sharing

### Contact:

Liz Hull  
ehull@mozilla.com

**Comment by geroter** [comment]
## ROLE TITLE: SUMO Contributor

### Team: SUMO

### Skills required:

answering use questions OR translating from English into your mother tongue OR writing informative and clear English instructions OR coding websites (+ GitHub)

### Time required:

from 0 to as many as you want

### Job description:

https://support.mozilla.org/get-involved

### Contact:

Michal  
mdziewonski@mozilla.com

**Comment by geroter** [comment]
## ROLE TITLE: Advocacy and Teaching Task Forces

### Team: Policy & Advocacy

### Skills required:

presentations, research, social media posting

### Time required:

1hr/wk

### Job description:

https://wiki.mozilla.org/Privacy/Privacy_Task_Force

### Contact:

Stacy Martin  
stacy@mozilla.com

**Comment by Amena-Islam** [comment]
Hi  @geroter , I am Amena Islam from Bangladesh. A Senior FSA  and Club lead as well. I am very much interested in the DSO project (Open Researcher). Currently I am working as a Teaching Assistant at University of Liberal Arts Bangladesh and Prepared the Institute for Engineers of Bangladesh(IEB), Institutional Accreditation Report for University of Liberal Arts Bangladesh. As my graduation will be completed within this month  and I was just thinking to work on a research project. I find This role right for me to put my potentiality, analytical skill and leadership skill  to enrich my research skill. I would love to be a part of this project.

Hope to hear from you soon.
Thank you.

**Comment by bacharakis** [comment]
Hi @Amena-Islam and thanks for the reply!
That's great! Feel free to send an email to Laura for this opening but do not forget that this opportunity is in Kenya.

**Comment by Raphseck** [comment]
Hi @geroter. My name is Raphael Eckhardt and I'd be more than happy to engage on the webcompat.com for the Design position! (Sorry about my not fluent English, but I hope it doesn't get on the way).
I already worked as a volunteer for Mozilla before, creating some badges and bookcovers. I'm the person who did Firefox OS guide book cover (Andre Garzia's book, who's also my friend and a rep here in Rio de Janeiro). Also, I did all the visual identity of Rio Mozilla Club that you can check at http://riomozillaclub.org/, an under development project in my city, Rio de Janeiro.
I'm looking forward to hear from you and be able to help Mozilla grow! :)

**Comment by ioana-chiorean** [comment]
hey @Raphseck - I think it will be better to mail the contact person from the webompat as mentioned in the description: 
Contact: Mike Taylor
miket@mozilla.com

**Comment by mijanurrahman** [comment]
wow ! Love to work with Team: Enterprise Information Security :+1: 
@amuntner I am here dude :D
