### ISSUE TITLE
[KR 1] NDA Process V1 Rolls Out by EOQ

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#238]
## Goal:

V1 of NDA process launches by EOQ. 
## Success:

A subset of communities are moved over to the new NDA and we've worked out an initial bugs. 
## Related Issues & Links:
#211
## Roles:

Owner: @lucyeoh
Involved: @ppapadeas 
## Current Status:
- [x] Multiple curators -> someone needs to apply
- [x] Showing legal document
- [x] Expiry set at 1 year
## Required:

High priority for Q1: 
- [ ] Enable invitation features [Done by: Feb 5th]
  - remove the apply button (make group invite only)
  - record who sent invitations 
  - re-work renewal system so that after one year they are automatically removed from the group and Inviters have to re-add them. 
- [ ] Being able to email the whole group [Done by: Feb 5th]
- [ ] Technical blocker removed [Done by: Jan 22nd) 
- [ ] Inform affected communities and prep them for starting to move people over (@lucyeoh, [medium], Due: Jan 20th) 
  - [x] SUMO
  - [x] Reps
  - [ ] FSA
  - [x] L10N
  - [x] Process for staff to add contributors

**Comment by LucyeoH** [comment]
BLOCKER: Green light from Mitchell & Dave
