### ISSUE TITLE
Pivot Participation Leaders goals - Firefox OS

### ISSUE THREAD

**Issue by elninosi** [mozilla/participation-org#240]
With the announcement that Firefox OS is pivoting to "Connected devices" Participation Leaders might also need to pivot their goals (if the goals were connected with Firefox OS on mobile).

**Comment by emmairwin** [comment]
@elninosi perhaps we can think about what those connections points might be already, and then build on them?  How do you see this process of pivoting?

**Comment by LucyeoH-zz** [comment]
@elninosi this is a great discussion for @emmairwin as she's been working on this. I don't think it needs to remain an issue so I'm closing this.
