### ISSUE TITLE
Local Swag production Initiative

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#241]
## Goal:

Produce Local Swag with communities
## Success:

  We have a solid plan for creating swag in communities. The plan is going to be made based on the mid term plan of each community and implemented on the Indonesian community
## Related Issues & Links:
#151
## Roles:

Owner: @couci
Involved: @deimidis, @alamanda, Indonesian community

**Comment by alamanda** [comment]
I'm adding @andi-belutz here

**Comment by Jobava** [comment]
I can produce all manner of swag in my home town relatively cheaply: pens, pins, stickers, embroidered patches, mugs, prints (any size). If you have some things in mind and quantities, I can give you a cost estimate. For example, T-shirt prints (one side, A4 size) are about 3.3EUR and the blank T-shirts (any size, several colors) about 5.5EUR.

**Comment by dricupello** [comment]
@couci can you put me onboard In this issue In Brazil?

**Comment by couci** [comment]
@Jobava a right now we are experimenting with communities that have a mid term planning so we need to wait and see what we can do in Romania. It can be a solution for Europe
@dricupello of course, for now we had the Indonesians since they already have a mid term planning we can work with and calculate the swag we need. Do you have the one from the Brazil community?

**Comment by deimidis** [comment]
@dricupello like @couci says we will wrok with Indonesian community so it could be use like an example to other communities. Anyways, it will be good that you continue looking here for your ideas and opinions

**Comment by alamanda** [comment]
hey @couci @andi-belutz and I have started the process and I've shared the midterm planning documents and rough draft of budget consolidation with you. should I share the same docs and spreadsheet with @deimidis too?

**Comment by couci** [comment]
@alamanda yes I think that since your budgeting includes the local swag initiative it would be could that @deimidis has access to it.

**Comment by couci** [comment]
@alamanda do we have a consolidated budget for swag you are going to need?

**Comment by alamanda** [comment]
can I have your email address @deimidis 
so sorry for missing this one out.

**Comment by couci** [comment]
for now we are working on formalising the budget for the Indonesian community so we can estimate the amount of the swag we will need. Once it is approved we will reopen this one.
