### ISSUE TITLE
Put together a process for building a comprehensive map of Mozilla's participation software/infrastructure landscape.

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#242]
## Goal:

Put together a process for building a comprehensive map of Mozilla's participation software and infrastructure landscape.
## Success:

Started the project. Recruit some people to help.
## Related Issues & Links:

Meta issue: https://github.com/mozilla/participation-org/issues/247
Google doc output: [DRAFT: Mapping Mozilla's Participation Software Landscape](https://docs.google.com/document/d/1nf-n2R4DfU3h1JzpbrQ-Z6a9u6G8cQrD0ZVl7-Z10qE/edit#)
## Roles:

Owner: Lyre Calliope
Involved: James Lewis
## Required:
- [x] Recruit help
- [x] Define scope of project
- [x] Put together framework that can be evaluated
- [x] Create collaborative and onboarding documentation

**Comment by Mte90** [comment]
Any info about that?

**Comment by geroter** [comment]
Lyre is rocking this one out!

**Comment by CaptainCalliope** [comment]
@Mte90 This came out of a conversation involving nearly 20 people about where to start in building the Participation Software Lab. I noticed that we were hung up on talking about specific infrastructure rather than creating an overarching strategy and I suggested that we needed a map of the territory lest we begin making piecemeal decisions regarding infrastructure.

And that's as much detail as I have right now. Will be working on getting to greater specificity over the coming days.

**Comment by ioana-chiorean** [comment]
@CaptainCalliope - @Mte90 started a platform to display something similar you propose:  https://mte90.github.io/Participation-Lead-Map/

**Comment by jgmac1106** [comment]
There is already a map to track mozilla Clubs on teach.mozilla.org.

Maybe you could just poach that code and fork it for participation leaders.

**Comment by Mte90** [comment]
There is also a map of the reps, I think that we can extend that to all the way of participation and create an unique app for that.

**Comment by CaptainCalliope** [comment]
Thanks for the tips I should clarify that I'm talking about a more conceptual map. I'm looking at various community asset mapping and resource inventory methodologies to come up with a lightweight process that we can deploy quickly and inexpensively (time and people-wise).

It's the kind of map we'd make in diagram and spreadsheet form after a two-day workshop with lots and lots of sticky notes. Only, we're not going to use sticky notes nor do we have two days to workshop this in person.

This should be fun. :)

**Comment by CaptainCalliope** [comment]
Relevant prior work that's been done:
- https://wiki.mozilla.org/MOSS/Projects_in_use_by_Mozilla
- https://wiki.mozilla.org/People:removing_roadblocks_to_productivity/survey_results

**Comment by CaptainCalliope** [comment]
I've recruited James Lewis, a brand new volunteer contributor, with experience in this kind of process.

Over the holiday we started work on this google doc which will function as a project overview, progress tracker, and for collaborative onboarding: https://docs.google.com/document/d/1nf-n2R4DfU3h1JzpbrQ-Z6a9u6G8cQrD0ZVl7-Z10qE/edit# 

It's a day or two from being really ready to share, but it's close enough. :) I'm not opening it up to editing yet, but feedback via comments are very much welcome and encouraged!

This issue can be marked as complete.

**Comment by brianking** [comment]
Great work.

**Comment by CaptainCalliope** [comment]
Thanks @brianking!

Would love feedback from anyone with free cycles, and especially anyone who's been part of the Participation Software Lab discussions thus far! Feedback can be given on github issue https://github.com/mozilla/participation-org/issues/247, [this discourse thread](https://discourse.mozilla-community.org/c/participation/parsol), and [via comments on the google doc itself](https://docs.google.com/document/d/1nf-n2R4DfU3h1JzpbrQ-Z6a9u6G8cQrD0ZVl7-Z10qE/edit?usp=sharing).
