### ISSUE TITLE
UK Community Mid-Term Plan Draft

### ISSUE THREAD

**Issue by tad124737337** [mozilla/participation-org#243]
# Goal:

Deliver a first draft of UK community plan for the next 6 months
# Success:

The plan is delivered and the community should have agreed
# Related Issues & Links:
# Roles:

Owner: @TomFarrow @nukeador 
# Involved:
# Required:
- [ ] Core group is formed, medium, Due: Jan 6th
- [ ] Initial conversations are started, small, Due: Jan 7th
- [ ] First draft delivered, large, Due: Jan 31
- [ ] Iteration created based on community feedback, medium, Due Feb 7th

**Comment by ioana-chiorean** [comment]
cc @AlexLakatos

**Comment by AlexLakatos** [comment]
I'm in London, anything I can do to help with this? cc @TomFarrow @nukeador

**Comment by nukeador** [comment]
First online meeting announced here

https://discourse.mozilla-community.org/t/important-mozilla-uk-online-meeting-december-22nd/5846/

Help spreading the word welcomed! :)

**Comment by LucyeoH-zz** [comment]
Hey @TomFarrow what's the status of this? Will it be done by January 29th or would you like me to add it to the Q1 Contributor milestone (that closes March 31st)?

**Comment by tad124737337** [comment]
Would be awesome to move this one to march 31st :)
