### ISSUE TITLE
Leverage our formal FSAs in Taiwan & China to re-active volunteers for campus event

### ISSUE THREAD

**Issue by irvin** [mozilla/participation-org#244]
## Goal:

Cooperation with Estela from Taipei, and Liu Ying from China, with the help from TJ to spread and promote our spring privacy campus event with formal FSAs from China & Taiwan's local FSA program.
## Success:

Get some students to carry out that campus event.
## Related Issues & Links:

[Reference meta issues and past issues] #
## Roles:

Owner: Irvin
Involved: TJ, Estela, Liu Ying, Liu Xing
## Required:
- [ ] Translate the spring event materials
- [ ] Prepare the contact info of those formal FSAs and save into mailing list
- [ ] Invite those formal FSAs to join Telegram / weChat group 
- [ ] Find some student volunteer to run spring event

**Comment by holywen** [comment]
Please count me in as well, thanks!

**Comment by ioana-chiorean** [comment]
@irvin do you have a link for the materials?

**Comment by irvin** [comment]
The event is still under design and has no any material yet.

Ioana Chiorean notifications@github.com 於 2015年12月13日 星期日寫道：

> @irvin https://github.com/irvin do you have a link for the materials?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/participation-org/issues/244#issuecomment-164286120
> .

## 

@ irvinfly: community liaison
moztw.org Mozilla Taiwan community

**Comment by shadowcrow** [comment]
I want to join this project. It would be great discuss with Estela and TJ.

Irvin notifications@github.com 於 2015年12月14日 星期一寫道：

> The event is still under design and has no any material yet.
> 
> Ioana Chiorean <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> 於 2015年12月13日
> 星期日寫道：
> 
> > @irvin https://github.com/irvin do you have a link for the materials?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/mozilla/participation-org/issues/244#issuecomment-164286120
> > 
> > .
> 
> ## 
> 
> @ irvinfly: community liaison
> moztw.org Mozilla Taiwan community
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/participation-org/issues/244#issuecomment-164320015
> .

## 

Lora Chen

**Comment by irvin** [comment]
@shadowcrow Already did. There is no specific plan on Taipei office on local FSAs.

**Comment by LucyeoH-zz** [comment]
@irvin hey! What's the status of this? Is it still ongoing? If you think it'll be done by Jan 29th I can add you to that milestone or I can add you to the Q1 Contributor Milestone if you need more time (that one ends March 31st).
