### ISSUE TITLE
Evolution of the Reps program: Next steps and working groups

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#245]
## Goal:

Evolution of the Reps program: Next steps and working groups
## Success:
- Get the plan for the next steps for implementing the proposal
- start identifying and creating the working groups
## Related Issues & Links:
#206
## Roles:

Owner: @rosanardila
Involved:@nukeador @MichaelKohler @bacharakis @ioana-chiorean @rara79
## Required:
- [x] identify biggest areas of change and preliminary timeline (@rosanardila, Reps Council, [large], Due: Jan 13th) 
- [x] define first set of working groups and owners (@rosanardila, Reps Coucil, [medium], Due: Jan 15th)  
- [ ] Communications to Reps and mentors  (@rosanardila, Reps Coucil, [medium], Due: Jan 18th)
- [ ] First working groups formed(@rosanardila, Reps Coucil, [medium], Due: Jan 22nd)

**Comment by LucyeoH-zz** [comment]
Merge with other issue.

**Comment by nukeador** [comment]
Working groups defined at SIngapore, finishing more details.

**Comment by rosanardila** [comment]
Document with questions and working groups proposals from Singapore:
https://docs.google.com/document/d/1EVngjiH1KtZXo0k01VTjImbITprQkL4Q5DJTQyzV2OU/edit#

More notes from the second session will follow up.

**Comment by RizRiyz** [comment]
@rosanardila I add myself to `Working group: Mentoring`
