### ISSUE TITLE
Write-up Mid-term planning goals for German-speaking community

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/participation-org#246]
## Goal:

Have a blog post which documents the mid-term planning goals for the German-speaking community.
## Success:

Written blog post that can be shared with everybody and can be used for inspiration for other communities.
## Related Issues & Links:

Meta issue: #171
## Roles:

Owner: @MichaelKohler
Involved: Focus group of the German-speaking community
## Required:
- [x] Translate goals from German to English (Due: Dec 14th)
- [x] Write additional information about what those goals are (Due: Dec 15th)
- [x] Create shareable slides for "quick consumption" (Due: Jan 7th)

**Comment by MichaelKohler** [comment]
http://cdn.meme.am/instances2/500x/3325809.jpg

**Comment by MichaelKohler** [comment]
https://michaelkohler.info/2015/german-speaking-community-mid-term-planning
https://docs.google.com/presentation/d/1v4Lfo4ypGMj2N-oGXbnrpSEt8gOMAFF5bvmdZQx5Ahs/edit#slide=id.p3

Feel free to get back to me with any feedback you have :)

**Comment by ioana-chiorean** [comment]
:tada:
