### ISSUE TITLE
Meta: MVP survey results for map of Mozilla's participation software/infrastructure landscape

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#247]
## Goal:

MVP survey results for map of Mozilla's participation software/infrastructure landscape
## Success:

Survey of participation software created and administered, initial data presented

This data will be used by key stakeholders to frame the discussion around the scope and strategies of the Participation Software Lab (ParSol).
## Related Issues & Links:

https://github.com/mozilla/participation-org/issues/290

This project:
- https://github.com/mozilla/participation-org/issues/242
- https://github.com/mozilla/participation-org/issues/299
- https://github.com/mozilla/participation-org/issues/300
- Onboarding and planning document: [Mapping Mozilla's Participation Software Landscape](https://docs.google.com/document/d/1nf-n2R4DfU3h1JzpbrQ-Z6a9u6G8cQrD0ZVl7-Z10qE/edit#)
## Roles:

Owner: @CaptainCalliope
Involved: 
- James Lewis
## Key results:
- Set in motion: Stage one (of two) of a plan to comprehensively collect data about participation software around Mozilla.
- Using preliminary survey results, we will begin to answer key questions involving what software/infrastructure we have, who is responsible for it, and what documentation exists.
- Answers to key questions will help inform ParSol scope and strategies
- Org-wide engagement around identifying participation software
- Get people thinking about participation within the context of the software they use every day as well as collaboration opportunities with ParSol
## Heartbeat Issues:
- **H1 - 29 January** Create project framework https://github.com/mozilla/participation-org/issues/242
- **H2 - 19 February** Vet project scope, framework, data model with input from staff and community https://github.com/mozilla/participation-org/issues/299 create plan for survey creation+administration https://github.com/mozilla/participation-org/issues/300
- **H3 - 11 March** Create first (of two) stage survey and gather organizational support for administration
- **H4 - 1 April** Begin administering survey

**Comment by CaptainCalliope** [comment]
Plz assign me to this issue.

Would also like to see an issue created around debriefing the meeting(s) we had in #mozlando.

**Comment by CaptainCalliope** [comment]
First step: https://github.com/mozilla/participation-org/issues/242

**Comment by CaptainCalliope** [comment]
Issue https://github.com/mozilla/participation-org/issues/242 is complete. Primary output: [DRAFT: Mapping Mozilla's Participation Software Landscape](https://docs.google.com/document/d/1nf-n2R4DfU3h1JzpbrQ-Z6a9u6G8cQrD0ZVl7-Z10qE/edit#heading=h.7q332xg7t48n) google doc with project overview, collaborative onboarding, and next steps.

A first version of this map is unrealistic for this first sprint, but probably a great goal for the second sprint!

Next steps are to vet the plan, determine the appropriate level of scope for data collection, and begin work on a survey process. Hopefully, we'll be able to accomplish this within the current sprint.

Also, we should probably update this issue. :)

**Comment by CaptainCalliope** [comment]
I've written a call to action on discourse: https://discourse.mozilla-community.org/t/call-for-feedback-and-volunteers-to-help-map-the-participation-software-landscape/6444/1

**Comment by jgmac1106** [comment]
I can help with the survey creation once the framework is set.

**Comment by CaptainCalliope** [comment]
Extensively revamped this issue to turn it into the Q1 meta issue for this project, broke work down into heartbeats and created issues for the next heartbeat (H2).
