### ISSUE TITLE
Kiberpipa community/hacker space experience in MozSpaces discussion

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/participation-org#250]
## Goal:
- Document Kiberpipa/Cyberpipe experience in MozSpaces discussion
## Success:

MozSpaces discussion is informed with past hackerspace experiences.
## Roles:

Owner: @katjagucek
Involved: @brianking

**Comment by LucyeoH-zz** [comment]
Hey @brianking is this still an ongoing project? I have it for the January 29th milestone but can add it to the Q1 contributor milestone if it's going to take longer and is ongoing.
