### ISSUE TITLE
Create Mozilla Space in Shanghai and organize events in China

### ISSUE THREAD

**Issue by meteormatt** [mozilla/participation-org#252]
## Goal:

Create Mozilla Space in Shanghai and organize events in China.
## Success:

More users and volunteers in China.
## Roles:

Owner: Liu Xing
Involved: Mozilla China Community
## Required:
- [ Create Mozilla Space in Shanghai ](Liu Xing, Due: Dec 1th) 
- [ Organize events in China ](Liu Xing, Due: Dec 1th)

**Comment by holywen** [comment]
Please count me in, Lets' do this together.

**Comment by LucyeoH-zz** [comment]
Hey @meteormatt are you still working on this? I added you to the Q1 milestone if you're still working on this and would like to share about your progress at the end of the Quarter (March 31st)!

**Comment by meteormatt** [comment]
@LucyeoH I currently not working on this now because I am very busy these days. I will try to make the plan by the end of the Quarter (March 31st).

**Comment by LucyeoH-zz** [comment]
@meteormatt no problem. I've moved it to the March 31st milestone.
