### ISSUE TITLE
Foxfooding QA task force

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#253]
## Goal:

Form a group of 5 QA staff and volunteers tasked to support Foxfooding program
## Success:
- list of priority tasks generated weekly for foxfooders 
- streamlined bug triaging process that scales
## Related Issues & Links:
- https://wiki.mozilla.org/B2G/QA 
## Roles:

Owner: @wquiviger 
Involved: @ensowhat
## Required:
- [x] set up kick-off meeting with key stakeholders (staff & volunteers)
- [x] create repository of all documentation related to bug triaging for Firefox OS
- [ ] 
## Notes fro Mozlando:
- Need community of testers/users/educators
- Reference device used as basis for testing
- How?
  *\* Budget and proper org structure
  *\* Triaging
  *\* Data Collection
  *\* Dedicated team
  *\* Foxfooding app
  *\* To report data
  *\* To opt-in to be a foxfooder (consent letter)
  *\* Avoid need to separate builds
  *\* Hackathon 
  *\* Communication (via the Hub)

**Comment by ioana-chiorean** [comment]
Adding myself as one of them. I will fw this to Marcela Oniga too as she is already doing this.

**Comment by Pensacola** [comment]
I'm in too.

**Comment by 1Jamie** [comment]
I am interested in helping with this

**Comment by anistuhin** [comment]
Would really love to join the team :)

**Comment by gaby2300** [comment]
I am in too!!!

Best regards,
Gabriela
QA Mozilla Hispano Team Responsible

**Comment by tsl143** [comment]
I am interested in volunteering for this!

Best Regards,
Trishul Goel

**Comment by birajkarmakar** [comment]
I am interested also.  Please count me in,

**Comment by iamVP7** [comment]
Would like to join the team. Please count me in.

**Comment by williamq** [comment]
Document created. Will be foundation for next heartbeat. 
https://docs.google.com/document/d/1gClt0SJLPYKmm85kUKlVmZCEUfPv-zqBML_t4T-ZzjQ/edit
