### ISSUE TITLE
Create the video-l10n community to work on Mozilla's video subtitle

### ISSUE THREAD

**Issue by irvin** [mozilla/participation-org#255]
## Goal:

Create communication channel for those who is interesting on creating video subtitles for mozilla videos and create some how to documents.
## Success:

Get 5 people work on different language's subtitle
## Related Issues & Links:

[Reference meta issues and past issues] #
## Roles:

Owner: Irvin
## Required:
- [ ] Create communication channels
  - [x] Telegram channel - #mozilla-videol10n  
    https://telegram.me/joinchat/AutpyAGi7CL74m0Zs7pPTA
  - [x] IRC channel - #videol10n
  - [X] Send notice to all team member and add channel info when people joined
  - [ ] Link telegram to IRC channel with some bots
- [ ] Prepare documents - http://folder.moztw.org/videol10n/
  - [ ] Create some how-to documents
  - [x] Gather some good started videos -  
    https://public.etherpad-mozilla.org/p/mozilla-video-l10n-goodstart
- [ ] Find some people to join
- [ ] Talk to l10n team as suggest on #issuecomment-199331674

**Comment by Mte90** [comment]
Any example of that videos? I propose that task to the Italian community

**Comment by irvin** [comment]
For eg., the new "behind the hidden business" video
http://amara.org/en/videos/UKluIntYM9Vy/info/behind-the-hidden-business-of-the-internet/
And "welcome to Firefox"
http://amara.org/en/videos/nUymqW9ivqgw/info/welcome-to-firefox/

Daniele Scasciafratte notifications@github.com於 2015年12月12日 週六，上午5:56寫道：

**Comment by ioana-chiorean** [comment]
I am gonna cc @jobava & @cristisilaghi as they are part of L10n team and can help you organize this and also do localization for Romanian.

**Comment by dricupello** [comment]
I did the Portuguese version right now.

**Comment by Mte90** [comment]
The Italian community report that in amara everyone can translate so this can create problem for the review.
There are alternative for that?

**Comment by vesper-mozilla** [comment]
Please don't forget about https://wiki.mozilla.org/L10n:Teams

**Comment by irvin** [comment]
No, but I don't see this as a problem. In the past 2 years it works good
for zh-TW.

For most cases, marketing people won't get the subtitle and add to
"official Firefox channel", so when we done the review, we still need to
download the subtitle (and video as well) and upload to our community's
YouTube to promote.

**Comment by flodolo** [comment]
@irvin 
The issue I had in the past was exactly with zh-TW ([Australis video](https://bugzilla.mozilla.org/show_bug.cgi?id=995555#c41)).

As for the feedback from the Italian community (which actually was a general feedback): I don't have an issue with Amara, just make sure to double check who does the translation, and eventually ping someone from the existing l10n team in case they want to check.

Also, I'd advise against having automatic sync between Amara and YouTube, which means some with access to YouTube will need to upload the .srt file there. 
Again, that's just to make sure the translation is signed-off by someone else, and has an acceptable quality. If the l10n team is not responsive it's up to you what to do ;-)

**Comment by anistuhin** [comment]
completely agree with @flodolo had the very same experience while we were creating subtitle for Project Code Rush one in bn-BD. so, Amara is great. ccing @bellayet as he can localize in Bengali.

**Comment by tad124737337** [comment]
Is there potential for us to leverage this team to start captioning archived content on air.mozilla.org?
We really need English captions on air.mo at minimum. Would anybody here object to us adding videos from air.mozilla.org to the Amara team?

**Comment by irvin** [comment]
@TomFarrow I had try add video from AirMo. The method is get the real link of the video from here (when you click the vid.ly download link will direct you to it's CloudFront's CDN link) and add to Mozilla's team on Amara. 

This is the rust session video from Mozlando that I just added for eg., http://www.amara.org/en/videos/QLI5HRitX3ZD/info/rust-built-by-community-built-for-community/

<img width="718" alt="2015-12-19 16 43 40" src="https://cloud.githubusercontent.com/assets/165936/11912293/e775a9dc-a670-11e5-82e0-f2be7cca2bfd.png">
<img width="803" alt="2015-12-19 16 51 42" src="https://cloud.githubusercontent.com/assets/165936/11912295/ed949882-a670-11e5-9270-5e4b71dc38ae.png">
<img width="1007" alt="2015-12-19 16 53 31" src="https://cloud.githubusercontent.com/assets/165936/11912300/139c5f10-a671-11e5-8541-0113aec13518.png">

**Comment by irvin** [comment]
And how can we add the subtitle to AirMozilla, that's another problem i have no idea.

**Comment by irvin** [comment]
Hi All, I'd create a Telegram group and there is a IRC channel we create some months ago, please join, 

Telegram: #mozilla-videol10n  https://telegram.me/joinchat/AutpyAGi7CL74m0Zs7pPTA
IRC:  irc.mozilla.org #videol10n

**Comment by irvin** [comment]
Here is the project folder to gather some useful links, please add your local community's channel (by click on 'pencil' to add the link on top right side of document list)
http://folder.moztw.org/videol10n

**Comment by irvin** [comment]
Here are some good starter videos to begin
http://folder.moztw.org/videol10n/https%253A%252F%252Fpublic.etherpad-mozilla.org%252Fp%252Fmozilla-video-l10n-goodstart

**Comment by tad124737337** [comment]
I know how to add the videos, it's more of a question of whether this group is willing to caption our airmo videos 

Sent from Outlook Mobile

On Sat, Dec 19, 2015 at 12:54 AM -0800, "Irvin" notifications@github.com wrote:

@TomFarrow I had try add video from AirMo. The method is get the real link of the video from here (when you click the vid.ly download link will direct you to it's CloudFront's CDN link) and add to Mozilla's team on Amara

**Comment by irvin** [comment]
@TomFarrow it doesn't matter where the videos from. I think you can just start add some AirMo's valuable videos to amara team, and if people think it's worth they'll just start it.

**Comment by LucyeoH-zz** [comment]
@irvin what's the status of this project? Is the relevant information now in issue #280? Can I close this? Or would you like it assigned to the Q1 milestone?

**Comment by irvin** [comment]
@LucyeoH Yes, Tom and I will meet in Singapore meetup discuss about the amara accounts issue. Please assigned to Q1.

**Comment by irvin** [comment]
I'd send out notice to all current team members encourage them to join Telegram/IRC channel, also updated the default message for new members.

**Comment by alex-mayorga** [comment]
¡Hola!

This sounds interesting, will give it a go for es-MX..

Does @gueroJeff know of this?

¡Gracias!

**Comment by irvin** [comment]
@alex-mayorga No I don't think so, can you help us reach out to him?

**Comment by tad124737337** [comment]
Axel should also be involved here.

**Comment by gueroJeff** [comment]
Hey Irvin,

This looks like an interesting project. If it's something that you're
interested in maintaining long term, it would be interesting to have a
discussion with the l10n-drivers (Peiying and Pascal would be a good start)
to see how you could leverage the existing l10n infrastructure for this. I
believe they've done a number of video projects like this and should
already have something scalable in place.

Jeff

On Sat, Mar 19, 2016 at 11:19 AM, Irvin notifications@github.com wrote:

> @alex-mayorga https://github.com/alex-mayorga No I don't think so, can
> you help us reach out to him?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/participation-org/issues/255#issuecomment-198751129

## 

Thanks,
Jeff

**Comment by irvin** [comment]
@gueroJeff cool, we'll have a l10n-thon mid this year in Taipei and I'll also reach to them before that online.

**Comment by irvin** [comment]
![amara_statistic 2016-04-06 16:49](https://cloud.githubusercontent.com/assets/165936/14311041/f0fb22d2-fc17-11e5-8b8a-bd055826dbb2.png)
I just found that we had a statistic page for Amara team
