### ISSUE TITLE
Community Spaces 2016 - Early Steps

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#256]
## Goal:

Kick-start the community spaces group!
## Success:

Initial list of stakeholders, setup initial communication channels, and lay the foundation for a plan.
## Related Issues & Links:
- https://wiki.mozilla.org/Contribute/WPR/Community_Space_Initiative
- https://wiki.mozilla.org/People:MozSpaces_Guidelines
## Roles:

Owner: @brianking
Involved: @mariobehling
## Required:
- [ ] Log post-it notes from Mozlando session (pictures, doc) and send out summary to attendees (@mariobehling, [small], Due: Due: Dec 21st) 
- [ ] Setup 'Community Spaces' Discourse category(@brianking @nukeador , [small], Due: Dec 21st) 
- [x] Setup first call with George to determine scope (@mariobehling, [small], Due: Dec 21st) 
- [x] Setup first group call (@brianking, [small], Due: Dec 23rd)

**Comment by sammyfung** [comment]
Any plan to setup new Community Spaces in 2016 ?

**Comment by shadowcrow** [comment]
Any plan for existing community space in 2016?

**Comment by brianking** [comment]
No solid plans yet @sammyfung @shadowcrow, we'll keep you in the loop.

**Comment by geroter** [comment]
There's a strong dependency here with Engagement and Dev Rel who will be our business partners on this. As well as WPR.

I would pause on setting up a Discourse category for the moment.

**Comment by Saallen** [comment]
adding myself here to be keep in the comment loop :palm_tree:

**Comment by brianking** [comment]
I talked with both volunteers and staff in Taipei to put out feelers for merging spaces there. There was positive reactions all round. I am going to drive this with Jabob Shen in the TPE office and others moving forward.

**Comment by williamq** [comment]
Good meeting with Ali and Janet in Singapore. This is our working document for Community sapces and Developer Marketing in H1 2016. https://docs.google.com/document/d/1tpsclS8T7hU8wMBQ4vm586Ijc5EJLA8wSnIE3AhLj3E/edit

**Comment by williamq** [comment]
Great meetings with MozID crew in Jakarta. A great space has been identified. Currently writing summary document with next steps. Will be an issue on its own for next heartbeat.

**Comment by brianking** [comment]
Ok going to close this now and open specific issue(s) for the next heartbeat.
