### ISSUE TITLE
H2: External Expert Interviews

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#26]
<h1>Project Description</h1>

We will find and interview organizations from outside of Mozilla who are taking an inspiring approach to participation. We will specifically target organizations/groups who are not the typical big organizations who can be "seen" from silicon valley. Instead we will focus on  contacting small local groups from around the world, and interview them to discover radical new approaches to participation. 

<h1>Why</h1>
- To expand our knowledge about how to do participation successfully
- To find new models and approaches for participatory success
- To connect with and build a network of inspiring organizations around the world
- To discover radical new approaches to participation

<h1>Primary Goals & Objectives</h1>
- Have the majority of community members we contact reply with the description of an organization
- Interview 10-20 organizations about their approach and experiences with participation
- Create a interesting and comprehensive report about how they are doing participation (either in the form of a podcast, blog, or presentation) 

<h1>Team</h1>
- Owner @lucyeoh
- Members: @nukeador  @francjp  

<h1>Milestones (complete before dates)</h1>
- [x] Final review of emails for community leaders & communities (due May 22nd)
- [x] Final review of form for organization nomination (due May 22nd)
- [x] Send emails to the 8 community leaders identified (due Monday, May 25th)
- [x] Follow-up with community leaders (Wednesday, May 27th) 
- [ ] Review collection process (Friday, May 29th) 
- [ ] Select 10 organizations to interview
- [ ] Begin interviews

**Comment by LucyeoH-zz** [comment]
Demo Review: 29/05/2015
What was supposed to happen?
- Leaders were supposed to pass it on to their communities
- Community members were supposed to respond

What did happen?
- We sent out communication to all of the leaders
- We had one response from Moz FR
- At least  2 leaders did pass on the message

What are some improvements we should make?
- Have one on one meetings with the leaders we identified to explain the purpose and the process that we're looking for
- Tapping into our own networks and starting to approach groups to be interviewed 

What should we keep the same in this process?
- Use spreadsheet for tracking
- Initial interview template 

What does the next Heartbeat for this project look like?
- Do in person follow-ups with leaders
- Start reaching out to groups in our communities/networks to do interviews

**Comment by LucyeoH** [comment]
External Experts tracking doc: https://docs.google.com/spreadsheets/d/1Pl0hjAQAh2HWtPOmVG7XcNM3dD_tHvIdFXoXSVjJ6fE/edit#gid=0

**Comment by brianking** [comment]
@LucyeoH Can this one be closed?
