### ISSUE TITLE
Start exploring closer collaboration between Reps and FSA in 2016

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#264]
## Goal:

Start exploring closer closer collaboration between Reps and FSA in 2016
## Success:
- Identify key stakeholders for collaboration
- Draft a plan to understand main challenges and opportunities
## Related Issues & Links:

[Reference meta issues and past issues]

Owner: @rosanardila
Involved: Faye, @nukeador 
## Required:
- [ ] Identify first list of stakeholders (@rosanardila, Faye, [small], Due: Jan 7th) 
- [ ] Contact first list and ask for feedback (@rosanardila, Faye, [small], Due: Jan 15th) 
- [ ] Create a draft to understand main challenges and opportunities (@rosanardila, Faye, [medium], Due: Jan 22nd)

**Comment by anistuhin** [comment]
Wow, really a great issue to work on. Would love to help if anyway possible. I am a Rep and also leading and supporting the local FSA community here in Bangladesh for a while, so would really like to contribute on this one specially :)

**Comment by fayepal** [comment]
Awesome~ Excited to work on this!

**Comment by RizRiyz** [comment]
Leave a comment to start following this issue!

**Comment by AkshayTiwari** [comment]
Great!

**Comment by jgmac1106** [comment]
Wondering where this fits in. May not be this issue. Can Mozilla Clubs
become a pipeline for Reps and/or FSA?

**Comment by sunnat629** [comment]
great news. as a Reps and RAL, it seems an awesome step for the FSA program.. :)

**Comment by iamVP7** [comment]
Its exciting one, would like to contribute to this. I will love to see Reps who are contributing to various areas like MDN, L10N, QA and so on.. mentoring FSA, so it becomes easier for FSA's to get started.

**Comment by rosanardila** [comment]
Result of the exploration for collaboration between Reps, FSA and the current participation initiatives: https://docs.google.com/document/d/1EVngjiH1KtZXo0k01VTjImbITprQkL4Q5DJTQyzV2OU/edit#
