### ISSUE TITLE
Chaos Communication Congress 2015

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#265]
## Goal:

Grow community, promote Mozilla goals and products and reach at least 500 developers.
## Success:

An organized presence at CCC (for first time), where many attendees are aware of what we are doing around security, privacy, IoT, and other focus areas of the conference. 
## Related Issues & Links:
- Event page: https://reps.mozilla.org/e/chaos-communication-congress-2015/
- Mozilla Assembly: https://events.ccc.de/congress/2015/wiki/Assembly:Mozilla
## Roles:

Owner: @mariobehling
Involved: @ensowhat
## Required:
- [x] Goals for during/after event defined (@mariobehling @ensowhat, [medium], Due: Dec 18th)
- [x] Budget request filed and approved (@mariobehling, [medium], Due: Dec 21st) 
- [x] All logistic setup, travel etc. (@mariobehling, [medium], Due: Dec 23rd) 
- [x] Attend, inform, and learn! (@mariobehling @ensowhat, [large], Due: Dec 27th-30th)
- [x] Report written (@mariobehling @ensowhat, [large], Due: Jan 6th)

**Comment by vesper-mozilla** [comment]
Keeping myself in the loop, so that I can drop a batch of SUMO promotional materials for you before the event :-)

**Comment by mariobehling** [comment]
@vesper-mozilla Not sure, if the time is sufficient for that. If it could arrive on 27th or 28th Dec. in Hamburg would be nice.

**Comment by vesper-mozilla** [comment]
@mariobehling I will coordinate with Madalina in Berlin to print and send it ASAP. Thanks!

**Comment by mariobehling** [comment]
@vesper-mozilla Sounds good. I am in the office later in the afternoon, but I am not sure, if she is there. Please keep me in the loop. We will also send one of FxOS TVs from the Berlin office.

**Comment by ensowhat** [comment]
Hey! I'll bring ten Z3C. I don't have much swag available in Paris, but I'll see what I can get.

**Comment by vesper-mozilla** [comment]
@mariobehling we decided to go for something more lightweight (and easier for you to manage) - can you print some copies of the PDFs from https://wiki.mozilla.org/Support/SUMO_event_kit#in_English and either put them up as posters around the Mozilla area or distribute them among the people attending your panels?

I hope it's not too much work... If it is, let me know! Thanks in advance for being awesome :-)

**Comment by brianking** [comment]
Blog post:
https://blog.mozilla.org/community/2016/01/13/32c3-report-chaos-time-zone/

@ensowhat @mariobehling Feel free to followup with more information if you want, but closing this one off.
