### ISSUE TITLE
Finalize plan, get sign-off and get first sprint off the ground for Participation Software Lab

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#266]
## Goal:

Finalize plan, get sign-off and get first sprint off the ground for Participation Software Lab.
## Success:

We have sign-off from SCVP on an approach for Q1, with clear success stage-gates developed.
## Roles:

Owner: @geroter
Involved: @davidascher @simonwex @ppapadeas 
## Required:
- [ ] Deck for presentation to Chris/SCVP is finalized (@geroter @davidascher , [medium], Due: Jan 6) 
- [ ] Presentation at SCVP or an appropriate subset (@geroter @davidascher, [medium], Due: Jan 12)

**Comment by LucyeoH-zz** [comment]
Connect to roadmap piece issue created by @ppapadeas
