### ISSUE TITLE
Come up with new design for Foxfooding logo

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#267]
## Goal:

Update the current Foxfooding logo to echo the program's focus on testing and innovation
## Success:

A beautiful community-designed logo that garners approval from the large majority of Foxfooders
## Related Issues & Links:
- Current logo: https://d1jou7z3786ary.cloudfront.net/static/img/foxfooding.faf04e875a62.png
- Foxfooding "About" page: https://firefoxos.mozilla.community/foxfooding-about/
## Roles:

Owner: @williamq
Involved: @elioqoshi @yopdesign
## Required:
- [ ] Bring together volunteer designers to iterate on new logo (@williamq, [medium], Due: Dec 26th) 
- [ ] Submit 3 distinct proposals to Foxfooders for vote (@williamq, [medium], Due: Dec 26th) 
- [ ] Choose final logo and submit on Foxfooding "About" page and other channels (@williamq, [medium], Due: Dec 26th)

**Comment by LucyeoH-zz** [comment]
Notes: Opportunity to use the Community Design Group!

**Comment by elioqoshi** [comment]
Thanks @williamq 
These are the current proposals from the prior batch @ppapadeas requested. I will try to come up with more ideas. @yopdesign can you also brainstorm a bit?

![foxfooding-01](https://cloud.githubusercontent.com/assets/5436686/11975235/d8d6bff8-a96b-11e5-9db9-97e7d1a8a6f7.jpg)
![foxfooding-02](https://cloud.githubusercontent.com/assets/5436686/11975234/d8c463f8-a96b-11e5-9a1d-5216d3ec1331.jpg)
![foxfooding-03](https://cloud.githubusercontent.com/assets/5436686/11975233/d8c19132-a96b-11e5-9d8a-26f9565e9df2.jpg)
![v2-01](https://cloud.githubusercontent.com/assets/5436686/11975232/d8bc50d2-a96b-11e5-9e4b-4e79c5320db1.jpg)

**Comment by LucyeoH-zz** [comment]
@williamq updates on this?
