### ISSUE TITLE
FSA program and campus campaign have a clear plan for Q1 and are ready to gather participation at the Leadership Summit

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#268]
## Goal:

FSA program and campus campaign have a clear plan for Q1 and are ready to gather participation at the Leadership Summit.
## Success:

Clear plan with responsibilities, milestones, and resources developed for both the FSA program and also the Campus Campaign.

Engagement from key volunteer and staff stakeholders in campaign planning leading up to and during the Leadership Summit.
## Related Issues & Links:
#239
## Roles:

Owner: @rosanardila 
Involved: @geroter
## Required:
- [ ] Draft plan circulated to key staff and volunteers in advance of Leadership Summit, informed by stakeholder engagement (@geroter, [large], Due: Jan 15) 
- [ ] Leadership Summit planning sessions fully formed (@rosanardila, [large], Due: Jan 21)

**Comment by iamVP7** [comment]
Commenting to learn more about the plan made in Leadership Summit.
