### ISSUE TITLE
Community Dashboards for Q4 2015

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#269]
## Goal:

Crunch the data for the 10 focused communities for Q4 2015 and add them on the dashboard
## Success:

All 10 dashboards are populated and up to date
## Roles:

Owner: @couci
Involved: @deimidis, @rosanardila @nukeador @francjp 
## Required:
- [x] Close the surveys and notify the Reps(@couci, [small], Due: 30th Dec)
- [x] Crunch the data so the team can populate the dashboards (@couci, [large],  Due: 8th Jan)
- [x] Produce the event reports (@couci, @francjp  [medium], Due: 11th Jan)
- [x] Edit and adjust the dashboards we have( @couci, @rosanardila , [medium],  Due: 18th Feb)
- [ ] Team populates the dashboards (@rosanardila,@nukeador, @deimidis  [medium],  Due: 18th Feb)

**Comment by couci** [comment]
survey has been closed, answer 199

**Comment by couci** [comment]
Data have been crunched and added on the spreadsheet for the team to utilize

**Comment by couci** [comment]
All of the team was working on the Leadership summit so we didn't have time for this. Moving to the next heartbeat.

**Comment by ioana-chiorean** [comment]
Is this something we can share when we have the results in the reps call?

**Comment by couci** [comment]
the results are in, I need to populate the dashboards. Will let you know by Wednesday if we can share

**Comment by ioana-chiorean** [comment]
Thanks @couci !

**Comment by couci** [comment]
Event data and survey date are in. Suggestions for dashboards next version have been made.
Next step is populating the dashobards.
Also we will move to a more simple version and give the crunched data to all communities so they can populate themselves.

**Comment by LucyeoH-zz** [comment]
Will be closed by EOW.

**Comment by couci** [comment]
https://docs.google.com/spreadsheets/d/1ox-c0csgoBYC9T5XW3w90HT2QtVKxyne1Ao905u63kw/edit#gid=726996331 this is the new template (populated) that communities will be able to use
