### ISSUE TITLE
Indonesian financial Role

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#271]
## Goal:

Implement the financial role on the Indonesian community
## Success:

The Indonesian community submits a budget based on their mid-term planning and have created a playbook for the rest of the communities
## Related Issues & Links:
#173 #151
## Roles:

Owner: @couci
Involved: @alamanda @andi-belutz 
Informed: @rosanardila 
## Required:
- [x] Create a draft budget based on the mid-term planning (@alamanda,  @andi-belutz [large], Due: 6th January)
- [x] Review and formalise the budget (@couci,@alamanda @andi-belutz [medium],  Due: 8th Jan)
- [x] Creat a community story as a guideline for the rest of the communities (@couci,@alamanda @andi-belutz [medium],  Due: 16th Feb)
- [x] Create a template and guidelines on how to use the template efficiently  (@couci,@alamanda @andi-belutz [medium],  Due: 19th Feb)

**Comment by helitomato** [comment]
Hello! I heard about this from my mentor @emmairwin and I think this would be something the Vancouver community would be interested in trying out as well.  We are a small community with limited community members, but we participate in the same annual events on a regular basis.  Please let me know if there's a way to be involved.  thanks!

**Comment by couci** [comment]
Hey @helitomato !
that's great news! 
What we are trying to do with the Indonesian community is to work on a budget based on their midterm planning, so the first step in your community is to work around that and based on your planning to work on a budget estimation for your future initiatives. 
You can find other communities planning on issue #151. Also we have the draft of the financial role [here](https://docs.google.com/document/d/165mt-1ivHw9YWszWWEYaIUGeYGDg2lLvkLhGXLRS3Bc/edit#heading=h.lz8ihns173k5) and we would love to have your feedback on how that role can be implemented in your local community

**Comment by couci** [comment]
The awesome Indonesian community has created a draft (can not be shared here since it contains budget info). Once is finalised it will be published in bugzilla so it can be accessible to all Reps.
@alamanda as suggested per e-mail can we divide the budget per initiative instead per Rep leader so we can move forward with reviewing it?
Thanks

**Comment by couci** [comment]
Review process has started

**Comment by couci** [comment]
working with @alamanda on submitting the budget to the council and create templates and guidelines for future communities to follow. Moving this to the next heartbeat.

**Comment by couci** [comment]
this is the version 0.1 of the budget template based on the Indonesian's community work.
https://docs.google.com/spreadsheets/d/1lbI752EPAPoSQgsSUHedyFU0W8NJVwwDckQIbNG7Fp4/edit#gid=146099952
Next steps is to automate this more and add a doc with guidelines

**Comment by couci** [comment]
This has changed slightly. Instead of submitting to the council we are focusing more on the guidelines plus guidelines on using the tools we are creating. Changes to the issue have been made.

**Comment by couci** [comment]
First draft of the guidelines can be found [here](https://docs.google.com/document/d/1hpDVJTEGRAeJTeE3hJaH702QxOpk0vA6-kBrZQnYSm0/edit#) The doc is open for comments so feedback are always welcome.
I'm re-adding the [Financial Role to the Community (FRC)](https://docs.google.com/document/d/165mt-1ivHw9YWszWWEYaIUGeYGDg2lLvkLhGXLRS3Bc/edit#) definition for reference. I've added some open questions that need to be discussed so @alamanda @andi-belutz feel free to chime in. The work here can be also connected with the work we are doing the [working group Resources](https://discourse.mozilla-community.org/t/working-group-resources-track/7011/3)

**Comment by couci** [comment]
Here is the [draft](https://docs.google.com/document/d/1GhxruLeg8DjAge-fB4fR5Q3hDgTpEnGEA38tiUhY1jM/edit#) for the template guidelines
Also the template has been changed into v.0.5 . Most of the changes are automate cells so it can be easier for the user to populate them

**Comment by alamanda** [comment]
Everything looks good, @couci 
I think other than these, if anyone still have questions, then we can answer based on the question. Thank you so much for guiding us through the whole process!
