### ISSUE TITLE
RepsNext evolution

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#273]
## Goal:

Get Reps program evolution plan in place
## Success:

Reps evolution plan delivered and general agreement from the program
## Roles:

Owner: @rosanardila @nukeador Council
Involved: 
## Required:

TBD

**Comment by LucyeoH-zz** [comment]
Notes: Provide detailed description of what is meant be a "plan"

**Comment by nukeador** [comment]
Duplicated #245
