### ISSUE TITLE
Reps Activity Campaign

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#274]
## Goal:

Get Reps activated for the end of the year campaign
## Success:

40% of current Reps are aligned, active and ready for next year plan.
## Roles:

Owner: @rosana @nukeador Council @bacharakis @MichaelKohler 
Involved: @couci @akatsoulas @francjp 
## Required:
- [x] Reminder to all Reps about campaign ([medium], @nukeador @bacharakis mentors Jan. 27th)
- [X] Comms to inactive Reps ([small], @nukeador Dec. 21st)
- [x] Comms to inactive Reps with pending budget bugs ([small], @bacharakis @couci Dec. 27th)
- [x] Report with inactive Reps to transition to Alumni ([medium], @nukeador @akatsoulas Jan. 4th)
- [x] Report with Reps reports in December ([medium], @nukeador @akatsoulas @couci Jan. 5th)
- [x] Certificates for alumnis and active Reps ([medium], @nukeador @francjp  Jan. 7th)
- [x] Actions for alumni transition ([medium], @nukeador Jan. 8th)

**Comment by nukeador** [comment]
Ping @bacharakis and @couci for pending budget comms.

**Comment by nukeador** [comment]
Certificates for all new alumnis sent.

We'll send certificates for active Reps soon.

**Comment by couci** [comment]
@bacharakis has sent the e-mails to all new now new alumnis and a lot of them replied by sending funds back or submitting their receipts. Need to check on those we didn't reply.

**Comment by nukeador** [comment]
All done now.
