### ISSUE TITLE
Advance mid-term planning in focus communities

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#275]
## Goal:

Finish mid-term plan in 3 communities and advance plan for the rest
## Success:

3 communities start implementing their plans and 7 others finish their plan for 2016
## Related Issues & Links:
#205 #175 #246 #243 #151
## Roles:

Owner: @rosanardila @nukeador @deimidis
Involved: 
## Required:
- [ ] General checking of mid-term status. 3 communities should have it published in some form ([small], @rosanardila @nukeador @deimidis, Jan. 7th) 
- [ ] Meetings to start mid-term planning done for the rest of the 7 communities ([medium], @rosanardila @nukeador @deimidis, Jan.11th)
- [ ] Initial activities to support community goals started ([medium], @rosanardila @nukeador @deimidis, Jan.14th)
- [ ] Mid-term plans delivered for 7 communities ([large], @rosanardila @nukeador @deimidis, Jan.21th)
- [ ] 3 communities reports of activities ([medium], @rosanardila @nukeador @deimidis, Jan.21th)

**Comment by nukeador** [comment]
German Community goals https://michaelkohler.info/2015/german-speaking-community-mid-term-planning

**Comment by LucyeoH-zz** [comment]
Struggling to establish proper communications with all communities. Some groups are still behind. Have to figure out whether to continue this. 

Action: Need to decide whether to move into H2. (Minimize scope in H2)

**Comment by LucyeoH-zz** [comment]
Transform into volunteer task.

**Comment by anistuhin** [comment]
Today we had the MozCoffee meetup with all community members and have made a draft Mid-term planning for us. So, we are having one for Mozilla Bangladesh community. @nukeador suggested me to do that and so far everything went great. Hoping to have ours one ready to go public within next week. So, we got another one after German community now :)
