### ISSUE TITLE
GitHub Tooling for Contributors is Figured Out by Jan 22nd

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#278]
## Goal:

Current permissions make it difficult for contributors to get access to the repo to add milestones, assign people, and use labels on issues. Two solutions are: 
- Develop a process of contributors to get added to participation repo
- Create a separate Participation Volunteer repo 
## Success:

It is easy for contributors to create and modify issues. It is clear how to create and modify issues and what the heartbeat process is, how they can be a part of it. 

Note: New process will have all contributors with issues listed in a given milestone, invited to the kick-off meetings. 
## Roles:

Owner: @lucyeoh
Involved: @ppapadeas 
Consulted: @emmairwin ParticipaitonTeam
## Required:
- [x] Discuss technical considerations for a number of options with @ppapadeas  (@lucyeoh, [small], Due: Jan 8th) 
- [x] Draft proposal circulate to team and contributors for feedback (@lucyeoh, [small], Due: Jan 14th) 
- [x] Implement new process  (@lucyeoh, [small], Due: Jan 22nd)

**Comment by jaredhirsch** [comment]
Hi there! I'm one of the github owners; we chatted briefly about this issue in IRC.

It looks like Github's current permissions model has [read, write, admin, and owner](https://help.github.com/articles/repository-permission-levels-for-an-organization/) options for each repository in an organization.

Users need write access to be able to create labels or milestones in a given repository. Unfortunately, write access also allows a user to:
- edit or delete anyone else's comments on any issue in the repository
- edit issue titles and descriptions
- close and reopen issues
- lock issues, disabling further discussion in that issue.

It's not terribly granular: giving a user write permissions gives them lots of trust/power to make changes. This seems like it could be appropriate for a smaller number of really dedicated volunteers. 

(Write access also lets users land pull requests, create releases, and make other potentially destructive changes to the code in a repo, though I'm not clear on whether these participation repos would contain code, or would just be for issue tracking.)

Have you considered using the per-repository github wikis as part of the workflow? Collaborators with read permissions can be given wiki editing abilities, so they can sign up for work or help organize or comment on work in the wiki. Github wikis are versioned, so you can [review wiki edit history](https://help.github.com/articles/viewing-a-wiki-s-history-of-changes/) and easily undo wiki changes, which makes it easy to deal with abuse or accidental edits.

I'm happy to help in the future, but you can also reach all of the github owners via the github-owners mailing list, and can ask for help by filing a bugzilla bug. See the wiki for more: https://wiki.mozilla.org/Github

**Comment by LucyeoH-zz** [comment]
@6a68 thanks so much for this! We've figured out a system for adding contributors who sign-up through a list to the github.com/mozilla/community-design and I think we'll probably follow a similar procedure for inviting contributors who work regularly with participation to write in this repo.

**Comment by asdofindia** [comment]
Lucy, sorry for speaking so late. But does this procedure cover participation leaders too? If yes, using this repo itself might not be ideal for two reasons
- it might make life difficult for the participation team
- participation leaders might feel intimidated to create issues here

**Comment by jaredhirsch** [comment]
@LucyeoH sounds good! Feel free to ping me in the future if you need Github help

**Comment by LucyeoH-zz** [comment]
@asdofindia we are going to be creating a separate Repo for the participation leaders (possibly with a nice friendly front-end too!). Stay tuned!

**Comment by LucyeoH-zz** [comment]
Put my proposal on Discourse [here](https://discourse.mozilla-community.org/t/coordinating-participation-on-github/6638)! Please leave feedback!

**Comment by LucyeoH-zz** [comment]
@asdofindia I'm sure by now you have seen the Participation Leaders Repo github.com/mozilla/participation-leaders-accountability/
