### ISSUE TITLE
Start account with Amara

### ISSUE THREAD

**Issue by tad124737337** [mozilla/participation-org#280]
# Goal

Start an account with Amara for video captioning + l10n
# Succes

Amara Enterprise account exists, and a controlled workflow is enabled.
# Related Issues

https://github.com/mozilla/participation-org/issues/255
# Roles

Owner: @tomfarrow
Involved: @geroter, Brian Smith
# Required
- [x] Sign enterprise agreement
- [x] Add an initial credit to account
- [x] Work with Amara team on access/workflow

**Comment by MichaelKohler** [comment]
Can we use this? http://amara.org/en/teams/mozilla/

**Comment by dricupello** [comment]
I saw the videos there, made my account and did 3 l10n in Portuguese few weeks ago

Adriano Cupello

celular:  21 988480481
dricupello@gmail.com

**Comment by tad124737337** [comment]
Hi both,

yes, we do have an Amara team. The Enterprise account is the backbone of
such a team.

I'm in discussions with Amara and am aware of the team. This is simply some
backbone work so that we can more officially support the usage of Amara.

**Comment by LucyeoH-zz** [comment]
@TomFarrow I'm guessing this might not be done by the end of the heartbeat (Jan 29th) so I moved it to the "End of Quarter" milestone. If you'd like to have it reviewed in this heartbeat move it to the Jan 29th milestone!

**Comment by tad124737337** [comment]
WE CAN DO IT!

I can't modify the milestone, but can you move it to Jan 29th, @LucyeoH ?

Provided @geroter has chance to do a final review on the agreement by the 25th, we absolutely can hit this one. I'm meeting with Darren on the third actionable item, and @couci is waiting for me to send her the agreement to input CC details

**Comment by tad124737337** [comment]
and done.

**Comment by LucyeoH-zz** [comment]
Hey @TomFarrow ! You should have permission to modify the milestone now but I switched it for you!
