### ISSUE TITLE
Update Wiki and Readme.md to use new logo

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#281]
Issue #149 has the new logo. To update:

https://github.com/mozilla/participation-org/blob/master/README.md
https://wiki.mozilla.org/Participation

**Comment by deimidis** [comment]
I have to investigate how to do it on Wiki. Le t me do it soon

**Comment by deimidis** [comment]
I changed Wiki one, but it doesn't reflect yet in the header, maybe cache issues

**Comment by brianking** [comment]
Great, thanks @deimidis I see it with Shift+Reload.

**Comment by comzeradd** [comment]
README also updated.

We should also udpate the [twitter account](https://twitter.com/MozParticipate).

**Comment by brianking** [comment]
@LucyeoH controls Twitter I believe.

**Comment by LucyeoH-zz** [comment]
I don't have have the password to the account I can just access it through Tweetdeck but it won't let me change the logo @nukeador I believe can update the logo

**Comment by brianking** [comment]
@nukeador updated Twitter. Closing.
