### ISSUE TITLE
A Redesigned Connected Devices participation program is resulting in active contributors

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#286]
## Goal:

A redesigned Connected Devices participation program is resulting in active contributors
## Key Results:
- [ ] **KR1**   500 foxfooding MAUs [Accountable - @williamq] [Involved - @brianking, @ensowhat ]
- [ ] **KR2**   Core contributor participation designed into 100% of new product trains [Accountable - @williamq] [Involved - @brianking, @ensowhat, @emmairwin]
- [ ] **KR3**   Established new participation health metric for Connected Devices [Accountable - @brianking] [Involved - Dominik, @ensowhat]
## Related Issues & Links:

[Reference meta issues and past issues] #

**Comment by brianking** [comment]
A lot has changed on the CD front and the scope has broadened. Some things have become more important and other things are being driven by other teams.

KR1 no longer relevant - foxfooding to be redefined at some point
KR2 In Progress
KR3 Dominik from CD Strategy Team responsible
