### ISSUE TITLE
Community spaces are up and running with active developer engagement activities

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#288]
## Goal:

Community spaces are up and running with active developer engagement activities
## Key Results:
- [x] **KR1**   2+ interactions (events and other) with 400 different developers through our community spaces [Accountable - @williamq ] [Involved - @brianking  , @rosanardila, @ensowhat ]
- [ ] **KR2**   Established a baseline measure of developer awareness/sentiment in all 5 markets [Accountable - @brianking ] [Involved - @geroter, Ali Spivak, Brad Cohen ]
- [x] **KR3**   Community spaces in Jakarta and Berlin are up and running [Accountable - @williamq  ] [Involved - @geroter  , @rosanardila ]
## Related Issues & Links:

[Reference meta issues and past issues] #

**Comment by brianking** [comment]
KR1 : Not completed. We are reaching the end of the planning phase, events will be starting early Q2.
KR2 : Not completed. Move to Q2.
KR3 : Jakarta space is acquired and being renovated. Will open in April. Planning has begun for Berlin, but no physical space has been acquired yet.

**Comment by williamq** [comment]
KR1 is complete across Taipei and Manila spaces. Still need to lock down final numbers. 

KR3 is semi-complete - Jakarta space is ready for lift off but Berlin space is still pending
