### ISSUE TITLE
DRAFT: Indonesia campus campaign

### ISSUE THREAD

**Issue by RizRiyz** [mozilla/participation-org#296]
## Goal:

[One line goal description] 
- Community Growth: Get 10 active supporters in each campusses group
- Product/Adoption: 100 install of firefox in each campusses
- Technology: 2 or more addons 
## Success:

  [What would success look like] 
- 2 or more addons published in addons.firefox.org by student from the campus
- Recruit 3 more active FSA from Indonesia
## Related Issues & Links:

[Reference meta issues and past issues] #
(coming)
## Roles:

Owner: @ariestiyansyah 
Involved: @kelimuttu @alamanda @dikyarga 
## Required:
- [ ] List down the FSA from each campuses that we targeted (dead line: 7 February 2016) 
- [ ] Approach potential established community in campuses to support our campaign (dead line: 7 February 2016)
- [ ]()

**Comment by LucyeoH-zz** [comment]
Hey @ariestiyansyah ! Looks like this is in the wrong repo :( you can move this to http://github.com/mozilla/participation-leaders-accountability/

**Comment by RizRiyz** [comment]
Thanks @LucyeoH .
Move to this issue https://github.com/mozilla/participation-leaders-accountability/issues/6
