### ISSUE TITLE
Is Webmaker's Heartbeat tool, the tool that we need?

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#3]
We need to find easy ways to organize our work and documentation, but it has to be, also transparent and open for our team and other contributors
### Audience

Our team, contributors that want to help at Participation team and mozillians that want to know what we are doing
### Success

Our team: we know what is the status of every project in the current Heartbeat and what other projects are waiting to be accomplish

Contributors: Know the status and the projects we are working, and find ways to participate
### Vision

A website where you could find the big picture and understand what is happening, but if you want to go deeper, you have the tools to do it
### Measurement

Heartbeats runs smoothly and the team is collaborating happily.

Contibutors participate in projects
### Roles
- Phase: 
- Driver: 
- Decision Maker: 
- Design Lead: 
- Development Lead: 
- Quality Verifier:

**Comment by deimidis** [comment]
We were working with Emma in some user cases:

# User cases

## Heartbeat participants:
- As a member of Heartbeat I want to know who I am working with, and what our responsibilities are.
- As a member of Heartbeat I want reminders of impending due-dates & milestones
- As a member of Heartbeat I want to know when task goals, or dates are updated
- As a member of the Heartbeat I want to update the status of my work
- As a member of Heartbeat I want to be aware of dependencies on my tasks
- As a member of Heartbeat I want to know when tasks I am dependent-on, are completed
- As a member of the Heartbeat I want to have an understanding of the big picture, and identify ways in which I can help
- As a member of the Heartbeat I want  a way to recognize trends (obstacles and outcomes for example)
- As a member of the Heartbeat I want to have a reminder of each Heartbeat's goals
- As a member of Heartbeat I want to give feedback to others, and make suggestions independent of my own tasks.

## Participation team
- As a member of the participation team, I want to know when new heartbeats are added
- As a member of the participation team I want to know how other projects/heartbeat are developing(updated, edited, stalled)
- As a member of the participation team I want to have a place to look at our current projects and how they relate into each others +1 to this
- As a member of the participation team I want to have a place where lead contributors to help +1 also huge
- As a member of the participation team, I want a clearly articulated description of how anyone can get involved. (this may be the same as the one above)
- As a member of the participation team, I want to select which notifications I receive +1
- As a member of the participation team, I want a way to 'suggest' Heartbeats
- As a member of the participation team, I want a way to give feedback on how the Heartbeat process or technology is working for me.
- As a member of the participation team, I want an a mobile-view

## Contributors
- As a contributor I want a place where find the status of the Participation team
- As a contributor I want a place where I could find ways to participate
- As a contributor I want a way to make suggestion in a way that doesn't require filling in a huge form, and logging in.
- As a contributor I want to know in a TL;DR kind of-way, what exactly I see, and do on Heartbeats
- As a contributor I want to 'share' cool things I see with others.

## General Public
- As a person interested in community development I want a place where I could learn how Mozilla works with their volunteer community
- As a person interested in Mozilla I can easily find heartbeats that relate to my interest/background

**Comment by djst** [comment]
# Milestones
- Write report with findings. @ppapadeas, 2015-04-29
- Implement first version of something and submit to Marketplace. @ppapadeas, 2015-04-30
- Do some stuff in the future. @deimidis, 2015-05-xx

(This comment is just a test to see how a manual milestones tracking might look like using GitHub. It's clearly not ideal.)
