### ISSUE TITLE
ParSol Map: Create plan for survey design and administration

### ISSUE THREAD

**Issue by CaptainCalliope** [mozilla/participation-org#300]
## Goal:

Create a plan for designing stage one (of two) of the org-wide participation software survey as well as strategies for effective administration.
## Success:

Specific requirements for survey design are determined.
Specific strategies and resources needed for org-wide survey administration are determined.
Help has been recruited to design the survey both textually and technically
## Related Issues & Links:

Meta issue: #247 
Depends upon: #299 
Past: #242 
Framework and Project planning: [Mapping Mozilla's Participation Software Landscape](https://docs.google.com/document/d/1nf-n2R4DfU3h1JzpbrQ-Z6a9u6G8cQrD0ZVl7-Z10qE/edit#heading=h.xrnrsckk2t9o)
## Roles:

Owner: @CaptainCalliope
Involved: 
- James Lewis
- @jgmac1106 [offered to help with survey creation](https://github.com/mozilla/participation-org/issues/247#issuecomment-170063849)
## Required:
- [ ] Figure out what the specific requirements and steps for this issue are. (Lyre Calliope, [small, medium, large], Due: 5 February)

**Comment by CaptainCalliope** [comment]
Spoke with @adamlofting this past week to brief him on this project. He had a fantastic suggestion for stage 2 of survey administration which may be applicable for stage 1. The main idea is to use a network-centric [snowball sampling](https://en.wikipedia.org/wiki/Snowball_sampling) approach.

I spoke with @geroter who is going to connect me with staff who might be able to help with survey design.

**Comment by jgmac1106** [comment]
@adamlofting is a sharp cookie. I can still look at your survey design and
offer feedback/help.

**Comment by CaptainCalliope** [comment]
@jgmac1106 Thx! I definitely plan on reaching out soon! Just have to get a few ducks in a row first.

**Comment by CaptainCalliope** [comment]
As issue https://github.com/mozilla/participation-org/issues/299 is a dependency for this issue, rolling it into the next heartbeat.
