### ISSUE TITLE
RepsNext working groups formed and timelines defined

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#303]
## Goal:

Working groups for the RepsNext proposal are set-up and actions and timelines are defined.
## Success:

All working groups are defined, have an owners, members and their next steps are defined with a clear timeline.
## Related Issues & Links:
- Previous issue: #245
- [Summary doc about working groups](https://docs.google.com/document/d/1EVngjiH1KtZXo0k01VTjImbITprQkL4Q5DJTQyzV2OU/edit#heading=h.p8w6mgsuag1l)
## Roles:
- Owner: @nukeador @rosanardila @shahidfarooqui @rara79 @umeshagarwal @bacharakis @MichaelKohler @thephoenixbird @Faisalaziz
- Involved: Mentors and Reps
## Required:
- [x] Owners are assigned for each group (@nukeador @rosanardila Council, [small], Due: Feb 3rd) 
- [x] Groups description are polished and published (@nukeador @rosanardila Council, [medium], Due: Feb 7th) 
- [x] Call for Reps to chime in groups (@nukeador @rosanardila Council, [medium], Due: Feb 8th)
- [x] Initial kick-off meetings (@nukeador @rosanardila Council, [medium], Due: Feb 11th)
- [x] Actions and timelines for each group are defined and documented (@nukeador @rosanardila Council, [large], Due: Feb 19th)
- [x] Each item is created as an issue and has an owner (@nukeador @rosanardila Council, [medium], Due: Feb 19th)

**Comment by anistuhin** [comment]
Any per-requisite to join a working group?? or just an open interest will do for now??

**Comment by nukeador** [comment]
No per-requisite, we'll do a call out and anyone who wants to commit to help will be welcomed and coordinated by the group owner.

**Comment by MichaelKohler** [comment]
I will be the owner of "Working group: Alignment with Participation Team and Mozilla"

**Comment by Amena-Islam** [comment]
I would like to join. But I am not Reps, a Senior FSA. Can I join?

**Comment by tsl143** [comment]
commenting for getting updates more about working groups :)

**Comment by nukeador** [comment]
Hey Council,

Let's find sometime before Monday EOD to polish our working groups (basically writing the goals for them and prepare a call for reps to help):
- Alignment with Participation Team and Mozilla - @MichaelKohler 
- Leadership Track - @rara79
- Mentoring - @shahidfarooqui
- META - @bacharakis 
- #344 Resources Track - @nukeador @Faisalaziz
- Application Process & Selection Criteria & Responsibilities - @shahidfarooqui @MichaelKohler 

@umeshagarwal @thephoenixbird please comment on which one do you want to help coordinating.

Thanks!

**Comment by MichaelKohler** [comment]
I think it would be great if @umeshagarwal or @thephoenixbird could lead the Application WG, so that we only have one main WG assigned per person. This wouldn't mean that others couldn't help out though. What do you two think?

**Comment by anistuhin** [comment]
We are in the group owner selection phase, right?? Or this is the call out, @nukeador was talking about??

**Comment by MichaelKohler** [comment]
We are assigning owners from the Council to every working group. The call out will happen shortly!

**Comment by MichaelKohler** [comment]
WIP drafting of working group goals: https://docs.google.com/document/d/1Vxy3l7t3sbULItBfGnKG0eaBXLqp77kW8PZzZoO9rQY/edit

Update: just noticed that this is Council-only, we will share this soon though.

**Comment by ThePhoenixBird** [comment]
I will follow @MichaelKohler suggestion and take the Application WG and help with the Alignment WG as well :)

**Comment by shahidfarooqui** [comment]
As Nuke mentioned in the comment above, I will be the owner of "Working group: Mentoring"

**Comment by jgmac1106** [comment]
Totally willing to help out Rara with the leadership track.

**Comment by nukeador** [comment]
Meetings are happening this week for most Working Groups.

**Comment by rara79** [comment]
@jgmac1106 feel free to jump into our first Community Leadership Track call today - Tue Feb 16th, 2016 - 16:00 UTC at MozillaReps Vidyo Room https://v.mozilla.com/flex.html?roomdirect.html&key=RWa4tTy27FSM 

See ya :)

**Comment by nukeador** [comment]
Issue for Resources track WG : #344

**Comment by Amena-Islam** [comment]
Sorry, unfortunately I missed yesterday community call. How can I get the
update? Is there  any etherpad or git issue link?

**Comment by MichaelKohler** [comment]
Everything is documented in the different working group topics on Discourse: https://discourse.mozilla-community.org/c/reps

**Comment by nukeador** [comment]
Today some meetings are happening, so we should have meetings, timelines and github issues done by today ;-)

**Comment by LucyeoH-zz** [comment]
Will be closed this weekend!

**Comment by ThePhoenixBird** [comment]
Issue for Application Process track WG #358
