### ISSUE TITLE
Brazil community meetup (community institute)

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#304]
## Goal:

Organize and plan community projects for 2016 aligned with Mozilla goals
## Success:
- Community is organized by teams
- Each team has a clear plan to work on 2016
- Community members develop and improve leadership and organizing skills
- 70% of projects are aligned with Campus Campaign or Connected devices
## Related Issues & Links:
#286  #287
## Roles:

Owner: @deimidis  
Involved: @rosanardila @francjp @emmairwin @williamq @brianking @270strategies
## Required:
- [x] Define city and dates (@deimidis, [small], Due: Feb 9th) 
- [x] Create invitee list (@deimidis @rosanardila , [medium], Due: Feb 16th) 
- [x] Define basic agenda (@deimidis, [large], Due: Feb 16th) with collaboration: @rosanardila @nukeador @emmairwin @williamq @brianking 
- [ ] Find venue and accomodations (@francjp, [medium], Due: Feb 19th)
- [x] Create form so community members suggest invitees (@deimidis, [small], Due: Feb 19th)
- [ ] Call for sessions (@deimidis, [medium], Due: Feb 19th)

**Comment by deimidis** [comment]
This is a draft, items could be added or deleted and will expand to others heartbeat

**Comment by ioana-chiorean** [comment]
Hey @deimidis do you think you can join one of the future Reps Call and share more on this? cc @couci

**Comment by deimidis** [comment]
@ioana-chiorean sorry, I just read this. No yet, I think we need to advance a little more. Maybe next week (Feb 25th)

**Comment by deimidis** [comment]
Delaying meeting to May. I defined the first list of 21 invitees and shared a form with them so they could suggest new ones. First draft of «Document» fro approval ready, waiting for Feedback from @rosanardila and @nukeador

**Comment by ioana-chiorean** [comment]
It is ok @deimidis - I will mail you up for logistics around he call! Thanks! :tada: :bow:
