### ISSUE TITLE
Coaching after Leadership Summit

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#305]
## Goal:

Continue conversation after Leadership Summit and help cohort participants to accomplish their goals
## Success:

90% of Leadership Summit participants have their plan on Github and have conversations with their partner
## Related Issues & Links:
#289
## Roles:

Owner: @deimidis @emmairwin 
Involved: @nukeador @rosanardila 
## Required:
- [ ] Set 1:1 conversations with LS participants (@deimidis, [small], Due: Feb 10th) 
- [ ] LS participants add their plans in github  (@emmairwin @deimidis, [large], Due: Feb 13th) 
- [ ] Each LS participant schedule a call with their cohort partner (@deimidis, [large], Due: Feb 13th)

**Comment by deimidis** [comment]
Still draft, needs to be reviewed by @emmairwin and @rosanardila

**Comment by LucyeoH-zz** [comment]
Changed focus (from regional to those with open issues).
