### ISSUE TITLE
Mexico mid term plannig ready to deploy

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#306]
## Goal:

Finish mid-term planing for 2016 in Mexico, with focus on Campus Campaign and Connected Devices
## Success:
- At least 80% of community members know and agree with plan
- Community members have a clear picture on next steps and goals for the year
## Related Issues & Links:
#205
## Roles:

Owner: @deimidis 
Involved: @lars21 @odin @alex-mayorga @Jusai @Yuli
## Required:
- [ ] Evaluate the work already made (@deimidis, [small], Due: Feb 5th) 
- [ ] Share Leadership Summit content and plans (@mexico_community, [medium], Due: Feb 10th) 
- [ ] Agree on CC and CD goals in Mexico (@mexico_community, [medium], Due: Feb 12th)
- [ ] First plan draft (@mexico_community, [medium], Due: Feb 15th)
- [ ] Plan ready to deploy (@mexico_community, [large], Due: Feb 19th)

**Comment by alex-mayorga** [comment]
Due to a GitHub limitation I'm @alex-mayorga over here =)

**Comment by deimidis** [comment]
Done!

**Comment by LucyeoH-zz** [comment]
End today with OKR's for the community.

**Comment by ioana-chiorean** [comment]
When you guys are ready, will you be able to share it in the reps call? cc @couci 
The next calls will be on Feb 25th, March 3rd, March 10th.
What do you think @lasr21 @odin @alex-mayorga @Jusai @Yuli?
