### ISSUE TITLE
Distribute and Create Procedures around Monthly Mozillians Newsletter

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#310]
## Goal:

The monthly newsletter is further established as a new way to communicate regularly with contributors. 
## Success:
- Wiki page created with way of submitting
- 30% open rate
## Roles:

Owner: @lucyeoh 
Involved: 
## Required:
- [x] Talk with Mofo about possible overlap
- [x] Email out to Participation Team, Internal, Marketing & PR calling for news/submissions 
- [x] Draft & send mid-November

**Comment by ioana-chiorean** [comment]
Miss @LucyeoH " Draft & send mid-November" ?
