### ISSUE TITLE
v1 of Foxfooding 2.0 plan co-created with Connected Devices team

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#311]
## Goal:

Come up with a draft plan for the next evolution of the Foxfooding program and prepare it for a full transition to the Connected Devices team. 
## Success:

Draft plan finalised and ready for feedback/approval
## Roles:

Owner: @williamq
Involved: @brianking, @ensowhat 
## Required:
- [x] Set up meeting with Vyk and Brian, (@williamq, [small] Due: Feb 8th) 
- [x] Write first draft of plan (@williamq, [medium], Due: Feb 29th) 
- [x] Get final approval for plan of next phase of Foxfooding before communication push (@williamq @vik, [medium], Due: Feb 29th)

**Comment by ioana-chiorean** [comment]
@williamq let me know if I can help here :)

**Comment by williamq** [comment]
Closing this issue and will create new one given that Foxfooding is entirely owned by Connected Devices team at this point.

**Comment by williamq** [comment]
Announcement on March 3, 2016: https://discourse.mozilla-community.org/t/foxfooding-update-devices/7378

**Comment by williamq** [comment]
Foxfooding DRAFT deck created Feb 19 https://docs.google.com/presentation/d/1B8B4KU8_PcBhRinYiD6reJHMGun03M5KNVGT4Ml18wg/edit#slide=id.gf05207de4_2_76
