### ISSUE TITLE
Jakarta Space - launch plan locked and approved

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#312]
## Goal:

Lock down plan for Jakarta space
## Success:

The plan is approved and we're ready to go. 
## Related Issues & Links:

https://docs.google.com/document/d/1syCuckcj-CDDmbhAjbfTTB3ITDFhcXIUreNswBi91uw/edit
## Roles:

Owner: @williamq
Involved: @brianking @geroter 
## Required:
- [x] schedule weekly planning meeting with Jakarta community (@williamq, [small], Due: Feb 5th) 
- [x] Prepare all documents for review (budget, photos, floor plan, lease) (@williamq, [small], Due: Feb 12th) 
- [x] Get sign-off to move forward (@williamq, [small], Due: Feb 19th)

**Comment by yofiesetiawan** [comment]
Thank you @williamq
