### ISSUE TITLE
Finalize plan for community spaces as magnets for developer engagement

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#313]
## Goal:

Finalize plan for Community Spaces as magnets for developer engagement and get buy-in from Engagement team. 
## Success:

Plan is ready to be rolled-out
## Related Issues & Links:

https://docs.google.com/document/d/1syCuckcj-CDDmbhAjbfTTB3ITDFhcXIUreNswBi91uw/edit 
## Roles:

Owner: @williamq
Involved: @jmswisher @aspivak
## Required:
- [x] Set up bi-weekly meeting with all stakeholders (@williamq, [small], Due: Feb 7th) 
- [x] Draft first version of plan (@williamq, [small], Due: Feb 7th) 
- [x] Create wiki with content ideas for Developer Marketing events in spaces (@jmswisher, [large], Due: Feb 19th) 
- [x] set up bi-weekly planning meeting with space stewards to flesh out content (@willimq, [medium], Due: Feb 26th) 
- [ ] Run trial events in Taipei and Manila (@williamq, [large], Due: March 11th)

**Comment by williamq** [comment]
Trian events scheduled next week. Will move this to next heartbeat.

**Comment by ioana-chiorean** [comment]
hey @williamq - would you like to share about this in one of the future reps call? cc @couci
