### ISSUE TITLE
Organize QA sprints and bring QA volunteer task force together

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#316]
## Goal:

Getting QA task force up & ready, and launch recurring synchronized Eu events (for a start).
## Success:

Organize one QA event in each Eu MozSpace (London, Paris and Berlin) to find at least 3 new contributors.
## Related Issues & Links:
- https://docs.google.com/a/mozilla.com/document/d/1gClt0SJLPYKmm85kUKlVmZCEUfPv-zqBML_t4T-ZzjQ/edit?usp=sharing
## Roles:

Owner: @ensowhat
Involved: @ioana-chiorean Marcia Knous @AlexLakatos @mikehenrty @arcturus @physte3 @JohanLorenzo 
## Required:
- [x] Decide on a date and find sponsors in every MozSpaces (@ensowhat, [small], Due: Feb 9th) 
- [ ] Organize and promote the event(s) (@ensowhat, [large], Due: Feb 19th)

**Comment by ensowhat** [comment]
Because of the grey area around the foxfooding program - which was the bootstrap for these events -  the organization was delayed. We're currently waiting for the confirmation of all the people involved to do this event on the 1st of March.

**Comment by gaby2300** [comment]
William, please count me in!!!

**Comment by williamq** [comment]
We need to revisit this for the next heartbeat.
