### ISSUE TITLE
Open Up Discussions on Metrics for CD Participation 

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#317]
## Goal:

All Mozillians are aware of discussion around what success metrics we are formulating, and are able to participate.
## Success:

We have a reference point for people to read related documents, and communication channels setup to discuss.
## Related Issues & Links:
# 
## Roles:

Owner: @brianking
Involved: @williamq @ensowhat 
Note that this is being led by Dominik and the Metrics team, with the Participation team playing a supporting role.
## Required:
- [x] Intro Call (Dominik, [small], Due: Feb 3rd) 
- [x] Create a place (e.g. wiki page or G Doc folder) to gather all relevant materials (@brianking, [medium], Due: Feb 10th) 
- [x] Have first engagement with volunteers on the topic (@brianking, [medium], Due: Feb 19th)

**Comment by brianking** [comment]
Will sync up with Dominik to get the latest on this. Moving out to next heartbeat.

**Comment by couci** [comment]
this is owned by Dominik, @brianking could you assign this to him?

**Comment by brianking** [comment]
Update last week from Dominik, who is now moving on from this so will have to find a new owner:

---

There is a first dashboard here:
https://metrics.mozilla.com/protected/shiny/dstrohmeier/contributors/

It's not much to see, but a lot of work has happened on the backend. We discussed with George that he wanted to have a first MVP which only shows numbers per month. I will work today still on fixing de-duplication the best that I can.

Documentation is here: https://docs.google.com/a/mozilla.com/document/d/15x0IM4NKs84yLNxU7rrMXuXsG_Z35W9j-g3vrXfjlFk/edit?usp=sharing

Meanwhile, the work on the infrastructure is also progressing. I will get an update today from Heather.

The goal is to be able to start work on more "interesting" success metrics in Q2.

---

**Comment by ensowhat** [comment]
Mentioning Dominik @onkeltom, in case he wants to add infos
