### ISSUE TITLE
Peer coaching framework for community

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#318]
## Goal:

Community members have a system to coaching peers
## Success:

Framework is ready to test on H3 with a small number of Cohort participants
## Related Issues & Links:
#222
## Roles:

Owner: @deimidis 
Involved: @emmairwin @rosanardila @nukeador Jane Finette
## Required:
- [ ] Post on discourse about the project (@deimidis, [small], Due: Feb 5th) 
- [ ] Curriculum content first draft (@deimidis @emmairwin, [medium], Due: Feb 10th) 
- [ ] «Framework proposal» (@deimidis, [medium], Due: Feb 12th)
- [ ] Feedback from stakeholders (@deimidis, [medium], Due: Feb 18th)
- [ ] Final framework to be tested on H3 (@deimidis, [medium], Due: Feb 19th)

**Comment by deimidis** [comment]
Late on this. Draft of the Discourse post is ready, with the plan on how to continue disucssion. Will move and modified it accordingly for next Heartbeat

**Comment by LucyeoH-zz** [comment]
This was de-prioritized.
