### ISSUE TITLE
Document a "Bootstrapping your project" event kit for Connected Devices

### ISSUE THREAD

**Issue by ensowhat** [mozilla/participation-org#319]
## Goal:

Let's offer documentation -as a kit- for people interested in organizing IoT workshop with CD.  
## Success:

Having the kit tested at least once.
## Related Issues & Links:
- https://wiki.mozilla.org/Connected_Devices/Participation/Build_Your_Own_Connected_Devices_Project

Workshops proposals:
- https://docs.google.com/document/d/1DvAgH0aTKelUwEosx-FwRHKmruHxDUrQAGnyMcZliVs/edit#heading=h.qc1d3ikfksim
## Roles:

Owner: @ensowhat
Involved: @williamq @brianking @autonome @deimidis @couci 
## Required:
- [x] Outline a document (@ensowhat, [small], Due: Feb 26th) 
- [ ] Talk to the different people involved to get feedback, and our document done (@ensowhat, [medium], Due: Feb 23rd) 
- [ ] Find someone to run an event (@ensowhat, [large], Due: March 7th)

**Comment by ensowhat** [comment]
The events involving RP2 port, FxOS phone hacking or porting seem to be the most reachable now.
Dietrich announced that an experimental b2g build for RP2 was ready and soon to be available to download. His basic exercises for hacking on old b2g phone will be available soon.
Mike Henretty is willing to organize a Raspberry Jam in Berlin.

**Comment by ensowhat** [comment]
London is building a planning for b2g hackathons for Q1 + Q2, I'm working with them on that.
SF is having an IoT Meetup on the 25th, waiting for the outcomes of this one.

**Comment by dvigneshwer** [comment]
Had made an event kit template for IOT based events for a community. 
( https://drive.google.com/file/d/0B7HeikLSZqGiaTRRV1k0eDhoVUU/view?usp=sharing )

Skills required for building products and protos for solving real time problems and providing end to end solutions are not developed in single day it is a continous process. This template is made keeping that fact in mind.

**Comment by williamq** [comment]
I will close this issue and create a follow-up issue called "Hackathon Toolkits for Connected Devices" as described here: https://wiki.mozilla.org/Connected_Devices/Participation#Hackathon_toolkits

**Comment by ioana-chiorean** [comment]
Hey @ensowhat @williamq - would you present this in a future reps call?  cc @couci
