### ISSUE TITLE
H3: Run training with Global Communications Group build engagement

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#32]
<h1>Project Description</h1>

Owner: @lucyeoh
Members: @francjp @deimidis @bacharakis @flore-mozfr
Informed: @rosanardila 

Implementing a volunteer led Global Communications Group that distributes and collects feedback from major Firefox OS announcements. See H2 for more project background #16 

<h1>Primary Goals & Objectives for This Heartbeat </h1>
- [x] Create strategy for raising attendance at meetings (Have at least to one person from each team attend)
- [x] Run training meeting for representatives

<h1>Milestones</h1>
- [x] Kickoff Meeting
- [x] Standup Meeting
- [x] Wrap-up Meeting
- [x] Send reminder email for 2nd meeting (Thurs May 4) 
- [x] 2nd meeting (Friday May 5) 
- [x] Schedule brainstorm meeting with small group (Wed May 3) 
- [x] Make suggested changes to Wiki page 
- [x] Find someone to run meeting on May 12th from team
- [x] Brainstorm meeting with small group re: whistler presentations
- [x] Send email re: new name for group ( @lucyeoh June 10)
- [x] Send reminder email for June 12th meeting ( @bacharakis due by June 11th)
- [x] Ping reps from French community (Theo, Imen, Goofy) Re: June 12th meeting ( @flore-mozfr due June 11th) 
- [x] Create & send feedback report for Patrick ( Due June 11th @lucyeoh)
- [x] Confirm training session (Friday May 12)

**Comment by Flore-mozfr** [comment]
I pinged french community reps but got no answer :'(
And I can't check the box
