### ISSUE TITLE
Explore collaboration between FSA and Campus Campaign

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#320]
## Goal:

Explore collaboration between FSA and Campus Campaign
## Success:
- have a plan to integrate FSA and Campus Campaign efforts
## Related Issues & Links:
# 
## Roles:

Owner: @rosanardila
Involved: @nukeador, FSA board, 270 strategies
Consulted:
## Required:
- [ ] Make a list of all FSA already interested and planning for Campus Campaign (FSA e-board [small], Due: Feb 8th)
- [ ] Start exploration of how to integrate FSA and campus campaign (@rosanardila, FSA eboard, 270 strategies, [medium], Due: Feb 18th)

**Comment by fayepal** [comment]
Hi @rosanardila! Just let us know how we could help you with this, especially with the first task of having a list of FSAs interested. :)

**Comment by rosanardila** [comment]
We had an initial conversation with the Eboard about the interest of the FSA program in Campus campaign. We started getting a better idea of how the communication channels from FSA could be used and coordination with Campus Campaign started. Since we still need to make a bit more progress with the Campaign planning and project management I'm moving this to the next heartbeat.
