### ISSUE TITLE
Connected Devices communication channels revisited

### ISSUE THREAD

**Issue by ensowhat** [mozilla/participation-org#321]
## Goal:

Centralize links to different communication channels relevant for CD, in order to make communication faster and more efficient.
## Success:

Document communication channels (existing and new) in one place.
## Related Issues & Links:
- https://wiki.mozilla.org/Connected_Devices/Participation

FxOS participation comm channels:
- https://docs.google.com/a/mozilla.com/document/d/1jhSMt85xTwA4xRFytMxxZSmdAHL57KMtBWS2HqDSf_o/edit?usp=sharing

CD comm channels:
- https://docs.google.com/a/mozilla.com/document/d/1xhfSIfZCUMRIk-ipkAOPxbFTEjk6fgU6Vd-hvPxw4DM/edit?usp=sharing

Discourse category creation request:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1249299
## Roles:

Owner: @ensowhat
Involved: @brianking @LucyeoH Asa Dotzler @nukeador 
## Required:
- [x] Organize a meeting with the people involved (@ensowhat, [small], Due: Feb 12th) 
- [x] Identify relevant and needed new communication channel (@ensowhat [medium], Due: Feb 19th) 
- [x] Document all the things (on the wiki) ! (@ensowhat, [medium], Due: Feb 19th)

**Comment by ensowhat** [comment]
New communication channels:
- Discourse category: Connected Devices Participation
- Discourse sub-category for NDA Mozillians and Staff
- #cd-participation on irc.mozilla.org as main instant messaging channel

To be announced as an addendum to @geroter 's "Official" communication out to non-staff #335 . Then on the channels listed here:
https://docs.google.com/document/d/1xhfSIfZCUMRIk-ipkAOPxbFTEjk6fgU6Vd-hvPxw4DM/edit#

To be deprecated (and eventually shut down in the future):
- inactive Mailing lists
- fxosparticipate twitter account
- Facebook group

Communicate towards other communities when we'll have more substantial content to share.

**Comment by geroter** [comment]
Two questions:

1) Should we include regular project meetings as part of this package?

2) Should we consider anything related to the new Bootstrap Experiments/Innovation projects that @rosanardila and @williamq are driving?

**Comment by ensowhat** [comment]
@geroter 
1) Yes, we get positive feedback on the CD innovation calls/office hours already, and I think making it easy to participate (early) in project meetings is a key here.
2) It might be too soon regarding this initiative, @rosanardila @williamq thoughts on that?

**Comment by ensowhat** [comment]
Yousef raises an interesting question [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1249299#c1): should we rename the Firefox OS Participation category? I'm thinking  "Firefox OS on phones", since there is an emerging community around this.

**Comment by brianking** [comment]
Yes for sure we should keep some of the phone channels alive, especially Discourse.

**Comment by LucyeoH-zz** [comment]
Blocker: whether to open new discourse topic or re-name. (Tied into transition of Firefox OS project). 

Close on Monday!

**Comment by brianking** [comment]
For reference:

https://wiki.mozilla.org/Connected_Devices/Participation#Get_Connected
