### ISSUE TITLE
Communication of Connected Devices direction builds trust and results in engagement from volunteers

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#324]
## Goal:

Communication of Connected Devices direction builds trust and results in engagement from volunteers
## Success:

1) Healthy, active discussion about CD direction on Discourse of dozens of Mozillians
2) We see a flurry of activity on IoT community-led innovation
## Related Issues & Links:
#286 #291
## Roles:

Owner: @geroter
Involved: @williamq @brianking @rosanardila @nukeador

**Comment by tsl143** [comment]
commenting to know more about getting involved in connected Devices

**Comment by geroter** [comment]
I think we had engagement, I'm not sure we have completely built trust yet.

Comms:
https://discourse.mozilla-community.org/t/firefox-os-connected-devices-announcement/
https://discourse.mozilla-community.org/t/ask-me-anything-with-ari-jaaksi-and-other-connected-devices-follow-up/7016
