### ISSUE TITLE
Foxfooding - past program/devices clarity to existing foxfooders

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#325]
## Goal:

Keep foxfooders up to date.
## Success:

Note to existing foxfooders to clarify what to do with devices, contract, etc
## Related Issues & Links:

[META] #327
## Roles:

Owner: Vik, John B
Involved: @williamq , @brianking, Jean Gong, @ensowhat 
## Required:
- [x] Call (Vik, [small], Due: Feb 10th) 
- [x] Draft (Vik, [medium], Due: Feb 10th)
- [x] Note sent (@ensowhat, [medium], Due: Feb 29th)

**Comment by brianking** [comment]
Meeting tonight to address:

a) technical flashing issues / impications
b) legal contract issues
c) logistics (requests, reclamations, remaining devices, ...)

**Comment by williamq** [comment]
Basic interim message sent out during AMA with Ari. Next step to send detailed next steps of foxfooding program end of February, once that plan is fleshed out.

**Comment by brianking** [comment]
Update from Vik:

We're aiming to have a  near final draft ready for review by all of us (including Erica/PR) by Wed. 2/24.  If there are no major necessary updates, then we should be ready to push the comm out (via email and Discourse as discussed earlier with William and Valentin) by end of the week.

**Comment by brianking** [comment]
Message went out yesterday by @ensowhat:

https://discourse.mozilla-community.org/t/foxfooding-update-devices/7378
