### ISSUE TITLE
CD - Hardware Kits for innovation projects

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#326]
## Goal:

Outline types of hardware kits that we could ship to contributors to test and support ongoing product initiatives. TBD - to support staff-run projects only or also to be part of innovation fund projects.
## Success:

  [What would success look like] 
## Related Issues & Links:

[META] #327 #319 
## Roles:

Owner: @brianking
Involved: @mikehenrty, @ensowhat, @mozillamarcia
## Required:
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: Aug 7th)

**Comment by brianking** [comment]
Going to morph this issue into specifically what will our hardware needs be for the G1 innovation projects that we are working with. e.g. Vaani.

**Comment by couci** [comment]
@rosanardila and @brianking will sync on this

**Comment by brianking** [comment]
@mozillamarcia you have been looking into hardware kits, in particular for the train projects like Vaani. Are you documenting anywhere?

**Comment by brianking** [comment]
Will be part of CEL and working with product trains. No plans made here yet.

Will be moved to next heartbeat.

**Comment by ensowhat** [comment]
Part of #400
