### ISSUE TITLE
Foxfooding - part of gating process

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#328]
## Goal:

Include Foxfooding as an optional tool in the gating process to collect feedback from users. Define a mechanism to offer this alternative in the gating process. In the longer term, to pilot an experience with one of the products that would be close to G2. 
## Success:

Outline of process for including foxfooding in the gating process.
## Related Issues & Links:

[META] #327
## Roles:

Owner: @dpalomino, Marcia
Involved: @brianking, @ensowhat
## Required:
- [x] Initial conversations (@dpalomino, [medium], Due: Feb 22nd) 
- [ ] Talk with PMs of Gate 1 projects (@dpalomino, [medium], Due: Mar 1st) 
- [ ] Document foxfooding in gating process as part of docs on participation in general in gated projects (@dpalomino @brianking, [medium], Due: Mar 8th)

**Comment by LucyeoH-zz** [comment]
@dpalomino  - Part of foxfooding proposal Vik is putting together?

**Comment by LucyeoH-zz** [comment]
Move to next heartbeat.

**Comment by dpalomino** [comment]
Yes, it will be considered for the overall foxfooding proposal. But we will need to wait until one of the projects running gating process would be closer to G2...

**Comment by brianking** [comment]
Assigned to @dpalomino and moving out to heartbeat after this one.

**Comment by brianking** [comment]
Out of scope now, closing.
