### ISSUE TITLE
Participation in Innovation Process

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#329]
## Goal:

Concept note - short-term actions + long-term framing --> run ideas by CD Senior Team + open for conversation
## Related Issues & Links:

[META] #327 
## Roles:

Owner: John B
Involved: 
## Required:
- [x] Followup with John (@brianking, [small], Due: Feb 22th)
- [x] Call with John (John B, [small], Due: Feb 29th) 
- [x] Note (John B, [medium], Due: Mar 2nd)

**Comment by LucyeoH-zz** [comment]
Ongoing, needs expansion and to be moved to the next heartbeat.

**Comment by brianking** [comment]
Will followup with John and likely nothing here until the week after next (post-MWC).

**Comment by brianking** [comment]
Seeking clarification from @geroter on what this is specifically about.

Is it:
- Related to the gated process G0 and before
- Related to participation in G1 projects that are ongoing?
- Related to broader process including the Community Experimentation Launchpad

**Comment by geroter** [comment]
Lots of meetings and conversations happened.

2 initial "presentations" have been synthesized (1) CD Participation Strategy; 2) Concept note on how participation should shape the strategy/theory of change for Mozilla's IoT efforts).

Job of socializing/getting feedback from CD Leadership is just finishing this weekend ... will be made public early next week.
