### ISSUE TITLE
H3: External Experts - Identified 5 groups/orgs to interview

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#33]
<h1>Project Description</h1>

Owner: @Lucyeoh
Member: @francjp 

Find and interview organizations who are taking an inspiring approach to participation.  See H2 for more project background #26  

<h1>Primary Goals & Objectives for This Heartbeat </h1>
- [x] Engage community leaders to our project and get their help spreading the word
- [x] Mine the Participation Team and our communities for possible groups to interview
- [x] Identify (min) 5 groups/orgs to interview

<h1>Milestones</h1>
- [x] Kick-off meeting
- [x] Divide up community leaders and arrange one on ones
- [x] Outreach for one on ones to all community leads ( @lucyeoh @francjp  due June 5th):
  - [x] Mozilla India - Abid @lucyeoh
  - [x] Mozilla Uganda/EA - San James @lucyeoh
  - [x] Mozilla Arabic - Melek, Sofien, Rami @lucyeoh 
  - [x] Mozilla West Africa - Tayo @francjp 
  - [x] Mozilla Balkans - Ioana @francjp 
  - [x] German Speaking - Michael @francjp 
- [x] Follow-up with participation team about orgs/groups to interview (@francjp due June 3)
- [x] Send request to Mozilla Hispano and Mozilla Brazil communities directly (@francjp June 5) 
- [x] Standup Meeting
- [x] Triage interview options from form (@francjp June 17th)
- [x] Triage interview options from in person interviews ( @lucyeoh June 17th)
- [x] Wrap-up Meeting

**Comment by LucyeoH** [comment]
External Experts Tracking Doc: https://docs.google.com/spreadsheets/d/1Pl0hjAQAh2HWtPOmVG7XcNM3dD_tHvIdFXoXSVjJ6fE/edit#gid=0

**Comment by LucyeoH-zz** [comment]
Organization Spreadsheet - http://ow.ly/OrfLp
