### ISSUE TITLE
Opening consultation into Firefox OS smartphone end-of-life decisions

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#330]
## Goal:

Determine what the existing process is an come up with a proposal
## Related Issues & Links:

[META] #327 
## Roles:

Owner: Julie
Involved: @williamq , @geroter , @brianking

**Comment by brianking** [comment]
Please include Porting to phones as a sub-category in this topic, in particular:
- future of b2gInstaller add-on
- publishing of instructions to build on CyanogenMod

These (and others) seems like they would be ripe for community ownership.

**Comment by brianking** [comment]
Related conversation:

https://discourse.mozilla-community.org/t/organising-the-afterlife-of-firefox-os/6943

Surely others happening.

**Comment by LucyeoH-zz** [comment]
I hear the Brazil community is taking up this cause you should talk Adriano

**Comment by LucyeoH-zz** [comment]
French contributors also @ensowhat

**Comment by LucyeoH-zz** [comment]
@williamq move to next heartbeat @geroter please comment.

**Comment by ensowhat** [comment]
For more reading: https://public.etherpad-mozilla.org/p/firefoxos_is_not_dead

**Comment by brianking** [comment]
George is leading the charge here.

We met yesterday with the rest of the team in the org working on the transition. There is hope for the staff bits and first-pass general code plan to be signed off on this week. Then we can plug that into the general community plan and open it up for wider discussion.

**Comment by brianking** [comment]
@geroter 's post from Monday this week:

https://discourse.mozilla-community.org/t/update-on-b2g-os-for-smartphones-transition/7364

Next step is to schedule the meeting based on the doodle referenced in the post.

**Comment by gaby2300** [comment]
Thanks Brian!

Gabriela
QA Mozilla Hispano Team Responsible

**Comment by gaby2300** [comment]
Have you already set the date and time for this meeting?

Many thanks!
Best regards,
Gabriela
QA Mozilla Hispano Team Responsible

**Comment by brianking** [comment]
I think we are good to close out this one.

First community meeting happened yesterday:
https://public.etherpad-mozilla.org/p/b2gostransition-kickoff

Wiki page up:
http://wiki.mozilla.org/B2G/Transition_Project

I recommend for anything related moving forward, we open new issues.
