### ISSUE TITLE
AMA with Ari

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#331]
## Goal:

Proposal for concept, tech and timing
## Related Issues & Links:

[META] #327 
## Roles:

Owner: @LucyeoH 
Involved: @nukeador , @geroter 
## Required:

**Monday Feb 8th**
- [x] Ask Ari to set-up AMA  topic on discourse ( @geroter 
- [x] Close discourse channel once it's created ( @nukeador 
- [x] Ping Mitchell asking her if she can be online Friday
- [x]  Send email to team with the plan and ask them to populate questions from discourse [here](https://docs.google.com/document/d/1q4MP4kY1TwtEJI0jYzLTp0uRToAwoYQcU773YHnz858/edit#) (Deadline: EOD Tuesday). (@lucyeoh)
- [x] Find someone to help Ari with Discourse ( @nukeador 
  **Tuesday Feb 9th**
- [x] Move questions to moderator tool (@lucyeoh) 
- [x] Update wiki with transition & moving forward CD plan ( @brianking 
- [x] Finalize content for follow-up email include instructions + moderator & discourse links. Send. (@lucyeoh & @geroter ) 
- [x] Share announcement on telegram (@nukeador) 
  **Thursday Feb 11th**
- [x] Send reminder email (@lucyeoh)
- [x] Send reminder through Telegram (@nukeador)
- [x] Copy & Paste top questions from moderator ( @lucyeoh or other)

**Comment by brianking** [comment]
https://discourse.mozilla-community.org/t/im-ari-jaaksi-svp-of-connected-devices-ama/6975

All done here? Any followup needed?

**Comment by nukeador** [comment]
Probably we should have a talk about it to see how did it go.

**Comment by ioana-chiorean** [comment]
I would suggest to check some metrics:  how many questions were answer, how many were posted in mozmoderator (ho many votes), how many not answered.

**Comment by LucyeoH-zz** [comment]
Hey All, here's the results of the AMA survey [here](https://docs.google.com/a/mozilla.com/forms/d/10TqEvJuaGiKoOHocQoQgKd6n4x1SFnR_ygLWuYbdKYM/viewanalytics#start=publishanalytics). 

General summary: 
- A slim majority felt it was worthwhile 
- People felt it was too short and that not enough questions got answered
- Want more answers about the future
- Felt the setting was too "political" 
- Some feedback suggested video would have been better
