### ISSUE TITLE
Keeping SC and CD Senior Team updated on non-staff engagement

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#332]
## Goal:

Keep leadership informed on participation momentum on SC.
## Related Issues & Links:

[META] #327 
## Roles:

Owner: @geroter 
Involved: 
## Required:
- [ ] EOW update (owner, [medium], Due: Feb 12th)

**Comment by brianking** [comment]
Continually engaged, another meeting Thursday.

**Comment by geroter** [comment]
Update given at CD Senior Team on framework of proposal. Also got to 4 decisions:

1) Trains past Gate 0 will be public -- Porfirio is leading, with Candice and Tony Appleton involvement + PR

2) Will build a process to articulate strategic questions in progress on an ongoing basis for input from the broader staff and non-staff community. -- George leading

3) Will have a pilot project for "senior" volunteer advisors to CD Senior Team and Innovation Board -- George leading

4) A few staff (exact # to be determined, but unlikely to be less than 5) will be assigned for 4-5 months to helping with smartphone code transition to an open source/non-staff owned project. -- TBD next steps and leader

Will also continue this issue in next HB.
