### ISSUE TITLE
Land/finalize the Reps Innovation Fund details

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#333]
## Goal:

Solidify plan for Reps Innovation Fund for CD
## Related Issues & Links:

[META] #327 
## Roles:

Owner: @rosanardila 
Involved: @williamq , @ensowhat , @brianking, Reps Council
## Required:
- [ ] Setup task force for mentoring and tech support, vetting projects, and so on (@williamq, [medium], Due: Feb 12th)
- [ ] Detailed ideas worked through/consulted for presentation to Reps + others (@rosanardila, [medium], Due: Feb 12th)

**Comment by brianking** [comment]
Initial call happened today.

@rosanardila @williamq are the next steps documented anywhere?

**Comment by MichaelKohler** [comment]
Since there was an initial call today, can I ask why there was no involvement of the Reps Council since we're clearly involved here?

**Comment by MichaelKohler** [comment]
@brianking  As far as Council knows, the next steps are documented at the end of this document: https://docs.google.com/document/d/1JBzIUq5F5d5HJhDNBklOe9t83NI4c8fU1NK0oJjyMYE/edit

**Comment by rosanardila** [comment]
To clarify: It was a short 15 min conversation between Nuke, William, Valentin and me for research. We added to the working doc some resources that were created for Singapore and we clarified who was the best person to approach from the CD team. This wasn't an "initial meeting".

**Comment by rosanardila** [comment]
The council discussed next steps with @williamq. Closing this, we will start a new issue for the next heartbeat with those next steps.
