### ISSUE TITLE
"Official" communication out to non-staff

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#335]
## Goal:

Update on process/next steps
## Related Issues & Links:

[META] #327 
## Roles:

Owner: @geroter 
Involved: @LucyeoH 
## Required:
- [x] Get the message out! (@geroter, [medium], Due: Feb 9th)

**Comment by brianking** [comment]
Are we done here @geroter ?

**Comment by brianking** [comment]
One went out last week, back looking. Aiming to get a forward looking one out this week.

**Comment by ensowhat** [comment]
We suggest to announce the new CD Participation channels (cf. #321 ) as an addition to this communication, can we synchornize on this ?

**Comment by geroter** [comment]
Yes, let's make sure:

a) Communication references these new channels.
b) Communication uses these new channels.

**Comment by geroter** [comment]
Communication is ongoing. One for this week is delayed -- a couple of blockers on information we needed to include. Should be ready for early next week.

Am continuing this issue for the next heartbeat.

**Comment by ensowhat** [comment]
The new Discourse category is here : https://discourse.mozilla-community.org/c/connected-devices

**Comment by brianking** [comment]
New communication written yesterday, currently being reviewed by @geroter who will send it out likely today.

**Comment by brianking** [comment]
https://discourse.mozilla-community.org/t/connected-devices-participation-update/7480

Done!
