### ISSUE TITLE
Playbook for Leadership Summit

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#339]
## Goal:

Create a playbook for the global gatherings
## Success:

Have a clear document about the logistics involved at the Global Gatherings, specifically Leadership Summit
## Related Issues & Links:
#249 #223
## Roles:

Owner: @francjp
Involved: @rosanardila @couci @emmairwin 
## Required:
- [x] Create a first draft of the doc (@francjp [medium], Due: Feb 17th) 
- [x] Review, and request feedback (all, [small], Due: Feb 24th) 
- [ ] Finalize and publish the document (@francjp [medium], Due: Mar 2nd)

**Comment by francjp** [comment]
First draft of the document is online now:
https://docs.google.com/document/d/15n27qJyWB0rnjDg6BD2fM9ZkckStnPmbbs9eK_TNQ1o/edit?usp=sharing

**Comment by francjp** [comment]
Moving to the following heartbeat and updating deadlines

**Comment by francjp** [comment]
Final document is ready to be published. Waiting on info or decision, where to publish the doc. The issue can be consider as closed

**Comment by LucyeoH-zz** [comment]
Blocker - needs to find out where to publish this on the wiki.

**Comment by ioana-chiorean** [comment]
@francjp - will you share about this in the Reps call? I think it would be usefull to. cc @couci

**Comment by emmairwin** [comment]
How do you see this merging with https://github.com/mozilla/participation-org/issues/349  ?
