### ISSUE TITLE
H3: Launch new contribute wiki page with participation directory

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#34]
<h1>Project Description</h1>

Owner: @lucyeoh @couci 
Revamp contribute wiki page so it can be used as a resource for contributors to find and connect with new projects, while preserving the old content of the wiki page on the participation wiki. 

<h1>Primary Goals & Objectives for This Heartbeat </h1>
- [x] Measure progress of new contribute page (sync up with @nukeador) 
- [x] Update Participation Wiki page
- [x] Incorporate resources from old contribute page in new section "Participation Resources" 

<h1>Milestones</h1>
- [x] Kick-off meeting
- [x] Standup Meeting
- [x] Wrap-up Meeting
- [x] Get in touch with team that's working on Staff + Participation (@couci )
- [x] Create draft of Participation Team page ( @lucyeoh Due: Monday May 25)
- [x] Create draft of Participation Resources page ( @couci Due: Monday May 25) 
- [x] Approve & launch pages ( @couchi & @lucyeoh due Thursday June 11th) 
- [x] Sync up with @nukeador and do testing on wiki.mozilla.org/contribute to see if it's achieving desired goals

**Comment by couci** [comment]
draft for participation resources can be found at the end of this document: https://docs.google.com/document/d/1jdDj-CGKDcQH4SN6FMARD-obnI0Uo7h7s2Qa7s-G57Q/edit# along with potential onboarding staff resources

**Comment by LucyeoH-zz** [comment]
Konstantina - Add community Survey
Lucy - Send resource page to participation team so they can add

**Comment by LucyeoH-zz** [comment]
Promotion - Create a discourse page, tell the communication team so that they can incorporate.

**Comment by brianking** [comment]
@LucyeoH  Please edit this comment and fill out this template. Thanks!

### What was supposed to happen?

...

### What did happen?

...

### What we learned?

...

### What are some improvements?

...

### What does the next Heartbeat for this project look like?

...
