### ISSUE TITLE
Debrief and Document FOSDEM 2016

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#340]
## Goal:

Create a debrief and produce a document with guidelines for FOSDEM
## Success:

Have a clear guideline for FOSDEM
## Related Issues & Links:
#225
## Roles:

Owner: @francjp
Involved: Ziggy-Maes, Benoit-Leseul
## Required:
- [x] Create the debrief of the event (@francjp [small], Due: Feb 15th) 
- [x] Review debrief, and create draft of the guidelines (@francjp, Benoit, Ziggy, [medium], Due: Feb 26th) 
- [ ] Publish the document, or create a wiki (@francjp, Ziggy [medium], Due: Mar 4th)

**Comment by brianking** [comment]
@ensowhat can help as well (and me).

**Comment by ioana-chiorean** [comment]
Count me in @francjp :D

**Comment by francjp** [comment]
Debrief created:
https://docs.google.com/document/d/1ieeIYs3J0TL6lv2KRGF6dbFkFz234fdsgPYwVnDzPxs/edit?usp=sharing

More info to follow soon.

**Comment by ioana-chiorean** [comment]
Three lessons learned from my side:
- For the shifts that did not work well - set earlier milestone to check with their process, understanding of the task
- Have the "on the same page " call - aka discuss the latest news with all
- Create a "strong points cheat-sheet " aka a database doc with strong point s of the volunteers present and point people to their twitter or mail for more questions or *_even better *_take their email and get back to them.

**Comment by francjp** [comment]
Hi @ioana-chiorean,

For feedback we've opened an etherpad: https://public.etherpad-mozilla.org/p/FOSDEM16-Feedback
In any case, I will include this on the pad.

Thanks

**Comment by ioana-chiorean** [comment]
Hey @francjp I did add my feedback there. This was specific as lessons learned for the debriefing.

**Comment by francjp** [comment]
Moving to the following heartbeat, and updating deadlines.

**Comment by francjp** [comment]
Guidelines and debrief reviewed: https://docs.google.com/document/d/1UyWlOGJJv03FGkxIOFMoEoefnnMVOla6DamTUi1XQD4/edit?usp=sharing

Need feedback on guidelines, but will be reviewing and publishing by the end of this week.

**Comment by francjp** [comment]
Waiting on final feedback of the doc, and polish a little bit.

Will be published under the wiki in FOSDEM page.
