### ISSUE TITLE
Work on a localization priority list

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#342]
## Goal:

Identify a list of languages that needs to be prioritized in localizing.
## Roles:

Owner: @bacharakis
Involved: @MichaelKohler, Reps Council
## Required:
- [ ] Contact the l10n team, the participation team and the council. (Due: Feb 13th)
- [ ] Identify and document the next steps (@Bacharakis, Due: Feb 20th)

**Comment by gueroJeff** [comment]
Could you provide more context within this issue's description please? I'm not sure if this is referring to Participation Team projects, Mozilla products, marketing campaigns, etc.
