### ISSUE TITLE
RepsNext: Resources track

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#344]
## Goal:

Create a specialization on resources for Reps who wish to empower their communities (be it local/regional or functional) by enabling them take advantage of the resources the Reps program has.
## Success:

Plan is approved and transition started.
## Related Issues & Links:
- META: #303
- [Discourse topic](https://discourse.mozilla-community.org/t/working-group-resources-track/7011)
- Meeting notes: [1st](https://discourse.mozilla-community.org/t/working-group-resources-track/7011/10?u=nukeador) [2nd](https://discourse.mozilla-community.org/t/working-group-resources-track/7011/13?u=nukeador)
- [Track details doc](https://docs.google.com/document/d/1spalJlpgY49eNlbwBxafbJHK1osY6hzO8rGzmJ4nXxA/edit#) (draft)
## Roles:
- Owner: @nukeador @Faisalaziz
- Involved: @francjp @couci 
## Required:
- [x] Analyze and identify mozillians interested in joining this track per community. (@couci, [medium] Due: Feb. 23)
- [x] Define a training plan for people in this track (@francjp, [medium] Due: Feb. 23)
- [x] Process to join the track defined. (@Faisalaziz @nukeador, [medium] Due: Feb. 23)
- [x] Description about the review team (@Faisalaziz @nukeador, [medium] Due: Feb. 23)
- [x] Experiments details (@Faisalaziz, [medium] Due: Feb. 23)
- [ ] Gather feedback from Reps and Council (all, [medium] Due: Feb. 26)
- [ ] Transition plan defined (@nukeador, [medium] Due: March. 4)
- [ ] Transition/test month starts (all, [medium] Due: March. 7)

**Comment by nukeador** [comment]
We will be meeting tomorrow 13:00UTC to check on planned actions status. There are a few we set for tomorrow, take sometime to advance them or at least have a draft to share.

Thanks!

**Comment by nukeador** [comment]
I've created [this doc](https://docs.google.com/document/d/1spalJlpgY49eNlbwBxafbJHK1osY6hzO8rGzmJ4nXxA/edit#) where we can document all the track details

**Comment by nukeador** [comment]
@couci @francjp and @Faisalaziz will complete the document with details by this Friday.

**Comment by couci** [comment]
Results for analysing and identifying Mozillians are in. Only problem is that we don't know the exact number of sub-communities in India, so the estimation might not be that accurate.

**Comment by nukeador** [comment]
Ping/reminder to include all the detailed information in the doc today if possible :-)

Thanks!

**Comment by nukeador** [comment]
We'll try to wrap up the details doc today so we can move it to Reps feedback and Council review.

**Comment by nukeador** [comment]
Draft 1.0 of the implementation doc is ready for review:

https://docs.google.com/document/d/1spalJlpgY49eNlbwBxafbJHK1osY6hzO8rGzmJ4nXxA/edit?pref=2&pli=1#

**Comment by nukeador** [comment]
This will be moved to next HB in order to get Council review and approval.

**Comment by couci** [comment]
Moved to Council for approval
