### ISSUE TITLE
Revamp CD Weekly Meetings

### ISSUE THREAD

**Issue by ensowhat** [mozilla/participation-org#346]
## Goal:

Structure CD weekly meetings/calls.
## Success:

Gathering more people to share their thoughts, and reports on their work in progress. 

Suggestions :
- Have status updates from each of the CD trains. Could include demos or tech talks about what they are working on.
- Get status updates from non-Mozilla CD projects, Medical Devices for instance.
- Invite members from other IoT projects to participate. For instance, OpenHab CEO could give a brief talk for his thoughts on voice control and IoT.
- Leave time for roundtable discussion at the end (people can stay or leave for this).
- Kill the current Gaia weekly meetings, and perhaps use their timeslot.
## Roles:

Owner: @ensowhat
Involved: @brianking 
## Required:  (TBD)
- [x] Gather more ideas and feedback for weekly meetings (@ensowhat, [medium], Due: Mar 4th) 
- [ ] Set date and agenda for first renewed meeting (@ensowhat, [medium], Due: Mar 8th) 
- [ ] Invite project staff to first meeting (@ensowhat, [medium], Due: Mar 9th)

**Comment by LucyeoH-zz** [comment]
@ensowhat can you re-work this issue slightly to put it in the form of a "to do". If it's not an actionable item I'd recommend putting it as a discussion on discourse. 

@brianking or I can help you turn this into an actionable issue for next quarter!

**Comment by brianking** [comment]
Yes, there are some tasks we can add to this one. Will work with @ensowhat. We can move to the next heartbeat.

**Comment by couci** [comment]
this is going to be built in the experimentation lab,

**Comment by brianking** [comment]
Ok will assign to @rosanardila 

Will move to next heartbeat.

**Comment by brianking** [comment]
Part of #400

**Comment by rosanardila** [comment]
this is covered by the redesign of the office hours done with @mikehenrty

**Comment by brianking** [comment]
https://docs.google.com/document/d/1879_uPfuI4suozLpg6aiuIteOnPIMoZBeq8C2m0KEm0/edit
