### ISSUE TITLE
RepsNext: Alignment with Participation and Mozilla Org

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/participation-org#348]
## Goal:

The goal of this working group is to create a plan on how to align with the Participation team to increase our impact and work on common goals to bring our mission forward.
## Success:
- We have a clear plan on when and how we plan/workout our alignment with the Participation team.
- We have a clear timeline on when we start discussing goals, mid-term review and final draft of the goals.
- We have a plan on how the goals are communicated with Reps (cadence, transparency)
- We have identified a way to address concerns regarding goals before they are set in stone
- We have identified a place to document Mozilla’s goals so Reps can easily look them up in one place
## Related Issues & Links:
- META: #303
- [Discourse topic](https://discourse.mozilla-community.org/t/working-group-alignment-with-participation-team-and-mozilla-organisation/7013)
- Meeting notes: [1](https://discourse.mozilla-community.org/t/working-group-alignment-with-participation-team-and-mozilla-organisation/7013/6?u=mkohler)
## Roles:
- Owner: @MichaelKohler @ThePhoenixBird
- Involved: @ioana-chiorean @couci @LucyeoH 
## Required:
- [x] understand how the participation team has done their planning to respect planned milestones (@ioana-chiorean, [medium], Due: Feb 21)
- [x] how does documentation work within the working group and then also outside (should be transparent anyway, but how do we do it?) (@MichaelKohler, [medium], Due: Feb 21)
- [x] Start a discussion around how this group and the Participation team can keep in sync during the working group and how we can keep the alignment for future semesters  (Sunnat, [medium], Due: Feb 21)
- [x] Organize the meeting for next week (@ioana-chiorean @MichaelKohler, [small], Due: Feb 21)
- [x] Figure out on how can we adapt during the quarter / semester if there are changes? (@MichaelKohler everybody, [medium], Due: March 31)
- [x] Finalize the plan on how we keep ourselves synced, how we communicate goals, how we document goals and how to deal with concerns (everybody, [small], Due: March 31)

**Comment by MichaelKohler** [comment]
We are starting to draft a plan here: https://docs.google.com/document/d/1nB5WHS9tNkNL0U_e7OPTrdkxhluV8nbi4k2cXFpOkf8/edit

I will start a discussion around adapting for changes on Discourse tonight.

**Comment by MichaelKohler** [comment]
Proposal here: https://docs.google.com/document/d/1hCdemwo5-ZQzzRPQe8MREbvzK9J2wBO34wKfzfZA89g/edit# . This is currently in open for final discussions and I'll move this to Council/Participation approval at the end of the week.

**Comment by geroter** [comment]
Pretty important I review this. I won't have time this week though as after
today I'm disconnecting/on vacation.

On Tue, Mar 15, 2016 at 3:00 PM, Michael Kohler notifications@github.com
wrote:

> Proposal here:
> https://docs.google.com/document/d/1hCdemwo5-ZQzzRPQe8MREbvzK9J2wBO34wKfzfZA89g/edit#
> . This is currently in open for final discussions and I'll move this to
> Council/Participation approval at the end of the week.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/mozilla/participation-org/issues/348#issuecomment-196833809

## 

George Roter
Head of Core Contributors, Participation

irc: geroter  |  skype: geroter
Cell - Canada: 416.670.2401
Cell - USA: 650.485.0079
<650%20308%208443>

**Comment by MichaelKohler** [comment]
Proposal: https://docs.google.com/document/d/1hCdemwo5-ZQzzRPQe8MREbvzK9J2wBO34wKfzfZA89g/edit (currently waiting for feedback from George)

**Comment by geroter** [comment]
Extensive feedback in the doc now. Sorry for the delay.

**Comment by MichaelKohler** [comment]
I've updated the doc to have everything from Berlin in it. Konstantina will look at it on Monday to make sure I haven't forgotten anything and then we are ready to send this for final approval and implementation: https://docs.google.com/document/d/1hCdemwo5-ZQzzRPQe8MREbvzK9J2wBO34wKfzfZA89g/edit

**Comment by MichaelKohler** [comment]
Final vote for Council created: https://reps.mozilla.org/v/alignment-proposal-final-vote/
