### ISSUE TITLE
Leadership summit playbook for event design & content is created

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#349]
## Goal:

Leadership Summit provides value for attendees
## Success:

Recommendations based on Debrief of Summit and community survey is created.
## Related Issues & Links:
#339
## Roles:

Owner: @emmairwin
Involved: @rosanardila @geroter @francjp 
## Required:
- [ ]  Create recommendation/playbook document based on team debrief  (@emmairwin, medium, Due: Feb 24th) 
- [x]  Summarize community survey for team (@emmairwin, medium, Due: Feb 25th) 
- [x]  Update playbook to reflect learning from community survey (@emmairwin, medium, Due: Feb 25th)

**Comment by brianking** [comment]
Dupe of #339 ?

**Comment by emmairwin** [comment]
@francjp  is doing logistics version, I am summarizing the recommendations from debrief.

**Comment by emmairwin** [comment]
Summary of volunteer survey https://docs.google.com/document/d/1TtosIhTqa56n-XfaNmrKA00C8tu25ZwKSnZ7n5FoyOk/edit

 (42 people responded)

**Comment by emmairwin** [comment]
Draft version of playbook/recommendations  https://docs.google.com/document/d/1nxnm_LInRCoS87AIlgxcx8pJV9ukt2Ihx1WkxmElDkA/edit#

Will turn into slide deck after feedback @geroter @rosanardila @francjp

**Comment by emmairwin** [comment]
https://docs.google.com/document/d/1nxnm_LInRCoS87AIlgxcx8pJV9ukt2Ihx1WkxmElDkA/edit#heading=h.zc15ai5s4lda
- missing some pieces on accountability, but will close this issue as those best practices are still forming.
