### ISSUE TITLE
H3: Track ongoing participation experiments, and continue to build registry of all participation projects - Extract lessons to present at Whistler

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#35]
<h1>Project Description</h1>

Owner: @lucyeoh 
Members: @emmairwin 
Informed: @geroter 

Track and support focused and distributed Participation Lab experiments and create a registry of ongoing participation activities. For more project background see: #17  

<h1>Primary Goals & Objectives for This Heartbeat </h1>
- [x] Continue tracking ongoing experiments and add new additions
- [x] Continue to build and develop registry

<h1>Milestones</h1>
- [x] Kickoff Meeting
- [x] Standup Meeting
- [x] Wrap-up Meeting
- [x] Update tracking with Science Lab ( @lucyeoh) 
- [x] Create plan for presenting at Whistler
  - [x] Create a document for talking points 
  - [x] Outreach to William Quiviger + Rosana to find strategic learnings for OS ( @emmairwin due Wed June 10)
  - [x] Outreach to Bobby to find strategic learnings for OS ( @lucyeoh due Wed June 10) 
  - [x] Finalize talking points document ( Due Thursday June 11th) 
  - [x] Divide the experiments into themes
  - [x] Send themes to George 
- [x] Follow-up with people for registry

**Comment by LucyeoH-zz** [comment]
Should look through this: https://events.mozspaces.org but also community calendar to search for Firefox OS initiatives.

**Comment by LucyeoH-zz** [comment]
Check out London events specifically (get on mailing list?)

**Comment by brianking** [comment]
https://reps.mozilla.org/events/ might be a good resource.

**Comment by LucyeoH-zz** [comment]
I talked to Bobby and got this great pdf about their learnings but I'm not sure what to pull from it -  https://webmaker-dist.s3.amazonaws.com/reports/bangladesh.pdf

**Comment by emmairwin** [comment]
Feedback on strategic advantage from Buddy Up

https://gist.githubusercontent.com/emmairwin/9e9260ccdbd4b460470c/raw/040827faab4701c782b865ffb9f91b2bbc4f02d6/gistfile1.txt

**Comment by LucyeoH-zz** [comment]
Next Heartbeat: 
- Follow-up with our enlisted experiments
- Start pulling out learnings
- What do we do with the learning points as we find them.
