### ISSUE TITLE
Participation strategy for education at Mozilla, and Leadership Framework  1.0 are proposed

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#350]
## Goal:

Participation in Curriculum working group provides value to group goals for  leadership, curriculum design and strong experiments for participation in Education at Mozilla .
## Success:
- A participation strategy for education at Mozilla is proposed in collaboration with core contributors.
- A new iteration of the Participation Leadership Framework is proposed in collaboration with curriculum working group.
## Related Issues & Links:

https://github.com/mozilla/learning-networks/issues/341
## Roles:

Owner: @emmairwin
Involved: @geroter @chadsansing  (and working group) @jgmac1106 
## Required:
- [x] Create initial proposal for Education participation hub at Mozilla
- [x] Create a second proposal for Education participation hub
- [x] Get feedback on both proposals, and consult with core contributors in education.
- [x] Create strategy for Education Participation based on proposals and feedback to launch next heartbeat.
- [x] Present history, and current framing for Leadership Framework to curriculum working group (as we have selected it for Leadership curriculum at Mozilla) ,   based on feedback - propose an improved 1.0 version .

**Comment by emmairwin** [comment]
First draft of first proposal:  https://docs.google.com/document/d/1urKpLfZ-5D-_bB7FzAcJWDmdxFa_HZu3yIkekzA6Zng/edit#

**Comment by emmairwin** [comment]
cc/ @jgmac1106

**Comment by emmairwin** [comment]
cc / 
@verenanz1 also need Helen's github name.  who else should we cc/ @jgmac1106  ?

**Comment by jgmac1106** [comment]
@omnignorant or @robertfriedman not sure how he roles on GitHUb

Daneile @mte90 as the developer stepping into teaching roles.

Karen Smith, not sure her GitHub handle

Ian O'Byrne, @wiobyrne

Amira @amirad, if she has capacity

Shreyas @dun3buggi3

@soapdog if capacity

@anme Chung, if capacity

Mikko Kontto (was on Web Lit team)

Tim Miller (was on Web Lit team)

Gauthamraj Elango

cc/@chadsansig to keep in the loop

**Comment by dvigneshwer** [comment]
Developing a skill is a long term process, I think education participation hub should be more like having elements available in sites such as coursera etc, which provides rich documentations and a way **self motivating stuctured learning**.

I went through the proposal, identifying contributors for different skills is an very good idea, provided we need to classify skills at a broader range so that we can cover a range of industrial grade productive education categories.

**Comment by amirad** [comment]
An education hub in Participation? Would love to hear more of what that is and what it would love like.

**Comment by emmairwin** [comment]
Thanks @dvigneshwer will follow up with some ideas, and a consulting phase.

**Comment by emmairwin** [comment]
@amirad linked above in document, but would also love to hear your thoughts.  will include you in consult phase also.

**Comment by emmairwin** [comment]
Summary of feedback, on bringing education contributors at Mozilla together.

https://docs.google.com/document/d/1wz4cP3whStE0qeqxOdJ1zIv4c2N63pFxszyFqVhh3Nw/edit#

**Proposal**
Run a one hour workshop with core 'EDU' contributors and others interested. During this workshop we will:
- Propose community design 
- Run an Educator's version of my workshop ‘[Building Bridges to Mozilla](https://docs.google.com/presentation/d/1US8gLMoucaRH46pOZIHSHyrAU4v18iU289rOEH_GDr0/edit#slide=id.p)’ to identify one or two experiments we can run for outreach.
- With the outcome, outline goals and KPI for starting this in the next heartbeat.

**Comment by emmairwin** [comment]
calls scheduled:   http://mozilla.github.io/participation-curriculum/education_at_mozilla for Wednesday, one early my time, one in the evening my time to include the most people.

**Comment by chadsansing** [comment]
Great area for collaboration across the org and between the org and community. I dig the layout and icons on the page. 
- Would be interested in intro copy before the March 9 agenda explaining the cross-over and collaboration between this community, Participation, and MoFo learning areas. Maybe comms people can get together? Is this needed? Wanted? Advisable and efficient?
- The last item under the March 9 agenda might be missing a bullet.

**Comment by emmairwin** [comment]
HI @chadsansing 

I'll summarize our community meeting(s) and  revisit this question. My instinct is that bringing in Comms now would be too early.   An early task for this group might be to write up a manifesto, or community mission statement, which can better inform that type of discussion. The goal is to grow this slowly, and thoughtfully not to rush , and to be as inclusive as possible of perspectives, and teams.

**Comment by chadsansing** [comment]
Sounds right for the community; in my questions, I was trying to go after language that helps clarify connections between spaces so community members feel able to move between them and further connect them, rather than to define any limiting factors :)

**Comment by emmairwin** [comment]
Had a couple of great calls - https://public.etherpad-mozilla.org/p/education-community
will summarize, and propose next steps .

**Comment by emmairwin** [comment]
will move over leadership framework to next heartbeat, still need to hear how @chadsansing is using the one we have.
