### ISSUE TITLE
Prepare and execute logistics for Berlin Training days

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#355]
## Goal:

Prepare the logistics for Berlin Training days in April
## Success:

Coordinate logistics and secure venue and hotel
## Related Issues & Links:
#309
## Roles:

Owner: @francjp
Involved: all participation team 
## Required:
- [x] Contact hotel and venue (@francjp [medium], Due: Feb 26th) 
- [x] Confirm requirements for the event (@francjp, @couci, [small], Due: Feb 29th) 
- [ ] Book hotel and confirm flighst (@francjp [medium], Due: Mar 4th) 
- [ ] Check or create the wiki (Participation team, [medium], Due: Mar 9th)

**Comment by LucyeoH-zz** [comment]
@francjp wanted to flag these from #343 you might want to add here 
- [x] Email staff re: booking flights & accommodations 
- [ ] Email Reps Council accommodations
- [ ] Coordinate flights 
- [x] Find and book meeting space 
- [ ] Finding the restaurant and making reservations (Ask @rosanardila re: restaurants)

**Comment by LucyeoH-zz** [comment]
Need to harass staff and council members for confirmation :)

**Comment by francjp** [comment]
Moving to the next heartbeat
