### ISSUE TITLE
RepsNext: Application Process track

### ISSUE THREAD

**Issue by ThePhoenixBird** [mozilla/participation-org#358]
# Goal:

The goal of this working group is to create a plan on how to align the application process, selection criteria and responsibilities with the new changes that will come up from other working groups.
# Success:
- We have a defined proposal for changes to the current application process to integrate the new changes.
- We have a re-worked list of criteria to become a Rep which incorporates the new strategy.
- We have defined responsibilities which every Rep should take on.
- We have defined a list of possible responsibilities that are specialisation-specific (to be confirmed, since the other groups might be working on this as well!)
# Related Issues & Links:

META: [#303](https://github.com/mozilla/participation-org/issues/303)
[Discourse topic](https://discourse.mozilla-community.org/t/working-group-application-process-track/7049)
Meeting notes: [1](https://docs.google.com/document/d/18XUfwBcoKMhokBGI3iu5GBbC6ky4X1X2tCW6RPF_zMo/edit?usp=sharing)
# Roles:

Owner: @thephoenixbird @umeshagarwal
Involved: 
# Required:
- [x] Organize the meeting for next week ([medium] Due: Feb. 26)
- [x] Analyze and identify mozillians interested in joining this track. ([medium] Due: Feb. 26)
- [ ] Process to join the track defined. ([medium] Due: Feb. 26)
- [ ] Description about the application team ([medium] Due: Feb. 26)
- [ ] Experiments details ([medium] Due: Feb. 26)
- [ ] Gather feedback from Reps and Council (all, [medium] Due: Feb. 26)
- [ ] Transition plan defined ([medium] Due: March. 11)
- [ ] Transition/test month starts (all, [medium] Due: March. 14)

**Comment by ThePhoenixBird** [comment]
Meeting notes for 2016, February 23, 12:30 - 01:30 UTC  [notes](https://docs.google.com/document/d/18XUfwBcoKMhokBGI3iu5GBbC6ky4X1X2tCW6RPF_zMo/edit?usp=sharing)

**Comment by umeshagarwal** [comment]
Meeting Notes - 2016, March 12 , 03:30 - 04:30 UTC  [Notes](https://docs.google.com/a/picobudget.com/document/d/18XUfwBcoKMhokBGI3iu5GBbC6ky4X1X2tCW6RPF_zMo/edit?usp=sharing)
