### ISSUE TITLE
H3 MarketPulse: 1) Run education course, synthesize lessons and report on impact from MarketPulse 2) build strategy for multiple experiments to build a market intelligence function in core contributor communities

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#36]
<h1>Project Description</h1>

Previous Heartbeat #14 

Completing the 4 week online course, we will synthesize the lessons we've learned about 
- Education & Training
- Empowering Contributors in Leadership Roles
- Effective Outreach
- Collaborating with Functional area experts to create educational content and learning from them about how that's being used, and how valuable it is . ( Dominik's & Lindsday report )
- Building Community around a specific skillset

We will also have a draft proposal/strategy/theory for  how we can build multiple experiments in support of a market intelligence function in core contributor communities.
 multiple experiments to build a market intelligence function in core contributor communities

1) In person
2) On line
3) Outreach to outside experts

<h1>Primary Goals & Objectives for This Heartbeat </h1>
- [x] Outreach for new target markets to Africa (Senegal, Tunesia) Europe (Fr, Sp, Gr)  and LATAM.
- [ ] Outreach outside of Mozilla community (linkedin for good?)
- [x] Complete Week 2 Course Content  & Hangout
- [x] Complete Week 3 Course Content  & Hangout
- [ ] Complete Week 4 Course Content  & Hangout
- [x] Ensure all participants receive their training material 
- [ ] Build Hand-off Strategy with Dominik, Bob & Akshay
- [x] Build Draft Strategy for building-on/extending Market Research as a core function in contributor communities.
- [ ] Capture lessons & successes
- [ ] Core Function for Whistler

<h1>Milestones</h1>
- [x] Kickoff Meeting
- [x] Standup Meeting
- [x] Wrap-up Meeting
- [x] Course Completion
- [x] Training Material successfully delivered
- [x] Hand-off strategy designed
- [x] Draft for Market Research core function submitted for feedback from key stake holders.
- [x] Arrange time to meet with Dominik and others on this topic in Whistler

<h1>Roles</h1>

Owner: @emmairwin
Member: @geroter

**Comment by emmairwin** [comment]
Week 3 content delivered

**Comment by brianking** [comment]
@emmairwin do you have more details on the data collection for Firefox OS in Africa? I'm talking with TJ and  Akshay tomorrow on a different topic but can bring this up.

**Comment by emmairwin** [comment]
Oh yes, thanks @brianking Here is the discouse on how to get involved:  https://discourse.mozilla-community.org/t/marketpulse-first-steps/2287   Our target markets are shifting a bit from India & Bangladesh to African countries (especially for the competition prices): Senegal, Tunisia, Cameroon, Cote d'Ivoire (to launch mid June).  Peru, Argentina, Chile, Colombia and Uruguay.

**Comment by emmairwin** [comment]
Latest  draft https://docs.google.com/document/d/1GUKD7YlGzKYwQRD55dcbYXutFJ-_otYVsms3wRSOA_U/edit#

**Comment by emmairwin** [comment]
our hashtag is catching on thanks to course participants :)  https://twitter.com/iSukantapal/status/610755539098689537

**Comment by emmairwin** [comment]
Created badges for Firefox OS contribution (3 plus months), and Interviewing Users for Mozilla Course

https://badges.mozilla.org/en-US/badges/badge/Interviewing-Users-for-Mozilla
https://badges.mozilla.org/en-US/badges/badge/Firefox-OS-Price-Collection

They match the steps/color/design of the education portal, so hoping that helps align what you have to accomplish.

Also completed a design for the certification we're awarding with the badge, and a form to  request  it:

https://docs.google.com/forms/d/1JU5lE9z3Qk1uz6CmZrzVfty_j7LVWXvXmByr02N0f0w/viewform

**Comment by emmairwin** [comment]
Course complete, summary sent to community leaders, draft strategy ready for whistler, some foobar things going on with materials (paypal and wikimedia are working on error), and we are still tracking books but otherwise closing .
