### ISSUE TITLE
Interactive Mini Page for Mozilla's Strategic Narrative is In Production

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#361]
## Goal:

Contractor has been hired and is on-track to have it done by EOQ. Preliminary draft is shown at a German events. 
## Success:

Contractor hired and work is underway. 
## Related Issues & Links:
#236
## Roles:

Owner: @lucyeoh 
Involved: 
## Required:
- [ ] Contract signed with engineer/designer for interactive mini site (@lucyeoh, Due: Feb 26th) 
- [ ] Date confirmed for preliminary draft of mini page (@lucyeoh, Due: Feb 26th) 
- [ ] Schedule a German meet-up to run a test of the draft page on (@lucyeo, Due: March 7th )

**Comment by MichaelKohler** [comment]
Intrigued, keep me in the loop! I asked Florian (@fiji-flo) to comment here in case he's interested in hosting the event in Germany.

**Comment by MichaelKohler** [comment]
Challenging thought: Do we need a contractor for this? We have the [Community Creative Team](https://github.com/mozilla/Community-Design/issues/) and [#firefox10](https://github.com/AlexLakatos/chooseindependent/graphs/contributors) showed that we can implement websites on a short notice with volunteers. (Don't be blended by the +/- statistics of mine, mostly merges of PRs)

**Comment by fiji-flo** [comment]
Danke, dass du an mich denkst. Aber leider passt mir die Page gerade nicht
wirklich in den Plan. Den Event allerdings mach ich gern!

Flo

**Comment by fiji-flo** [comment]
I would absolutely host the event in Germany! Thanks mentioning me Michael.
