### ISSUE TITLE
Community Design Challenge is Designed and Ready to Launch

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#362]
## Goal:

To have a final plan for implementation the Community Design Challenge. 
## Success:

All stakeholders are signed-off on a challenge that helps our awesome community designers have an impact on the future of Firefox brand and marketing!
## Related Issues & Links:
#233
## Roles:

Owner: @lucyeoh
Involved: @elioqoshi
## Required:
- [x] Create brief for Rebel Design campaign (@lucyeoh, Due: Feb 24th) 
- [x] Get sign off from Eric & Tim (@lucyeoh, Due: Feb 29th) 
- [x] Finalize brief and get creative assets built for the contest (using community-design of course!) (@lucyeoh, Due: March 10th)
- [x] Strategy for collecting assets is figured out (@lucyeoh Due: March 11th)

**Comment by elioqoshi** [comment]
@LucyeoH can you fill me in regarding this?

**Comment by LucyeoH-zz** [comment]
Up and running! https://github.com/mozilla/Community-Design/issues/39
