### ISSUE TITLE
Brazil community meetup preparations

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#366]
## Goal:

Advance on organization and content creation for Brazil Community meetup
## Success:

At the end of the heartbeat we have approval for the meeting (including budget and goals)
## Related Issues & Links:

[Reference meta issues and past issues] #289 #304
## Roles:

Owner: @deimidis
Involved: @rosanardila @nukeador @francjp @couci @emmairwin @geroter
## Required:
- [ ] End budget proposal (@deimidis, Due: Feb 26th) 
- [ ] End Event proposal (including goals and budget) (@deimidis, Due: Mar 1st) 
- [ ] Generate session list and content (@deimidis @rosanardila @emmairwin, Due: Mar 8th)
- [ ] Get approval for event and budget (@deimidis @rosanardila), Due: Mar 11th)

**Comment by LucyeoH-zz** [comment]
Needs to be updated.
