### ISSUE TITLE
RepsNext working groups start implementing changes

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#367]
## Goal:

Working groups for the RepsNext proposal start the transition process.
## Success:

All working groups start implementing initial actions/changes for transition.
## Related Issues & Links:
- Previous issue: #303
- [Summary doc about working groups](https://docs.google.com/document/d/1EVngjiH1KtZXo0k01VTjImbITprQkL4Q5DJTQyzV2OU/edit#heading=h.p8w6mgsuag1l)
## Roles:
- Owner: @nukeador @rosanardila @shahidfarooqui @rara79 @umeshagarwal @bacharakis @MichaelKohler @thephoenixbird @Faisalaziz
- Involved: Mentors and Reps
## Required:
- [ ] Next steps, drafts, plans are documented (all, [medium], Due: Feb. 28)
- [ ] Conversations and feedback taking place (all, [large], Due: Feb Mar. 6)
- [ ] Some conversations are finished and approved to move ahead (all, [large], Due: Mar. 11)

**Comment by nukeador** [comment]
Updated with next steps

**Comment by nukeador** [comment]
This will be moved to next HB in order to have time for some WGs to start implementing

**Comment by LucyeoH-zz** [comment]
Blocked by survey.
