### ISSUE TITLE
Mexico community agreed on plans and begins to work

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#368]
## Goal:

Mexico community begins to implement their mid term planification
## Success:

At the end of the heartbeat Mexico community had a clear plan to focus their work
## Related Issues & Links:

[Reference meta issues and past issues] #205 #306
## Roles:

Owner: @deimidis
Involved: @rosanardila @nukeador @lasr21 @odin @alex-mayorga
## Required:
- [ ] Create OKRs for 8 goals (@deimidis, @lasr21, @alex-mayorga, Due: Mar 4th) 
- [ ] Approval from Community (@deimidis, Due: Mar 11th)

**Comment by LucyeoH-zz** [comment]
Blocked by community.
