### ISSUE TITLE
Mozilla's communities participate at Flisol event

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#369]
## Goal:

Mozilla's community has a common participation at Flisol this year
## Success:
- Mozilla's communities shared commons goals at Flisol, with same goals and resources
- Mozilla's goals are known by Flisol participants
- Mozilla's communities content/participation is shared on Social networks
## Related Issues & Links:

[Reference meta issues and past issues] #289
## Roles:

Owner: @deimidis
Involved: @francjp @couci
## Required:
- [x] Create the list of communities that will participate this year (@deimidis, Due: Feb 26th) 
- [ ] Decide content that could be shared in all LATAM  (@deimidis, Due: Mar 2nd)
- [ ] Content creation with community members (@deimidis, Due: Mar 5th)
- [ ] Arrange swag and resources that will be shipped (@deimidis @couci, Due: Mar 11th)

**Comment by LucyeoH-zz** [comment]
Needs to be updated.

**Comment by deimidis** [comment]
Moves to next Hearbeat, I will change name to the convention accodingly

**Comment by ioana-chiorean** [comment]
Is this something you @deimidis or @francjp can share more in one of the calls? cc @couci
