### ISSUE TITLE
Peer coaching framework

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#370]
## Goal:

Create a framework where community members could help each other based on coaching themselves
## Success:
- At the end of the Hearbeat, we have a group of people willing to participate 
- We create the first round of content to be shared by this group
## Related Issues & Links:

[Reference meta issues and past issues] #318
## Roles:

Owner: @deimidis
Involved: @emmairwin @rosanardila @nukeador
## Required:
- [x] Post on discourse about the project (@deimidis, [small], Due: Feb 25th)
- [ ] Curriculum content first draft (@deimidis @emmairwin, [medium], Due: Mar 2nd)
- [ ] «Framework proposal» (@deimidis, [medium], Due: Mar 4th)
- [ ] Feedback from stakeholders (@deimidis, [medium], Due: Mar 8th)
- [ ] Final framework to be tested on next heartbeat (@deimidis, [medium], Due: Mar 11th)

**Comment by deimidis** [comment]
I just published the [topic on discourse](https://discourse.mozilla-community.org/t/project-peer-coaching-system-a-proposal/7531). I couldn't advance in the other items, so I will move this to the next heartbeat

**Comment by LucyeoH-zz** [comment]
Didn't have enough time. Move to next heartbeat.

**Comment by ioana-chiorean** [comment]
This is a cool thing! :tada:
