### ISSUE TITLE
Create and set up communication/education activities and infrastructure for Connected Devices

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#371]
## Goal:

Create infrastructure and a set of activities to educate and raise awareness about Connected Devices participation initiatives
## Related Issues & Links:
#321 #346
## Roles:

Owner: @williamq
Involved: @ensowhat, @brianking , @emmairwin , @rosanardila , @marciazikan
## Required:
- [ ] Listed on the Participation Hub (@marciazikan, Due: TBD) 
- [ ] Weekly digest of articles, blogs, resources on IoT (@ensowhat, Due: TBD) 
- [x] Weekly community calls (@ensowhat, Due: TBD) 
- [ ] Stand up a collaboration tool (Mattermost + Wiki or something similar) -- so people can help each other through the learning stages, and so they can share what they learn/inspire each other (@rosanaardila, @williamq, Due: TBD)
- [ ] Create key educational resources -- likely prioritize i) human centered design, ii) getting setup with Raspberry Pi + sensors (@emmairwin, Due: )

**Comment by williamq** [comment]
Re-assigning to Brian. I will play a supporting role.

**Comment by brianking** [comment]
Meeting setup for next week, 18:30 CET.

**Comment by brianking** [comment]
@emmairwin I believe you have already started thinking about the education piece?

**Comment by couci** [comment]
this issue needs to be split into 2

**Comment by brianking** [comment]
Maybe even 3
1. Communication channels - Mostly done
2. Stand up new tool, e.g. Mattermost - To investigate
3. Education resources - TODO, synced up with Emma yesterday

**Comment by brianking** [comment]
No further updates on this currently.

Will move to next milestone.
