### ISSUE TITLE
RepsNext: Update the Mentoring Structure

### ISSUE THREAD

**Issue by shahidfarooqui** [mozilla/participation-org#372]
## Goal:

The goal of this working group is to update the mentorship structure (including educational materials and staff support) to provide more coaching and personal/professional development for Reps, rather than a focus on bureaucratic tasks. We will also try to create ways to recognize the impact that Reps are having ranging from a recognition culture to LinkedIn recommendations. The another important goal of this working group is to introduce a 1 year term to all roles within Reps. After 1 year all different roles need to be evaluated and reconfirmed.
## Success:

 Revamping the mentor-ship structure (including educational materials and staff support) to provide more coaching and personal/professional development for Reps.
## Related Issues & Links:

[Discourse topic](https://discourse.mozilla-community.org/t/working-groups-mentoring/7048)
Meeting Notes: 
[Track details docs](https://docs.google.com/document/d/1SYLwRZOmcjcbdFAVFAqfIasW1u6lz5zYnAlnCct3wYs/edit)
## Roles:

Owner: @shahidfarooqui
Involved: @ariestiyansyah @kelimuttu @Christos @shihan.viswa @ariestiyansyah.rizky @mpbonillap @ping2ayan @anconpaul1 @avikpal.me @anupkumarmishra29 @ahsan.net @dvigneshwer @emmairwin
## Required:
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by RizRiyz** [comment]
@ariestiyansyah and @ariestiyansyah.rizky is one person.

**Comment by nukeador** [comment]
Hey, did you already meet for this? Can we get the gdoc public to read?

Thanks!

**Comment by shahidfarooqui** [comment]
Hi Ruben,

No we could not meet as of now.

Based on doodle input, I scheduled the meeting couple of time but
unfortunately no one turned up.
I have to schedule the meeting once more. I will be doing this next week
(possibly on Monday or Tuesday)

Thanks & Regards

Shahid

**Comment by shahidfarooqui** [comment]
Dear All

Since our previous meeting could not happen due to some unavoidable circumstances, you are requested to fill out following doodle option to schedule a meeting.

http://doodle.com/poll/cem4e6cre3tx482b

Thanks & Regards

Shahid

**Comment by anistuhin** [comment]
Open for anyone to join the meeting?? I am a ReMo.

**Comment by shahidfarooqui** [comment]
Hi Anis,

Anyone can join in the meeting.

**Comment by anistuhin** [comment]
Hi, where are we with this?? Any update??
