### ISSUE TITLE
RepsNext: Community Leadership Track

### ISSUE THREAD

**Issue by rara79** [mozilla/participation-org#374]
## Goal:

Create a specialization track for Community Leadership, for Reps interested in community building and organizing, who are interested in growing their leadership skills and who want more support for building and organizing Mozilla communities around the world.

Reps specialized in Leadership are Reps that want to focus on community building and mobilizing as their main area of contribution. They focus on building and supporting local communities, inspiring and recruiting new Mozillians and mentoring future Reps.
## Success:

We have a solid plan of what will Community Leadership track look like, and documented.
## Related Issues & Links:
- META: #303 
- [Discourse topic](https://discourse.mozilla-community.org/t/working-group-community-leadership-track/7033)
- Meeting notes: [1](https://docs.google.com/document/d/15zArTb842Aev6bZ2DAWRvaiaaNTO6abYc0tuY9u5Qn4/edit?usp=sharing) 
- [Community survey questions](https://docs.google.com/document/d/15GK_FTIPLTupf06ONdxH8szhNGiHT7HJeH3dTeWNxiQ/edit?usp=sharing)
## Roles:

Owner: @rara79
Involved: @Mte90 @bobreyes @mahayalamkhan @aminezaafouri @ganesh @emmairwin @rosanardila 
## Required:
- [x] Prepare a survey with all the information because we have to ask to every community and analyse that data to improve the leadership in that community (all, [medium] Due: Feb 19th) 
- [ ] Finding the challenges of various communities by asking the community leaders to share the challenges they encounter, including onboarding and recruiting new Mozillians → open a Discourse topic
  (@rara, [medium] Due: Feb 26th) 
- [x] Organize a follow up call in the same time next week (@rara, [small] Due: Feb 23rd)
- [x] Join the Meta track to create community leadership survey (@Mte90, [medium] Due: Mar 1st)
- [ ] Checking the community survey from the end of last year (@rosanardila, [medium] Due: Mar 1st) 
- [ ] Finalize survey questions in the google form format and send it through all communication channels (mailing lists, Reps call, telegram groups, discourse topic, github, etc) (all, [medium] Due: Mar 4th) 
- [ ] Finding a way to define what skills and what responsibilities a Rep in this track should have and from there finding a better name for the track (@rosanaardila, [medium] Due: Mar 1st)
- [ ] Documenting the leadership from other communities (create a community leadership guidelines) (blocked before survey, [medium] Due: Mar 11th)
- [ ] Define the bureaucratic/blocking tasks that can help the Reps to organize the event (blocked before survey, [medium] Due: Mar 18th)

**Comment by jgmac1106** [comment]
I don't know how big the rep program is but in terms of your survey design
all of your questions are short answer response.

Depending on your sampke size this can make analysis very labor intensive.

While not as rich in data you may want to ask likert questions that get at
opinion (how strongly you feel on scale 1-4 or 5), self-efficacy (on scale
how much do you believe in your ability to... ), frequency (how often)

Questions like these can be used in pre and post measures. Results can be
made into pretty pictures funders love.

I would include 2-3 open ended questions at the most.

Save the other questions for hosted Twitter chats Telegram feeds, or
community calls.

You would still get the data but it would be rooted in your teaching and
you could set it aside for later analysis.

Even the most rudimentary content analysis takes a lot of time and
resources.

**Comment by Mte90** [comment]
Simple question are easy to use for elaborate the next steps of the working group.
We have to listen the feelings of the reps to continue the work of the working groups.

**Comment by jgmac1106** [comment]
+1. Apologize if I misinterpreted the goal of the reps survey.

**Comment by LucyeoH-zz** [comment]
Move to next quarter.
