### ISSUE TITLE
Groups on mozillians.org can be edited efficiently

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/participation-org#375]
## Goal:

Refactor groups edit (starting from NDA functionality) to enable better handling of groups
## Success:

Groups on mozillians.org can be edited efficiently
## Related Issues & Links:

https://bugzilla.mozilla.org/show_bug.cgi?id=1243774
## Roles:

Owner: @ppapadeas
Involved: @mozilla/participation-infrastructure 
## Required:
- [x] Deliver front-end mockups (@comzeradd, Due: Feb 24th)
- [x] Code front-end forms (@akatsoulas, Due: Feb 29th) 
- [x] Code communications subsystem and refactor emails (@johngian, Due: Mar 4th) 
- [x] QA and delivery (@akatsoulas @johngian , Due: Mar 11th)

**Comment by LucyeoH-zz** [comment]
Partially blocked by security push on other project.

**Comment by ppapadeas** [comment]
Delivered in production!
