### ISSUE TITLE
Organize Ari's meeting with the French community in Paris

### ISSUE THREAD

**Issue by ensowhat** [mozilla/participation-org#377]
## Goal:

Let Ari and the community exchange about the future of Connected Devices. Create dialogue. Show the community is active.
## Success:

Smooth organization and more than 20 contributors.
## Roles:

Owner: @ensowhat
Involved: @julienw @dscravag 
## Required:
- [x] Validate the general program (@ensowhat, Due: Feb 26th) 
- [x] Communicate widely and organize the subscriptions to the event (@ensowhat, Due: Feb 26th) 
- [x] Host and run the event (@julienw @ensowhat, Due: Mar 3rd)

**Comment by brianking** [comment]
Is there anything to demo when he is there ... would be cool to have something to show.

**Comment by brianking** [comment]
Is there anything to demo when he is there ... would be cool to have something to show.

**Comment by ensowhat** [comment]
Quick report:
Around 32 people participate.
The community was happy with the way Ari was honest and direct in his communication and Ari was pleasantly surprised with the community attention, enthusiasm and ideas. On leaving the event he said it had a positive impact and it reinforced his idea that the CD team and the community should work together.

During the discussion, the idea of having a Mentoring Program with regular meeting to help with contributors projects emerged. Idea that we discussed with @mikehenrty @rosanardila @brianking and @pdolanjski today, so that's perfect.
