### ISSUE TITLE
H3 Implement identified Communication Plan P1s for the Participation Team

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#38]
<h1>Project Description</h1>

Previous Heartbeat #13

Etherpad: https://participation.etherpad.mozilla.org/comms

By the end of June, everyone who cares  about participation in Mozilla knows what the participation team has  been up to (plans, successes, failures, lessons, etc), has seen  opportunities to have their ideas shape participation moving forward,  and has clarity on the actions they can take that matter to Mozilla.
# Primary Goals/Objectives - Success Measures

Start communicating regularly what we're up to & implement p1's

<h1>Primary Goals & Objectives for This Heartbeat </h1>
- [ ] Setup Twitter, Blog & Planet 
- [ ] Content Goals  - 3 launching articles, 5 team articles 10 total including outside teams
- [ ]  Whistler Outreach

<h1>Milestones</h1>

Week 1 = June 5
Week 2 =  June 13
Week 3  = June 19
- [x] Kickoff Meeting
- [x] Standup Meeting
- [ ] Wrap-up Meeting
- [x] Week 1 Request Blog @nukeador 
- [x]  Week 1 Brainstorm 3 articles to publish on launch @emmairwin @LucyeoH 
- [x] Week 1 Request a planet, ask infra, community it. @nukeador 
- [ ] Week 1 Find 8 feeds to add to the beginning form team, at least 3 from outside team.
- [x] Find presenters and run participation call on June 11th @emmairwin @lucyeoh
  - [x] Lucy to contact Science Lab (Due Monday June 8th EOD) 
  - [x] Emma to contact Sumanth (Due Monday June 8th EOD) 
  - [x] Lucy to update agenda and send reminder email on CBT List(Due Wednesday  June 10th EOD) 
- [x] @nukeador  to create discourse topic & poll re: new formats for Participation Call  (Due Tues June 9th) 
- [x] Lucy to distribute discourse topic & poll (Due Wed June 10th)  
- [x] Lucy to feel out blog.mozilla.org/community (Due Wed June 10 EOD) 
- [x]  Agree on blog posts and timeline (EOD Thur June 11)
- [ ] Blog: Participation Team - Q2 Goals, and why we chose them ( @nukeador Due Friday July 19th)
- [ ] Blog: What the Participation Team is doing at Whistler ( @lucyeoh Due Friday July 19th) 
- [x] Blog:And here's what we're seeing as a result of the Participation Lab  ( 3 themes and any other leanings)  (Emma)
- [x] Week 2 Create Twitter account (automate)
- [x] Week 2 Create Twitter account (automate), publish first articles, planet pulshes
- [x] Week 2 Brainstorm Outreach Whistler
- [ ] Week 3 : Do wider outreach email

<h1>Roles</h1>

Owner: @emmairwin , @nukeador 
Member: @LucyeoH

**Comment by LucyeoH-zz** [comment]
Agenda for this week's meeting: https://participation.etherpad.mozilla.org/participation-call-june-11-2015

**Comment by LucyeoH-zz** [comment]
@emmairwin @nukeador Science Lab is in!

**Comment by nukeador** [comment]
So blog is being blocked right now, I'm trying to get an answer from Mozilla IT about when would be possible to have it ready since last week:

https://bugzilla.mozilla.org/show_bug.cgi?id=1171126

**Comment by nukeador** [comment]
It seems we need approval from PR to open a blog. Waiting more next steps.

**Comment by emmairwin** [comment]
Sumanth  will attend the call

**Comment by emmairwin** [comment]
Brainstorm of blog posts 
1. Participation and Evangelism - How marketing and participation work together with 3 examples (lucy) 
2. Participation and Training - Showcase 3 examples of participation and training (emma) 
3. Participation and Research - How community can play a part in collecting data for research 
4.  Recap

**Comment by emmairwin** [comment]
call scheduled for tomorrow (checkin/standup)

**Comment by LucyeoH-zz** [comment]
Re: Getting us permissions for the Community Blog. 

I got in touch with Janet Swisher. Apparently David Boswell used to own the blog but no one owns it now. I filed a Bugzilla request to get permissions  [1173460](https://bugzilla.mozilla.org/show_bug.cgi?id=1173460) to access. There shouldn't a problem with us posting once we have access.

**Comment by nukeador** [comment]
Planet is now ready: http://planet.mozilla.org/participation/
Blog, we'll use the community one under participation category: http://blog.mozilla.org/community/category/participation/

**Comment by nukeador** [comment]
Call for people blogging about participation: https://discourse.mozilla-community.org/t/do-you-blog-about-participation-at-mozilla-we-want-to-know/2318

**Comment by emmairwin** [comment]
reminder of these due this week @LucyeoH @nukeador ,

Blog: Participation Team - Q2 Goals, and why we chose them  (Ruben)
Blog: Participaton Team in Whistler( Lucy )
