### ISSUE TITLE
Upgrade mozillians.org to django 1.8.x

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/participation-org#381]
## Goal:

Fix security issues on django on mozillians.org
## Success:

Upgrade mozillians.org to djnago 1.8.x
## Related Issues & Links:

https://bugzilla.mozilla.org/show_bug.cgi?id=1243710
## Roles:

Owner: @ppapadeas
Involved: @mozilla/participation-infrastructure 
## Required:
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1243711
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1243714
- [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1252078

**Comment by LucyeoH-zz** [comment]
Pushing to production on Tuesday.
