### ISSUE TITLE
FSA for Mozilla Hispano

### ISSUE THREAD

**Issue by fayepal** [mozilla/participation-org#385]
## Goal:

Customize the FSA program for the Hispano community.
## Success:

An FSA arm to suit the needs of MozHispano under the FSA Global.
## Related Issues & Links:

https://docs.google.com/document/d/1_V8HBciEfKqGuqXYfu0qTtgHuqMwE47zhtqaeZ4Sh0o/edit
https://public.etherpad-mozilla.org/p/localization_list_for_fsa_hispano
## Roles:

Owner: Carlos El Halabi w/ Hispano community members, FSA E-board
Involved: FSA RALs
## Required:
- [ ] Form a group of Mozillians from the Hispano community to focus on this (Carlos, Due: March 26th) 
- [ ] Complete list of things to localize (FSA Team, Due: March 26th) 
- [ ] Work with Mozilla employees in localizing website, sign-up form and onboarding e-mails (FSA Eboard, Due: April 2nd) 
- [ ] Localize content (MozHispano, Due: May 28th) 
- [ ] Launch FSA recruitment campaign for Moz Hispano (MozHispano, Due: Sept. 2016)

**Comment by hellokarthic** [comment]
https://drive.google.com/folderview?id=0B84D7PhWR2flWnYxOFJkZ0ZVdk0&usp=sharing CLT modules
Newsletter should also be localized

**Comment by carloselhalabi** [comment]
Thanks for the suggestion @hellokarthic, it has been added to the list. Should the[ FSA project blog](https://blog.mozilla.org/studentambassadors/) be localized too?

**Comment by carloselhalabi** [comment]
Why was this closed @LucyeoH ?

**Comment by bacharakis** [comment]
Hi @carloselhalabi and apologies for the inconvenience. 
I believe Lucy closed this because it should be included in the broader feedback we currently gathering for reinventing Mozilla on campus!

Cheers
-Christos
