### ISSUE TITLE
Document and Debrief experiments at Open Source Events

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#393]
## Goal:

Create a document with activities to perform at Open Source events, where Mozilla has presence through a booth, or only by talks
## Success:

Have a clear guidelines of activities that mozillians can do at events, to improve impact and presence.
## Related Issues & Links:
#354
## Roles:

Owner: @francjp
Involved: 
## Required:
- [ ] Review and debrief FOSSASIA experiments (@francjp, Due: Mar 24th) 
- [x] Create a list of activities, and guidelines to follow (@francjp [medium], Due: Mar 28th) 
- [ ] Publish the document on a wiki like an SOP (@francjp, [medium] Due: Mar 30th)

**Comment by francjp** [comment]
Draft for activities: https://docs.google.com/document/d/1DsnO6ZZXtsa4zDUZxtscj__OebdysHgW9oF8JaaDOZM/edit?usp=sharing

**Comment by LucyeoH-zz** [comment]
Move to next quarter
