### ISSUE TITLE
Review and improve Events Playbook

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#394]
## Goal:

Improve the Playbook for events, based on the last experiences
## Success:

Have a playbook useful for several events, Campus Campaign, Connected Devices, etc.
## Related Issues & Links:
#339
## Roles:

Owner: @francjp
Involved: 
## Required:
- [x] Review the previous documents (@francjp, Due: Mar 18th) 
- [x] Review the debriefs from last events (@francjp, Due: Mar 22nd) 
- [x] Create a draft for the playbook (@francjp, Due: Mar 28th) 
- [x] Finalize and publish the playbook (@francjp [large], Due: Mar 31st)

**Comment by ioana-chiorean** [comment]
@francjp - will you share about this in the Reps call? I think it would be usefull to. cc @couci

**Comment by francjp** [comment]
Preparing the first draft for the playbook

**Comment by francjp** [comment]
Draft in google doc: https://docs.google.com/document/d/1Me6jN1S1zqRiHNtUttX-fZibuK1-uB_XHQbG4dYhHww/edit?usp=sharing

Will be presented at the Reps Call on March 31st.

**Comment by francjp** [comment]
Draft reviewed and ready to be public. Closing this issue
