### ISSUE TITLE
Mexico community has a plan for the next months

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#399]
## Goal:

Mexico community ends their plans for the coming months
## Success:

Anyone in the community have clear goals for the next months
## Related Issues & Links:

 #368
## Roles:

Owner: @deimidis  
Involved: @alex-mayorga @lasr21
## Required:
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, [small, medium, large], Due: Aug 7th)

**Comment by deimidis** [comment]
We make some advance in the planification, but still not there. There were some advance in WoMoz goals, and update the wiki of the community with information on how to colaborate and participate in the community

**Comment by lasr21** [comment]
Can I reopen this issue for tracking purposes?

**Comment by ioana-chiorean** [comment]
@lasr21 I think creating a new one will be better and u can reference int here this issue.
