### ISSUE TITLE
Mozilla Community Building Ahmedabad, Gujarat

### ISSUE THREAD

**Issue by nomadicmehul** [mozilla/participation-org#407]
Goal: 
Meet Teach and hang together to build a better community, discuss all the things which we are doing and planing our future activities.
## Reps Event:

https://reps.mozilla.org/e/mozilla-community-pop-up-meet-ahmedabad/
## Agenda:
1. Discuss and Planning Future events 
2. Event proposal, formats & its structure design for more improvement 
3. Community Design, Structure & Roles for FSA's 
4. Planning for Take Back The Web campaign
5. Feedback 
## Related Issues & Links:

Takebacktheweb Campaign:
https://takebacktheweb.mozilla.community/
- Way to bring privacy and encryption concerns to the common people
- Awareness about local issues
- This is a part of the campus campaign
- Campus Team:
    The team organizes events
- Local coach:
    Mentors the teams and interacts with the Mozilla staff
## Pre Checklist:
- [x] [EtherPad Agenda](https://public.etherpad-mozilla.org/p/Mozilla_Community_POP-UP_Meet_Ahmedabad)

**Comment by LucyeoH-zz** [comment]
Hey @rowdymehul please move this to the Reps Repo! https://github.com/mozilla/reps

**Comment by nomadicmehul** [comment]
Okay. Thank you.

_Regards,_
_Mehul Patel._

_Mozilla Reps https://reps.mozilla.org/u/rowdymehul/_

_Regional Ambassador Lead - Mozilla_
_@rowdymehul_ https://twitter.com/rowdymehul

_Learn, Teach & Innovate! :)_
