### ISSUE TITLE
Next three community gatherings are decided and framework plan has started

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#411]
## Objective Goal:

Next three gatherings are decided and framework plan has started
- Responsible: @emmairwin @francjp @deimidis @nukeador
- Accountable: @nukeador
- Supporter: @couci 
- Consulted: @rosanardila @geroter
- Informed: 

Supporting: [O4KR3](https://docs.google.com/spreadsheets/d/14v_8OajXaaqxdBQZp1w5-fyj3OaotB0Ra6Y-QJ8vtoM/edit?pref=2&pli=1#gid=198884355) _"Plan for 5 committed and systematized leadership/functional institutes is delivered"_
## Sub-Goal Success:
- [ ] Three next community gatherings decided (R: @nukeador @deimidis)
- [x] Initial work on framework/needs started (R: @emmairwin S: @nukeador @deimidis @francjp)
- [x] Planning for first experiment is done (R: @deimidis S: @nukeador @francjp)
## Related Issues & Links:

[Community gatherings repo](https://github.com/mozilla/Community-Gatherings/issues/)

**Comment by LucyeoH-zz** [comment]
@nukeador I think it would make sense to have a sub-goal around London here for this quarter...

**Comment by nukeador** [comment]
@LucyeoH you are right, I'll check with @emmairwin and @francjp to see what's expected in this first HB around London and add that here.

**Comment by emmairwin** [comment]
@nukeador  Can you explain my role here?  It's not clear to me.

**Comment by emmairwin** [comment]
Will self-assign role of content creation and learning solutions.

**Comment by nukeador** [comment]
Note: We don't need to create any content, this is very important. We need to decide the needs and figure out which _existing_ learning experiences we want to deliver.

@emmairwin your role here is to figure out this and work with @deimidis and @francjp to pack it into a systematized framework we can re-use for future gatherings.

**Comment by geroter** [comment]
Let me jump in.

For me, a systematized framework isn't necessarily just a process for
gathering feedback and then planning. Instead it's a common narrative and
structure and content that we can apply/adapt to different groups, but
building common skills and language and participation areas.

**Comment by nukeador** [comment]
@geroter yeah, maybe wording is complicated here. When I talk about framework I talk about this common process/plan/structure we can apply to more groups in the future.

**Comment by geroter** [comment]
Great! Just clarifying!

**Comment by nukeador** [comment]
So we had out kick off meeting today and clarified next steps and accountability. People responsible of each task will lead each front and mobilize others to get things done.

Decision on the next community gatherings should be consulted with the rest of the participation team. We will be using https://github.com/mozilla/Community-Gatherings/issues/ to project managing the small tasks.

**Comment by nukeador** [comment]
We have started the planning for the first experiment that we will end early next week, this is the foundation of the framework/guide for the next ones.

Next ones are still waiting for team feedback.

**Comment by nukeador** [comment]
We will continue in #421
