### ISSUE TITLE
The NDA mechanism is running in Exact Target and we have identified a plan for getting a shareable version of the mission and vision 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#413]
## Objective Goal:

R: @lucyeoh 
A: @lucyeoh  @ppapadeas 
C: @geroter
I:
## Sub-Goal Success:
- [ ] NDA is working in Exact Target and has had at least 5 comms sent through it (@lucyeoh) 
- [ ] We have identified a plan for identifying a shareable version of the mission/vision (@lucyeoh) 
## Related Issues & Links:

[Reference meta issues and past issues] #

**Comment by LucyeoH** [comment]
- Delayed by technical blockers might be able to get it in by EOD but otherwise going to next week. 
- Have lots of info but don't have sign-off to share or something concrete to share
