### ISSUE TITLE
Story board about Reps is delivered and research phase takes place

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#419]
## Objective Goal:

Story board about Reps is delivered and research phase takes place
- Responsible: @couci @nukeador Council
- Accountable: @rosanardila 
- Supporter: @deimidis 
- Consulted: @rosanardila
- Informed: Reps

Supporting: [O4KR2](https://docs.google.com/spreadsheets/d/14v_8OajXaaqxdBQZp1w5-fyj3OaotB0Ra6Y-QJ8vtoM/edit?pref=2&pli=1#gid=198884355) _"Reps program successfuly implements alignement, mentoring and resources changes with broad agreement"_
## Sub-Goal Success:
- [x] :white_check_mark: Alignment working group is fully implemented (R: @couci A: @rosana C: I:)
- [ ] :warning: New mentors are on boarded and training materials are ready (R: @deimidis @umeshagarwal A: C: I: ) 
- [ ] :warning: Review Team is decided and planning for start operating ready (R: @couci A: @nukeador C: I: ) 
- [ ] :red_circle: ~~Storyboard about where the Program is ready for London (R: @rosanardila A: C: I: )~~ (will happen in London)
- [x] :white_check_mark: Research phase (data and council 1:1s) is done (R: @couci @nukeador A: C: I: ) 
- [x] :white_check_mark: Preparation for London sessions is finished (R: @rosana A: C: I: ) 
## Related Issues & Links:

Previous HB: #409
- [Mozilla Reps repo](https://github.com/mozilla/Reps/issues/)

_:white_check_mark: On track :warning: At risk :red_circle: Major change or not going to happen_

**Comment by nukeador** [comment]
Updating the task reflecting the actual subgoals

**Comment by rosanardila** [comment]
We have included an exercise for London where we will collectively create a storyboard. So moving that to London. We're prepared and have a facilitator for that process.

**Comment by nukeador** [comment]
Moving to #429
