### ISSUE TITLE
Leadership toolkit is delivered together with initial unification of the group

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#420]
## Objective Goal:

Leadership toolkit is delivered together with initial unification of the group
- Responsible: @emmairwin @deimidis @nukeador
- Accountable: @nukeador
- Supporter: @couci
- Consulted:
- Informed: 

Supporting: [O4KR1](https://docs.google.com/spreadsheets/d/14v_8OajXaaqxdBQZp1w5-fyj3OaotB0Ra6Y-QJ8vtoM/edit?pref=2&pli=1#gid=198884355) _"Core leaders group is unified, trained and aligned with our impact-focus initiatives"_
## Sub-Goal Success:
- [ ] :white_check_mark: **Leaders**: Unified group decision is done and planning for comms is ready (R: @nukeador @emmairwin A: C: I: ) 
- [ ]   :warning: **Curriculum/skill building**: Finish prioritization of skills + delivering first version of the leadership toolking (resources) (R: @emmairwin A: C:  I: )
- [ ] :white_check_mark: **Coaching**: Training guide is delivered, planning for mentor training is clear (R: @deimidis A: C: I: ) 
- [x] :white_check_mark: **Initiatives**: "Weekly updates continue + more clarity on initiatives is delivered. (R: @nukeador A: C: I: ) 
- [ ]  :red_circle: ~~Initiatives: Light/initial support for two initiatives has started (R: @nukeador A: C: I: )~~
## Related Issues & Links:

Previous HB #410 

_:white_check_mark: On track :warning: At risk :red_circle: Major change or not going to happen_

**Comment by LucyeoH-zz** [comment]
"Coaching: Training is defined and new mentors are trained" clarify -> "5 new mentors have undergone initial training" - Is that the right number?

**Comment by nukeador** [comment]
@LucyeoH Probably yes, we talked about a minimum of 5 mentors. @deimidis ?

**Comment by nukeador** [comment]
Updating based on the current status.

**Comment by nukeador** [comment]
Most of this didn't happen, moving to #428
