### ISSUE TITLE
Learnings from first gathering are used as foundation for gathering guideline

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#421]
## Objective Goal:

Learning from first gathering are used as foundation for gathering guideline
- Responsible: @emmairwin @francjp @deimidis @nukeador
- Accountable: @nukeador
- Supporter: @couci 
- Consulted: @rosanardila @geroter
- Informed: 

Supporting: [O4KR3](https://docs.google.com/spreadsheets/d/14v_8OajXaaqxdBQZp1w5-fyj3OaotB0Ra6Y-QJ8vtoM/edit?pref=2&pli=1#gid=198884355) _"Plan for 5 committed and systematized leadership/functional institutes is delivered"_
## Sub-Goal Success:
- [x] :white_check_mark: First learnings from Brazil are delivered (R: @deimidis @nukeador A: C: @emmairwin I: ) 
- [x] :white_check_mark: Resources for next gatherings are decided (R: @deimidis @nukeador A: @geroter C: Participation Team I: ) 
- [x] :warning: Volunteer participants have received coaching for London (R: @emmairwin A: C: I: ) 
- [ ] :white_check_mark: Previous experiences (playbook) + Brazil learnings are merged into a standard guide (R: @deimidis @francjp A: @nukeador C: @rosanardila I:)
## Related Issues & Links:

Previous HB #411 
[Community gatherings repo](https://github.com/mozilla/Community-Gatherings/issues/)

_:white_check_mark: On track :warning: At risk :red_circle: Major change or not going to happen_

**Comment by emmairwin** [comment]
Playbook from Leadership that can be forked, or built on   https://docs.google.com/document/u/1/d/1nxnm_LInRCoS87AIlgxcx8pJV9ukt2Ihx1WkxmElDkA/edit

**Comment by emmairwin** [comment]
leadership summit content playbook - to fork or build on https://docs.google.com/document/u/1/d/1nxnm_LInRCoS87AIlgxcx8pJV9ukt2Ihx1WkxmElDkA/edit

**Comment by nukeador** [comment]
- Coaching is on going effort.
- We are gathering all feedback from Brazil.
- We are merging diverse playbooks with Brazil learnings to have a guide for next gatherings.

**Comment by francjp** [comment]
Draft of the Community Gatherings Playbook (alpha version):
https://docs.google.com/a/mozilla.com/document/d/12tuiXMLMUpdq1cm-7nwhpXwSJZlk6MfWGM3QEzIqynQ/edit?usp=sharing

**Comment by nukeador** [comment]
Continuing in #430
