### ISSUE TITLE
The Mozilla Berlin Community has a plan

### ISSUE THREAD

**Issue by ensowhat** [mozilla/participation-org#427]
## Objective Goal:

A community planing document is drafted, including:
- Event and activities agenda for the next 5 months (June to October), with clear objectives;
- Useful communication channels and infrastructure.

R: @ensowhat
A: @brianking @geroter 
C: Mozillians in Berlin
I:
### Communication channels
- https://lists.mozilla.org/listinfo/community-berlin
- Mozilla Berlin group on Telegram (invite only?)
- http://mozilla.berlin/
- http://www.meetup.com/Berlin-Mozilla-Meetup/
- http://www.eventbrite.com/o/mozilla-berlin-10663488541
- https://mozillians.org/en-US/group/berlin/
- facebook group ?
- twitter account ?
### Upcoming events
- Mozilla Tech Weekend (2-3 Jul) https://public.etherpad-mozilla.org/p/MozillaTechWeekend_2016-07-02
- View Source Conference (12-14 Sept) https://viewsourceconf.org/berlin-2016/
- Codemotion Berlin (24-25 Oct) http://berlin2016.codemotionworld.com/
## Sub-Goal Success:
- [x] List existing communication channels and infra (R: @ensowhat A: C: Mozillians in Berlin I: @brianking @geroter ) 
- [ ] List needed communication channels and infra (R: @ensowhat Mozillians in Berlin A: @brianking @geroter C: I: ) 
- [x] Plan and organize community events (R: @ensowhat Mozillians in Berlin A: C: @brianking @geroter I: ) 
- [x] Plan and organize participation events (R: @ensowhat Mozillians in Berlin A: @brianking @geroter C: I: )
## Related Issues & Links:

[Reference meta issues and past issues] #

**Comment by ensowhat** [comment]
Report with status and proposals to be send today.

**Comment by ensowhat** [comment]
## Communication Channels

### Talk and get in touch
- Orga team Telegram group (invitation only)
- https://lists.mozilla.org/listinfo/community-berlin
- https://mozillians.org/en-US/group/berlin/

I recommend a public instant messaging channel, accessible to anybody to ask questions and get in touch easily.

### Information
- The blog http://mozilla.berlin/

Recommendations: Ask Mario for access. Make time in meetings to choose updates about the Mozilla Berlin Community activities to publish here and on the …

### Social Networks

Ask Mario about credentials for all these.
- https://twitter.com/mozillaberlin
- https://www.facebook.com/Mozilla-Berlin-417762471753823/

See also:
- https://twitter.com/mozillade
- https://twitter.com/mozilla_deutsch
- https://www.facebook.com/mozilla.de/
- http://www.meetup.com/Rust-Berlin/
- https://twitter.com/rustberlin

### Event communication/organization:
- http://www.meetup.com/Berlin-Mozilla-Meetup/
- For other events: http://www.eventbrite.com/o/mozilla-berlin-10663488541

## Upcoming events

### Mozilla Berlin Community organized events
- Mozilla Tech Weekend: IoT Edition (2-3 Jul)
  https://public.etherpad-mozilla.org/p/MozillaTechWeekend_2016-07-02
- Take advantage of the tech scene excitement in Berlin in September to organize an event around the 17 Sept? 

Recommendation : define areas where we are the most excited to build, project we want to launch and/or contribute to and plan events accordingly. Get closer to our friend organizations, hackerspaces, tech companies in Berlin to work and organize with them.

### Mozilla Berlin Community to participate to …
- View Source Conference (12-14 Sept) https://viewsourceconf.org/berlin-2016/
- Codemotion Berlin (24-25 Oct) http://berlin2016.codemotionworld.com/
  Being organized with Francisco Picolini

Recommendations: Have an etherpad (or something else) to drop interesting links and do a regular review in meeting.

**Comment by brianking** [comment]
Next Steps:
- Mozilla Tech Weekend: IoT Edition (2-3 Jul) https://public.etherpad-mozilla.org/p/MozillaTechWeekend_2016-07-02
- Define roles for next 3 months
- Write out plan for next 3 months for the Berlin community.

For another heartbeat.

**Comment by brianking** [comment]
Continued in issue #438.
