### ISSUE TITLE
Core leaders comms are underway, toolkit for coaching and leadership are delivered

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#428]
## Objective Goal:

Core leaders comms are underway, toolkit for coaching and leadership are delivered
- Responsible: @nukeador @deimidis
- Accountable: @nukeador
- Supporter: @verenanz1, @xellpher
- Consulted: @geroter 
- Informed: 

Supporting: [O4KR1](https://docs.google.com/spreadsheets/d/14v_8OajXaaqxdBQZp1w5-fyj3OaotB0Ra6Y-QJ8vtoM/edit?pref=2&pli=1#gid=198884355) _"Core leaders group is unified, trained and aligned with our impact-focus initiatives"_
## Sub-Goal Success:
- [x] Reach out to potential core leaders in a unified channel is done. (R: @nukeador Date: June 24th) 
- [x] Coaching guide and plan is ready  (R: @deimidis C: @nukeador @xellpher @verenanz1 Date: June 24th) 
- [ ] Leadership toolkit draft is ready (R: @nukeador S: @verenanz1, @xellpher C: @geroter Date: July 7th) 
- [x] Clarity on which ones are focus initiatives for us and how to get involved is developed and delivered (this will provide content to coaching and Reps activity campaign) (R: @nukeador S: @brianking C: @geroter Date: July 1st) 
- [ ] Having 9-10 mentors trained in coaching (R: @deimidis S: @nukeador Date: July 7th)
- [ ] Mentors start their first coaching relationship (R: @deimidis Date: July 8th)
## Related Issues & Links:

Previous HB #420

**Comment by verenanz1** [comment]
Will look forward to seeing a list of the skills, behaviours - I will be able to give feedback by next week.

**Comment by rosanardila** [comment]
I'm wondering if the "RepsNext" pilot and the activity campaign should be in this HB or linked to this

**Comment by nukeador** [comment]
@rosanardila The activity campaign is what we call focus activities and the rest of RepsNext is under the Reps issue #429

**Comment by nukeador** [comment]
Comms about participation leaders and reach out is now done

https://discourse.mozilla-community.org/t/participation-leaders-cohort-moving-forward/9409

**Comment by nukeador** [comment]
We have an initial set of focus initiatives, we are currently working with functional areas to define specific activities.

https://discourse.mozilla-community.org/t/defining-focus-activities/9474/

**Comment by nukeador** [comment]
Leadership toolkit is on track

https://discourse.mozilla-community.org/t/leadership-toolkit-update/9564/

**Comment by nukeador** [comment]
Coaching plan is ready is about the be implemented

https://discourse.mozilla-community.org/t/coach-framework-for-participation-leaders/9611/
