### ISSUE TITLE
Reps review team start operating, new mentors are trained and comm plan is implemented

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#429]
## Objective Goal:

Reps review team start operating, new mentors are trained and comm plan is implemented.
- Responsible: @couci @nukeador Council
- Accountable: @rosanardila 
- Supporter: @deimidis 
- Consulted: @rosanardila
- Informed: Reps

Supporting: [O4KR2](https://docs.google.com/spreadsheets/d/14v_8OajXaaqxdBQZp1w5-fyj3OaotB0Ra6Y-QJ8vtoM/edit?pref=2&pli=1#gid=198884355) _"Reps program successfuly implements alignement, mentoring and resources changes with broad agreement"_
## Sub-Goal Success:
- [x] Review team in place (R: @couci Faisal Date: July 7th)
- [x] New mentors on boarded (@deimidis Umesh Date: July 1st) (depends on coaching being done on #428)
- [ ] Communication and engagement plan for RepsNext implemented (R: @rosanardila @MichaelKohler)
- [ ] Provide clarity on which are the focus initiatives and how to get involved through an activity campaign (R: @nukeador S: @brianking C: @geroter Date: July 1st) (work is done in #428)
## Related Issues & Links:

Previous HB: #419
- [Mozilla Reps repo](https://github.com/mozilla/Reps/issues/)

**Comment by geroter** [comment]
3 comments:
1) Clarity on focused initiatives ... a bit vague. Means they are designed programmatically? Or just listed and more design comes later?

2) I think focused initiatives should have myself as Consulted.

3) I also wonder if you could get help in initiative design from @brianking ... based on where the CD work is right now he could have some bandwidth

**Comment by nukeador** [comment]
Added clarification that the work on the initiatives is part of #428 and Reps will use this for an activity campaign.

**Comment by nukeador** [comment]
For focus initiatives, we have an initial set and we are currently working with functional areas to define specific activities. Once that's done we will communicate to Reps and others.

https://discourse.mozilla-community.org/t/defining-focus-activities/9474/

**Comment by couci** [comment]
Review team updates are being tracked here: https://github.com/mozilla/Reps/issues/1

Summary:
- members have been decided
- meeting has been arranged
- announcement to the Reps about members has been made
- Responsibilities have been finalised
- presentation explaining what the Review Team has been made

Next steps:
- Create a transition plan
- Review Team starts operating

**Comment by deimidis** [comment]
Mentors are decided. First Training call will be next Monday July 11th. Guide for the Coaching Training is ready (online and PDF), plus more resources to help the training.

Plan for training and next steps is defined and Council agreed on that
