### ISSUE TITLE
Next gatherings are decided and initial guide delivered

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#430]
## Objective Goal:

Next gatherings are decided and initial guide delivered
- Responsible: @deimidis @francjp
- Accountable: @nukeador
- Supporter: @nukeador
- Consulted: @rosanardila @geroter
- Informed: 

Supporting: [O4KR3](https://docs.google.com/spreadsheets/d/14v_8OajXaaqxdBQZp1w5-fyj3OaotB0Ra6Y-QJ8vtoM/edit?pref=2&pli=1#gid=198884355) _"Plan for 5 committed and systematized leadership/functional institutes is delivered"_
## Sub-Goal Success:
- [x] Proposal for next gatherings this year (R: @nukeador @deimidis C: @rosanardila @geroter  Date: July 1st)
- [ ] Sign-off (R: @geroter @rosanardila Date: July 7th)
- [ ] First version of gathering guide is delivered with focus on user friendly format (content improvement depends on leadership toolkit in #428) (R: @francjp @deimidis C: @nukeador)
## Related Issues & Links:

Previous HB #421 
[Community gatherings repo](https://github.com/mozilla/Community-Gatherings/issues/)

**Comment by nukeador** [comment]
The proposal is ready, waiting for sign-off

**Comment by deimidis** [comment]
We are still reviewing the «friendly» version of the guide. The content is ready, just waiting for reviewing on format to make a second version

**Comment by francjp** [comment]
Friendly version of the logistics here: https://docs.google.com/a/mozilla.com/presentation/d/1NpBh1nrcMmP704gidLle0TXIrEsn5YZLSTNOgh3qh0g/edit?usp=sharing
Needed to be reviewed and aligned with the content part.
