### ISSUE TITLE
Henrik's MozLondon Round-Up and ParSoL Ramp-Up

### ISSUE THREAD

**Issue by hmitsch** [mozilla/participation-org#431]
## Objective Goal:

Follow-up on open points from ParSoL meetings attended at MozLondon

Supporting: [O5](https://docs.google.com/spreadsheets/d/14v_8OajXaaqxdBQZp1w5-fyj3OaotB0Ra6Y-QJ8vtoM/edit?pref=2&pli=1#gid=198884355) "_We have momentum by having collaborated across Mozilla to build a few small pieces of well-designed participation software while building the requirements and foundational pieces needed for 2H_"
## Sub-Goal Success:
- [x] Schedule regular meeting with Hermina (R: @hmitsch)
- [x] Align with George on big picture (R: @hmitsch @geroter)
- [x] Create a sketch of current understanding (R: @hmitsch)
## Related Issues & Links:
#323

**Comment by hmitsch** [comment]
Sub-Goal 1: Done. I am now a regular participant in Hermina's Participations Systems Weekly meetings.
Sub-Goal 2 & 3: At the Participation Strategy Days in Berlin (27/28 JUN 2016) I got the chance to align on the big picture and create a sketch of my current understanding.

**Comment by hmitsch** [comment]
![2016 07 - parsys strategic objectives](https://cloud.githubusercontent.com/assets/869692/16687897/86247560-451b-11e6-8322-4391b4c05f89.png)

**Comment by ioana-chiorean** [comment]
@hmitsch on the slide i see it required NDA - is it ok to be shred here?

**Comment by hmitsch** [comment]
Thanks for catching this @ioana-chiorean. 
The slide is taken from a deck which is certainly not ready to be shared widely. This particular slide I am comfortable with sharing. So let's keep it open. :-)

## 

Henrik Mitsch
