### ISSUE TITLE
A set of CD community experiments are designed for Q3 based on progress at London and evaluation of hypotheses/lessons

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#432]
## Objective Goal: Build a great Connected Devices participation program

A set of CD community experiments are designed for Q3 based on progress at London and evaluation of hypotheses/lessons

R: @geroter, @rosanardila, @brianking, @mikehenrty
A: @geroter
C: connected devices team, innovation team
I: participation team
## Sub-Goal Success:
- [ ] Roll out the "market" research piece for Reps and get data in (R: @rosanardila @geroter A: @geroter C: @nukeador @a-kilroy I: Reps Council)
- [ ] Synthetize lessons from the CD skill building in London (R: @rosanardila @mikehenrty)
## Related Issues & Links:
#414
#423

**Comment by rosanardila** [comment]
added Arielle to be consulted on the market research piece

**Comment by rosanardila** [comment]
Form is created: https://docs.google.com/a/mozilla.com/forms/d/17XmaG1eWBYroXQ1C_o0EQt1aMdu2qebxmkJOGoVQUhQ/viewform
Waiting for some testing to roll out to Reps.

**Comment by brianking** [comment]
Looks good, but the last 3 questions need more clarity.

What are the preferred platforms for IoT in your region?
I'd say not many people know what and IoT 'platform' is

What are popular digital services in your region?
Are we talking about things like Facebook here, or something else?

What hardware is popular in your region?
IoT hardware, or all hardware?

**Comment by hmitsch** [comment]
Following-up on @brianking's feedback:
- @brianking connects the questionnaire to IoT. This probably makes sense as this issue has "CD community experiments" in its name
- To me, the questionnaire is much broader. Do we look for specific connections to the IoT space or to a broader technology space?

If we look for the latter, the question "Type of Organization" might also benefit from an additional option: "Technology meetup"
