### ISSUE TITLE
Reps are in sync with Activity Campaign and Regional coaches

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#440]
## Objective Goal:

Reps are in sync with Activity Campaign and Regional coaches
- Responsible: @nukeador @couci 
- Accountable: @nukeador
- Supporter: @deimidis @brianking 
- Consulted: Council
- Informed: Reps

Supporting: [O2](https://docs.google.com/spreadsheets/d/1pR3DAlS32SB_RVBAM-595t4eXNU9fpWapwupQrQakYE/edit#gid=198884355) _"Reps is the program for most core volunteers where many communities feel their voice represented and influencing the organization, and where mozillians join to be more aligned, grow their skills and be more impactful in mobilizing others."_
## Sub-Goal Success:
- [x] **Regional coaches:** All coaches had an initial training (R: @nukeador S: @Mte90)
- [ ] **Regional coaches:** First meetings with communities happen. (R: @nukeador S: @Mte90)
- [x] **Activity Campaign:** Sync with Council and first comms to all Reps about the campaign and how to get involved (R: @nukeador S: @brianking)
- [x] **Activity Campaign:** Activities and initiatives are added to the portal (R: @nukeador S: @brianking)
- [x] **Activity Campaign:** Reps Q3 OKRs adapted to focus initiatives (R: @nukeador S: @brianking)
- [x] **Get the basics right:** Budget per initiative has been decided (R: @couci S: @nukeador)
## Related Issues & Links:
- [Reps planning repo](https://github.com/mozilla/Reps/issues)

**Comment by couci** [comment]
Budget initiative update: we are currently discussing with initiatives will be funded and what with which budget. This also includes swag requests.

**Comment by couci** [comment]
Reps OKRs: Participation OKRs have been shared with the council and now the council is working on creating their owns with keeping in mind the activity campaign
Sync council with activity campaign: conversation has been initiated on how the council can help, allocate special budget and the participation of the Review Team

**Comment by deimidis** [comment]
First meeting with Regional Coaches will be next week (wwek from August 8th hto Aug 13th)

**Comment by Mte90** [comment]
We also published the list of regional coaches: https://discourse.mozilla-community.org/t/new-reps-regional-coaches-august-2016/10104
