### ISSUE TITLE
Research for a 'Comunity Call Reboot' is completed, with an initial proposal for feedback ready.

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#460]
## Objective Goal:

[List objective & link]

R: @emmairwin
A: @geroter 
C: @LucyeoH 
I:
## Sub-Goal Success:
- [ ] Outreach to past and potential participants of the community managers call (previously Participation call) to gain insights into value and potential value.
- [ ] External to Mozilla, investigate and research how other community manager calls bring value, excitement, engagement.
- [ ] Create an initial proposal for feedback.

**Comment by ioana-chiorean** [comment]
We grew our Reps Call and I have a feeling it became sort of a Participation Call - many non reps attend depending on the topics, we have many external speakers ( non reps program) etc.
Maybe worth consider this point. 
@couci - can you voice this in the Participation Team discussions?

**Comment by couci** [comment]
I don't know exactly what are the discussion going on here @emmairwin might loop me in? I see this is also closed so I am not sure if it's still going on

**Comment by emmairwin** [comment]
Two quick things, 

This would not be a participation call, but rather a Community Manger's call.  
Opened a new issue #462
