### ISSUE TITLE
We have run a first series of D&I focus groups & 1:1 Interviews 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#490]
## Objective Goal: 
Prioritized set of D&I initiatives, informed by research/insights gathering, to run in Q2 [shared with D&I]

### Subgoal 1
We have completed interviews with 10 focus group: one for each of our focus areas, and at least one comprised of only women, and at least 4 in-person for no or low bandwidth audiences, and at least 4 in first-languages other than English.

### Subgoal 2 
30+ of 1:1 interviews with individuals who have expressed interest in D&I, or who are recognized as important in the conversation have been completed(should tap invites)

![Insights Phase](https://cdn-images-1.medium.com/max/800/0*XcOwCBVciy0yvTPL.png)

## Related documents and links 
* [Q1 Project Plan ](https://docs.google.com/document/d/1C5kI1u45BvJwG3uXvYkJvGqBEpJ9wVOBe2nlrSPTEmk/edit#)
* [HB 1 Summary](https://docs.google.com/document/d/1zhGv0UGHHrfSsOW4R2jsaUV4LWJ1-Vvzkl7sTQbOrS0/edit#heading=h.vuafdnmge6cc)
* [Call for Nominations](https://medium.com/@sunnydeveloper/call-for-nominations-d-i-for-participation-focus-groups-67d0ef569d7c)
* [What is Participation Design Anyway - Blog Post](https://medium.com/@sunnydeveloper/what-is-participation-design-anyway-7fc220129053#.32pdjv9mh)
* [Diversity and Inclusion - a Plan for Strategy](https://medium.com/p/77224f32a992/edit)

## Item list:
- [x] Targeted outreach - seeking  voices for Focus Group nominations is completed and results in diverse list of participants for focus groups and 1:1 interviews. (R: @emmairwin I: everyone)
- [x] Through a weekly triage, and scheduling strategy, 8 focus groups have been identified, scheduled and completed - including 2 in a language other than English, 2 'in person' and one comprised of individuals who identify as a gender other than male. (R: @emmairwin @larissashapiro @nasmaahmed)
- [x] We have templated, and documented the non-English interview process so that Regional coaches and other community leaders can also conduct first-language interviews.  (R: @kristiprogri @bee2502 @Psubhashish, C: @emmairwin)
- [x] Outreach to Regional Coaches, Reps & Womoz - to participate, and receive training as interviewers in first-languages other than English has been completed. (R: @emmairwin, @couci, @Psubhashish )

- [x] We have complete 15 1:1 interviews with a individuals identified as having key insights in d&i for participation (staff, volunteers, and outside the project) with **some in-person** , with another 15 scheduled for the next heartbeat. (R: @emmairwin @nasmaahmed , C: @larissashapiro)

## Related Issues
#476

**Comment by emmairwin** [comment]
This Week's (Jan 30) Priorities based on standup.

- [x] Update the [template](https://docs.google.com/document/d/1Y94l4oT2GjqSdj0s3ZuHSmQWwXCC3lcBfsjPBNxurYY/edit#heading=h.vhm1rjnq5v9z) with /best practices we learned from Jeff, especially using Google translate and explaining English words that don't have a specific translation. 
- [x] @bee2502  and @kristiprogri - please find time to discuss your individual goals for first-language.  On Monday we'll use these goals to track progress.  
- [x] @bee2502  is to reach  out to Hindi translators for support.
- [x] @Psubhashish Outreach to Regional Coaches, Reps & Womoz - to participate, and receive training as interviewers in first-languages other than English has been completed (planning to reach out to the RCs, Reps and Womoz this week to discuss)

**Comment by emmairwin** [comment]
[Best practices documen](https://docs.google.com/document/d/1YcuD-BRF_XY-sfsYQWsav54nIcqOq4k50Nwg7yjjsJ4/edit#)t from @bee2502 and @kristiprogri   added to [template](https://docs.google.com/document/d/1Y94l4oT2GjqSdj0s3ZuHSmQWwXCC3lcBfsjPBNxurYY/edit#).

 @bee2502 and @kristiprogri Can you please check the checkbox above with your names on it, when you are happy that these documents are ready to share with others to do first languages as well.  Thank yoU!

(from comment above)

![page-shot-2017-1-30 mozilla community-development](https://cloud.githubusercontent.com/assets/60618/22438871/65f9ded8-e6e2-11e6-964c-a259ad56669c.png)

**Comment by emmairwin** [comment]
Goal was 30 1:1 interviews - actual:   29   !     with another   30 scheduled until end of month.
Goal was 8 Focus Group interviews  - Actual:   5  but with 10 scheduled for each of next two weeks.   It should be noted that people were given the option to attend focus group (including all women) or 1:1 largely people have chosen 1:1  but we will encourage focus group participation ongoing.  We have run interviews in Hindi, Albanian language, with others planned for French and Spanish.

Both focus group interviews and 1:1 have been done in Vidyo, Hangouts, Skype and a few in Telegram depending on bandwidth.

**Comment by emmairwin** [comment]
@psubhashish by end of Friday can you please update this task with update on outreach and support in first-languages.   In the next heartbeat we will pick up from there with a new tasks.  Thanks!

**Comment by psubhashish** [comment]
@emmairwin I reached out to one Rep and a WoMoz. The Rep has agreed to conduct one-two first language (in Telugu language) interview(s) next week. I am still following up with the WoMoz to learn about someone to interview.

**Comment by emmairwin** [comment]
wonderful thanks @psubhashish !

**Comment by bee2502** [comment]
@emmairwin dvigheshwer is also conducting interviews in Malyalam and Tamil.
