### ISSUE TITLE
We have begun to summarize existing sources for gender, language, age and country. 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#491]
## Objective Goal: 
Prioritized set of D&I initiatives, informed by research/insights gathering, to run in Q2 [shared with D&I]

### Subgoal
Data analysis and data visualization drawn from existing sources has been completed.  We understand and can communicate the quality of the data we have, and are beginning to formulate an early hypothesis on 'Metric the Matter' tracking our progress in D&I initiatives moving forward. 

## Related documents and links 
* [D&I Data Attributes](https://docs.google.com/document/d/1qp2k77UqSaj5iXcIrOFcSE2koCCqGH2xNqDhFF5hDWU/edit#heading=h.6yzr8pr1vzk)
* [Diversity and Inclusion - a Plan for Strategy](https://medium.com/p/77224f32a992/edit)

## Item list:
NOTE: We are focusing on 4 specific D&I data attributes for this heartbeat, these are the simplest and most common in forms and surveys related to our data goals.  Future Hearbeats we'll take what we learn form this experience for additional attributes.  

- [x] All data sources available with fields for gender, language, age and country have been identified, and we agree on a which we should use (prioritization) for analysis in this heartbeat. (R: @bee2502  @emmairwin @larissashapiro )
- [x] A strategy for analyzing data is identified and documented for future heartbeats. This how we rate the data quality itself.   (R: @bee2502 )
- [ ] Data has been analyzed according to strategy for gender, language, age and country and a summary provided for each.  This summary will include rating the data itself. (R: @bee2502 @emmairwin C: @nasmaahmed)

## Related Issues

#490

**Comment by bee2502** [comment]
A list of data sources identified for the current round of heartbeat is here : https://docs.google.com/a/mozilla.com/spreadsheets/d/1G-GwPZQcAR7muVXMCiCEI-8a5ULErx70wAhDo_P860g/edit?usp=sharing

**Comment by emmairwin** [comment]
@bee2502 can you update this ticket, to say where we are with this work by end of day Friday?   I have a good idea, but didn't want to make assumptions. We will open a new task for the new heartbeat next week .  Thank you!

**Comment by geroter** [comment]
Wondering if there are any other data sources of significance?

Ideas:
- Mozillians.org...massive DB, not correlated with contribution
- FSA mailing list...again, massive DB not correlated with contribution
- MozFest overall registration from the Foundation
- any other data from the Foundation?
- any major or regular meetups and their attendee data? (Eg Rust meetups)

**Comment by SpikeUK** [comment]
> - MozFest overall registration from the Foundation

I think you would be running in to Data Protection issues with this @geroter -Sarah Allan could advise on this.

In the UK data is normally used only for the event (for example) that it was supplied for. Datamining for something that is not MozFest is likely to be outside of that permitted.

**Comment by emmairwin** [comment]
@geroter the problem we have hit with Mozillians and Reps is that we do not have database access, and the analytics currently being pulled from there do not include diversity data.   A goal for data work in the next heartbeat is to generate user stories to submit to @hmitsch 's team so we can have that data available on the dashboard. 

I will talk to Sarah, we have Mozfest participation (global leadership) from 2015 in our reports, but not last year. I will look for that.

**Comment by geroter** [comment]
Why can't they just do a DB dump from Mozillians and Reps?

**Comment by emmairwin** [comment]
@hmitsch indicated data privacy issues he was working with, and requsted user stories.  Henrik can you share more on that?

**Comment by bee2502** [comment]
All data sources available with fields for gender, language, age and country have been identified and more information on the ones we would be using for this heartbeat is [here.](https://docs.google.com/a/mozilla.com/spreadsheets/d/1G-GwPZQcAR7muVXMCiCEI-8a5ULErx70wAhDo_P860g/edit?usp=sharing) A primary list of questions for working with the data sources has been compiled and can be found [here.](https://docs.google.com/a/mozilla.com/document/d/1Y6kX9nRTOnmhGYEOvEtpBhDl5y4IocvebfJZXoGuNos/edit?usp=sharing)

**Comment by emmairwin** [comment]
fantastic and you rock @bee2502   !
