### ISSUE TITLE
Have a clear communications plan for NDA Mozillians

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#496]
## Objective Goal: 
Create a comms plan for NDA Mozillians and Reps

## Item list:
- [x] Take ownership and training of the NDA salesforce (R:@couci)
- [x] Follow-up with the partsys team on support (R:@couci, @nukeador)
- [x] Create a broader plan for comms for NDA Mozillians (keep track of what we already have, create strategy on our current channels, implement small experiments on fb) (R: @couci @alakatos)
- [x] Decide newsletter concept for Reps (R:@alakatos, S:@couci)

## Related Issues
[Reference meta issues and past issues] #

**Comment by couci** [comment]
Strategy for comms is here and open for feedback https://docs.google.com/document/d/17RoZHYce9cUIsdkUo3UAixBy7Eng7sW6H6seSxXV3gU/edit#
@AlexLakatos @LucyeoH  please review and add your ideas

**Comment by couci** [comment]
training has just happened, I am on a coworking mode until I totally own this

**Comment by couci** [comment]
support on parsys won't be needed on this part of comms

**Comment by couci** [comment]
The newletter is on testing mode and going to be ready by the end of February by @AlexLakatos

**Comment by AlexLakatos** [comment]
Shipped the first newsletter. Web version available at http://mozilla.github.io/Reps/newsletter/02-2017/
