### ISSUE TITLE
We have identified an interactive platform for hosting our high quality learning acitivities

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#506]
## Objective Goal: 
Improve our learning activities

## Related documents and links 
* [Links here](https://docs.google.com/spreadsheets/d/1aiCIM4eIMatmrO6FJBen5VoFDY0RRwB6BpqP6TODRac/edit#gid=0)

## Item list:
- [x] Make a complete analysis of existing platforms like exercism.io (R:)

## Related Issues
[Reference meta issues and past issues] #

**Comment by jgmac1106** [comment]
Make sure to follow the work of the starter kits they are building into
Thimble around WebVR and IoT and a bunch of others.

**Comment by bacharakis** [comment]
We have identified exercism as our platform for supporting our students improving their skills.
More here: https://github.com/mozilla/Campus-Program/issues/333
