### ISSUE TITLE
An affliated Clubs strategy is signed-off on by stakeholders

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#514]
## Objective Goal: 
The affiliate club strategy for Campus Clubs has been developed and shared with stakeholders for initial feedback

## Related documents and links
[Draft strategy doc](https://docs.google.com/document/d/1klQtw3xEpZzKoPqK_Tn8y9Lj4oBjA2badwG1z6biLmM/edit)
## Item list:
- [x] Branding agrees to create an "affiliate" version of the Mozilla logo for us (R: @LucyeoH )
- [x] George signs off on strategy (R: @LucyeoH )
- [x] D&I requirements are scoped and understood (R: LucyeoH)
- [x] The roadmap for Affiliate Club execution is drafted and ready (R: @LucyeoH )

## Related Issues
#500

**Comment by LucyeoH-zz** [comment]
- [x] Additional stakeholders: Dev Marketing & MoFo have been identified and this has been shared
