### ISSUE TITLE
A new activity is developed 

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#515]
## Objective Goal: 
We have developed an activity which is contributing to a Mozilla product with the cooperation of the relevant internal team

## Related documents and links 
* [Links here](/thelink)

## Item list:
- [x] Identify a topic for the new activity (R: @bacharakis)
- [x] Connect with the relevant Mozilla team and sync on activity's goals, outcome and impact (R:@bacharakis)
- [x] Build the activity (R: @bacharakis)
- [x] The activity is reviewed
- [x] We have informed all of our students for the new activity (R: @psubhashish )

## Related Issues
#501

**Comment by psubhashish** [comment]
@bacharakis can this be closed now or anything to be done from my end?
