### ISSUE TITLE
A collaboration strategy proposal for GitHub has been signed off

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#516]
## Objective Goal: 
We a detailed strategy with next steps and action items on how to collaborate with GitHub with the rest of 2017.

## Related documents and links 
* [Links here](/thelink)

## Item list:
- [ ] A collaboration strategy is drafted (R:@bacharakis)
- [ ] Shared with stakeholders for initial feedback (R:@bacharakis)
- [ ] Strategy is signed off by GitHub and internal stakeholders (R: @bacharakis)

## Related Issues
[Reference meta issues and past issues] #

**Comment by a-kilroy** [comment]
Is there a document for this?

**Comment by bacharakis** [comment]
Hi @a-kilroy , following our last week's call/conversation:
We use GitHub services and the platform in a lot of our activities as Campus Clubs.
Starting from asking our students to upload their makes and contribution to the relevant repos in GitHub, up to using the GitHub services for hosting our website and all of the available activities for students.

We also hold a regular call with Joe who is running the GitHub Campus Experts program for exchanging information, experiences and status updates.

We identified that there is not a need for having a strategy document because we are just sharing status updates. We will discuss any collaboration opportunities as we identify them by moving forward evolving our own programs individually.

That's why we also closed it issue 4 days ago. 

If you have any further questions, please let me know.
Cheers

**Comment by a-kilroy** [comment]
Nope, all good. Thanks!
