### ISSUE TITLE
We have a US research preliminary report - infra changes are identified

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#518]
## Objective Goal: 
We have some preliminary results from the US research and based on them we have identified the necessary infrastructure changes for our program

## Related documents and links 
* [Links here](/thelink)

## Item list:
- [x] We have a US research preliminary report (R: @bacharakis, @LucyeoH )

## Related Issues
[Reference meta issues and past issues] #

**Comment by a-kilroy** [comment]
When can you share?

**Comment by bacharakis** [comment]
Our researcher is committed to deliver some preliminary reports by the end of the month
