### ISSUE TITLE
A plan for Reps that don't want to commit to Mobilizers role have been created and RepsNext steps have been finalized

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#529]
## Objective Goal: 
Draft for Reps that don't want to commit on Mobilizers role is been created while we finalize work on Resources and Leadership track

## Item list:
- [ ] Create a draft for Reps that don't want to commit on Mobilizers role (R:@nukeador, S:@floreallemandu, @couci)
- [x] Finalize Resources Track training (R: @couci)
- [ ] Create application for Reps that want to join the Resources Track (R: @couci, @kelimuttu S: @floreallemandu)
- [x] Synthesize work that happened in leadership toolkit  (R:@couci, S: @emmairwin )
- [x] Synthesize coaching work ( @couci, @rara79)

## Related Issues
https://github.com/mozilla/community-development/issues/495

**Comment by LucyeoH-zz** [comment]
@couci where are we going to be hosting the resource track training? GH pages? [Teachable](http://mozilla.teachable.com)?

**Comment by couci** [comment]
I was thinking teachable cause it gives the right to kind of gamifing the training and also centralizes resources. I guess @LucyeoH i will ping you more once the material is ready on how we can put it in there

**Comment by couci** [comment]
The resources track is ready to be pass in teachable while the work on coaching has been synthesized and sent to council for feedback and next steps.
Reps that don't want to be mobilizers conversations has been initiated inside the council

**Comment by couci** [comment]
We synthesized coaching and now we are discussing on how to put the resources leadership toolkit for use from coaches.
The draft will be pushed back for the end of next quarter

**Comment by couci** [comment]
pending steps will be carried on the next HB
