### ISSUE TITLE
Reps Comms plan has been implimented

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#530]
## Objective Goal: 
Implement the reps comms plan we decided last heartbeat

## Related documents and links 
* https://docs.google.com/document/d/17RoZHYce9cUIsdkUo3UAixBy7Eng7sW6H6seSxXV3gU/edit

## Item list:
- [x] publish comms in discourse (R:@couci)
- [x] Initiate facebook experiment (R: @couci, @ioana-chiorean @Srushtika)
- [x] ensure all internal meeting notes are been published at discourse (R: @couci)
- [ ] initiate conversation with Mardi on internal comms (R: @couci)

**Comment by couci** [comment]
https://discourse.mozilla-community.org/t/communication-plan-for-mozillians-nda-mozillians-and-reps-for-q1-2017/13789 comms have been published

**Comment by hossainalikram** [comment]
For the Facebook experiment, is there any space that needs help? I would love to help for such cases :)

**Comment by couci** [comment]
Internal meeting notes are up and fb experiment has been started by @Srusthtika . Also the newsletter is out :)

**Comment by couci** [comment]
pending steps will be carried on the next HB
