### ISSUE TITLE
Deliver Reps swag survey

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/participation-org#538]
## Objective Goal: 
Reps swag survey (including Mozactivate local swag) is delivered to the Reps

## Related documents and links 
* [Survey draft](https://docs.google.com/a/mozilla.com/document/d/1F2Ktb_OhKyZIg2fI9KgdKEDQjadtnGR3EZR5r6PR3n8/edit?usp=sharing)

## Item list:
- [x] Draft is finalized (R:)
- [x] Feedback is gathered (R:)
- [x] Discourse post (R:)
- [x] Survey was sent to the Reps (R:)

## Related Issues
[Reference meta issues and past issues] #

**Comment by kelimuttu** [comment]
Draft is finished. @couci would you mind to take the initial review before I send them to the rest of the Reps Council?

**Comment by couci** [comment]
thanks miss! Initial feedback added on the doc

**Comment by kelimuttu** [comment]
Thank you. Do you think it would be okay to create 2 surveys for local swag? Or should I just combine it together? @couci

**Comment by couci** [comment]
I think it should be one, the less stuff we send the more replies we get the less complicated it is for people

**Comment by kelimuttu** [comment]
Got it!
