### ISSUE TITLE
Improve Measurability of Activate Activities

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#539]
## Objective Goal: 
Ensure that we **understand** and can **measure** the activities people (1) choose, whether they (2)run them, and what (3) outcomes are produced from those activities. 

(Note: Some of this is measuring things that already exist, and some requires producing new measurement structures)

## Related documents and links 
* http://activate.mozilla.community/

## To Do List:
**Understand how many Reps choose to participate in Activate activities (and which ones)**
- [ ] We have the GA set-up to understand how many ppl are viewing the activate site and choosing to click into activities 

**Understand how many people actually run the activities** 
- [ ] **Create a reporting form that organizers should use at the event to capture GitHub handles of attendees** (@couci) 
- [ ] Make sure reporting form is linked from all activities that need to measure developers engaged/attending (@couci)
- [x] Make sure we can see which Activate activities Reps ran on the Reps Portal 

**Understand what "impact" is produced from each activity:** 
- [ ]   [Community Participation Guidelines](https://activate.mozilla.community/community-participation-guideline/) has good metrics: 
 -- Number of people who fill out the form to receive credit (@emmairwin)

- [ ] [Web Extension](https://activate.mozilla.community/webextensions/) has good tracking: 
-- Update activitity description to prompt organizers to collect GitHub handles via form(@couci) 
-- Ensure we can count the number add-ons tagged with mozactivate17 in addons.mozilla.org. 
-- Ensure we can measure the number of social media posts about WebExtensions add-ons referencing #MozActivate (@couci) 

- [ ] [RUST Hack](https://activate.mozilla.community/rust-hack/) has clear metrics:
 -- Update the activity description to prompt organizers to capture web developers (usernames) captured through the form (@couci) 
 -- Ensure we have a way of tracking how many blog posts are produced
 -- Ensure we have a way of knowing how many people sign-ups to the Rust list AT or FROM an activate activity 
-- Update activity so that we have a way of capturing the bonus info (either through the activity or in a follow-up email)
_Bonus: Number of attendees creating a rustaceans profile?, Number of attendees joining the rust users discourse channel?, Number of attendees tweeting to rustlang about a feature of rust?, Number of attendees joining the Reddit channel?, Number of attendees interested in creating a crate?, Number of attendees interested in conducting a rust event?_

- [ ] [Web VR Camp](https://activate.mozilla.community/webvr-camp/) is very measurable: 
-- Update activity to prompt organizers to capture how many developers were at the A-Frame event (captured through the form) @couci 
-- Ensure we know how many people have built things in A-Frame from activate events  
-- Ensure we'll know how many people signed up to the A-Frame slack channel (from Activate) 
-- Ensure we have a way of tracking blog posts 
-- Ensure we have a way of tracking social shares with #MozActivate, #WebVRCamp, @aframevr, @mozillavr 

- [ ] [Web Compat Sprint](https://activate.mozilla.community/webcompat-sprint/)
 -- Update activity to prompt organizers to track how many developers attended the events (captured through the form) @couci 
 -- Ensure we'll know how many add-ons they created  
 -- Ensure we'll know how many web compat issues were filed (from Activate)

**Share the Results of Activate this Quarter**
- [ ] Create a presentation that summarizes the impact of activate this quarter: (@couci)
--  Number of views on activities 
-- Number of activities run
--  Outputs from each activity 
-- Recommendations for Q2

**Comment by couci** [comment]
All Rep activities now are represented on the portal as Inititiative: Activate and then the functional area

**Comment by LucyeoH-zz** [comment]
@couci Feel free to re-open if you want to drag across to Q2 HB1.
