### ISSUE TITLE
Improve the Quality of Activate Activities

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#540]
## Objective Goal: 
Ensure that the quality of activate activities is ever improving and that the [initial feedback](https://docs.google.com/presentation/d/1ajGYh77KVdKJvz-ty-xMRtENHI-mLlXZJyzi56TuAlw/edit#slide=id.g1c5efd9b98_0_59) is shaping the existing activities. 

## Related documents and links 
* #539 

## Item list:
- [x] Create a MozActivate version of the [Campus Web VR Template](https://mozillacampusclubs.github.io/Build-a-Virtual-World/) ( @AlexLakatos ) (+ @bacharakis for support)
- [ ] Create “improved” versions of each activity (@couci) 
 -- Transfer each activity over to new template
 -- Add graphics
 -- Minimize text
 -- Clarify goals
- [ ] Get one person to run each activity and provide feedback (@couci)

**Comment by couci** [comment]
the run the activity part will be held with @nukeador mobilizers experiment
