### ISSUE TITLE
Facebook experiment has been launched and the Reps program is moving to the mobilizers role

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#544]
## Objective Goal: 
Launch facebook experiment and impliment changes that will help to move to the Mobilizers role

## Item list:
- [x] Launch fb experiment (R: @Srushtika , @ioana-chiorean )
- [x] Announce budget for Q1 and Q2 (@couci)
- [ ] The recommitment procedure is ready (@couci, @nukeador, @MichaelKohler )
- [x] New Reps have been onboarded ( @MichaelKohler , @couci, @brianking )
- [x] New metrics have been added to portal ( @couci )
- [ ] Teachable school is ready for Resources and new coaches (@couci, @LucyeoH )

**Comment by couci** [comment]
Draft for the budget announcement has been sent to the council for review. Once it passes the review time we will publish (aiming for the end of this week)

**Comment by Srushtika** [comment]
FB experiment is up and running, and it is being documented here: https://github.com/Srushtika/RepsFBexperiment/issues

Till now:
-Many new reps added to the FB group.
-Template for ROM and Reps Moments is ready.
-Recording reps' reactions to these initiatives before moving forward.

**Comment by MichaelKohler** [comment]
Regarding re-commitment procedure: https://github.com/mozilla/Reps/issues/146

**Comment by MichaelKohler** [comment]
Regarding webinar: I've just scheduled a date for the Webinar (calendar invite) and updated all application bugs.
