### ISSUE TITLE
Regional Coach role is defined and clearly communicated with volunteers

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#547]
## Objective Goal: 
Regional Coach is defined and communications to communities are clear

## Item list:
- [ ] Create a draft for communication plan for communities (R: @francjp)
- [ ] Meeting with all Regional Coaches to discuss and inform about the new plan (R: @francjp)
- [ ] Review the list of active Regional Coaches (R: @francjp)

## Related Issues
#546

**Comment by LucyeoH-zz** [comment]
@francjp can be re-opened if you want to drag this (or a version of this) across to Q2HB1
