### ISSUE TITLE
Communities and Contributors Research - Kick-off actions

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#549]
## Objective Goal: 
All actions that need to happen this HB around the Communities and Contributors Research

## Related documents and links 
* [Project plan](https://docs.google.com/document/d/1nRJIgQzcwTI-ywNyUidVWwTWA6mM1ZkbGLKz9uS62pU/edit#)

## Item list:

_Items with no owner are on @nukeador_

### General

- [ ] ⚪️ Better visual for the project approach (presentation based in the internal research one)
- [x] 👍 Improve milestones and timeline
- [x] 👍 Define a cadence to inform the overall strategy project (With Patrick and Susy)
- [x] 👍 [Blog post about the project](https://docs.google.com/document/d/187qm6JYeAuXWj1DHXq8y_L5OtUJ2w0JdUA24n6JlfkU/edit#) (Sync with Alex and Patrick needed)
- [x] 👍 Solid plan for cross-reference data (R: @nukeador S: Legal C: Susy, Patrick, Rina)
- [X] 👍 [List of all stakeholders](https://docs.google.com/spreadsheets/d/18B1gO38bhaYRsaymbpvyLEM6IcTkQiIzGDHlDQfyk0c/edit?ts=58d31506#gid=1057454089) we need to engage (R: @nukeador C: Susy, Patrick)
  - [x] 👍 [Engage with stakeholders](https://docs.google.com/document/d/1wGsHwjf0JWPU2OUgYKD2CDuheikTXeca1A7WAeTeE3s/edit).

### Survey 

**Content**
- [x] 👍 How do we know if people went to other organizations?
- [x] 👍 Define Contribution areas > Contribution types > Skillsets (@nukeador @rinatambo)
- [x] 👍 How do we identify leaders? Adding a question? Post-analysis based on email?
- [x] 👍 Get stakeholders input on questions (CMs and others).
  - [x] Apply feedback to survey content
- [x] 👍 Welcome texts.
- [x] 👍 Content localization.
     - [x]  Content localization insert to survey
- [x] 👍 Legal notices
     - [x] 👍 Legal notices on page 1, 6 and 7
- [x] D&I questions
- [X] Links to email in intro
- [x] REMOVE PAGE NAMES IN SURVEYGIZMO
- [x] optional vs required for all questions
- [x] Tense (past future update)
- [x] Dave herman input updated
- [x] [Logic tested](https://docs.google.com/document/d/1P2QCTQltTfXQcmgMQLKcMJS2KqHBxpfEUjHAucIWVhY/edit)
- [x]  Update previous and no contribution to match the updated questions

**Comms**
- [x] 👍 Ensure we reach out to people inside projects like Rust, Servo... that might not have a mozillians.org profile.
  - [x] Feedback from Rust and A-Frame CMs on how to reach out groups
- [x] 👍 Explore reaching out to wider audience (bugzilla?)
- [x] 👍 Launch plan (R: @nukeador S: @couci @flekkowich)
  - [x] Email copy ready
  - [x] Audiences defined
  - [x] Final list set up on mailing tool (@couci)
  - [x] Emails sent (@couci)

### Analysis

- [x] ❗️ How do we know if people is going to other organizations? (figure out with @LucyeoH and Bitergia if tech is ready for this)
  - [x] ⚪️ Check with @bacharakis SoC project
- [ ] ⚪️ Bonus: Is there a way to systematize parts of the research for future iterations?
- [x] ❗️ How do we compare qualitative and quantitative data? (Can this be incorporated to the scope?)
- [ ] 👍 Figure out if missing data source can be ready for the research
  - [ ] ⚪️ Kitsune
  - [ ] ⚪️ MDN
  - [ ] ❗️ L10n
  - [x] ❗️ Addons (@nukeador @geroter)
  - [ ] 👍 Marketing contributions
- [X] 👍 Ensure we are getting data from Rust, Servo and ET projects.
  - [x] ⚪️ Be aware of the forked repos and duplicated emails issue.

Legend: ⚪️ Not started 👍 On track ❗️ At risk 🔴 Won't happen

**Comment by flekkowich** [comment]
Can we add Launch plan to survey actions?

**Comment by flekkowich** [comment]
Also, add Action: We will need to decide which questions to force and which to allow free skips. For instance, the initial filter or splash page questions tend to be forced because the response will structure the page-viewing order.

**Comment by flekkowich** [comment]
Add action item: Create welcome page: The splash page should contain a short description of the goals and types of information sought in the survey, with a reasonable expected completion time (i.e. “about 15 minutes”)

**Comment by flekkowich** [comment]
Action: Tool list consolidate

**Comment by nukeador** [comment]
@flekkowich let me know if you can edit now, I invited you to the repo.
