### ISSUE TITLE
India community restructuring meta team - next steps

### ISSUE THREAD

**Issue by psubhashish** [mozilla/participation-org#551]
## Objective Goal: 
Work closely with the provisional meta team and help them take full control of the community activities in India

## Progress at April 7th
- [x] Call with Meta Team - explain process, ask if they have questions, make sure they understand. Offer help with recruiting

## Progress at April 17th
- [ ] Meta team is formed - recruited a few more people (more women) clearly understand what they're going to do

## Related Issues
[Reference meta issues and past issues] #

**Comment by LucyeoH-zz** [comment]
Meta team is still recruiting for new people.
