### ISSUE TITLE
We have identified and contacted at least 40 diverse US Clubs

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#553]
## Objective Goal: 
We have identified and contacted at least 40 diverse US Clubs which will run at least one of our activities and contribute to a Mozilla Project.

## Item list:
- [x] We have identified and contacted at least 40 diverse US Clubs, inviting them to run our activities (R: @bacharakis)

**Comment by MichaelKohler** [comment]
Did the goal change from 20 to 40 or are you just feeling amazing in doubling it? :)

**Comment by bacharakis** [comment]
Hahaha! For recruiting at least 20 you need to definitely aim high.
