### ISSUE TITLE
High Quality Content (Activities / Training)

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#554]
## Objective Goal: 
We have excellent new activities, a new OS specific training and are continuing with our communications plan

## Item list:
- [ ] We have 2 new technical activities which are measured around WebExtenstions and WebVR. (R: @bacharakis)
- [x] Gather up all existing content for compiling and Open Source training and get commitment from Red Hat/POSSE (R: @LucyeoH )
- [ ] We have informed all of our students for our two new activities (R: @bacharakis)

**Comment by LucyeoH-zz** [comment]
We have a preliminary content draft and have POSSE's commitment to work with us on it.
