### ISSUE TITLE
Infrastructure / Alignment	

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#555]
## Objective Goal: 
This is part of our objective around Alignment with MoFo and Open Innovation

## Item list:
- [x] We are working closely with the CoSS team on implementing any necessary changes based on the alignment proposal for Clubs and Campus Clubs (R: @bacharakis)
- [ ] MoFo and OI have stop-gap alignment (R: @LucyeoH )
- [x] We are closely working with OI colleagues on experiments (Don Marti), 
- [x] implementing new activities (Don, Michael, Alex) and aligning on goals. 
- [x] OI is informed about the US research findings.(R: @bacharakis)

**Comment by LucyeoH-zz** [comment]
We have shared a strategy for alignment with Arielle who will be guiding an alignment conversation.
