### ISSUE TITLE
US new leaders track

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#556]
## Objective Goal: 
A group of diverse US leaders is helping us evolve and adapt our program for the US	

## Item list:
- [x] Role description and expectations are ready (includes: time commitment and timeline)  (R: @LucyeoH )
- [x] Role description is shared on multiple lists and preliminary candidates are interviewed (R: @LucyeoH )

**Comment by LucyeoH-zz** [comment]
Role description and registration form shared on multiple lists - haven't started interviewing yet.
