### ISSUE TITLE
[Training on Bitergia] Community Development Project Owners Understand How to Use Bitergia to Understand Their Communities

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#557]
## Overview: 
Christos, Ruben, Konstantina, Lucy need access to the bitergia Repo and a 1hr hands on training so they understand and feel fully confident adding new people and using the visualizations to track and share out their progress. 

## User Story # 1: 
As a project owner I want to understand how to add my community members to bitergia so that I can understand how and where they contribute:

I need:  
* Permission to Read/Write in the Repo 
* To know what information I need to collect to use bitergia 
* To have an opportunity to practice adding people
* To know who to speak to if something breaks 
* How do I add mass data to the list
* How do I create new organizations
* How do I see the outputs from my organization
* How can I share the outputs from my oganization

# Identities
Identities are defined here: https://github.com/mozilla/participation-metrics-identities

## User Story # 2: 
As a project owner I want to add new repositories to the list so that I can see who is interacting with it: 
* Permission to make changes/pull requests in the Repo
* How to add the new Organziation

# Tracked Github Repos
Tracked Github repos are here: https://github.com/Bitergia/projects-mozilla/
You can create a Pull Request on this list anytime. Supposedly, it will take between 1 or 2 days to be included.

**Comment by LucyeoH-zz** [comment]
@bacharakis @couci @nukeador please update with any other questions you'd like addressed/covered in this training.

**Comment by hmitsch** [comment]
I just spoke to Bitergita anf git the info we need.

There are three pre-packaged trainings from Bitergia. All of them are free to us (included in our service contract):

1. Community Analytics Dashboard (e.g. using Community Analytics, Kibana)
1. /edit mode (e.g. Kibana queries deep dive)
1. Python queries (e.g. querying the elasticsearch indeces)

Each training is 1 hour and can be delivery as video conference or in-person in a Mozilla office.

@bacharakis @couci @nukeador @LucyeoH how do we want to proceed with this?

**Comment by MichaelKohler** [comment]
I think for you it would make sense to do 1 and 2, I'd certainly be interested in 2 :)

**Comment by couci** [comment]
thanks @hmitsch for this, I think 1 and 2 are really interesting for me too

**Comment by LucyeoH-zz** [comment]
Perhaps we could offer them all to the whole team (create a quick sign-up
spreadsheet) and run the ones where there's sufficient interest.

Would that work?
Lucy

**Comment by hmitsch** [comment]
Mail sent to Manrique, introducing @LucyeoH.

*Next Step:* Moving to done on the ParSys board as this does not require further involvement from ParSys side.

-Henrik

**Comment by hmitsch** [comment]
DONE: https://air.mozilla.org/?tag=community+analytics
