### ISSUE TITLE
To Be Able to Track Community Members To/From Non Mozilla Repos 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#558]
## Objective Goal: 
For community strategy & campus clubs we need to understand where people go/come from on GitHub beyond Mozilla Repos. 

## User Story 

As a staff member working on understanding our existing community I need to know....
*  if there are trends in where people in the "community" group contribute to after they contribute to Mozilla. 
* if there are trends in where people in the "community" group contributed before they contributed to Mozilla. 
* I need to know how long they've been on GitHub and how long they contributed to other projects.

**Comment by LucyeoH-zz** [comment]
@nukeador @bacharakis please update the issue above if there are other parts of the user story not captured here.

**Comment by hmitsch** [comment]
I will **reference** this issue in the [Bitergia alignment board](https://github.com/mozilla/participation-metrics-org/projects/1) to see if this kind of analytics data can even be retrieved from Community Analytics.

**Comment by hmitsch** [comment]
Moved to Backlog because of Bitergia's focus on the _Contributor Research_.
