### ISSUE TITLE
Improvements for Reps Infrastructure and work for Reps future path is in place

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#560]
## Objective Goal: 
Initiate a series of actions that will improve the Reps infrastructure and create the form for the Reps future path

## Item list:
- [x] Meeting with MoFo team to define Teachable collaboration (R: @couci, S: @LucyeoH )
- [x] Create the form for Reps path (R: @couci)
- [ ] Open for feedback the coaching training for the Reps ( R:@couci)
- [x] Onboard new Reps and arrange onboarding for the next bunch (R: @couci, @MichaelKohler , @AlexLakatos )
- [x] Add Reps metrics in the portal (R: @couci)
- [x] Reps elections have been announced (R: @ioana-chiorean , S: @couci, @nukeador )

## Related Issues
[Reference meta issues and past issues] #

**Comment by couci** [comment]
Metrics have been added https://discourse.mozilla-community.org/t/new-metrics-in-the-portal/14900?source_topic_id=14231

**Comment by couci** [comment]
@MichaelKohler since the onboarding has finished what is the plan for the next bunch?

**Comment by MichaelKohler** [comment]
I'm a little bit behind with doing https://github.com/mozilla/Reps/issues/154 . We will send out requests for "plans" for Cohort 1. I wouldn't say the onboarding has finished though.

For the next cohort, I think we can start somewhere end of April if we haven't any indicators until then that this is not a good idea. So far I really like the approach.

**Comment by couci** [comment]
I've taken the ok to use teachable for Reps courses. The elections have been announced by @ioana-chiorean in the 13/04 call.
Reps have been onboarded and asked to share their plan. Next bunch will be probably be on-boarded next month.
The coaching piece is still on early feedback with Verena (based on the work she did on the Open Leadership toolkit).
