### ISSUE TITLE
H3 : Bangladesh community transitions to distributed leadership model and is aligned with Webmaker rollout

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#57]
<h1>Project Description</h1>

Owner: @brianking
Members: @rosanardila @geroter @LauraReynal
Informed: 

Start the processing of moving the community to a better organisational model that helps them scale better and provide more impact on Mozilla projects. The initial project to unite the community behind is  

<h1>Primary Goals & Objectives for This Heartbeat </h1>
- [x] The community internalizes the Mozilla Participation Guidelines
- [x] The community is structured into teams to support the upcoming Webmaker launch
- [x] The community understands the idea of distributed leadership and is encouraged to move to a model that supports this

<h1>Milestones</h1>
- [x] Kickoff Meeting
- [x] Community Meetup (@brianking, @rosanardila, @LauraReynal)
- [ ] Community Meetup debrief and report (@brianking, @rosanardila)
- [x] Building and documenting Webmaker teams (@brianking, @LauraReynal)
- [x] Build out community led GTM plans for Webmaker (@LauraReynal)

**Comment by lauradereynal** [comment]
Cc / @secretrobotron

**Comment by brianking** [comment]
@LauraReynal @secretrobotron Please post updates here on formation and status of the GTM teams from the community. And please let us know what post-meetup support you would like from us.

**Comment by lauradereynal** [comment]
All the teams are in this git-hub repo : https://github.com/mozilla/webmaker-launch/issues?q=is%3Aopen+is%3Aissue+label%3ABangladesh+label%3A%22GTM+Teams%22
in each issue you can find an etherpad with the plan 

This week i'm working on opening everything more widely to the community and to make everything move forward. Will give another update later. thanks

**Comment by brianking** [comment]
Community Health update

COMPLETED
- 5-6 June: Meetup happened
- 8 June: Internal debrief sent to Participation team by Rosana and Brian
- 17 June: Post-event survey published and sent to participants

TODO
- Event Report with recommendations on next steps for the community

**Comment by brianking** [comment]
### What was supposed to happen?

All the checkbox items listed above, but essentially it was to a) have the community meetup to start the community transition to distributed leadership and b) setup the Webmaker team for success in BD by the getting the community on board for the campaign.

### What did happen?
- The community meetup happened
- Laura did an extra couple of weeks 

### What we learned?

The main learning are still to be synthesized, however on a very high level we can say a few things:
- we got more insight into how the community works, in terms of structure and people dynamics
- however, change will not happen overnight and is an ongoing process
- Instead of a confrontational approach at the meetup, we instead took the approach of being conciliatory and looking to the mission and participation guidelines to get everyone working towards the same goals
- getting the BD community fully behind the Webmaker campaign is challenging, due to where they are at currently
- the Participation and Webmaker teams working closely together has been a good model to expand upon moving forward.

### What are some improvements?
- more lead-in time needed for meetups
- Do not underestimate time needed to change a community and move them in a different direction

### What does the next Heartbeat for this project look like?
- determining what level of support is needed from the P team for the continuing Webmaker work
- writing the post-event report
- writing the plan to work with the BD community and support them moving forward
