### ISSUE TITLE
US New Leaders - We have Identified 20 Open Source Student Leaders 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#577]
## Objective Goal: 
From the recruiting done in HB1 we have identified 20 candidates

## Related documents and links 
* [Links here](/thelink)

## Item list:
- [x] Follow-up with all lists to generate more groups (R: @lucyeoh )
- [x] Follow-up with all nominations (have them fill out self-nomination) (R: @lucyeoh )
- [x] Identify 20 good candidates  (R: @lucyeoh )
- [x] We have identified who will community manage the leaders (R: @lucyeoh, @bacharakis )
- [ ] Send acceptance/rejections  (R: @lucyeoh )

## Related Issues
#556

**Comment by bacharakis** [comment]
Send acceptance/rejections will happen in HB3
