### ISSUE TITLE
Reps Budget for Q2

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/participation-org#578]
## Objective Goal: 
Reps budget for Q2 allocation has been finalized and report has been made. 

## Related documents and links 
* [Q2 Allocation](https://datastudio.google.com/u/0/org//reporting/0B8afomu5khGpMVB6QnV4X2hoaU0/page/Zt4D)

## Item list:
- [x] Spreadsheet  for Q2 April, May, and June has been created (R: @kelimuttu)
- [x] Data studio page for Q2 & April has been created (R: @kelimuttu)

## Related Issues
[Reference meta issues and past issues] #

**Comment by kelimuttu** [comment]
@couci is the allocation percentage would be the same like Q1?

**Comment by MichaelKohler** [comment]
Yes, what we communicated recently was for both Q1 and Q2.

**Comment by kelimuttu** [comment]
ok. Thanks @MichaelKohler
