### ISSUE TITLE
Impact form is localized and results are properly tracked while Nightly activity is life

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#582]
## Objective Goal: 
Impact form is localized and results are properly tracked while Nightly activity is life

## Related documents and links 
[Roadmap](https://docs.google.com/spreadsheets/d/1z4pDflpGqk1LoB69WZ21Q8e2jSqF5lVjMfQhD3_exnk/edit?ts=58dd52ba#gid=1142344156)

## Item list:
- [x] Localized impact forms are available for Reps in their locals (R: @MichaelKohler , @kelimuttu ) @)
- [ ] Group for people that Reps have brought via the impact form is being created (R:  @couci )
- [ ] Dashboard for Reps impact has been created (R: @MichaelKohler @couci )
- [x] Nightly activity is being reviewed  (R: @couci, @LucyeoH @MichaelKohler )
- [x] Nightly activity is being shipped  (R: @MichaelKohler )

## Related Issues
https://github.com/mozilla/community-development/issues/576

**Comment by kelimuttu** [comment]
Issue for localizing impact form can be tracked here https://github.com/mozilla/activate.mozilla.community/issues/249

**Comment by couci** [comment]
Nightly has been shipped as well as the localized form
@MichaelKohler is still working on the dashboard for groups we decided to take the approach of running a script instead.
