### ISSUE TITLE
Report from Sony Z3C program

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#588]
## Objective Goal: 
Create a report for Sony Z3C new program with results over the Q2

## Related documents and links 
* [Project plan](https://docs.google.com/a/mozilla.com/document/d/11pajrSIlzexubac2HwRsvcic5aNEZPtOCIaWOtxYqKQ/edit?usp=sharing)

## Item list:
- [x] Create template report to help communities report in an easy way (R: @francjp)
- [x] Contact all mozillians that received the device (R: @francjp)
- [x] Create a draft for the report based on reports shared by the community (R: @francjp)
- [ ] Share report with the team (R: @francjp)

## Related Issues
none

**Comment by ioana-chiorean** [comment]
Was this done? can it be shared in a Reps Call?

**Comment by francjp** [comment]
It's done, but pending to be reviewed by the team... sorry, it can be shared right now :/

**Comment by ioana-chiorean** [comment]
can or can't?

**Comment by francjp** [comment]
can't... give me a few days ;)

**Comment by ioana-chiorean** [comment]
Sure! Just wanted to check  - when ever you are ready - you know the drill

**Comment by ioana-chiorean** [comment]
@francjp ready? cc @couci

**Comment by francjp** [comment]
@ioana-chiorean here it is: https://docs.google.com/a/mozilla.com/document/d/11-swsfJVtjfau6yE7XGDqNXQNqUCIbVXSfXLZBiRiuM/edit?usp=sharing
(Pending to be reviewed)
