### ISSUE TITLE
Engaged Non-Coders/Enthusiasts in 2 well designed non-coding activities that allow us to produce hypotheses about the audience’s preferences and how to optimize value for Mozilla.

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#596]
## Objective Goal: 
Create 2 activities for our non-coding audience bring value back to Mozilla 

This is a key Result from the Community Development team

## Item list:
- [ ] Have discussions with voice project, marketing and comfortability about the possibilities of activities (R:)
- [ ] Decide on 2 activities we will run with
- [ ] Create draft workflow for the activities
- [ ] Decide on comms approach
- [ ] Decide on engagement approach and usage of the Mobilizers community
- [ ] Launch activities

**Comment by Mte90** [comment]
@edovio was thinking to create one about l10n but was for campus club maybe join the forces can be an idea?

**Comment by couci** [comment]
that sounds interesting, @edovio could you add more details?

**Comment by zilmarr** [comment]
I'd like to propose a SUMO activity. That's how I (not developer) joined Mozilla.

**Comment by barrosgg** [comment]
Hi K,
I see 3 important, essential and strong areas to Mozilla's products growth across the universe 🌌. These areas are:
- [Support](https://support.mozilla.org)
- [Localization](https://l10n.mozilla.org/)
- [Quality Assurance](https://quality.mozilla.org/)

Mozilla's products rely on these important areas to grow in all regions of the world, creating an activity for each area ensures that the community can engage more people in those areas and ensure that areas are strong for long term.

**Comment by zilmarr** [comment]
I second what @barrosgeraldo said and also it's important to note that there's a massive amount of people in Brazil getting a sense of what's the Web just now, with an appropriate support, well localized and high quality products we have a greater chance to have these people as our users.
