### ISSUE TITLE
Follow-up with all volunteer attendees

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#60]
This is mainly getting the survey out, but there may be other pieces as well such as messaging around sessions, thank yous, and so on.

**Comment by francjp** [comment]
Survey sent today:
https://docs.google.com/a/mozilla.com/forms/d/1hBO1m0gynqzgj6roG2F8953WOWDadQjGKpLsSxOhbUc/edit#

Cheers,

**Comment by brianking** [comment]
Am wondering if there is any other followup required here?

@emmairwin , @francjp , @geroter

**Comment by francjp** [comment]
I think that the blogpost from Participation will be also a part of the follow up to tell what happened at Whistler. Only 27 replies to the Survey... maybe it would be good to send a reminder.

**Comment by rosanardila** [comment]
hey @francjp and @brianking do you have results from the survey? Thanks!

**Comment by brianking** [comment]
Results are in!

https://docs.google.com/a/mozilla.com/document/d/1kOA7uU2v_fion8tT99cNraCz949oOSduGPA3Ac2tnb0/edit?usp=sharing
