### ISSUE TITLE
Consolidate pictures taken (whiteboards)

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#61]
I have uploaded some already, but they will be moved to a consolidated folder on G Drive by @nukeador

**Comment by nukeador** [comment]
https://drive.google.com/drive/u/0/folders/0B3CuegKgwkKkfjhxNmJEeHpncEtYTmxOOWgzU2tERWN6MWtkUTYzZGlMcGM2MUE2QlFhYm8

**Comment by deimidis** [comment]
I just uploaded the whiteboards that we made at Radical Participation sessions

**Comment by brianking** [comment]
@nukeador have Christos' pictures been added?

**Comment by nukeador** [comment]
I was told so, I'll ping again.

**Comment by bacharakis** [comment]
Hi guys! 
As I have already wrote in my mail a week ago, I have included my photos in the "whiteboards" folder. https://drive.google.com/drive/u/0/folders/0Bw8tHLgpWV_PVXE2Rk8tck8tRlU
