### ISSUE TITLE
Documenting/capturing the strategy conversation that we had at Whistler

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#63]
This is a follow up on documenting the strategy sessions that the participation team had in Whistler.

Moderators and their sessions:
- @rosanardila Volunteer Leadership and Org. Model
- @brianking Tech Contributors
- @francjp Communication
- @michaelkohler Interface with Mozilla
- @emmairwin Education

Action items:
- [x] gather all the notes
- [x] transform the photos into notes
- [x] create sharable documents for the community

**Comment by couci** [comment]
Tech contributors session notes:https://docs.google.com/document/d/1Xt5sUzA_ElV-b64XuDhKLL84eK-VBfUG8Xj2PNh2IGE/edit from @brianking (as the moderator of the session).

**Comment by MichaelKohler** [comment]
Christos will share the pictures from the "Interface to Mozilla" session as well

**Comment by couci** [comment]
Interface with Mozilla (moderator @MichaelKohler) and Volunteer Leadership and Org. Model (moderator @rosanardila) sessions' photos can be found here https://drive.google.com/drive/u/0/folders/0B8afomu5khGpfjlPRlp0N2RCVEdHbElUN3FyWVBVVUJPLVBYaUxiLTJ0blBRek41QjFWMFk

**Comment by couci** [comment]
Communication session notes here:https://docs.google.com/document/d/1Q9VETA8_np7kjPuFu_2GYjjc1dmdfxU1MfJ7o5M09GY/edit (moderator @francjp)

**Comment by brianking** [comment]
We are missing two sessions:

Education led by @emmairwin 
Community Leadership led by @rosanardila

**Comment by rosanardila** [comment]
Big thanks an the amazing @couci for taking the notes and creating the document:
https://docs.google.com/document/d/1zMh9DgzLHBWMt-ANBm1kz72_MH0UHsD0NlDyac3LtEc/edit

**Comment by couci** [comment]
Recap:
pictures from the sessions' notes can be found here:
https://drive.google.com/open?id=0B8afomu5khGpfjlPRlp0N2RCVEdHbElUN3FyWVBVVUJPLVBYaUxiLTJ0blBRek41QjFWMFk
Sessions' docs can be found here:
https://drive.google.com/open?id=0B8afomu5khGpflNnalg3b1R4NFluenp4a2wyeE1tY1NMekJnQkpmNGZJZGh0R1dtcF9vSFE
We are still missing education notes from @emmairwin

**Comment by emmairwin** [comment]
We only had 20 minutes for education - but here are the notes.  I couldn't add this to the drive as I got 'view only' message

**Comment by emmairwin** [comment]
We only had 20 minutes for education - but here are the notes.  I couldn't add this to the drive as I got 'view only' message

https://docs.google.com/document/d/1BABEw1EIzLsbxHNDZkdP6epV7L8MbmqWG8nQElYGdYY/edit

**Comment by couci** [comment]
added, thanks a lot @emmairwin !

**Comment by emmairwin** [comment]
@couci we close this one?

**Comment by couci** [comment]
Yup all sessions are in, so this can be closed.
