### ISSUE TITLE
Write a blog post about Whistler to Participation Planet

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#64]
Owner: @emmairwin
Member:  @LucyeoH 

This is a partner task of 'Write to Mozillians about Whistler' a issue not yet  created. (will update)
- [x] Encouraging Team Blogs (Emma)
- [x] Making sure we retweet/tweet other blogs on the topic of Participation at Whistler to the Planet. ( @emmairwin @LucyeoH , @francjp, @LucyeoH , @nukeador )
- [x] Invite any bloggers you see with a regular topic on participation/contribution at Mozilla to sign up to the planet ( everyone)
- [x] Blog the results of  https://github.com/mozilla/participation-org/issues/65   (Emma)

**Comment by LucyeoH** [comment]
Should go with - "Write to Mozillians about what happened in Whistler" (not yet in Git)

**Comment by emmairwin** [comment]
@francjp
