### ISSUE TITLE
Re-work the playbook for sessions

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#66]
Owner: @emmairwin
Member: @ppapadeas 
- [x] Create copy of existing playbook, with place for additional resources
- [x] Meeting or ansyncronous collaboration invitation to  collaborate on document sent to @ppapadeas 
- [x] Reworked copy July 9th
- [ ] Added to Github EOD July 10th

**Comment by emmairwin** [comment]
V1 Ready in Google Doc, will move to Github after review and feedback from team. I tried to make this something anyone could run for a team, although there are a couple of mentions in it of the Participation Team. I think ti can be improved on as we run more of these, but ideally this feels like a good starting point ?  
Perhaps @geroter @LucyeoH @deimidis @brianking @williamq have comments
Or Christos, Michael, Ioana from volunteer standpoint interested to know if this is somethign you think you could run on your own next time?

https://docs.google.com/document/d/1B6J9vk00gBKWSr8N1wpILt5DtWXhzyBxRdwa-ae_pu8/edit#

**Comment by ioana-chiorean** [comment]
Hey @emmairwin I will have a look and get back to you here. cc @MichaelKohler @bacharakis

**Comment by emmairwin** [comment]
Thanks!

**Comment by geroter** [comment]
Hey @emmairwin I added some comments.

On Fri, Jul 10, 2015 at 5:12 PM, Emma notifications@github.com wrote:

> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/participation-org/issues/66#issuecomment-120530729
> .

## 

George Roter
Participation Sherpa

irc: geroter  |  skype: geroter
Cell - Canada: 416.670.2401
Cell - USA: 650.485.0079
<650%20308%208443>

**Comment by emmairwin** [comment]
Thanks !

**Comment by emmairwin** [comment]
extracting George's comments so we can reflect back without chasing through docs:

My big lesson from doing these sessions is that there are actually multiple purposes/sessions, and that we should consider splitting this resource into pieces that can work with one another, but don't need to:

1) A fit for Mozilla way for people to learn the basics of Human Centered Design -- this should simply be a modulation of the d.school workshop, with one version for offline and another for online learning. -- primary output is learning
- it should then point to a host of other resources on HCD so that people can actually build a full HCD process for problem solving

2) A resource to help people learn how to structure problems. Again, this is another learning piece, possibly a companion to the Impact Chain workshop.
- we don't really have this built out yet

3) A playbook to help people select the right tools for problem solving with teams based on where things are at. And then some tips on how to incorporate these into a process that is strong for the group.
- this would be the start of a bigger tool on facilitating great problem solving/group work

Overall, a playbook is less of a step-by-step how-to, and instead a set of tools to help people identify what they are actually working on, and then a set of resources they can recombine/use to help them solve that thing. It's about building adaptability.

Practically, what I would do with the work you've already done is:

a) You've run the learning workshop of HCD a few times now. Really polish this up for a Mozilla leadership audience.

b) Start a new resource to help people identify what type of situation they are in, and therefore what types of tools they should be looking at.

c) If there's time, start to build/outline a separate learning workshop based on the Problem Statement worksheet.

**Comment by emmairwin** [comment]
Version 1 now on Educational Portal: http://education.mozilla-community.org/

**Comment by emmairwin** [comment]
These are slides I started to help me brainstorm around what George's feedback was:  https://docs.google.com/presentation/d/1SllRsNAAZiWJD55Zu7VHslBe6l6PC_RDaaocnNLllss/edit#slide=id.g9cff24e8a_0_0      .
