### ISSUE TITLE
Follow-up & Survey to Teams - consolidate notes and send with survey to teams

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#68]
Owner: @lucyoeh
Team: @francjp 
Involved: All

Consolidate all of the notes and have each team lead send out their notes and the survey to the lead of the projects they met with. 

To Do: 
- [x] Create email template
- [x] Create feedback survey 
- [x] Make sure all notes are cleaned-up (Monday July 6th) 
- [x] Make sure surveys and notes are all sent (Friday July 10th) 
- [x] Harass liberally

**Comment by LucyeoH-zz** [comment]
STEPS TO FOLLOW FOR FOLLOW-UPS: 
1. Clean-up your meeting notes from Whistler
2. Customize [this email template](https://docs.google.com/a/mozilla.com/document/d/1pi8UtPLO17yjVya98I-E5KN4IeR1pZUxhv25HpIqQX4/edit?usp=sharing) and add the links to your notes 
3. Check-off the box beside your name below. 
4. CELEBRATE!

Hint: Can't remember who you need to email. Check this list [here](https://docs.google.com/spreadsheets/d/1YN5gILqzQb8Spx7L5kIAhEJoW_GtcR7NfrtnkkQDJM0/edit#gid=1008214327)

**Comment by LucyeoH-zz** [comment]
Check-off Once the Email is Sent! 
- [x] Webmaker Product - William
- [x] L10N - Emma
- [ ] Android: India   - Brian
- [x] Content Services - Rosana
- [x] CommsSquared - Lucy
- [x] QA Leadership - Emma
- [x] MDN - Emma
- [x] SuMo Retention - Ruben
- [x] QA + Reps - Ruben
- [x] Shape of the Web - Lucy
- [x] Advocacy  - Rosana
- [ ] Growing B2G - Brian
- [x] User insight/research - Emma
- [x] ScienceLab - Lucy
- [ ] Rust/Research     - Pierros
- [ ] FSA Design - William
- [ ] OneAndDone   - Pierros
- [ ] FxOS IoT - Pierros
- [x] Codebase Retention - Emma
- [ ] Automation Team - Pierros
- [x] Moz Clubs Onboard     - Ruben
- [x] SUMO: Desktop BuddyUp - Brian

**Comment by nukeador** [comment]
Done from my side.

**Comment by emmairwin** [comment]
Done

**Comment by rosanardila** [comment]
@LucyeoH do we have results for the survey to functional teams yet? Thanks!
