### ISSUE TITLE
Build out workflow for the Participation team - review Heartbeat

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#69]
Owner: @lucyeoh
Team: @emmairwin @brianking 

Look at the workflow for the Participation Team, review it and establish process going forward. 

To Do: 
- [x] Create survey questions https://participation.etherpad.mozilla.org/HeartbeatReview
- [x] Compile into survey and circulate to team
- [x] Schedule meeting with team to follow-up with responses from survey and discuss the process moving forward

**Comment by geroter** [comment]
Let's combine assessment of Heartbeat with team diagnostic survey. Can you
send a few questions, the results of which will help drive a discussion?

On Thu, Jul 2, 2015 at 12:38 PM, LucyeoH notifications@github.com wrote:

> Owner: @lucyeoh https://github.com/lucyeoh
> Team: @emmairwin https://github.com/emmairwin @brianking
> https://github.com/brianking
> 
> Look at the workflow for the Participation Team, review it and establish
> process going forward.
> 
> To Do:
> [ ] Set-up meeting to begin discussions
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/participation-org/issues/69.

## 

George Roter
Participation Sherpa

irc: geroter  |  skype: geroter
Cell - Canada: 416.670.2401
Cell - USA: 650.485.0079
<650%20308%208443>

**Comment by LucyeoH-zz** [comment]
Sure! Here are some potential questions to send around to the team, would love some feedback before I throw them into a Google Survey: 
https://participation.etherpad.mozilla.org/HeartbeatReview
@geroter

**Comment by LucyeoH-zz** [comment]
Blocked: Waiting for responses from team diagnostic survey.

**Comment by emmairwin** [comment]
@LucyeoH can we close this one?
