### ISSUE TITLE
Test Heartbeat project to do stuff that involves multiple people

### ISSUE THREAD

**Issue by djst** [mozilla/participation-org#7]
This is a Heartbeat project and it involves more than one people. It will have several important tasks/milestones assigned to different people with a tight timeline. Every task will need due dates and I as the project manager of this Heartbeat will want to monitor progress closely so late deliveries are not jeopardizing the success of the project as a whole.

**Comment by djst** [comment]
Here is a task that is owned by Pierros: Do XYZ by due date. 

(This seems to be the only way to assign a task. Just a comment in a text box.)

**Comment by emmairwin** [comment]
@djst I just assigned this task to myself via the 'assignee' cog in the right hand menu
