### ISSUE TITLE
Chota Fennec - Follow up

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#77]
Build on the momentum of Chota Fennec and catalyze interest and energy.
- [x] Follow up with the fennec team: product and engineering team
- [x] Follow up with Chota fennec team 
- [x] Include emerging and interested stake holders.
- [x] Create Wiki page
- [x] Document project in the wiki

Team: 
@deimidis

**Comment by rosanardila** [comment]
Created wiki page: https://wiki.mozilla.org/Participation/Chota-fennec

**Comment by ioana-chiorean** [comment]
Hey @rosanardila as I am doing QA for regular Firefox for Android  - pls let me know if you need QA support here (and not only QA).

**Comment by rosanardila** [comment]
next meeting scheduled for Mon July 20th, wiki populated and fennec PM in the loop
