### ISSUE TITLE
Openess of documents

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/participation-org#78]
I came across a few protected Google Docs that are linked in the issues here. Could you please make sure that these are only protected if not otherwise possible? One example would be the session notes from Franc's session.

Further, is there a more discoverable way for the documents than searching through the issues here? Could the folder be made public while still having the possibility to protect single documents?

**Comment by geroter** [comment]
Here's the working folder for the Participation team:
https://drive.google.com/drive/folders/0B-K4Qlfh3pISfnlHaU1Id1k0SW9ESEZUenFtemZNcHdkZ0FZZFhGZm0ySkt3NmVxWV9TRDA

This is also on the Participation wiki page.

**Comment by francjp** [comment]
Hi @MichaelKohler, I've just change the permissions (sorry, need to remember to change the default settings for these kind of things).

Cheers

**Comment by brianking** [comment]
@MichaelKohler any suggestions on how we can make our documents more discoverable and searchable?

**Comment by emmairwin** [comment]
I want to suggest two things

1) Make all google documents that don't need to be google docs into Markdown and store in our participation repository
2) Or we can leverage the publish as web page functionality:  https://support.google.com/docs/answer/183965?hl=en which actually (if I read correctly) indexes those documents in search engines?
3) For what needs to be accessible and open it almost feels like we need an index of files - because even I'm not sure what's available google docs can be so crazy (which is why I prefer repos)

**Comment by brianking** [comment]
Thanks Emma. I agree indexing and accessibility are crucial. For now it seems like 2 is an easy first step (on new docs at least, to create that habit), and then perhaps we can find tools to convert them and move them to a new location.

**Comment by emmairwin** [comment]
Question from @akatsoulas   ping to @LucyeoH 

"Participation team, I hope it's okay to "request access" to any google drive link that's in the participation-org repo. (Sometimes I don't actually need access, but I automatically click request access :P)"

I would say yes it's OK. of course, not all times will that be granted under circumstances of privacy , but it's a little unclear still what people should expect.

**Comment by sammyfung** [comment]
Working folder for the Participation team is public readable but it's almost no document found in each sub-folders.

**Comment by LucyeoH-zz** [comment]
Hey! Yes people can always request access though there might be some occasions where it isn't granted. Same thing with anything linked to on this GitHub repo!
