### ISSUE TITLE
Concept for Leadership Development gatherings and selection processes completed and launched, including consulting stakeholders

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#80]
### Goal:

Design and consultation phases for building out the volunteer leadership development goals for 3 global gatherings (MozFest, Leadership Summit and Orlando workweek), and also creating an integrated selection process.

**Planning document is here:**
https://docs.google.com/document/d/1D6GaVk64BqgR7sR_rg_HOelD9iY9hyjGqMNL01ebiVk/edit

**Objective:** Launch the basics of a refreshed leadership development program

**Key result 1:** Volunteer selection for MozFest, Leadership Summit and Orlando Work Week is strategic and builds trust with volunteer communities, by designing, executing and systematizing a process

**Key result 2:** Outline and plan for a Leadership Summit to be held in late 2015 or early 2016
### Success:

1) Build a strategy/concept document on what the 3 different events are, their goals, and the likely attendees with personas. 70% quality -- solid version

2) Consult early with Reps Council and provide framing for conversations with Mentors.

3) Develop 2-3 different options for volunteer selection, based on research of what we've done in the past and what users might want, including resource and technology requirements based -- these should include basic prototypes
### Roles:

Owner: @geroter
Responsible: @geroter, @nukeador, @francjp, @emmairwin, @LucyeoH 
Involved: @rosanardila, @ppapadeas  
Reviewer: @rosanardila  
### Required:
- [x] Basic "wait and see" communication out to various groups who need to hear (@nukedor, 1 hr, Mon Aug 3)
- [x] Draft concept for gatherings, circulate to various people for review (@geroter 4hrs, @emmairwin 2hrs, Wed Aug 5)
- [x] Document with research on past selection processes (@francjp 5hrs, Tues Aug 4)
- [x] Draft designs for selection processes, including basic prototypes in Google Docs/sketches (@francjp 5hrs, @nukeador 4hrs, @couci 4hrs, Thurs Aug 6)
- [x] Engagement to get feedback from Council/Reps/Team and Functional/Product leads on the concepts (@nukeador 3hrs, @couci 3hrs, @geroter 2hrs Wed Aug 12)
- [ ] Finalize concept and selection process based on feedback (@geroter 4hrs, @emmairwin 2hrs, @nukeador 2hrs, @couci 2hrs Fri Aug 14)
- [ ] Communication to Functional/Product leads and staff on Orlando process (@francjp 4hrs, Wed Aug 19)
- [ ] Setup and test application tool (@nukeador or @couci 4hrs, Wed Aug 19)
- [ ] Write and send broad communication to volunteers with application process, including support materials for rest of Participation Team and others to answer questions (@LucyeoH 2hrs, @geroter 4hrs, @couci or @nukeador 2hrs, Thurs Aug 20)

**Comment by LucyeoH-zz** [comment]
@geroter let's put the Key Results here as the key results for this heartbeat, rather than the whole Quarter Goal.

**Comment by francjp** [comment]
Done the first draft of the previous selection: https://docs.google.com/document/d/1ScRqDtq92AkbOwxt8qE6NHuS-GgD7ViZhjsphASPgcc/edit?usp=sharing

Also included some ideas for future selections.

**Comment by geroter** [comment]
Thanks @francjp ... I added a comment to the Google Doc that will help guide a second draft.

**Comment by nukeador** [comment]
I've done communications to mozillians and Reps about the process.

Mozillians: https://discourse.mozilla-community.org/t/mozfest-2015/3058
Reps: https://discourse.mozilla-community.org/t/mozfest-remo-camp-2015-and-other-leadership-events/3059 (and also reps-general)

**Comment by francjp** [comment]
Draft with three options for Selection process already done: https://docs.google.com/a/mozilla.com/document/d/1kKAg2QUtr0BKxT2iPQSeYggzq6vzfnJ5OJGSNLkRYKk/edit?usp=sharing

**Comment by couci** [comment]
option one draft drawing can be found here: https://docs.google.com/drawings/d/14Z19dYhWBC48BSZgzeDdSuIda50myeSvleUKU2MKw5E/edit . Waiting for screenshots on previous tools.
I've added all the documents of this heartbeat on the heartbeat specific folder https://drive.google.com/drive/u/1/folders/0B8afomu5khGpfkhWYy13NGFobmpibVgweE9VQktvTTJ0SHJrSE9MRUc2ZnJCRTFDNU04YUE

**Comment by geroter** [comment]
Can I suggest that because we haven't really expanded the criteria that we're solving for, we're still very much thinking inside the box on what we've done in the past on selection processes.

My strong recommendation would be to work with @francjp  on building out those criteria, different ways of solving for each one, and then get quite creative with some ideas/options for a selection process.

**Comment by SpikeUK** [comment]
I would be interested in discussing how the Reps selected to attend MozFest can work closer with the local volunteers.
Spike (MozFest local volunteer coordinator)

**Comment by emmairwin** [comment]
@SpikeUK we are chatting with Michelle and Sarah(next week) about designing leadership pathways/space for mozfest, this is a good thing for us to have in mind .  I'll reach out to you on this topic before-hand,  because yes that would be great to think about.

**Comment by emmairwin** [comment]
@couci and @francjp also please reach out to me, I am doing a lot of thinking and designing for goal-setting and training that will make selected candidates successful, so have workflow ideas.

**Comment by rtsayles** [comment]
@emmairwin @SpikeUK Excellent idea for MozFest. I would love to be involve with the discussion regarding the volunteers.

**Comment by emmairwin** [comment]
@rtsayles yay!  - @SpikeUK and I spoke today and I left with two 'thinking points'  for our work here:
1) Can our sponsored community leaders teach/facilitate a session/workshop (something) that connect svolunteers with Participation at Mozilla? This would/could be part of the Leadership pathway for our sponsored volunteers, proving them with an opportunity to flex their facilitation skills as well.

2) Is there value in joining volunteers with sponsored community leaders, as part of the Buddy pathway at  Mozfest?

I think Spike has very specific ideas about buddying and volunteer participation that falls outside of this, but it feels good to explore intersection of goals like this :)

We'll be talking to Sarah and Michelle next week and will include these questions, and follow up shortly afterwards.

For those reading, who want to know more about pathways and personas at mozfest, there's a great summary here:  https://wiki.mozilla.org/Mozfest/2015/Mozretreat

**Comment by geroter** [comment]
Draft concept for Participation Leaders and Global Gatherings is completed. Will be getting broad feedback over the next few days:
https://docs.google.com/presentation/d/1twJ0oZPbKs7aRzGb-5gpbNZPBg0c49F2m-FKQlyv2fg/edit#slide=id.p

**Comment by brianking** [comment]
How/where will you be opening up feedback @geroter? The doc is read-only for me right now.

**Comment by geroter** [comment]
Discuss on Discourse or send me an email!

https://discourse.mozilla-community.org/t/draft-for-feedback-developing-participation-leaders-mozfest-leadership-summit-work-week-2015/3390

**Comment by geroter** [comment]
Update on progress:
- about a week behind on getting feedback and finalizing the process. Communication to go out broadly by 8/28.
- application tool should be ready by 8/21

**Comment by LucyeoH-zz** [comment]
Blockers 
- project management/process related needed to map PTO to actual plan 
- needed everyone involved in the kick-off meeting 
- needed more project management (pinging & poking) 
- A week late (Move it over to the next HB)
