### ISSUE TITLE
Foundations of Mozilla Curriculum - Research

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#81]
### Goal:

Research and consultation phases for  developing a basic model basic concept/model of “Foundations of Mozilla” Curriculum with pillars: **skills, knowledge attitude**. 

**Planning document is here:**
https://docs.google.com/document/d/1fZyp6q3RHAYFI-OKxue5Gtmg3JaDCb4jEvq_OFiFBEQ/edit

**Objective:**
Completed research and learning outcomes validated by Stakeholders.

**Key results:** 
- Documented list of stakeholders
- Documented list of key learning outcomes for 'Foundation of Mozilla' informed by Stakeholders and \* \* Research.
- List of existing resources (internal and external)
- Gap Analysis of those resources for learning outcomes.
### Success:

Complete all research steps required to inform the development phase of Foundations of Mozilla Curriculum including a Gap analysis of  teaching & training resources for identified learning objectives.
### Roles:

Owner: @emmairwin
Responsible: @geroter, 
Reviewers: @rosanardila, @couci  @nukeador @williamq @brianking 
### Required:
- [x] Decide on guidelines and method for tracking research, stakeholders/consultant information, and notes.  Create document(s)  @emmairwin
- [x] Create list of internal and external Stakeholders & Consultants (email, setup calls) @emmairwin
- [x] Create & blog volunteer tasks
- [x] Email & Schedule Interviews w Consultant & Stakeholders
- [x] Interviews Completed @emmairwin **(August 13th)**
- [x] Research (Internal) @emmairwin and volunteer researchers @emmairwin  **(August 14th)**
- [x] Research (External) @emmairwin and volunteer researchers @emmairwin **(August 19th)**
- [x] Check-in Call @emmairwin @geroter **(August 12th)**
- [x]  Curriculum Standard - Research Completed with stakeholders  **(August 14th)**
- [ ] Identify Key Learning Outcomes based on stakeholder feedback, consultant feedback + internal and external research.  @emmairwin and volunteer educator  **(August 20th)**
- [ ] Gap Analysis. Based on research, and learning outcomes identify what we can reuse, remix and what is missing entirely. @emmairwin **(August 20th)**
- [x] Draft of curriculum standard @emmairwin **(August 20th)**
- [x] Wrap-up call @emmairwin @geroter  **(August 20th)**
#### Volunteer Opportunities
- #101 (Researcher)
- #102 (Curriculum Design)
- #103 (Design Mockup for Education Portal based on Design Standards for Mozilla)
- #104  (Implement Design)

**Comment by emmairwin** [comment]
Created form for tracking research data.   https://docs.google.com/forms/d/1SN7LeAOKDYy7j6UqemnYgavwKr6snssXo1PincCaAlU/viewform

**Comment by emmairwin** [comment]
Created a github repo for curriculum we'll build"  https://github.com/emmairwin/community_curriculum/tree/master/participation

And also places we'll document the process  and standards  (so others can clearly see how to plug into the process)

https://github.com/emmairwin/community_curriculum/tree/master/education_portal

**Comment by emmairwin** [comment]
Form for nomination of consultants/stakeholders:  https://docs.google.com/forms/d/14mykUSwF1K4gbOl5IzB3djqGT8A2Eqasg85Xiz4Q0vA/viewform

**Comment by hmitsch** [comment]
Hi @emmairwin, 

thanks for the conversation earlier today. I just submitted a handful of resources through the form mentioned in comment https://github.com/mozilla/participation-org/issues/81#issuecomment-126510468 .

Best regards,
   Henrik

**Comment by emmairwin** [comment]
Thanks so much @hmitsch !

**Comment by LucyeoH-zz** [comment]
@emmairwin thanks for checking these off as they happen! Can you please add due-dates next to your "to dos" so I can see when you're anticipating having various things done by? Don't have to be precise and you can always change them later.

**Comment by emmairwin** [comment]
Due dates added @LucyeoH

**Comment by emmairwin** [comment]
have so far interviewed twelve people (seven more to go), trying to  capture knowledge, skills, attitudes here: https://docs.google.com/spreadsheets/d/1t59IlS8DHQCKK9tGnd8j34gP0jFn1vmYXS27MmHt9Ys/edit#gid=0  

Interviewees range from community leaders, to emerging leaders, project leads, technical and non-technical project-focus, as well as teaching, facilitating and learning experts across (and outside) the project.

With a more general summary of comments, suggestions and wisdom to come.

**Comment by emmairwin** [comment]
Have also been talking to people who want to contribute curriculum to the education portal asking these questions
1. What format do you expect to run this training (online, workshop / in person, other)
2. What help do you need as you design curriculum?
3. Will you have multi-media, if so what requirements would you have for media display?
4. Are you comfortable with a review process which includes suggestions for edit?
5. Do you have any community ready to beta test your curriculum?
6. Will you be providing certification, badge or other aknowledgement for completion of training/curriculum?
   7 Are you comfortable receiving and commenting on contribution(pull requests) from community to your content?  This means commenting in an issue, making suggestions and giving approval for merge?
7. Do you have any existing forums you would like to use for course 'conversation' or would you be OK with using our Discourse forum?

I'll summarize the outcomes of these as well as part of proposed design

Doing research for solutions that allow us to connect people unsure about Github with the process of submitting content to...Github (which includes a pull request like acceptance).   Found this:  http://t.co/pMxEIxYhSn  but seems too heavy.  Understand there may be a similar effort on the foundation side so looking into that as well.  Also @SOFTowaha is helping this research.

**Comment by emmairwin** [comment]
A better summary document: https://docs.google.com/document/d/1x2o1au_EUH5FRM_YHJMHYvz2VU9ssvg9bjifBjfvk28/edit#

**Comment by emmairwin** [comment]
I'm trying out this tool (trial period, but that's OK) to work out some things in a sticky-note way.  Feel free to leave comments, or I can send you an invite to collaborate
http://mur.al/bKQ3Xe8N

**Comment by emmairwin** [comment]
Current Skills, knowledge, attitude Org:  ![myteam69 1439417254528](https://cloud.githubusercontent.com/assets/60618/9260101/685cef86-41ba-11e5-8a09-04ce7b5d2be3.png)

**Comment by emmairwin** [comment]
Update and Request for Feedback

Since last week, I took everyone's feedback (captured in the first whiteboard) , stepped back and identified what I thought were three separate buckets, and worked on defining those:
- [Mozilla 101](https://app.mural.ly/!/#/myteam69/1439839712610/view/639884490)
- ['Lens of Empowerment' - Building Bridges for People](https://app.mural.ly/!/#/myteam69/1439851296188/view/364490711)
- [Impact Planning for Community Leadership](https://app.mural.ly/api/murals/myteam69.1439849942874/share/view/4004163987?sender=emmairwin)

This helped me think more deeply about knowledge, skills and attitudes, which I was more intentional about this round. And then I left the computer walked, drove home, walked some more talking out loud came up with a first draft of what I think the Foundations of Mozilla 'for Community Leadership' curriculum might be emerging as (with brief descriptions)

**Activating**: Activating people, making ideas real, generating excitement, unblocking, inspiring
**Connecting**: People to projects, people toe ach other, bridges between communities, people to Mozilla, energy to ideas
**Empowering**: Diversity & Inclusiveness, mentoring, teaching, conflict resolution, me/myself/i
**Building**: Community, planning, structuring, iterating, tools, evangelism,
**Sharing**: Open practices, publishing, writing, social media, story telling

Would super, extra love your thoughts and feedback.

**Comment by jgmac1106** [comment]
I have heard evangelism is a word that does not work in every cultural
context. May want to reconsider.
I like agency better  than  me/myself/i because I am made up of multiple
mes.
Might want to include scale or scaling up under building referring to both
community, design, and tools.

**Comment by emmairwin** [comment]
@jgmac1106 thanks for this fantastic feedback.  It's true even as I wrote evangelism, I was thinking it has negative context in speaker circuits as well.  But excellent point - I wonder what another good word would be?
Agency - Perfect word.
and yes Scaling, will add.  

So appreciate.

**Comment by emmairwin** [comment]
Draft of Curriculum submission process:  https://docs.google.com/document/d/1TtL-sCmCVpOYUftdAxdy6AFU0wgxxr6hvyU7QYJZOB4/edit#

Will polish this week, and add to the portal.   I may also do a video tutorial so this doesn't seem to overwhelming.

**Comment by LucyeoH-zz** [comment]
- Needed to wait until other parts were finished -> Move to next Heartbeat.

**Comment by emmairwin** [comment]
Next Steps 

1) Propose three naming variations of taxonomy that represent our conversations so far (building blocks, foundations, pillars) as they relate to the top level, (open, impact, empower, build, connect), and their units.  For feedback and selection.
2)  Clarify language that explains each of the 5 in a way that connects to top level.
3)  Clarify language for top level.
4) Propose 6 workshops structure leading with the one focused on 'know thyself/leadership identity' ,  one Mozilla 101, and one each of the 5, built under the primary topic.
5) Get feedback over the two weeks Emma is away  
6) Recruit people to take first round of testing while Emma is away (being mindful it will be about one week into the next heartbeat before we can realistically run something.
