### ISSUE TITLE
Whistler Session Follow-Ups

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#84]
### Goal

To close-out all Whistler Session follow-ups 
### Success

Every team we met with in Whistler has had personal contact from a member of the Participation Team and feels that their projects and time were valued. 
### Roles

Owner: @lucyeoh 
### Required
- [x] Send out all team email with status update
- [x] Follow-up with individual tasks 
  - [x] George all follow-ups (@gerorter Due Aug 7th) 
  - [x] Bring 2 projects into German Community Plan (@lucyeoh @brianking @williamq Due: Aug 10th)
  - [x] Comms Squared follow up (@lucyeoh @rosanardila @emmairwin Due: Aug 7th) 
  - [x] SUMO follow up (@brianking @lucyeoh due: Aug 7th) 
    - introduction sent to Madalina whose away until Aug 11th. 
  - [x] User Insight follow up (@emmairwin @rosanardila @williamq due: Aug 7th)  
- [x] Draft email for remaining teams (@lucyeoh Due: Aug 10th) 
- [x] Make sure all emails have been sent (@lucyeoh Due: Aug 14)

**Comment by MichaelKohler** [comment]
Please keep me updated regarding the point "Bring 2 projects into German Community Plan"

**Comment by emmairwin** [comment]
Meeting with Rosana and William set for Thur the 6th to discuss user insight/research participation.

**Comment by LucyeoH-zz** [comment]
@emmairwin great! Let me know when you have made contact with the User Insight Team!

**Comment by emmairwin** [comment]
Met with @rosanardila and @williamq , and informed @AkshayTiwari and Bob Reyes the results.

Topic: What Research opportunities exist in current heartbeats, that we can extend to the Marketpulse community, and can build greater engagement as per our draft for Market & User Insight strategy. Results:
1. Value in interviewing FFOS contributors who have dropped off (to better understand why), and those who have stayed-on as regular contributors to inform better decision making around developer engagement.
   Leveraging the super-mentors who finished our 'Interviewing with Users for Mozilla" course seems a good first step.  @williamq   to provide a list of names/or places to look for interview candidates
2.  There are 10 target market for Firefox OS among them: India, Bangaldesh, Philippines, Indonesia, Germany, France, UK, Mexico. and we need to activate researchers in this area to help describe the 'mobile landscape'.  This is not only important, but can be super fun to leverage the skills we learned in our course. @rosanardila to provide a list of attributes for research on this topic.
3. Continued data collection for Marketpulse which is still a high priority.

@AkshayTiwari to continue community engagement in collaboration with myself & Bob.
@emmairwin to update Akshay and Bob when we have task outlines from Rosana and William.

@LucyeoH do you prefer I update the team on this status, or wait until the community has task definitions?

**Comment by emmairwin** [comment]
ping @rosanardila @williamq  - we have Marketpulse contributors asking how to help.  
referencing @https://github.com/mozilla/participation-org/issues/84   as well.
@LucyeoH  preference for outreach to the team ?  THanks :)

**Comment by LucyeoH-zz** [comment]
@emmairwin sounds good! What would be the function of an all-team udpate on this? Seems like the relevant people have been brought in, though could make a good demo topic if there's a call to action for the rest of the team...

**Comment by emmairwin** [comment]
@LucyeoH to be clear, this is in reference to your comment above re:  User Insight Team
There is no User Insight team so much as a group of people working in research at Mozilla who we shared the draft strategy with in Whistler, that might appreciate the update.  The Marketpulse community is also waiting for the task lists above, so the way I envision closing this is:
- [ ] 1) Rosana and William provide the details for contribution as per comments above. 
- [ ] 2) I connect with our Marketpulse mentors and leaders to discuss these new opportunities ( I have been telling them 'new opportunities are coming...). I know that at least one of our course participants is ready to lead one of the initiatives  (and has pinged me a couple of times already)
- [ ] 3) We update the User Insight group from Whistler , with an outline of the above points with perhaps, what we expect to come next for contribution in this area.  @geroter might also have important insights into how this should be wrapped.

**Comment by LucyeoH-zz** [comment]
Hey @emmairwin that sounds like a great plan. Let's see if @geroter has any additional ideas than I think it makes sense just to send an update email to the rest of the the user insight team letting them know who they can connect with if they want to stay involved and the areas Rosana and William mentioned. Is there anyway I can help with this?

**Comment by LucyeoH-zz** [comment]
Hey @rosanardila  @williamq can you send the info asap. Currently waiting on this info is a blocker for closing this issue. Thanks!

**Comment by LucyeoH-zz** [comment]
Update: All of the remaining teams have received a version of [this](https://docs.google.com/document/d/13Tp7QItS6oovQtCsEAXDnM0CYXqQawe33yyXN3Rm-Xc/edit) email.

**Comment by LucyeoH-zz** [comment]
User Insight Team follow-up needs to be pulled over to next HB & closed asap.
