### ISSUE TITLE
Set-Up Infrastructure to track lessons & insights around Participation 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#85]
### Goal:

This quarter we will focus on identifying a series of interesting topics pertaining to areas in which Mozilla could improve, and developing a method for tracking and synthesizing those lessons and insights through the Participation Lab 

View the full [Q3 Objective Summary here](https://docs.google.com/document/d/1yNmVptwrpOi8lt-VdhLveYoQkhSWqRVNopXhip__VaY/edit#). 

Some overlap with #17  
### Success:

5 clear topics that we will surface insights/lessons around, 20 individuals/teams/initiatives to interview and track, a clear format for executing, recording and tracking lessons. 
### Roles:

Owner: @lucyeoh
Member: @emmairwin 
### Required:
- [x] Identify 10 ideas (5 each) of important topics, or existing trends to surface insights around. (@emmairwin @lucyeoh, Reqd Time 45 mins,  Due: Aug 7th) 
- [x] Decide on 5 topics to persue (@emmairwin @lucyeoh, Req'd Time 30 min (mtng), Due: Aug 7th) 
- [x] Create a document for tracking  potential people/lessons to explore further (@lucyeoh Req'd Time: 30 mins, Due: Aug 10th) 
- [x] Identify relevant groups to talk to for each of the lesson/insight you are looking for(@lucyeoh @emmairwin 1hr, Due Aug 13). 
- [x] Develop a preliminary draft of interview questions (@emmairwin, Time: 1.5 hrs, Due: Aug 17th)
- [x] Turn our etherpad plan into a Google Doc that we can share (@lucyeoh, time: .5 hrs Due: Aug 14) 
- [x] Circulate for feedback with (@geroter  August 17th) 
- [x] Final draft completed and signed off on (@lucyoeh @emmairwin, Time: .5 hrs, Due: Aug 20)

**Comment by brianking** [comment]
Set-Up Infrastructure to ??

**Comment by LucyeoH-zz** [comment]
Ideas for insights & lessons to explore here: https://participation.etherpad.mozilla.org/ParticipationLabNotes

**Comment by LucyeoH-zz** [comment]
[Participation Lab](https://docs.google.com/document/d/1YaADpq7S9pma6oZF3ZxjgXNIU118cogiHsdPrHf1cDM/edit#heading=h.bq0cgsl5p6im)  planning document to circulate (will unlock after final review).
