### ISSUE TITLE
Objective 1: Design a community program for Firefox OS Ignite Initiative that has full buy in by the FxOS team

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#88]
# Planning Issue:  FxOS Participation

**Full initiative plan:** [here](https://docs.google.com/document/d/1JBRVlUPA-L4efLVD0rxMcjwCgx_hglImHMu5_j_BQVs/edit#) 

**Objectives:** At the end of the quarter, we will have made sure that the FirefoxOS Ignite Initiative has a great, validated community program design.  

**Key results:** 
- long-term plan for FirefoxOS community program  
- 100 weekly users of updated Foxfooding tools 
- 100 weekly contributors on ‘beta’ community collaboration platform 
- 10 “test” events for in-person contribution and community building 400 active foxfooders

**Owners:** @williamq & @brianking 
**Involved:**

**Links:**

**Heartbeat Issues:**
August 21st - #96 #95 #94 #93 #92 
September 11th - #130 #131 
September 30th -

**Comment by MichaelKohler** [comment]
could somebody fix "FirefoxOS" in the title?
