### ISSUE TITLE
Scope and design the regional/local community dashboard and focus country profile

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#89]
### Goal

The goal is to define the scope, elements and user stories for a regional/local community dashboard and for the focus country profiles.
- [Q3 goal document](https://docs.google.com/document/d/1eggb62IbSj4lc3OCzX8BF0WwGubW_pPQbJRvJ2Eegj4/edit#)
- [Docs for this project](https://drive.google.com/drive/u/0/folders/0B3CuegKgwkKkfnEzSzVMd3FrdmhEQTdYanpJX0oyNGVLalFmVW0tM1J6eUo5djhhbVZHR00)
### Success
- Specs for the dashboard are delivered:
- Information fields are defined as well as how to obtain the data
- User stories for the dashboard created
### Roles:

Owner: @rosanardila
Responsible: @nukeador, @couci @deimidis 
Involved: @williamq @brianking 
### Required:
- [x] Research on community/org health dashboards and country profiles, done by Aug 11th @rosanardila @deimidis @nukeador @couci (the more technical piece around google docs) (2 hours each) - [Working document](https://docs.google.com/document/d/1PNBFu79aDytrweY3C3JgTzjyayD61chq-udb-nKzpqE/edit)
- [x] Get user stories from participation team, communities and Reps, done by Aug 11th @nukeador @deimidis (2 hours) - [Working document](https://docs.google.com/document/d/1BS_tN3a5XJFkSVJ2ybKaQU5Jie8yFtUj7ZYzgA0MZP8/edit#)
- [x] First draft of data proposed to be included in dashboard, open questions about data, by August 12th @rosanardila @deimidis @ppapadeas 
- [ ] First draft of information to be included in country profile @rosanardila, @deimidis (feedback: @wquiviger, @brianking, @geroter 
- [ ] Getting feedback from volunteers 17th @rosanardila @deimidis @francjp
- [ ] Deciding on the data to be included in the first prototype and next steps by August 20th @rosanardila @couci @deimidis @ppapadeas @brianking  @wquiviger

**Comment by nukeador** [comment]
I'm documenting dashboard research here: https://docs.google.com/document/d/1PNBFu79aDytrweY3C3JgTzjyayD61chq-udb-nKzpqE/edit

**Comment by nukeador** [comment]
Note also the Part Infra Strategy has a component about visualizing some information as community managers that could overlap with the efforts here:

https://docs.google.com/document/d/1ZM0v8l6h0r5uMGdXAIXUozgXvS4btLmh6v0a1GiR1tg/edit#heading=h.i85kgurfa1kj

Ping @ppapadeas for his input, just in case.

**Comment by geroter** [comment]
This is probably part of the user stories, but I would suggest really thinking through/detailing:
1) The process side of how the dashboard will be used. Who will look at it? When? How will it be updated with qualitative information?
2) The types of decisions that this process and dashboard will enable, in the Participation Team, with volunteers and in the broader organization.

**Comment by nukeador** [comment]
I've added the working documents for both dashboard research and country profile user stories.

**Comment by rosanardila** [comment]
The market pulse community can probably help us with a lot of the market research for the country profiles. @nukeador we can create the specs for the country profile and include then @emmairwin so that we can work together with the market pulse community.

**Comment by nukeador** [comment]
I've pinged Reps mentors to help with volunteer user stories and I've added some from the CM point of view.

**Comment by LucyeoH-zz** [comment]
@rosanardila were you able to get those first two items done this week? Feel free to extend the dates if they need more time.

**Comment by rosanardila** [comment]
@LucyeoH  extending dates

**Comment by emmairwin** [comment]
marketpulse community waiting for directions https://github.com/mozilla/participation-org/issues/84  - steps as discussed  are outlined in this task:

**Comment by rosanardila** [comment]
Adding the first draft of the dashboard: https://docs.google.com/spreadsheets/d/160q5hV6wklxGp0BqsCaelBVVVRD76aWzPS3XHC9RVYs/edit#gid=0

**Comment by LucyeoH-zz** [comment]
Needed more time, and waiting on responses from community. Also PTO was a barrier. Will finish next heartbeat.
