### ISSUE TITLE
Scope and design the framework for mid-term planning

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#90]
### Goal

The goal is to define the scope, elements and user stories for a framework for mid-term planning
Q3 goal document: https://docs.google.com/document/d/1eggb62IbSj4lc3OCzX8BF0WwGubW_pPQbJRvJ2Eegj4/edit#
### Success
- Basic framework is delivered
### Roles:

Owner: @rosanardila
Responsible: @nukeador, @couci @deimidis 
Involved: @williamq @brianking @francjp 
### Required:
- [ ] Research on planning frameworks, done by Aug 13th @deimidis @nukeador @rosanardila (2 hours each)
- [ ] Get user stories for planning from communities and Reps, done by Aug 13th @nukeador @deimidis (2 hours) - [Document](https://docs.google.com/document/d/1FQqzvELuuP-w47Djw0JhK-aaELux0ZrUTzipimvtp3E/edit)
- [x] First draft of planning framework, by August 14th @rosanardila (4 hours) @deimidis @francjp @couci (30 min for feedback)
- [ ] Documenting feedback from volunteers by August 17th @rosanardila @deimidis @francjp 
- [ ] Second iteration and visual guide by August 20th @rosanardila @deimidis

**Comment by LucyeoH-zz** [comment]
@rosanardila were you able to get those first two items done this week?

**Comment by rosanardila** [comment]
extending the dates

**Comment by rosanardila** [comment]
adding first iteration of planning framework: https://docs.google.com/document/d/1LRS4mKCumoVKHD6nQYN4i8HUCUlASZgvY3ktY1PO_hk/edit#

**Comment by LucyeoH-zz** [comment]
Didn't have enough time, everyone involved was on PTO (Participation Staff) move over to next heartbeat. Might condense or simplify.
