### ISSUE TITLE
Scope and design framework for volunteer coaching

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#91]
### Goal

The goal is to define the scope, elements and user stories for a framework for volunteer coaching.
- [Q3 goal document](https://docs.google.com/document/d/1eggb62IbSj4lc3OCzX8BF0WwGubW_pPQbJRvJ2Eegj4/edit#)
- [Docs for this project](https://drive.google.com/drive/u/0/folders/0B3CuegKgwkKkfl9hRVNtNGNBd08tN3hTamxLTjlVX29vZ2JNTzhLcHNyMTBSaDZfZWxCb1k)
### Success
- Basic framework is delivered
### Roles:
- Owner: @nukeador, @deimidis
- Responsible: @rosanardila, @couci
- Involved: @williamq @brianking @francjp 
### Required:
- [x] Reach out to people interested in coaching around Mozilla to invite them to join this initiative @deimidis, @nukeador (2h each) by Aug 9th
- [ ] Run a quick 1:1 with key stakeholders (staff and volunteers) to understand the needs @deimidis (2h each) by Aug 16th
- [x] Get external views/resources about coaching @deimidis Aug 16th
- [ ] Create a draft with answers to: Why, what and how coaching? @deimidis @rosanardila @couci by Aug 20th - [Document](https://drive.google.com/open?id=1FQqzvELuuP-w47Djw0JhK-aaELux0ZrUTzipimvtp3E)
- [ ] Create a final proposal with coaching template @deimidis @rosanardila @couci by Aug 21

**Comment by nukeador** [comment]
@deimidis and me will lead this part.

**Comment by nukeador** [comment]
Required section updated.

**Comment by nukeador** [comment]
Update with the documentation folder: https://drive.google.com/drive/u/0/folders/0B3CuegKgwkKkfl9hRVNtNGNBd08tN3hTamxLTjlVX29vZ2JNTzhLcHNyMTBSaDZfZWxCb1k

**Comment by nukeador** [comment]
Pinged reps-mentors to help with volunteer user stories.

**Comment by LucyeoH-zz** [comment]
@nukeador can you put a status update here with:  
- What the blockers were that stopped the sub-issues from being completed
- What you'll be carrying over to the next HB

**Comment by nukeador** [comment]
I've just returned from PTO and I'm checking with the rest of the team about the status of the sub-issues. I hope to have them updated by today.

**Comment by LucyeoH-zz** [comment]
@nukeador great! Please add notes when this is done and close the issue. Tx

**Comment by nukeador** [comment]
We need to carry over some stuff into the next HB. Basically unifying all the information gathered from 1:1s into conclusions.
