### ISSUE TITLE
Create v1 of plan for internal foxfooding

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#92]
## Goal

The goal is to create an action plan that will ensure that core volunteers committed to participating in the foxfooding program are vetted are given a Sony Xperia Z3C device. 

This is a continuation of #88 
## Success

Plan is approved and we are ready to implement immediately at start of next heartbeat.
## Roles

Owner: @williamq 
Responsible: @LucyeoH 
Involved: Jean Gong 
Reviewer: @brianking
## Required
- [x] Weekly meeting setup and first meeting takes place (@williamq 1 hr, Week ending Aug 14)
- [ ] Determine upcoming availability of the Sony devices (@williamq 1 hr, Week ending Aug 14)
- [ ] Draft document with plan outline (@williamq 5hrs, Week ending Aug 21)

**Comment by LucyeoH-zz** [comment]
@williamq same as others - please add "required" list of things you'll be doing over the next 3 weeks here. Tx.

**Comment by brianking** [comment]
@LucyeoH updated!

**Comment by williamq** [comment]
This issue is dependent on Jean Gong. She just got back from a long PTO - I'm syncing up with her on Monday. I'm carrying this issue over to the next HB.
