### ISSUE TITLE
Validate specs and begin development for Q3 iteration of Fx OS Ignite community platform

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#93]
## Goal

The goal is to spec out the Q3 iteration (v0.1) of the Fx OS Ignite community portal and begin development.

This is a continuation of #88 

User stories: https://docs.google.com/document/d/18hLL0Pe-fvEnMcTjIuZiESTu6GoAD0sAxEjTKf7x7og/edit#heading=h.mviz33xr0exz
## Success

We have fully spec'd out v0.1, we have gotten full buy in from the broader Fx OS participation team and we have begun development of v0.1
## Roles

Owner: @williamq
Responsible: @ppapadeas 
Involved: @brianking 
## Required
- [x] Validate user stories (@ppapadeas 1 hr, Week ending Aug 14)
- [x] Team call to discuss next steps (@brianking, @ppapadeas, @williamq 1hr, Aug 17)
- [x] v0.1 Draft document (@ppapadeas, @williamq 6hrs, Week ending Aug 21)

**Comment by LucyeoH-zz** [comment]
@williamq same as other two - please add "required" list of things you'll be doing over the next 3 weeks here. Tx.

**Comment by brianking** [comment]
@LucyeoH updated!

**Comment by williamq** [comment]
Everything on track. 

v0.1 plan here: https://docs.google.com/document/d/18hLL0Pe-fvEnMcTjIuZiESTu6GoAD0sAxEjTKf7x7og/edit

Development work beginning week of Aug 25th.
