### ISSUE TITLE
First phase of research on target audience (ie. early adopters + developers) is finished

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#94]
## Goal

We need to conduct research to have an understanding of: 
- our target audience (early adopters and developers)
- the roadmap of the areas that foxfooding should be focused on and know what product areas are going to be impacted by foxfooding. What are we going to use foxfooders' support to develop? Is it core functionality, add-ons, testing, etc.? We need to have a high-level understanding of what the impact of foxfooding will be on the product.

This is a continuation of #88. 
## Success

We have gathered solid insights into our target audience and we have a clear roadmap of which product areas will be impacted by the foxfooding program. 
## Roles

Owner: @williamq
Responsible: @williamq 
Involved: @brianking 
## Required
- [x] Build out 'system mapping' of Firefox OS contribution opportunities (@williamq 2 hr, Week ending Aug 14)
- [x] Misc research on topic (@williamq 10hrs, Aug 20)
- [x] Document summarising research findings (@williamq 5hrs, Week ending Aug 21)

**Comment by LucyeoH-zz** [comment]
@williamq please add "required" list of things you'll be doing over the next 3 weeks. Tx.

**Comment by brianking** [comment]
@LucyeoH updated!

**Comment by williamq** [comment]
Link to research (product focus) : https://drive.google.com/open?id=0B7ydSxIYybP5aU5iUE1mTGZwWHc

New report with contributor focus updated tonight.
