### ISSUE TITLE
Test community driven porting events in Taiwan

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#95]
## Goal

The goal is to create a plan to test Fx OS porting events entirely run by volunteers. These test events will be tested in Taiwan where we have a strong community already well-verse in porting. 

This is a continuation of #88 
## Success

We have a plan and we are ready to run these test events during the next heartbeat. 
## Roles

Owner: @williamq
Responsible: @brianking
Involved: Michael Wu
## Required
- [x] Gather feedback on feasibility of such events (@brianking 2hrs, Week ending Aug 14)
- [ ] Draft document with plan outline (@brianking 5hrs, Week ending Aug 21)

**Comment by LucyeoH-zz** [comment]
@williamq can you add sub-goals to this, for example describing what you hope to accomplish each week. Here's one of my issues as an example: https://github.com/mozilla/participation-org/issues/84 Let me know if you need help!

**Comment by brianking** [comment]
@LucyeoH updated!

**Comment by williamq** [comment]
This is dependent on staff availbility (Alexandre Lissy) and device availibility. Carrying over to next heartbeat.

**Comment by LucyeoH-zz** [comment]
Overestimated amount of content that already existed and speed at which they could be obtained. Will be carried over to next HB.
