### ISSUE TITLE
Create a participation strategy for Firefox OS Porting / B2GDroid

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#97]
### Goal:

Increase participation in the Foxfooding program by making Firefox OS available on more devices.

**Planning document is here:**
https://docs.google.com/a/mozilla.com/document/d/1JBRVlUPA-L4efLVD0rxMcjwCgx_hglImHMu5_j_BQVs/edit?usp=sharing

**Objective:** Plan the basics of a new Firefox OS core development program

**Key result 1:** Porting engineers on Mozilla staff are participating in the program

**Key result 2:** Scope of the program is agreed up with different weighting given to porting vs. B2GDroid

**Key result 3:** Awareness among Mozillians
### Success:

1) Consult with core Firefox OS engineers and bring them on board to help build out and execute the program.

2) Build a strategy/concept document on what  Firefox OS porting looks like, with solid program recommendations. 70% quality -- draft version

3) Awareness of the new plan is distributed among the whole Firefox OS team
### Roles:

Owner: @brianking
Responsible: @brianking, @williamq
Involved: 
Reviewer: 
### Required:
- [x] Weekly meeting setup and first meeting takes place (@brianking 1 hr, Thurs Aug 13)
- [x] Research on scope of the program (@brianking 2hrs, Week ending Aug 14)
- [x] Draft document with plan outline (@brianking 5hrs, Week ending Aug 14)
- [ ] Initial wiki page setup

**Comment by brianking** [comment]
Document (WIP):

https://docs.google.com/document/d/14UBDjYpY5IeJZg_kWkjJxm_O6jrG5OTfwohVkWXkov8/edit?usp=sharing

We'll be organising our thoughts more on this in slides for a meeting next week with Chris Beard.

We've been working closely on this with some core Firefox OS folks, gathering all the information we need to come up with a participation strategy.

It is too early to make  wiki page changes, that will come once the plan is finalised and we have more details and resources to point to.

**Comment by LucyeoH-zz** [comment]
Initial wiki page setup - Not ready to put forward the documentation, requires more planning before this can happen (Push forward 2 heartbeats)
