### ISSUE TITLE
Form a team in India to work on bugs to make Firefox for Android smaller

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#98]
### Goal:

Bring local value and impact to Firefox for Android in India by increasing participation on core engineering with the goal of shrinking down the size of the APK.

**Planning document is here:**
https://docs.google.com/document/d/1tvC-SXVpKYVdkJ8YqIIsaHHfjmZpQYUGOnD2QWCMDGo/edit?usp=sharing

**Reference:**
https://wiki.mozilla.org/Mobile/Fatfennec

**Objective:** Recruit a team to work on Fat Fennec bugs

**Key result 1:** Tools dependencies determined and scoped

**Key result 2:** Mentors assigned in Android team to help guide the program

**Key result 3:** 10 volunteers recruited
### Success:

1) Consult with core Firefox for Android engineers and bring them on board to help build out and execute the program.

2) Build volunteer leadership for the program

3) Awareness of the new plan is distributed among the whole Firefox for Android team
### Roles:

Owner: @brianking
Responsible: @brianking, @rosanardila 
Involved: @debloper, @ppapadeas 
Reviewer: @williamq
### Required:
- [x] Initial meeting takes place (@brianking 1 hr, Week ending Aug 21)
- [x] Tools discussion and scoping (@debloper 3hrs, Week ending Aug 21)
- [x] Open up signups for the team

**Comment by brianking** [comment]
Talked with @debloper today about this. We're onboard with building out a team from this point as quick as we can. Deb is putting out some feelers over the weekend, get initial signups, and I'll follow through early next week with the follow up.

Signup form:
https://docs.google.com/a/mozilla.com/forms/d/1mpa7AL0JCKPXPbP2HBohjuesvnpffU189xcHgA3DYLU/viewform

We have decided that for this to work we need to provide some big picture content of why this is important (i.e. in the wider India context), and well as more immediate incentives such as certificates. For the latter, we will create a program that participants can point to afterwards as an achievement, with recognition and the ability to put it on their resume. Branding of program TBD.

**Comment by debloper** [comment]
Thanks Brian for initiating this.

Can't edit/update your comment, so here's the response doc: https://docs.google.com/spreadsheets/d/1tkBegQSE8PdcVOXd-1cfK3n18w_gv3l0aP553uFeibQ/edit - please add/update it as necessary.

**Comment by brianking** [comment]
Don't have access to the doc @debloper

**Comment by brianking** [comment]
Next steps:
- Screen applicants to the team
- Document what the program will look like, get feedback and iterate, and socialise among the team
